# Generated by Django 5.2.8 on 2026-05-06 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("economy", "0012_phase_d_fortress_pin_hash"),
        ("games", "0007_gametournamentconfig_credential_schema_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title (e.g. 'The Survivor's Path').", max_length=120
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Player-facing description of the mission and rules."
                    ),
                ),
                (
                    "entry_fee_dc",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="DeltaCoins the player locks at enrollment.  Forfeited on failure.",
                    ),
                ),
                (
                    "reward_dc",
                    models.PositiveIntegerField(
                        default=0, help_text="DeltaCoins paid on successful completion."
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("TOP_N_FINISH", "Top-N finishes within window"),
                            ("WIN_STREAK", "Win streak"),
                            ("MATCHES_PLAYED", "Number of matches played"),
                            ("KILL_THRESHOLD", "Total kills threshold"),
                            ("CUSTOM", "Custom (free-form goal_spec)"),
                        ],
                        default="CUSTOM",
                        help_text="Hint for the verification engine on how to read goal_spec.",
                        max_length=24,
                    ),
                ),
                (
                    "goal_spec",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Machine-readable goal.  Example for \'TOP_N_FINISH\':\n  {"metric": "top_n_finish", "n": 5, "count": 3, "window_hours": 24}',
                    ),
                ),
                (
                    "badge_slug",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional badge slug awarded on completion (e.g. 'survivor').",
                        max_length=50,
                    ),
                ),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Hours the player has to complete the goal after enrollment.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game this contract applies to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_templates",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Template",
                "verbose_name_plural": "Contract Templates",
                "db_table": "contracts_template",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        db_index=True,
                        help_text="Stable reference (e.g. 'CT-PUBGM-A1B2C3').",
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active — In progress"),
                            ("COMPLETED", "Completed — Reward paid"),
                            ("FAILED", "Failed — Goal not met"),
                            ("EXPIRED", "Expired — Deadline passed"),
                            ("CANCELLED", "Cancelled — User opted out"),
                            ("VOIDED", "Voided — Admin remediation"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Running counters for the verification engine.",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deadline_at",
                    models.DateTimeField(
                        help_text="UTC timestamp by which the goal must be completed."
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not closed"),
                            ("COMPLETED", "Goal met — reward paid"),
                            ("FAILED", "Goal missed within deadline"),
                            ("EXPIRED", "Deadline passed without resolution"),
                            ("CANCELLED", "Cancelled by user (entry fee forfeited)"),
                            ("VOIDED", "Voided by admin (entry fee refunded)"),
                        ],
                        db_index=True,
                        default="",
                        help_text="Why the contract closed.  UI must surface this rather than a bare countdown.",
                        max_length=24,
                    ),
                ),
                (
                    "closure_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form admin/system note for the closure.",
                    ),
                ),
                (
                    "escrow_lock_txn",
                    models.ForeignKey(
                        blank=True,
                        help_text="Player's entry-fee lock transaction (set at enrollment).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="economy.deltacrowntransaction",
                    ),
                ),
                (
                    "reward_payout_txn",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reward payout transaction (set on COMPLETED).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="economy.deltacrowntransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="contracts.contracttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Enrollment",
                "verbose_name_plural": "Contract Enrollments",
                "db_table": "contracts_enrollment",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contracttemplate",
            index=models.Index(fields=["is_active", "game"], name="contracts_t_is_acti_c1140f_idx"),
        ),
        migrations.AddIndex(
            model_name="contractenrollment",
            index=models.Index(fields=["user", "status"], name="contracts_e_user_id_ea6e5c_idx"),
        ),
        migrations.AddIndex(
            model_name="contractenrollment",
            index=models.Index(
                fields=["status", "deadline_at"], name="contracts_e_status_205de2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractenrollment",
            index=models.Index(
                fields=["template", "status"], name="contracts_e_templat_13898a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("user", "template"),
                name="one_active_enrollment_per_user_template",
            ),
        ),
    ]
