# Generated by Django 5.2.8 on 2026-05-16 20:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractProofSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("proof_url", models.URLField(max_length=500)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending Review"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING_REVIEW",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Private operator note. Do not expose publicly.",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="contracts.contractenrollment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mission_proofs_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mission_proof_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission Proof Submission",
                "verbose_name_plural": "Mission Proof Submissions",
                "db_table": "contracts_proof_submission",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["enrollment", "-submitted_at"],
                        name="contracts_p_enrollm_f9cea7_idx",
                    ),
                    models.Index(
                        fields=["status", "-submitted_at"], name="contracts_p_status_f466fb_idx"
                    ),
                    models.Index(
                        fields=["submitted_by", "-submitted_at"],
                        name="contracts_p_submitt_0b8f1c_idx",
                    ),
                ],
            },
        ),
    ]
