# Generated by Django 5.2.8 on 2026-05-16 20:50

import apps.common.validators
import apps.contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contractproofsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractproofsubmission",
            name="proof_file",
            field=models.FileField(
                blank=True,
                default="",
                help_text="Optional uploaded image proof. URL-only submissions remain supported.",
                upload_to=apps.contracts.models._mission_proof_upload_to,
                validators=[apps.common.validators.validate_payment_proof_upload],
            ),
        ),
        migrations.AlterField(
            model_name="contractproofsubmission",
            name="proof_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
