# Generated by Django 5.2.8 on 2026-04-05 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match_engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("match_id", models.PositiveIntegerField(db_index=True)),
                ("display_name", models.CharField(max_length=100)),
                ("avatar_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "side",
                    models.SmallIntegerField(default=0, help_text="1=P1, 2=P2, 0=staff/system"),
                ),
                ("text", models.TextField(max_length=500)),
                (
                    "msg_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("system", "System"),
                            ("voice_link", "Voice Link"),
                        ],
                        default="chat",
                        max_length=12,
                    ),
                ),
                ("is_official", models.BooleanField(default=False)),
                ("extra", models.JSONField(blank=True, default=dict, help_text="voice_url etc.")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "match_engine_chat_message",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["match_id", "created_at"], name="match_engin_match_i_e8d3d0_idx"
                    )
                ],
            },
        ),
    ]
