"""
Canonical Match Read Model.

One authoritative view of every match in a tournament — used by:
  * TOC Matches list
  * TOC Schedule
  * HUB Matches (schedule tab)
  * HUB Bracket placeholder resolution
  * Public detail Matches tab

Why this exists
---------------
Prior versions had every surface query `Match.objects.filter(tournament=...)`
and derive stage/round-label independently. When bracket generation left
`Match.bracket_id` null, each surface would classify the same match
differently: the bracket tree saw it as a knockout (via `BracketNode.match`),
while the list views saw it as group-stage. This module resolves all such
disagreements in one place.

Core idea
---------
The bracket tree (BracketNode.match OneToOne FK) is AUTHORITATIVE for
knockout stage classification. Any Match reachable from a BracketNode is a
knockout match, regardless of what `Match.bracket_id` says. We pre-compute
the BracketNode-backed metadata per match, then merge with the raw Match row.

Public API
----------

  MatchReadModel.for_tournament(tournament) -> MatchReadModel
    Build (and cache per-request) a canonical view for all matches.

  .list() -> list[MatchView]
    Every match with canonical classification + label + source.

  .by_id(match_id) -> MatchView | None
  .filter(state=None, stage=None, round_number=None, search=None) -> list[MatchView]
  .round_options() -> list[{value, label, stage}]
    Canonical round filter options.

  .resolve_node(bracket_node) -> MatchView | None
    Fallback resolver for a BracketNode whose match FK is missing — finds
    a candidate Match by coordinate.

Typing note: we return plain dicts (not dataclasses) so consumers can
extend/augment them with surface-specific fields without fighting the
type system.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Iterable, List, Optional

from django.db.models import Q

from apps.tournaments.models.match import Match
from apps.tournaments.services.match_classification import (
    classify_stage as _classify_stage,
    compute_round_label as _compute_round_label,
    tournament_total_rounds as _total_rounds,
    is_pure_knockout as _is_pure_knockout,
)

logger = logging.getLogger(__name__)


def _node_stage(bracket_type: Optional[str]) -> str:
    """Map BracketNode.bracket_type → canonical stage."""
    bt = (bracket_type or '').lower()
    # third-place / losers / main are all still knockout rounds.
    return 'knockout'


class MatchReadModel:
    """Pre-computed canonical view for every match in a tournament."""

    __slots__ = ('_tournament', '_bracket', '_views', '_by_id',
                 '_by_coord', '_node_index', '_total_rounds', '_fmt')

    def __init__(self, tournament):
        self._tournament = tournament
        self._fmt = (getattr(tournament, 'format', '') or '').lower()
        self._bracket = None
        self._views: List[Dict[str, Any]] = []
        self._by_id: Dict[int, Dict[str, Any]] = {}
        self._by_coord: Dict[tuple, Dict[str, Any]] = {}
        self._node_index: Dict[int, Dict[str, Any]] = {}  # match_id -> node meta
        self._total_rounds: int = 0

    # ── Factory ───────────────────────────────────────────────

    @classmethod
    def for_tournament(cls, tournament) -> 'MatchReadModel':
        inst = cls(tournament)
        inst._load()
        return inst

    # ── Build ─────────────────────────────────────────────────

    def _load(self) -> None:
        try:
            from apps.brackets.models import Bracket, BracketNode
        except ImportError:
            Bracket = BracketNode = None

        tournament = self._tournament

        # Resolve bracket + total_rounds via canonical helper.
        if Bracket is not None:
            try:
                self._bracket = Bracket.objects.filter(tournament=tournament).first()
            except Exception:
                self._bracket = None
        self._total_rounds = _total_rounds(tournament, bracket=self._bracket)

        # Pre-index BracketNodes. Two lookup tables:
        #   self._node_index[match_id]           -> node meta (for direct FK hits)
        #   nodes_by_coord[(rn, mn_in_round)]   -> node (for coordinate lookup
        #                                          when FK is missing)
        # Note: BracketNode coordinates are authoritative for knockout matches.
        # Match.round_number / match_number may disagree (especially for
        # tournaments generated by older code paths).
        nodes_by_coord: Dict[tuple, Any] = {}
        if BracketNode is not None and self._bracket is not None:
            try:
                for node in BracketNode.objects.filter(bracket=self._bracket):
                    meta = {
                        'bracket_node_id': node.id,
                        'bracket_type': node.bracket_type,
                        'is_bye': bool(getattr(node, 'is_bye', False)),
                        'node_round_number': node.round_number,
                        'node_match_number': node.match_number_in_round,
                        'node_participant1_id': node.participant1_id,
                        'node_participant1_name': node.participant1_name or '',
                        'node_participant2_id': node.participant2_id,
                        'node_participant2_name': node.participant2_name or '',
                        'node_winner_id': node.winner_id,
                    }
                    if node.match_id:
                        self._node_index[node.match_id] = meta
                    nodes_by_coord[(node.round_number, node.match_number_in_round)] = node
            except Exception:
                logger.exception('Failed to index BracketNodes for %s', tournament)

        # Load matches.
        matches = list(
            Match.objects.filter(tournament=tournament, is_deleted=False)
            .order_by('round_number', 'match_number', 'id')
        )

        for m in matches:
            view = self._serialize_match(m, nodes_by_coord)
            self._views.append(view)
            self._by_id[m.id] = view
            self._by_coord[(m.round_number or 0, m.match_number or 0)] = view

    def _serialize_match(self, m: Match, nodes_by_coord: Dict[tuple, Any]) -> Dict[str, Any]:
        # Determine whether this match is tied to a BracketNode.
        #   1. direct: BracketNode.match_id == m.id (via self._node_index)
        #   2. inferred: BracketNode exists at (m.round_number, m.match_number)
        #      but its match FK was never written
        node_meta = self._node_index.get(m.id)
        inferred = False
        if node_meta is None:
            coord_node = nodes_by_coord.get((m.round_number, m.match_number))
            if coord_node is not None and coord_node.match_id is None:
                node_meta = {
                    'bracket_node_id': coord_node.id,
                    'bracket_type': coord_node.bracket_type,
                    'is_bye': bool(getattr(coord_node, 'is_bye', False)),
                    'node_round_number': coord_node.round_number,
                    'node_match_number': coord_node.match_number_in_round,
                    'node_participant1_id': coord_node.participant1_id,
                    'node_participant1_name': coord_node.participant1_name or '',
                    'node_participant2_id': coord_node.participant2_id,
                    'node_participant2_name': coord_node.participant2_name or '',
                    'node_winner_id': coord_node.winner_id,
                }
                inferred = True

        is_bracket_linked = bool(node_meta) or bool(m.bracket_id)

        # Canonical stage — BracketNode presence wins.
        if node_meta:
            stage = _node_stage(node_meta.get('bracket_type'))
        elif _is_pure_knockout(self._fmt):
            stage = 'knockout'
        elif is_bracket_linked and self._fmt == 'group_playoff':
            stage = 'knockout'
        else:
            stage = _classify_stage(self._tournament, m)

        # Canonical round_number — when bracket-linked, use the node's
        # round_number. The tree is authoritative; a Match.round_number that
        # disagrees is a data artifact from legacy generators.
        canonical_round_number = (
            node_meta['node_round_number']
            if node_meta and node_meta.get('node_round_number') is not None
            else m.round_number
        )
        canonical_match_number = (
            node_meta['node_match_number']
            if node_meta and node_meta.get('node_match_number') is not None
            else m.match_number
        )

        # Canonical round label — compute from the canonical round_number so
        # dropdown filtering + match cards agree even when Match.round_number
        # differs from BracketNode.round_number.
        from types import SimpleNamespace
        label_shim = SimpleNamespace(
            round_number=canonical_round_number,
            bracket_id=m.bracket_id or getattr(self._bracket, 'id', None),
        )
        round_label = ''
        if canonical_round_number:
            round_label = _compute_round_label(
                self._tournament, label_shim,
                bracket=self._bracket,
                total_rounds=self._total_rounds,
            ) or f'Round {canonical_round_number}'
        if node_meta and node_meta.get('bracket_type') == 'third-place':
            round_label = 'Third Place Match'

        if inferred:
            source = 'inferred_legacy'
        elif node_meta:
            source = 'bracket_node'
        else:
            source = 'match'

        # Canonical participant resolution (the BIG fix).
        #
        # Truth contract:
        #   * When a BracketNode is linked/inferred AND has a participant in
        #     slot N, that participant is authoritative for slot N. A Match
        #     row showing TBA/empty should not override a node that knows
        #     the real team.
        #   * When the node slot is empty (genuinely TBD) but the Match row
        #     has a participant, use the Match row (rare but legal during
        #     partial repair).
        #   * When neither has a participant, the slot is genuinely TBD.
        #
        # `_pick` enforces this for id/name pairs atomically — we never
        # mix an id from one source with a name from another, which would
        # produce misleading display.

        def _pick_pair(node_id, node_name, match_id, match_name):
            node_id = node_id if node_id else None
            match_id = match_id if match_id else None
            node_name = (node_name or '').strip() or None
            match_name = (match_name or '').strip() or None
            # Prefer node when it has a real id OR a real name.
            if node_id or node_name:
                return node_id, node_name or ''
            if match_id or match_name:
                return match_id, match_name or ''
            return None, ''

        if node_meta:
            p1_id, p1_name = _pick_pair(
                node_meta.get('node_participant1_id'),
                node_meta.get('node_participant1_name'),
                m.participant1_id, m.participant1_name,
            )
            p2_id, p2_name = _pick_pair(
                node_meta.get('node_participant2_id'),
                node_meta.get('node_participant2_name'),
                m.participant2_id, m.participant2_name,
            )
            node_winner_id = node_meta.get('node_winner_id')
            winner_id = node_winner_id or m.winner_id
        else:
            p1_id = m.participant1_id or None
            p1_name = m.participant1_name or ''
            p2_id = m.participant2_id or None
            p2_name = m.participant2_name or ''
            winner_id = m.winner_id

        winner_name = ''
        winner_side = 0
        if winner_id and p1_id and winner_id == p1_id:
            winner_side = 1
            winner_name = p1_name
        elif winner_id and p2_id and winner_id == p2_id:
            winner_side = 2
            winner_name = p2_name

        return {
            'canonical_match_id': m.id,
            'source': source,
            'match_id': m.id,
            'bracket_node_id': node_meta.get('bracket_node_id') if node_meta else None,
            'bracket_id': (
                m.bracket_id
                or (getattr(self._bracket, 'id', None) if node_meta else None)
            ),
            'is_bracket_linked': is_bracket_linked,
            'is_bye': node_meta.get('is_bye', False) if node_meta else False,
            'bracket_type': node_meta.get('bracket_type') if node_meta else None,
            'stage': stage,
            'round_label': round_label,
            'round_number': canonical_round_number,
            'match_number': canonical_match_number,
            # Canonical participant slots — node wins when non-empty.
            'participant1_id': p1_id,
            'participant1_name': p1_name,
            'participant2_id': p2_id,
            'participant2_name': p2_name,
            'participant1_score': m.participant1_score,
            'participant2_score': m.participant2_score,
            'state': m.state,
            'winner_id': winner_id,
            'winner_name': winner_name,
            'winner_side': winner_side,
            'loser_id': m.loser_id,
            'scheduled_time': m.scheduled_time,
            'started_at': m.started_at,
            'completed_at': m.completed_at,
            'best_of': getattr(m, 'best_of', 1) or 1,
            'is_placeholder': False,
            # Raw Match fields preserved for debugging + repair tooling.
            'raw_round_number': m.round_number,
            'raw_match_number': m.match_number,
            'raw_participant1_id': m.participant1_id,
            'raw_participant1_name': m.participant1_name or '',
            'raw_participant2_id': m.participant2_id,
            'raw_participant2_name': m.participant2_name or '',
        }

    # ── Query ─────────────────────────────────────────────────

    def list(self) -> List[Dict[str, Any]]:
        return list(self._views)

    def by_id(self, match_id: int) -> Optional[Dict[str, Any]]:
        return self._by_id.get(int(match_id))

    def filter(
        self,
        *,
        state: Optional[str] = None,
        stage: Optional[str] = None,
        round_number: Optional[int] = None,
        search: Optional[str] = None,
    ) -> List[Dict[str, Any]]:
        rows = self._views
        if state:
            rows = [r for r in rows if r['state'] == state]
        if stage:
            rows = [r for r in rows if r['stage'] == stage]
        if round_number is not None:
            rows = [r for r in rows if r['round_number'] == round_number]
        if search:
            needle = str(search).lower()
            rows = [r for r in rows
                    if needle in (r['participant1_name'] or '').lower()
                    or needle in (r['participant2_name'] or '').lower()]
        return list(rows)

    def round_options(self) -> List[Dict[str, Any]]:
        """Canonical round filter options — ordered, de-duplicated, labelled."""
        seen = {}
        for r in self._views:
            rn = r.get('round_number')
            if not rn or rn in seen:
                continue
            seen[rn] = {
                'value': int(rn),
                'label': r.get('round_label') or f'Round {rn}',
                'stage': r.get('stage'),
            }
        return sorted(seen.values(), key=lambda x: x['value'])

    def resolve_node(self, node) -> Optional[Dict[str, Any]]:
        """Return the canonical MatchView for a BracketNode, if any."""
        if getattr(node, 'match_id', None):
            return self._by_id.get(node.match_id)
        rn = getattr(node, 'round_number', None)
        mn = getattr(node, 'match_number_in_round', None)
        if rn is not None and mn is not None:
            return self._by_coord.get((rn, mn))
        return None

    # ── Diagnostics ───────────────────────────────────────────

    @property
    def bracket(self):
        return self._bracket

    @property
    def total_rounds(self) -> int:
        return self._total_rounds


__all__ = ['MatchReadModel']
