# Generated by Django 4.2.23 on 2025-09-17 20:25

from django.db import migrations


def _table_exists(schema_editor, table_name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        tables = schema_editor.connection.introspection.table_names(cursor)
    return table_name in tables


def create_user_table(apps, schema_editor):
    user_model = apps.get_model("accounts", "User")
    table_name = user_model._meta.db_table
    if _table_exists(schema_editor, table_name):
        return
    schema_editor.create_model(user_model)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_user_table, noop_reverse),
    ]
