# Generated by Django 5.2.8 on 2026-01-02 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled for deletion"),
                            ("CANCELED", "Canceled by user"),
                            ("COMPLETED", "Deletion completed"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        help_text="Date when deletion will be finalized (requested_at + 14 days)"
                    ),
                ),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Optional reason for deletion provided by user"
                    ),
                ),
                (
                    "confirmation_phrase",
                    models.CharField(
                        blank=True, help_text="Confirmation phrase entered by user", max_length=100
                    ),
                ),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account to be deleted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_for"], name="accounts_ac_status_b163ed_idx"
                    )
                ],
            },
        ),
    ]
