# Generated by Django 4.2.24 on 2025-09-17 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def prune_orphan_emailotps(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    EmailOTP = apps.get_model('accounts', 'EmailOTP')
    valid_ids = list(User.objects.values_list('id', flat=True))
    if not valid_ids:
        EmailOTP.objects.all().delete()
        return
    EmailOTP.objects.exclude(user_id__in=valid_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(prune_orphan_emailotps, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='pending_signup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to='accounts.pendingsignup'),
        ),
    ]
