# Generated by Django 5.2.8 on 2025-12-05 12:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0008_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Technical name (e.g., 'Valorant')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Display name (e.g., 'VALORANT™')", max_length=150)),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g., 'valorant')", unique=True)),
                ('short_code', models.CharField(help_text="Short identifier (e.g., 'VAL', 'CS2', 'PUBGM')", max_length=10, unique=True)),
                ('category', models.CharField(choices=[('FPS', 'First-Person Shooter'), ('MOBA', 'Multiplayer Online Battle Arena'), ('BR', 'Battle Royale'), ('SPORTS', 'Sports/Esports Simulation'), ('FIGHTING', 'Fighting Game'), ('STRATEGY', 'Strategy'), ('CCG', 'Card Game'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('game_type', models.CharField(choices=[('TEAM_VS_TEAM', 'Team vs Team'), ('1V1', '1 vs 1'), ('BATTLE_ROYALE', 'Battle Royale'), ('FREE_FOR_ALL', 'Free-for-All')], default='TEAM_VS_TEAM', max_length=50)),
                ('platforms', models.JSONField(default=list, help_text="List of platforms: ['PC', 'Mobile', 'Console']")),
                ('icon', models.ImageField(blank=True, null=True, upload_to='games/icons/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='games/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='games/banners/')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='games/cards/')),
                ('primary_color', models.CharField(default='#7c3aed', help_text='Hex color code (e.g., #7c3aed)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(default='#1e1b4b', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('accent_color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this game available for tournaments/teams?')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on homepage?')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Game description for display')),
                ('official_website', models.URLField(blank=True)),
                ('developer', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'games_game',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayerIdentityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Technical field name (e.g., 'riot_id', 'steam_id', 'uid')", max_length=50)),
                ('display_name', models.CharField(help_text="Human-readable name (e.g., 'Riot ID', 'Steam ID', 'Character ID')", max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('EMAIL', 'Email'), ('URL', 'URL')], default='TEXT', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Is this field mandatory?')),
                ('validation_regex', models.CharField(blank=True, help_text='Regex pattern for validation (optional)', max_length=500)),
                ('validation_error_message', models.CharField(blank=True, help_text='Custom error message for validation failure', max_length=200)),
                ('min_length', models.IntegerField(blank=True, help_text='Minimum character length', null=True)),
                ('max_length', models.IntegerField(blank=True, help_text='Maximum character length', null=True)),
                ('placeholder', models.CharField(blank=True, help_text="Placeholder text for input field (e.g., 'PlayerName#1234')", max_length=200)),
                ('help_text', models.TextField(blank=True, help_text='Additional help text for users')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = shown first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_configs', to='games.game')),
            ],
            options={
                'verbose_name': 'Player Identity Config',
                'verbose_name_plural': 'Player Identity Configs',
                'db_table': 'games_player_identity_config',
                'ordering': ['game', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GameRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(help_text="Role name (e.g., 'Duelist', 'Controller', 'Tank')", max_length=50)),
                ('role_code', models.CharField(help_text="Short code for role (e.g., 'DUE', 'CTRL', 'TNK')", max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of role responsibilities')),
                ('icon', models.CharField(blank=True, help_text="Icon identifier or emoji (e.g., '🎯', 'duelist-icon')", max_length=50)),
                ('color', models.CharField(blank=True, help_text="Hex color for role (e.g., '#ff4655')", max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_competitive', models.BooleanField(default=True, help_text='Is this a competitive/ranked role?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this role currently active in the meta?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='games.game')),
            ],
            options={
                'verbose_name': 'Game Role',
                'verbose_name_plural': 'Game Roles',
                'db_table': 'games_role',
                'ordering': ['game', 'order', 'role_name'],
            },
        ),
        migrations.CreateModel(
            name='GameRosterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_team_size', models.IntegerField(default=1, help_text='Minimum players on field during match')),
                ('max_team_size', models.IntegerField(default=5, help_text='Maximum players on field during match')),
                ('min_substitutes', models.IntegerField(default=0, help_text='Minimum substitute players')),
                ('max_substitutes', models.IntegerField(default=2, help_text='Maximum substitute players')),
                ('min_roster_size', models.IntegerField(default=1, help_text='Minimum total roster size (including subs)')),
                ('max_roster_size', models.IntegerField(default=10, help_text='Maximum total roster size (including subs)')),
                ('allow_coaches', models.BooleanField(default=True, help_text='Allow coaches on roster?')),
                ('max_coaches', models.IntegerField(default=2, help_text='Maximum number of coaches')),
                ('allow_analysts', models.BooleanField(default=True, help_text='Allow analysts on roster?')),
                ('max_analysts', models.IntegerField(default=1, help_text='Maximum number of analysts')),
                ('allow_managers', models.BooleanField(default=True, help_text='Allow managers on roster?')),
                ('max_managers', models.IntegerField(default=2, help_text='Maximum number of managers')),
                ('has_roles', models.BooleanField(default=False, help_text='Does this game have defined roles (e.g., Duelist, Support)?')),
                ('require_unique_roles', models.BooleanField(default=False, help_text='Each role can only be filled by one player')),
                ('allow_multi_role', models.BooleanField(default=True, help_text='Can players have multiple roles?')),
                ('has_regions', models.BooleanField(default=False, help_text='Does this game have regional restrictions?')),
                ('available_regions', models.JSONField(default=list, help_text="[{'code': 'NA', 'name': 'North America'}, ...]")),
                ('extra_rules', models.JSONField(blank=True, default=dict, help_text='Additional game-specific roster rules (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster_config', to='games.game')),
            ],
            options={
                'verbose_name': 'Roster Configuration',
                'verbose_name_plural': 'Roster Configurations',
                'db_table': 'games_roster_config',
            },
        ),
        migrations.CreateModel(
            name='GameTournamentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_match_formats', models.JSONField(default=list, help_text="List of allowed match formats (e.g., ['BO1', 'BO3', 'BO5'])")),
                ('default_match_format', models.CharField(choices=[('BO1', 'Best of 1'), ('BO3', 'Best of 3'), ('BO5', 'Best of 5'), ('BO7', 'Best of 7'), ('SINGLE', 'Single Match'), ('SERIES', 'Match Series')], default='BO3', max_length=20)),
                ('default_scoring_type', models.CharField(choices=[('WIN_LOSS', 'Win/Loss Only'), ('POINTS', 'Points-based'), ('ROUNDS', 'Round-based (FPS)'), ('KILLS', 'Kill-based (BR)'), ('PLACEMENT', 'Placement-based (BR)'), ('GOALS', 'Goal-based (Sports)'), ('CUSTOM', 'Custom Scoring')], default='WIN_LOSS', max_length=20)),
                ('scoring_rules', models.JSONField(blank=True, default=dict, help_text='Detailed scoring configuration (JSON)')),
                ('default_tiebreakers', models.JSONField(default=list, help_text="Ordered list of tiebreaker criteria (e.g., ['head_to_head', 'round_diff', 'rounds_won'])")),
                ('supports_single_elimination', models.BooleanField(default=True)),
                ('supports_double_elimination', models.BooleanField(default=True)),
                ('supports_round_robin', models.BooleanField(default=True)),
                ('supports_swiss', models.BooleanField(default=False)),
                ('supports_group_stage', models.BooleanField(default=True)),
                ('default_match_duration_minutes', models.IntegerField(default=60, help_text='Expected match duration in minutes')),
                ('allow_draws', models.BooleanField(default=False, help_text='Can matches end in a draw?')),
                ('overtime_enabled', models.BooleanField(default=True, help_text='Is overtime/sudden death available?')),
                ('require_check_in', models.BooleanField(default=True, help_text='Do teams need to check in before matches?')),
                ('check_in_window_minutes', models.IntegerField(default=30, help_text='How long before match start can teams check in?')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Game-specific tournament configuration (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_config', to='games.game')),
            ],
            options={
                'verbose_name': 'Tournament Configuration',
                'verbose_name_plural': 'Tournament Configurations',
                'db_table': 'games_tournament_config',
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['slug'], name='games_game_slug_161310_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['is_active', 'is_featured'], name='games_game_is_acti_84a4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['category', 'is_active'], name='games_game_categor_421ddf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameplayeridentityconfig',
            unique_together={('game', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='gamerole',
            index=models.Index(fields=['game', 'is_active'], name='games_role_game_id_d796e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gamerole',
            unique_together={('game', 'role_name')},
        ),
    ]
