# Generated by Django 5.2.8 on 2025-12-08 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametournamentconfig',
            name='allow_cross_region',
            field=models.BooleanField(default=False, help_text='Whether teams can have players from different regions'),
        ),
        migrations.AddField(
            model_name='gametournamentconfig',
            name='identity_requirements',
            field=models.JSONField(blank=True, default=dict, help_text="Additional identity validation requirements (e.g., {'min_account_level': 30})"),
        ),
        migrations.AddField(
            model_name='gametournamentconfig',
            name='max_team_size',
            field=models.IntegerField(default=5, help_text='Maximum number of players per team'),
        ),
        migrations.AddField(
            model_name='gametournamentconfig',
            name='min_team_size',
            field=models.IntegerField(default=1, help_text='Minimum number of players per team'),
        ),
        migrations.AddField(
            model_name='gametournamentconfig',
            name='require_verified_email',
            field=models.BooleanField(default=True, help_text='Whether all players must have verified email addresses'),
        ),
        migrations.AddField(
            model_name='gametournamentconfig',
            name='require_verified_phone',
            field=models.BooleanField(default=False, help_text='Whether all players must have verified phone numbers'),
        ),
        migrations.CreateModel(
            name='GameScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('win_loss', 'Win/Loss (binary outcome)'), ('points_accumulation', 'Points Accumulation (sum of stats)'), ('placement_order', 'Placement Order (rank-based)'), ('time_based', 'Time-Based (fastest time wins)'), ('custom', 'Custom Logic')], help_text='Type of scoring algorithm', max_length=50)),
                ('config', models.JSONField(default=dict, help_text="Scoring configuration (e.g., {'kill_points': 1, 'placement_points': [10, 6, 4, 2]})")),
                ('description', models.TextField(help_text='Human-readable explanation of this scoring rule')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently in use')),
                ('priority', models.IntegerField(default=0, help_text='Priority order when multiple rules exist (higher = used first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(help_text='The game this scoring rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='games.game')),
            ],
            options={
                'verbose_name': 'Game Scoring Rule',
                'verbose_name_plural': 'Game Scoring Rules',
                'db_table': 'games_scoring_rule',
                'ordering': ['game', '-priority', 'rule_type'],
            },
        ),
        migrations.CreateModel(
            name='GameMatchResultSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Field name in match result payload (e.g., 'kills', 'placement')", max_length=100)),
                ('display_label', models.CharField(help_text="User-facing label (e.g., 'Kills', 'Final Placement')", max_length=200)),
                ('field_type', models.CharField(choices=[('integer', 'Integer'), ('decimal', 'Decimal'), ('text', 'Text'), ('boolean', 'Boolean'), ('enum', 'Enum (predefined choices)'), ('json', 'JSON Object')], help_text='Data type of this field', max_length=20)),
                ('validation', models.JSONField(blank=True, default=dict, help_text="Additional validation rules (e.g., {'min': 0, 'max': 100} for integers, {'choices': [...]} for enums)")),
                ('is_required', models.BooleanField(default=True, help_text='Whether this field must be present in match results')),
                ('help_text', models.TextField(blank=True, help_text='Instructions for tournament organizers/submitters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(help_text='The game this schema applies to', on_delete=django.db.models.deletion.CASCADE, related_name='match_result_schemas', to='games.game')),
            ],
            options={
                'verbose_name': 'Game Match Result Schema',
                'verbose_name_plural': 'Game Match Result Schemas',
                'db_table': 'games_match_result_schema',
                'ordering': ['game', 'field_name'],
                'unique_together': {('game', 'field_name')},
            },
        ),
    ]
