# Generated by Django 5.2.8 on 2026-01-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_games",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="gamematchresultschema",
            name="game",
            field=models.ForeignKey(
                help_text="The game this schema applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_result_schemas",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gameplayeridentityconfig",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identity_configs",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gamerole",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="roles", to="games.game"
            ),
        ),
        migrations.AddField(
            model_name="gamerosterconfig",
            name="game",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roster_config",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gamescoringrule",
            name="game",
            field=models.ForeignKey(
                help_text="The game this scoring rule applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_rules",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gametournamentconfig",
            name="game",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_config",
                to="games.game",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["slug"], name="games_game_slug_161310_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["is_active", "is_featured"], name="games_game_is_acti_84a4b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["category", "is_active"], name="games_game_categor_421ddf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamematchresultschema",
            unique_together={("game", "field_name")},
        ),
        migrations.AlterUniqueTogether(
            name="gameplayeridentityconfig",
            unique_together={("game", "field_name")},
        ),
        migrations.AddIndex(
            model_name="gamerole",
            index=models.Index(fields=["game", "is_active"], name="games_role_game_id_d796e2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="gamerole",
            unique_together={("game", "role_name")},
        ),
    ]
