# Generated by Django 5.2.8 on 2025-12-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gametournamentconfig_allow_cross_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayeridentityconfig',
            name='is_immutable',
            field=models.BooleanField(default=False, help_text='Can this field be changed after initial setup?'),
        ),
    ]
