# Generated by Django 5.2.8 on 2025-12-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_gameplayeridentityconfig_is_immutable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gametournamentconfig",
            name="default_tiebreakers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of tiebreaker criteria (e.g., ['head_to_head', 'round_diff', 'rounds_won']). Leave empty if not applicable.",
            ),
        ),
    ]
