# Generated by Django 5.2.8 on 2026-04-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_gamematchpipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamematchpipeline",
            name="archetype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tactical_fps", "Tactical FPS"),
                    ("moba", "MOBA"),
                    ("battle_royale", "Battle Royale"),
                    ("sports", "Sports"),
                    ("duel_1v1", "1v1 / Duel"),
                ],
                default="",
                help_text="Game archetype — auto-resolved from game if blank.",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="VetoConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Human label, e.g. "BO3 Map Veto" or "Captain\'s Mode Draft".',
                        max_length=120,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("map", "Map Veto"),
                            ("hero", "Hero / Champion Draft"),
                            ("operator", "Operator / Agent Ban"),
                            ("custom", "Custom"),
                        ],
                        default="map",
                        help_text="What entity is being banned/picked (maps, heroes, etc.).",
                        max_length=20,
                    ),
                ),
                (
                    "sequence",
                    models.JSONField(
                        default=list,
                        help_text='Ordered list of veto steps. Each step: {"action": "ban"|"pick", "team": "A"|"B", "count": 1}. Example BO3: Ban-Ban-Pick-Pick-Ban-Ban-Decider.',
                    ),
                ),
                (
                    "pool",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Default pool of available items (map names, hero names, etc.).",
                    ),
                ),
                (
                    "time_per_action_seconds",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Seconds allowed per ban/pick action before auto-random.",
                    ),
                ),
                (
                    "auto_random_on_timeout",
                    models.BooleanField(
                        default=True,
                        help_text="If True, a random choice is made when the timer expires.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        help_text="The game this veto/draft configuration applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veto_configurations",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veto Configuration",
                "verbose_name_plural": "Veto Configurations",
                "db_table": "games_veto_configuration",
                "ordering": ["game", "name"],
                "unique_together": {("game", "name")},
            },
        ),
    ]
