# Generated by Django 5.2.8 on 2025-12-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_make_tiebreakers_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_passport_supported",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Does this game support Game Passport functionality? (Admin filter)",
            ),
        ),
    ]
