# Generated by Django 5.2.8 on 2025-12-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_add_is_passport_supported"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="available_ranks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Game-specific ranks: [{'value': 'iron', 'label': 'Iron'}, ...]",
            ),
        ),
    ]
