# Generated by Django 5.2.8 on 2025-12-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_add_is_passport_supported"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE games_game
                ADD COLUMN IF NOT EXISTS available_ranks jsonb DEFAULT '[]'::jsonb NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE games_game DROP COLUMN IF EXISTS available_ranks;
            """,
        ),
    ]
