# Generated by Django 5.2.8 on 2026-04-11 08:28

import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_remove_gamematchpipeline_from_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="gametournamentconfig",
            name="credential_schema",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='JSON array of lobby credential fields. Example: [{"key": "lobby_code", "label": "Lobby Code", "kind": "text", "required": true}]. Empty list = use default schema from GamePipelineTemplate.',
            ),
        ),
        migrations.AddField(
            model_name="gametournamentconfig",
            name="max_score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum valid score per match side (e.g., 13 for Valorant, 999 for BR kill totals). Null = no limit.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="games/banners/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="card_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="games/cards/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="games/icons/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="games/logos/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.CreateModel(
            name="GameMapPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "map_name",
                    models.CharField(
                        help_text="Display name of the map (e.g. 'Ascent', 'Mirage')",
                        max_length=100,
                    ),
                ),
                (
                    "map_code",
                    models.SlugField(help_text="Internal code/slug for the map", max_length=100),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional map thumbnail",
                        null=True,
                        upload_to="games/maps/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this map is in the current active pool",
                    ),
                ),
                (
                    "is_competitive",
                    models.BooleanField(
                        default=True, help_text="Whether this map is in the competitive rotation"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within the pool"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        help_text="The game this map belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_pool",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Map Pool Entry",
                "verbose_name_plural": "Game Map Pool Entries",
                "db_table": "games_map_pool",
                "ordering": ["game", "order", "map_name"],
                "indexes": [
                    models.Index(
                        fields=["game", "is_active", "order"], name="games_map_p_game_id_2ba09e_idx"
                    )
                ],
                "unique_together": {("game", "map_code")},
            },
        ),
        migrations.CreateModel(
            name="GamePipelineTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g. 'Standard Competitive', 'Casual Scrims')",
                        max_length=150,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the default template for the game",
                    ),
                ),
                (
                    "pipeline_mode",
                    models.CharField(
                        choices=[
                            ("veto", "Map Veto"),
                            ("direct", "Direct Ready"),
                            ("coin_toss", "Coin Toss"),
                        ],
                        default="direct",
                        help_text="How the match-room pipeline starts (veto, direct, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "scoring_type",
                    models.CharField(
                        choices=[
                            ("WIN_LOSS", "Win/Loss Only"),
                            ("POINTS", "Points-based"),
                            ("ROUNDS", "Round-based (FPS)"),
                            ("KILLS", "Kill-based (BR)"),
                            ("PLACEMENT", "Placement-based (BR)"),
                            ("GOALS", "Goal-based (Sports)"),
                            ("CUSTOM", "Custom Scoring"),
                        ],
                        default="WIN_LOSS",
                        help_text="Default scoring type for matches using this template",
                        max_length=20,
                    ),
                ),
                (
                    "default_match_format",
                    models.CharField(
                        choices=[
                            ("BO1", "Best of 1"),
                            ("BO3", "Best of 3"),
                            ("BO5", "Best of 5"),
                            ("BO7", "Best of 7"),
                        ],
                        default="BO3",
                        max_length=10,
                    ),
                ),
                (
                    "credential_schema",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='JSON array of lobby credential fields. Example: [{"key": "lobby_code", "label": "Lobby Code", "kind": "text", "required": true}]',
                    ),
                ),
                (
                    "tiebreakers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of tiebreaker keys (e.g. ['goal_difference', 'goals_for'])",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        help_text="The game this template applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_templates",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Pipeline Template",
                "verbose_name_plural": "Game Pipeline Templates",
                "db_table": "games_pipeline_template",
                "ordering": ["game", "-is_default", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("game",),
                        name="unique_default_template_per_game",
                    )
                ],
            },
        ),
    ]
