# Generated by Django 5.2.8 on 2025-12-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_available_ranks"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE games_game
                ADD COLUMN IF NOT EXISTS has_rank_system boolean DEFAULT false NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE games_game DROP COLUMN IF EXISTS has_rank_system;
            """,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE games_game
                ADD COLUMN IF NOT EXISTS has_servers boolean DEFAULT false NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE games_game DROP COLUMN IF EXISTS has_servers;
            """,
        ),
    ]
