# Generated by Django 5.2.8 on 2025-12-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_available_ranks"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="has_rank_system",
            field=models.BooleanField(
                default=False, help_text="Does this game have a competitive rank/tier system?"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="has_servers",
            field=models.BooleanField(
                default=False,
                help_text="Does this game have regional servers that affect gameplay/ranking?",
            ),
        ),
    ]
