# Generated by Django 5.2.8 on 2025-12-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_add_conditional_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="available_ranks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Game-specific ranks: [{'value': 'iron', 'label': 'Iron'}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="has_rank_system",
            field=models.BooleanField(
                default=False, help_text="Does this game have a competitive rank/tier system?"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="has_servers",
            field=models.BooleanField(
                default=False,
                help_text="Does this game have regional servers that affect gameplay/ranking?",
            ),
        ),
    ]
