# Generated by Django 5.2.8 on 2026-05-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_maintenancerunlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mediacleanupcandidate",
            new_name="games_media_status_21cd18_idx",
            old_name="games_media_status_elig_idx",
        ),
        migrations.RenameIndex(
            model_name="mediacleanupcandidate",
            new_name="games_media_file_na_da355b_idx",
            old_name="games_media_file_name_idx",
        ),
    ]
