
> CREATE TABLE "organizations_team" ("id" bigint NOT NULL 
PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" 
varchar(100) NOT NULL, "slug" varchar(100) NOT NULL UNIQUE, 
"game_id" integer NOT NULL, "region" varchar(50) NOT NULL, 
"status" varchar(20) NOT NULL, "logo" varchar(100) NULL, 
"banner" varchar(100) NULL, "description" text NOT NULL, 
"preferred_server" varchar(50) NOT NULL, 
"emergency_contact_discord" varchar(50) NOT NULL, 
"emergency_contact_phone" varchar(20) NOT NULL, 
"is_temporary" boolean NOT NULL, "created_at" timestamp 
with time zone NOT NULL, "updated_at" timestamp with time 
zone NOT NULL, "organization_id" bigint NULL, "owner_id" 
bigint NULL);
  --
  -- Create model OrganizationMembership
  --
  CREATE TABLE "organizations_org_membership" ("id" bigint 
NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
"role" varchar(20) NOT NULL, "permissions" jsonb NOT NULL, 
"joined_at" timestamp with time zone NOT NULL, 
"organization_id" bigint NOT NULL, "user_id" bigint NOT 
NULL);
  --


