"""Create missing organizations_organization table"""
import django, os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'deltacrown.settings')
django.setup()

from django.db import connection

create_table_sql = """
CREATE TABLE IF NOT EXISTS "organizations_organization" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL UNIQUE,
    "slug" varchar(100) NOT NULL UNIQUE,
    "is_verified" boolean NOT NULL DEFAULT false,
    "verification_date" timestamp with time zone NULL,
    "logo" varchar(100) NULL,
    "badge" varchar(100) NULL,
    "banner" varchar(100) NULL,
    "description" text NOT NULL DEFAULT '',
    "website" varchar(200) NULL,
    "twitter" varchar(50) NULL,
    "master_wallet_id" integer NULL,
    "enforce_brand" boolean NOT NULL DEFAULT false,
    "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT NOW(),
    "ceo_id" bigint NULL
);
"""

create_indexes_sql = """
CREATE INDEX IF NOT EXISTS "org_slug_idx" ON "organizations_organization" ("slug");
CREATE INDEX IF NOT EXISTS "org_ceo_idx" ON "organizations_organization" ("ceo_id");
CREATE INDEX IF NOT EXISTS "org_verified_idx" ON "organizations_organization" ("is_verified");
"""

with connection.cursor() as cursor:
    print("Creating organizations_organization table...")
    cursor.execute(create_table_sql)
    print("✓ Table created")
    
    print("Creating indexes...")
    cursor.execute(create_indexes_sql)
    print("✓ Indexes created")
    
    # Verify table exists
    cursor.execute("""
        SELECT EXISTS (
            SELECT FROM pg_tables 
            WHERE schemaname = 'public' 
            AND tablename = 'organizations_organization'
        )
    """)
    exists = cursor.fetchone()[0]
    if exists:
        print("✓ organizations_organization table now exists")
    else:
        print("✗ FAILED: Table still doesn't exist")
