"""
Manually create the organizations_team table that is missing from the database.
This is a temporary fix until we can properly resolve the migration state.
"""
import django
import os

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'deltacrown.settings')
django.setup()

from django.db import connection

# Create the organizations_team table using the exact SQL from the migration
create_table_sql = """
CREATE TABLE IF NOT EXISTS "organizations_team" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "name" varchar(100) NOT NULL, 
    "slug" varchar(100) NOT NULL UNIQUE, 
    "game_id" integer NOT NULL, 
    "region" varchar(50) NOT NULL, 
    "status" varchar(20) NOT NULL, 
    "logo" varchar(100) NULL, 
    "banner" varchar(100) NULL, 
    "description" text NOT NULL, 
    "preferred_server" varchar(50) NOT NULL, 
    "emergency_contact_discord" varchar(50) NOT NULL, 
    "emergency_contact_phone" varchar(20) NOT NULL, 
    "is_temporary" boolean NOT NULL, 
    "created_at" timestamp with time zone NOT NULL, 
    "updated_at" timestamp with time zone NOT NULL, 
    "organization_id" bigint NULL, 
    "owner_id" bigint NULL,
    "tag" varchar(10) NULL,
    "tagline" varchar(200) NULL,
    "visibility" varchar(20) DEFAULT 'PUBLIC',
    "twitter" varchar(50) NULL,
    "youtube" varchar(100) NULL,
    "twitch" varchar(50) NULL,
    "discord" varchar(100) NULL,
    "facebook" varchar(100) NULL,
    "primary_color" varchar(7) NULL,
    "secondary_color" varchar(7) NULL,
    CONSTRAINT "organizations_team_game_id_9a7e2f3b" CHECK ("game_id" >= 0)
);
"""

create_indexes_sql = """
CREATE INDEX IF NOT EXISTS "organizations_team_game_id_9a7e2f3b" ON "organizations_team" ("game_id");
CREATE INDEX IF NOT EXISTS "organizations_team_slug_a4e8d1c2" ON "organizations_team" ("slug");
CREATE INDEX IF NOT EXISTS "organizations_team_organization_id_1a2b3c4d" ON "organizations_team" ("organization_id");
CREATE INDEX IF NOT EXISTS "organizations_team_owner_id_5e6f7g8h" ON "organizations_team" ("owner_id");
CREATE INDEX IF NOT EXISTS "organizations_team_status_9i0j1k2l" ON "organizations_team" ("status");
"""

with connection.cursor() as cursor:
    print("Creating organizations_team table...")
    cursor.execute(create_table_sql)
    print("✓ Table created")
    
    print("Creating indexes...")
    cursor.execute(create_indexes_sql)
    print("✓ Indexes created")
    
    # Verify table exists
    cursor.execute("""
        SELECT EXISTS (
            SELECT FROM pg_tables 
            WHERE schemaname = 'public' 
            AND tablename = 'organizations_team'
        )
    """)
    exists = cursor.fetchone()[0]
    if exists:
        print("✓ organizations_team table now exists")
    else:
        print("✗ FAILED: Table still doesn't exist")
