"""
Update games with 2025 competitive ranks using actual game names
"""
import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'deltacrown.settings')
django.setup()

from apps.games.models import Game

# Real 2025 competitive ranks for each game
RANKS_BY_NAME = {
    'VALORANT': [
        {'value': 'iron_1', 'label': 'Iron 1'},
        {'value': 'iron_2', 'label': 'Iron 2'},
        {'value': 'iron_3', 'label': 'Iron 3'},
        {'value': 'bronze_1', 'label': 'Bronze 1'},
        {'value': 'bronze_2', 'label': 'Bronze 2'},
        {'value': 'bronze_3', 'label': 'Bronze 3'},
        {'value': 'silver_1', 'label': 'Silver 1'},
        {'value': 'silver_2', 'label': 'Silver 2'},
        {'value': 'silver_3', 'label': 'Silver 3'},
        {'value': 'gold_1', 'label': 'Gold 1'},
        {'value': 'gold_2', 'label': 'Gold 2'},
        {'value': 'gold_3', 'label': 'Gold 3'},
        {'value': 'platinum_1', 'label': 'Platinum 1'},
        {'value': 'platinum_2', 'label': 'Platinum 2'},
        {'value': 'platinum_3', 'label': 'Platinum 3'},
        {'value': 'diamond_1', 'label': 'Diamond 1'},
        {'value': 'diamond_2', 'label': 'Diamond 2'},
        {'value': 'diamond_3', 'label': 'Diamond 3'},
        {'value': 'ascendant_1', 'label': 'Ascendant 1'},
        {'value': 'ascendant_2', 'label': 'Ascendant 2'},
        {'value': 'ascendant_3', 'label': 'Ascendant 3'},
        {'value': 'immortal_1', 'label': 'Immortal 1'},
        {'value': 'immortal_2', 'label': 'Immortal 2'},
        {'value': 'immortal_3', 'label': 'Immortal 3'},
        {'value': 'radiant', 'label': 'Radiant'},
    ],
    'Counter-Strike 2': [
        {'value': 'silver_1', 'label': 'Silver 1'},
        {'value': 'silver_2', 'label': 'Silver 2'},
        {'value': 'silver_3', 'label': 'Silver 3'},
        {'value': 'silver_4', 'label': 'Silver 4'},
        {'value': 'silver_elite', 'label': 'Silver Elite'},
        {'value': 'silver_elite_master', 'label': 'Silver Elite Master'},
        {'value': 'gold_nova_1', 'label': 'Gold Nova 1'},
        {'value': 'gold_nova_2', 'label': 'Gold Nova 2'},
        {'value': 'gold_nova_3', 'label': 'Gold Nova 3'},
        {'value': 'gold_nova_master', 'label': 'Gold Nova Master'},
        {'value': 'master_guardian_1', 'label': 'Master Guardian I'},
        {'value': 'master_guardian_2', 'label': 'Master Guardian II'},
        {'value': 'master_guardian_elite', 'label': 'Master Guardian Elite'},
        {'value': 'distinguished_master_guardian', 'label': 'Distinguished Master Guardian'},
        {'value': 'legendary_eagle', 'label': 'Legendary Eagle'},
        {'value': 'legendary_eagle_master', 'label': 'Legendary Eagle Master'},
        {'value': 'supreme_master_first_class', 'label': 'Supreme Master First Class'},
        {'value': 'the_global_elite', 'label': 'The Global Elite'},
    ],
    'Dota 2': [
        {'value': 'herald', 'label': 'Herald'},
        {'value': 'guardian', 'label': 'Guardian'},
        {'value': 'crusader', 'label': 'Crusader'},
        {'value': 'archon', 'label': 'Archon'},
        {'value': 'legend', 'label': 'Legend'},
        {'value': 'ancient', 'label': 'Ancient'},
        {'value': 'divine', 'label': 'Divine'},
        {'value': 'immortal', 'label': 'Immortal'},
    ],
    'EA SPORTS FC™ 26': [
        {'value': 'division_10', 'label': 'Division 10'},
        {'value': 'division_9', 'label': 'Division 9'},
        {'value': 'division_8', 'label': 'Division 8'},
        {'value': 'division_7', 'label': 'Division 7'},
        {'value': 'division_6', 'label': 'Division 6'},
        {'value': 'division_5', 'label': 'Division 5'},
        {'value': 'division_4', 'label': 'Division 4'},
        {'value': 'division_3', 'label': 'Division 3'},
        {'value': 'division_2', 'label': 'Division 2'},
        {'value': 'division_1', 'label': 'Division 1'},
        {'value': 'elite_division', 'label': 'Elite Division'},
    ],
    'eFootball™ 2026': [
        {'value': 'beginner', 'label': 'Beginner'},
        {'value': 'amateur', 'label': 'Amateur'},
        {'value': 'intermediate', 'label': 'Intermediate'},
        {'value': 'advanced', 'label': 'Advanced'},
        {'value': 'professional', 'label': 'Professional'},
        {'value': 'expert', 'label': 'Expert'},
        {'value': 'champion', 'label': 'Champion'},
    ],
    'PUBG MOBILE': [
        {'value': 'bronze', 'label': 'Bronze'},
        {'value': 'silver', 'label': 'Silver'},
        {'value': 'gold', 'label': 'Gold'},
        {'value': 'platinum', 'label': 'Platinum'},
        {'value': 'diamond', 'label': 'Diamond'},
        {'value': 'crown', 'label': 'Crown'},
        {'value': 'ace', 'label': 'Ace'},
        {'value': 'ace_master', 'label': 'Ace Master'},
        {'value': 'ace_dominator', 'label': 'Ace Dominator'},
        {'value': 'conqueror', 'label': 'Conqueror'},
    ],
    'Mobile Legends: Bang Bang': [
        {'value': 'warrior', 'label': 'Warrior'},
        {'value': 'elite', 'label': 'Elite'},
        {'value': 'master', 'label': 'Master'},
        {'value': 'grandmaster', 'label': 'Grandmaster'},
        {'value': 'epic', 'label': 'Epic'},
        {'value': 'legend', 'label': 'Legend'},
        {'value': 'mythic', 'label': 'Mythic'},
        {'value': 'mythic_honor', 'label': 'Mythic Honor'},
        {'value': 'mythic_glory', 'label': 'Mythic Glory'},
        {'value': 'mythic_immortal', 'label': 'Mythic Immortal'},
    ],
    'Free Fire': [
        {'value': 'bronze', 'label': 'Bronze'},
        {'value': 'silver', 'label': 'Silver'},
        {'value': 'gold', 'label': 'Gold'},
        {'value': 'platinum', 'label': 'Platinum'},
        {'value': 'diamond', 'label': 'Diamond'},
        {'value': 'heroic', 'label': 'Heroic'},
        {'value': 'grandmaster', 'label': 'Grandmaster'},
    ],
    'Call of Duty®: Mobile': [
        {'value': 'rookie', 'label': 'Rookie'},
        {'value': 'veteran', 'label': 'Veteran'},
        {'value': 'elite', 'label': 'Elite'},
        {'value': 'pro', 'label': 'Pro'},
        {'value': 'master', 'label': 'Master'},
        {'value': 'grandmaster', 'label': 'Grandmaster'},
        {'value': 'legendary', 'label': 'Legendary'},
    ],
    'Rocket League': [
        {'value': 'bronze_1', 'label': 'Bronze I'},
        {'value': 'bronze_2', 'label': 'Bronze II'},
        {'value': 'bronze_3', 'label': 'Bronze III'},
        {'value': 'silver_1', 'label': 'Silver I'},
        {'value': 'silver_2', 'label': 'Silver II'},
        {'value': 'silver_3', 'label': 'Silver III'},
        {'value': 'gold_1', 'label': 'Gold I'},
        {'value': 'gold_2', 'label': 'Gold II'},
        {'value': 'gold_3', 'label': 'Gold III'},
        {'value': 'platinum_1', 'label': 'Platinum I'},
        {'value': 'platinum_2', 'label': 'Platinum II'},
        {'value': 'platinum_3', 'label': 'Platinum III'},
        {'value': 'diamond_1', 'label': 'Diamond I'},
        {'value': 'diamond_2', 'label': 'Diamond II'},
        {'value': 'diamond_3', 'label': 'Diamond III'},
        {'value': 'champion_1', 'label': 'Champion I'},
        {'value': 'champion_2', 'label': 'Champion II'},
        {'value': 'champion_3', 'label': 'Champion III'},
        {'value': 'grand_champion_1', 'label': 'Grand Champion I'},
        {'value': 'grand_champion_2', 'label': 'Grand Champion II'},
        {'value': 'grand_champion_3', 'label': 'Grand Champion III'},
        {'value': 'supersonic_legend', 'label': 'Supersonic Legend'},
    ],
    'Tom Clancy\'s Rainbow Six® Siege': [
        {'value': 'copper_5', 'label': 'Copper V'},
        {'value': 'copper_4', 'label': 'Copper IV'},
        {'value': 'copper_3', 'label': 'Copper III'},
        {'value': 'copper_2', 'label': 'Copper II'},
        {'value': 'copper_1', 'label': 'Copper I'},
        {'value': 'bronze_5', 'label': 'Bronze V'},
        {'value': 'bronze_4', 'label': 'Bronze IV'},
        {'value': 'bronze_3', 'label': 'Bronze III'},
        {'value': 'bronze_2', 'label': 'Bronze II'},
        {'value': 'bronze_1', 'label': 'Bronze I'},
        {'value': 'silver_5', 'label': 'Silver V'},
        {'value': 'silver_4', 'label': 'Silver IV'},
        {'value': 'silver_3', 'label': 'Silver III'},
        {'value': 'silver_2', 'label': 'Silver II'},
        {'value': 'silver_1', 'label': 'Silver I'},
        {'value': 'gold_3', 'label': 'Gold III'},
        {'value': 'gold_2', 'label': 'Gold II'},
        {'value': 'gold_1', 'label': 'Gold I'},
        {'value': 'platinum_3', 'label': 'Platinum III'},
        {'value': 'platinum_2', 'label': 'Platinum II'},
        {'value': 'platinum_1', 'label': 'Platinum I'},
        {'value': 'emerald_3', 'label': 'Emerald III'},
        {'value': 'emerald_2', 'label': 'Emerald II'},
        {'value': 'emerald_1', 'label': 'Emerald I'},
        {'value': 'diamond_3', 'label': 'Diamond III'},
        {'value': 'diamond_2', 'label': 'Diamond II'},
        {'value': 'diamond_1', 'label': 'Diamond I'},
        {'value': 'champion', 'label': 'Champion'},
    ],
}

print("\n===== UPDATING GAMES WITH 2025 COMPETITIVE RANKS =====\n")

for game_name, ranks in RANKS_BY_NAME.items():
    try:
        game = Game.objects.get(name=game_name)
        game.available_ranks = ranks
        game.save()
        print(f"✓ {game.name}: {len(ranks)} ranks added")
    except Game.DoesNotExist:
        print(f"✗ Game not found: {game_name}")

print("\n===== DONE! =====")
print(f"Updated {len(RANKS_BY_NAME)} games with authentic 2025 competitive ranks")
