# Generated by Django 5.2.8 on 2025-11-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='file_type',
            field=models.CharField(blank=True, choices=[('IMAGE', 'Image'), ('PDF', 'PDF Document')], default='', help_text='Type of uploaded proof file', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, default='', help_text='Payment reference number from receipt', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Payment proof file upload (image or PDF, max 5MB)', null=True, upload_to='payment_proofs/%Y/%m/'),
        ),
    ]
