# Generated by Django 5.2.8 on 2026-01-23 17:57

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False  # Changed from True - FK additions must run after initial batch

    dependencies = [
        ("teams", "0002_initial"),
        ("tournaments", "0001_initial"),
        ("user_profile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentteaminvitation",
            name="invited_by",
            field=models.ForeignKey(
                help_text="Organizer/staff who sent the invitation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_tournament_invitations",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="tournamentteaminvitation",
            name="registration",
            field=models.OneToOneField(
                blank=True,
                help_text="Registration created when invitation was accepted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_from_invitation",
                to="tournaments.registration",
            ),
        ),
        migrations.AddField(
            model_name="tournamentteaminvitation",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Team member who responded to invitation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responded_tournament_invitations",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="tournamentteaminvitation",
            name="team",
            field=models.ForeignKey(
                help_text="Team being invited",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_invitations",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="tournamentteaminvitation",
            name="tournament",
            field=models.ForeignKey(
                help_text="Tournament extending the invitation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_invitations",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="tournamenttemplate",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this template",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamenttemplate",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamenttemplate",
            name="game",
            field=models.ForeignKey(
                blank=True,
                help_text="Game for this template (null = multi-game)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="tournaments.game",
            ),
        ),
        migrations.AddField(
            model_name="tournamentversion",
            name="changed_by",
            field=models.ForeignKey(
                help_text="User who made this change",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_version_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamentversion",
            name="rolled_back_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the rollback",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_version_rollbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamentversion",
            name="tournament",
            field=models.ForeignKey(
                help_text="Tournament this version belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="webhook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="tournaments.formwebhook",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="tournaments_action_39ba8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "timestamp"], name="tournaments_user_id_2867cc_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tournament_id", "timestamp"], name="tournaments_tournam_6d0f12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["match_id", "timestamp"], name="tournaments_match_i_2383e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["correlation_id"], name="tournaments_correla_e1e6fb_idx"),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(fields=["dispute"], name="idx_evidence_dispute"),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(fields=["created_at"], name="idx_evidence_created_at"),
        ),
        migrations.AddIndex(
            model_name="groupstanding",
            index=models.Index(
                fields=["group", "is_deleted"], name="tournament__group_i_f1ecf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupstanding",
            index=models.Index(fields=["group", "rank"], name="tournament__group_i_80c9f3_idx"),
        ),
        migrations.AddIndex(
            model_name="groupstanding",
            index=models.Index(
                fields=["group", "-points", "-goal_difference"],
                name="tournament__group_i_0f377c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="groupstanding",
            index=models.Index(
                fields=["user", "is_deleted"], name="tournament__user_id_4f5139_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupstanding",
            index=models.Index(
                fields=["team", "is_deleted"], name="tournament__team_id_f2eb53_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupstanding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("team__isnull", True)),
                    models.Q(("user__isnull", True), ("team__isnull", False)),
                    _connector="OR",
                ),
                name="group_standing_user_or_team_xor",
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["match", "status"], name="idx_dispute_match_status"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["status", "created_at"], name="idx_dispute_status_created"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["reason"], name="idx_dispute_reason"),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reason__in",
                        ["score_mismatch", "no_show", "cheating", "technical_issue", "other"],
                    )
                ),
                name="chk_dispute_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["open", "under_review", "resolved", "escalated"])
                ),
                name="chk_dispute_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="bracketnode",
            index=models.Index(fields=["bracket"], name="idx_bracketnode_bracket"),
        ),
        migrations.AddIndex(
            model_name="bracketnode",
            index=models.Index(fields=["bracket", "round_number"], name="idx_bracketnode_round"),
        ),
        migrations.AddIndex(
            model_name="bracketnode",
            index=models.Index(fields=["position"], name="idx_bracketnode_position"),
        ),
        migrations.AddIndex(
            model_name="bracketnode",
            index=models.Index(fields=["match"], name="idx_bracketnode_match"),
        ),
        migrations.AddIndex(
            model_name="bracketnode",
            index=models.Index(fields=["parent_node"], name="idx_bracketnode_parent"),
        ),
        migrations.AddIndex(
            model_name="bracketnode",
            index=models.Index(
                fields=["bracket", "child1_node", "child2_node"], name="idx_bracketnode_children"
            ),
        ),
        migrations.AddIndex(
            model_name="bracketnode",
            index=models.Index(
                fields=["participant1_id", "participant2_id"], name="idx_bracketnode_participants"
            ),
        ),
        migrations.AddConstraint(
            model_name="bracketnode",
            constraint=models.UniqueConstraint(
                fields=("bracket", "position"), name="uq_bracketnode_bracket_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="bracketnode",
            constraint=models.CheckConstraint(
                condition=models.Q(("round_number__gt", 0)), name="chk_bracketnode_round_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="bracketnode",
            constraint=models.CheckConstraint(
                condition=models.Q(("match_number_in_round__gt", 0)),
                name="chk_bracketnode_match_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="bracketnode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent_slot__isnull", True), ("parent_slot__in", [1, 2]), _connector="OR"
                ),
                name="chk_bracketnode_parent_slot",
            ),
        ),
        migrations.AddIndex(
            model_name="matchmoderatornote",
            index=models.Index(
                fields=["match", "created_at"], name="match_moder_match_i_0b3733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchmoderatornote",
            index=models.Index(
                fields=["author_user_id", "created_at"], name="match_moder_author__b7bd70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchoperationlog",
            index=models.Index(
                fields=["match", "created_at"], name="match_opera_match_i_f2124c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchoperationlog",
            index=models.Index(
                fields=["operation_type", "created_at"], name="match_opera_operati_c45d02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchoperationlog",
            index=models.Index(
                fields=["operator_user_id", "created_at"], name="match_opera_operato_2d5df3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchresultsubmission",
            index=models.Index(fields=["match", "status"], name="idx_submission_match_status"),
        ),
        migrations.AddIndex(
            model_name="matchresultsubmission",
            index=models.Index(fields=["submitted_at"], name="idx_submission_submitted_at"),
        ),
        migrations.AddIndex(
            model_name="matchresultsubmission",
            index=models.Index(fields=["auto_confirm_deadline"], name="idx_submission_deadline"),
        ),
        migrations.AddIndex(
            model_name="disputerecord",
            index=models.Index(
                fields=["submission", "status"], name="idx_dispute_submission_status"
            ),
        ),
        migrations.AddIndex(
            model_name="disputerecord",
            index=models.Index(fields=["opened_at"], name="idx_dispute_opened_at"),
        ),
        migrations.AddIndex(
            model_name="disputerecord",
            index=models.Index(fields=["resolved_at"], name="idx_dispute_resolved_at"),
        ),
        migrations.AddIndex(
            model_name="disputerecord",
            index=models.Index(fields=["status"], name="idx_dispute_status"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["registration"], name="tournaments_registr_e9e4b4_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_method", "status"], name="tournaments_payment_2b7bd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "-submitted_at"], name="tournaments_status_51a576_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["verified_by", "verified_at"], name="tournaments_verifie_c340c8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("payment_method__in", ["bkash", "nagad", "rocket", "bank", "deltacoin"])
                ),
                name="payment_method_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "submitted", "verified", "rejected", "refunded"])
                ),
                name="payment_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "verified"),
                        ("verified_at__isnull", False),
                        ("verified_by__isnull", False),
                    ),
                    models.Q(("status", "verified"), _negated=True),
                    _connector="OR",
                ),
                name="payment_verification_complete",
            ),
        ),
        migrations.AddIndex(
            model_name="registrationformtemplate",
            index=models.Index(fields=["participation_type", "game"], name="formtpl_type_game_idx"),
        ),
        migrations.AddIndex(
            model_name="registrationformtemplate",
            index=models.Index(
                fields=["is_active", "is_system_template"], name="formtpl_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrationformtemplate",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tags"], name="formtpl_tags_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrationanswer",
            index=models.Index(fields=["registration"], name="tournaments_registr_69595e_idx"),
        ),
        migrations.AddIndex(
            model_name="registrationanswer",
            index=models.Index(fields=["question"], name="tournaments_questio_2d7e06_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="registrationanswer",
            unique_together={("registration", "question")},
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["status", "tournament_start"], name="tournaments_status_bdcbab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["game", "status"], name="tournaments_game_id_c3d078_idx"),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["organizer", "status"], name="tournaments_organiz_e7ca48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["slug"], name="tournaments_slug_2e3c0a_idx"),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["is_official", "tournament_start"], name="tournaments_is_offi_24a3c6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_participants__gte", 2)), name="min_participants_at_least_2"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_participants__gte", models.F("min_participants"))),
                name="max_participants_gte_min_participants",
            ),
        ),
        migrations.AddIndex(
            model_name="teamregistrationpermissionrequest",
            index=models.Index(
                fields=["status", "created_at"], name="tournaments_status_e9028f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamregistrationpermissionrequest",
            index=models.Index(fields=["team", "status"], name="tournaments_team_id_228dde_idx"),
        ),
        migrations.AddIndex(
            model_name="teamregistrationpermissionrequest",
            index=models.Index(
                fields=["requester", "status"], name="tournaments_request_35bd76_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamregistrationpermissionrequest",
            unique_together={("team", "tournament", "requester", "status")},
        ),
        migrations.AddIndex(
            model_name="registrationrule",
            index=models.Index(
                fields=["tournament", "is_active", "priority"],
                name="tournaments_tournam_f4f1d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registrationquestion",
            index=models.Index(
                fields=["tournament", "order"], name="tournaments_tournam_8f69ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrationquestion",
            index=models.Index(fields=["game", "order"], name="tournaments_game_id_f4dffb_idx"),
        ),
        migrations.AddIndex(
            model_name="registrationquestion",
            index=models.Index(fields=["slug"], name="tournaments_slug_28527a_idx"),
        ),
        migrations.AddIndex(
            model_name="registrationdraft",
            index=models.Index(fields=["uuid"], name="tournaments_uuid_5b9ded_idx"),
        ),
        migrations.AddIndex(
            model_name="registrationdraft",
            index=models.Index(
                fields=["registration_number"], name="tournaments_registr_3c3301_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrationdraft",
            index=models.Index(fields=["expires_at"], name="tournaments_expires_437943_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="registrationdraft",
            unique_together={("user", "tournament")},
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["tournament", "status"], name="tournaments_tournam_c14717_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["user", "-created_at"], name="tournaments_user_id_fa73e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["team_id", "-created_at"], name="tournaments_team_id_ca35f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["status", "registered_at"], name="tournaments_status_f855db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["tournament", "slot_number"], name="tournaments_tournam_951e51_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("team_id__isnull", True), ("user__isnull", False)),
                    models.Q(("team_id__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="registration_user_xor_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("slot_number__isnull", False)),
                fields=("tournament", "slot_number"),
                name="unique_slot_per_tournament",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("team_id__isnull", False)),
                fields=("tournament", "team_id"),
                name="unique_team_per_tournament",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending",
                            "payment_submitted",
                            "confirmed",
                            "rejected",
                            "cancelled",
                            "no_show",
                        ],
                    )
                ),
                name="registration_valid_status",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("tournament", "user")},
        ),
        migrations.AddIndex(
            model_name="prizetransaction",
            index=models.Index(fields=["tournament", "status"], name="prize_tournament_status_idx"),
        ),
        migrations.AddIndex(
            model_name="prizetransaction",
            index=models.Index(fields=["participant"], name="prize_participant_idx"),
        ),
        migrations.AddIndex(
            model_name="prizetransaction",
            index=models.Index(fields=["coin_transaction_id"], name="prize_coin_tx_idx"),
        ),
        migrations.AddConstraint(
            model_name="prizetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="prize_amount_positive",
                violation_error_message="Prize amount must be non-negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="prizetransaction",
            constraint=models.UniqueConstraint(
                fields=("tournament", "participant", "placement"),
                name="unique_prize_per_participant_placement",
                violation_error_message="Participant can only receive one prize per placement per tournament",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["tournament"], name="idx_match_tournament"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["bracket"], name="idx_match_bracket"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["bracket", "round_number"], name="idx_match_round"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["state"], name="idx_match_state"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["scheduled_time"], name="idx_match_scheduled"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["participant1_id", "participant2_id"], name="idx_match_participants"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["winner_id"], name="idx_match_winner"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                condition=models.Q(("state", "check_in")),
                fields=["check_in_deadline", "state"],
                name="idx_match_check_in",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                condition=models.Q(("state", "live")),
                fields=["tournament", "state"],
                name="idx_match_live",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["lobby_info"], name="idx_match_lobby_gin"),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "scheduled",
                            "check_in",
                            "ready",
                            "live",
                            "pending_result",
                            "completed",
                            "disputed",
                            "forfeit",
                            "cancelled",
                        ],
                    )
                ),
                name="chk_match_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(("participant1_score__gte", 0), ("participant2_score__gte", 0)),
                name="chk_match_scores_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("loser_id__isnull", False),
                        ("state", "completed"),
                        ("winner_id__isnull", False),
                    ),
                    models.Q(("state", "completed"), _negated=True),
                    _connector="OR",
                ),
                name="chk_match_completed_has_winner",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(("round_number__gt", 0), ("match_number__gt", 0)),
                name="chk_match_numbers_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="groupstage",
            index=models.Index(
                fields=["tournament", "state"], name="tournament__tournam_149f52_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupstage",
            constraint=models.CheckConstraint(
                condition=models.Q(("num_groups__gte", 1)), name="groupstage_min_groups"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupstage",
            constraint=models.CheckConstraint(
                condition=models.Q(("group_size__gte", 2)), name="groupstage_min_group_size"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupstage",
            constraint=models.CheckConstraint(
                condition=models.Q(("advancement_count_per_group__gte", 1)),
                name="groupstage_min_advancement",
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["tournament", "is_deleted"], name="tournament__tournam_c29a8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["tournament", "display_order"], name="tournament__tournam_8645e7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_participants__gte", 2)), name="group_min_participants"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.CheckConstraint(
                condition=models.Q(("advancement_count__gte", 1)), name="group_min_advancement"
            ),
        ),
        migrations.AddIndex(
            model_name="customfield",
            index=models.Index(
                fields=["tournament", "order"], name="tournaments_tournam_68e8eb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customfield",
            unique_together={("tournament", "field_key")},
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["tournament", "is_checked_in"], name="tournament__tournam_9b1ee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["tournament", "is_forfeited"], name="tournament__tournam_48ee90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(fields=["registration"], name="tournament__registr_5535aa_idx"),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["user", "tournament"], name="tournament__user_id_45beaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["team", "tournament"], name="tournament__team_id_cd3e44_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("team__isnull", True)),
                    models.Q(("user__isnull", True), ("team__isnull", False)),
                    _connector="OR",
                ),
                name="check_in_user_or_team_xor",
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["tournament", "certificate_type"], name="tournament__tournam_2379ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["participant"], name="tournament__partici_7878dd_idx"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["verification_code"], name="tournament__verific_700652_idx"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["revoked_at"], name="tournament__revoked_9ba592_idx"),
        ),
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("tournament", "participant", "certificate_type"),
                name="unique_cert_per_type_per_participant",
            ),
        ),
        migrations.AddIndex(
            model_name="bracket",
            index=models.Index(fields=["tournament"], name="idx_bracket_tournament"),
        ),
        migrations.AddIndex(
            model_name="bracket",
            index=models.Index(fields=["format"], name="idx_bracket_format"),
        ),
        migrations.AddIndex(
            model_name="bracket",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["bracket_structure"], name="idx_bracket_structure_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentannouncement",
            index=models.Index(
                fields=["tournament", "-created_at"], name="tournament__tournam_303fb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentannouncement",
            index=models.Index(
                fields=["is_pinned", "-created_at"], name="tournament__is_pinn_2a775f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lobbyannouncement",
            index=models.Index(
                fields=["lobby", "is_visible", "is_deleted"], name="tournament__lobby_i_548773_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lobbyannouncement",
            index=models.Index(
                fields=["lobby", "-is_pinned", "-created_at"], name="tournament__lobby_i_d10432_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentpaymentmethod",
            index=models.Index(
                fields=["tournament", "is_enabled"], name="tournaments_tournam_18174f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentpaymentmethod",
            index=models.Index(
                fields=["method", "is_enabled"], name="tournaments_method_0554ff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentpaymentmethod",
            unique_together={("tournament", "method")},
        ),
        migrations.AddIndex(
            model_name="formresponse",
            index=models.Index(fields=["tournament", "status"], name="formresp_tourn_status_idx"),
        ),
        migrations.AddIndex(
            model_name="formresponse",
            index=models.Index(fields=["user", "tournament"], name="formresp_user_tourn_idx"),
        ),
        migrations.AddIndex(
            model_name="formresponse",
            index=models.Index(
                fields=["status", "payment_verified"], name="formresp_status_pay_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formresponse",
            unique_together={("tournament", "user")},
        ),
        migrations.AddIndex(
            model_name="tournamentresult",
            index=models.Index(fields=["tournament"], name="idx_result_tournament"),
        ),
        migrations.AddIndex(
            model_name="tournamentresult",
            index=models.Index(fields=["winner"], name="idx_result_winner"),
        ),
        migrations.AddIndex(
            model_name="tournamentresult",
            index=models.Index(fields=["determination_method"], name="idx_result_method"),
        ),
        migrations.AddIndex(
            model_name="tournamentresult",
            index=models.Index(fields=["requires_review"], name="idx_result_review"),
        ),
        migrations.AddIndex(
            model_name="tournamentresult",
            index=models.Index(fields=["created_at"], name="idx_result_created"),
        ),
        migrations.AddConstraint(
            model_name="tournamentresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("runner_up", models.F("winner")), _negated=True),
                name="runner_up_not_winner",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("third_place__isnull", True),
                    models.Q(
                        models.Q(("third_place", models.F("winner")), _negated=True),
                        models.Q(("third_place", models.F("runner_up")), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="third_place_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="matchrefereeassignment",
            index=models.Index(
                fields=["match", "is_primary"], name="match_refer_match_i_6a7d06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchrefereeassignment",
            index=models.Index(fields=["staff_assignment"], name="match_refer_staff_a_1c2e52_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="matchrefereeassignment",
            unique_together={("match", "staff_assignment")},
        ),
        migrations.AddIndex(
            model_name="tournamentstaff",
            index=models.Index(
                fields=["tournament", "is_active"], name="tournaments_tournam_508750_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentstaff",
            index=models.Index(fields=["user", "is_active"], name="tournaments_user_id_52e2b7_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamentstaff",
            index=models.Index(
                fields=["tournament", "user"], name="tournaments_tournam_a3baa6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentstaff",
            unique_together={("tournament", "user", "role")},
        ),
        migrations.AddIndex(
            model_name="tournamentstage",
            index=models.Index(
                fields=["tournament", "order"], name="tournament__tournam_1b0228_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentstage",
            index=models.Index(
                fields=["tournament", "state"], name="tournament__tournam_d6c7b1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentstage",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 1)), name="stage_min_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentstage",
            constraint=models.CheckConstraint(
                condition=models.Q(("advancement_count__gte", 0)), name="stage_min_advancement"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentstage",
            unique_together={("tournament", "order")},
        ),
        migrations.AddIndex(
            model_name="tournamentstaffassignment",
            index=models.Index(
                fields=["tournament", "is_active"], name="tournament__tournam_8d0a9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentstaffassignment",
            index=models.Index(fields=["user", "is_active"], name="tournament__user_id_64f712_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamentstaffassignment",
            index=models.Index(fields=["role", "is_active"], name="tournament__role_id_b751ea_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentstaffassignment",
            unique_together={("tournament", "user", "role")},
        ),
        migrations.AddIndex(
            model_name="tournamentteaminvitation",
            index=models.Index(fields=["tournament", "status"], name="tournament_inv_status_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamentteaminvitation",
            index=models.Index(fields=["team", "status"], name="team_inv_status_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamentteaminvitation",
            index=models.Index(fields=["invited_at"], name="tournaments_invited_fae84c_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamentteaminvitation",
            index=models.Index(fields=["expires_at"], name="tournaments_expires_587c66_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentteaminvitation",
            unique_together={("tournament", "team")},
        ),
        migrations.AddIndex(
            model_name="tournamenttemplate",
            index=models.Index(
                fields=["created_by", "is_active"], name="template_creator_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamenttemplate",
            index=models.Index(fields=["game", "visibility"], name="template_game_visibility_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamenttemplate",
            index=models.Index(
                fields=["visibility", "is_active"], name="template_visibility_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamenttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("created_by", "game", "name"),
                name="unique_template_per_creator_game_name",
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentversion",
            index=models.Index(
                fields=["tournament", "-version_number"], name="tournaments_tournam_2a9b1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentversion",
            index=models.Index(fields=["changed_at"], name="tournaments_changed_55b4d2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentversion",
            unique_together={("tournament", "version_number")},
        ),
    ]
