# Generated by Django 5.2.8 on 2025-11-07 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Action type (e.g., payment_verify, bracket_regenerate)', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('metadata', models.JSONField(default=dict, help_text='Action-specific data (tournament_id, payment_id, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from request', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null if system action)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='tournaments_action_39ba8c_idx'), models.Index(fields=['user', 'timestamp'], name='tournaments_user_id_2867cc_idx')],
            },
        ),
    ]
