# Generated by Django 5.2.8 on 2025-11-16 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='require_terms_acceptance',
            field=models.BooleanField(default=True, help_text='Require participants to explicitly accept terms during registration'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Terms and conditions that all participants must agree to'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='terms_pdf',
            field=models.FileField(blank=True, help_text='Terms & Conditions PDF document (optional)', null=True, upload_to='tournaments/terms/'),
        ),
        migrations.CreateModel(
            name='TournamentPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('deltacoin', 'DeltaCoin'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer')], help_text='Payment method type', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this payment method is currently active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order in payment options (lower = higher priority)')),
                ('bkash_account_number', models.CharField(blank=True, help_text='bKash account/merchant number (e.g., 01712345678)', max_length=20)),
                ('bkash_account_type', models.CharField(blank=True, choices=[('personal', 'Personal Account'), ('merchant', 'Merchant Account'), ('agent', 'Agent Account')], default='personal', help_text='Type of bKash account', max_length=20)),
                ('bkash_account_name', models.CharField(blank=True, help_text='Name on bKash account (for verification)', max_length=100)),
                ('bkash_instructions', models.TextField(blank=True, help_text='Step-by-step payment instructions for participants (supports Markdown)')),
                ('bkash_reference_required', models.BooleanField(default=True, help_text='Require participants to provide bKash transaction ID')),
                ('nagad_account_number', models.CharField(blank=True, help_text='Nagad account/merchant number', max_length=20)),
                ('nagad_account_type', models.CharField(blank=True, choices=[('personal', 'Personal Account'), ('merchant', 'Merchant Account'), ('agent', 'Agent Account')], default='personal', help_text='Type of Nagad account', max_length=20)),
                ('nagad_account_name', models.CharField(blank=True, help_text='Name on Nagad account', max_length=100)),
                ('nagad_instructions', models.TextField(blank=True, help_text='Step-by-step payment instructions for participants')),
                ('nagad_reference_required', models.BooleanField(default=True, help_text='Require participants to provide Nagad transaction ID')),
                ('rocket_account_number', models.CharField(blank=True, help_text='Rocket account number', max_length=20)),
                ('rocket_account_type', models.CharField(blank=True, choices=[('personal', 'Personal Account'), ('merchant', 'Merchant Account'), ('agent', 'Agent Account')], default='personal', help_text='Type of Rocket account', max_length=20)),
                ('rocket_account_name', models.CharField(blank=True, help_text='Name on Rocket account', max_length=100)),
                ('rocket_instructions', models.TextField(blank=True, help_text='Step-by-step payment instructions for participants')),
                ('rocket_reference_required', models.BooleanField(default=True, help_text='Require participants to provide Rocket transaction ID')),
                ('bank_name', models.CharField(blank=True, help_text='Bank name (e.g., Dutch Bangla Bank Limited)', max_length=100)),
                ('bank_branch', models.CharField(blank=True, help_text='Bank branch name/location', max_length=100)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number', max_length=50)),
                ('bank_account_name', models.CharField(blank=True, help_text='Account holder name', max_length=100)),
                ('bank_routing_number', models.CharField(blank=True, help_text='Bank routing number (if applicable)', max_length=50)),
                ('bank_swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code for international transfers', max_length=20)),
                ('bank_instructions', models.TextField(blank=True, help_text='Step-by-step bank transfer instructions')),
                ('bank_reference_required', models.BooleanField(default=True, help_text='Require participants to provide bank reference/transaction ID')),
                ('deltacoin_instructions', models.TextField(blank=True, help_text='Custom instructions for DeltaCoin payment (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(help_text='Tournament this payment method belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_configurations', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Payment Method',
                'verbose_name_plural': 'Tournament Payment Methods',
                'db_table': 'tournaments_tournament_payment_method',
                'ordering': ['display_order', 'method'],
                'indexes': [models.Index(fields=['tournament', 'is_enabled'], name='tournaments_tournam_18174f_idx'), models.Index(fields=['method', 'is_enabled'], name='tournaments_method_0554ff_idx')],
                'unique_together': {('tournament', 'method')},
            },
        ),
    ]
