# Generated by Django 5.2.8 on 2025-11-16 21:46

from django.db import migrations
from django.utils.text import slugify


def create_default_staff_roles(apps, schema_editor):
    """
    Create default tournament staff roles with permissions.
    
    These roles provide granular permission control for tournament staff.
    """
    TournamentStaffRole = apps.get_model('tournaments', 'TournamentStaffRole')
    
    default_roles = [
        {
            'name': 'Participant Reviewer',
            'slug': 'participant-reviewer',
            'description': 'Reviews and verifies participant registrations, checks eligibility, and approves/rejects applications.',
            'permissions': {
                'can_review_participants': True,
                'can_view_pii': True,
            },
            'is_system_role': True,
        },
        {
            'name': 'Payment Verifier',
            'slug': 'payment-verifier',
            'description': 'Verifies payment proofs and entry fees, confirms transactions, and updates payment status.',
            'permissions': {
                'can_verify_payments': True,
                'can_view_payment_proofs': True,
                'can_view_pii': True,
            },
            'is_system_role': True,
        },
        {
            'name': 'Bracket Manager',
            'slug': 'bracket-manager',
            'description': 'Creates and manages tournament brackets, handles seeding, and schedules matches.',
            'permissions': {
                'can_manage_brackets': True,
                'can_manage_matches': True,
            },
            'is_system_role': True,
        },
        {
            'name': 'Scorekeeper',
            'slug': 'scorekeeper',
            'description': 'Enters and verifies match scores, updates match results, and maintains accurate records.',
            'permissions': {
                'can_enter_scores': True,
                'can_manage_matches': True,
            },
            'is_system_role': True,
        },
        {
            'name': 'Dispute Resolver',
            'slug': 'dispute-resolver',
            'description': 'Handles match disputes, investigates claims, reviews evidence, and makes final rulings.',
            'permissions': {
                'can_handle_disputes': True,
                'can_view_pii': True,
            },
            'is_system_role': True,
        },
        {
            'name': 'Support Staff',
            'slug': 'support-staff',
            'description': 'Provides participant support, answers questions, and assists with technical issues.',
            'permissions': {
                'can_access_support': True,
                'can_view_pii': True,
            },
            'is_system_role': True,
        },
        {
            'name': 'Social Media Manager',
            'slug': 'social-media',
            'description': 'Manages tournament social media, posts updates, sends announcements, and engages with audience.',
            'permissions': {
                'can_send_notifications': True,
                'can_manage_social_media': True,
            },
            'is_system_role': True,
        },
        {
            'name': 'Tournament Admin',
            'slug': 'tournament-admin',
            'description': 'Full administrative access to all tournament management features. Can perform any action.',
            'permissions': {
                'can_review_participants': True,
                'can_verify_payments': True,
                'can_manage_brackets': True,
                'can_manage_matches': True,
                'can_enter_scores': True,
                'can_handle_disputes': True,
                'can_send_notifications': True,
                'can_manage_social_media': True,
                'can_access_support': True,
                'can_modify_tournament': True,
                'can_view_pii': True,
                'can_view_payment_proofs': True,
                'can_export_data': True,
            },
            'is_system_role': True,
        },
    ]
    
    created_count = 0
    for role_data in default_roles:
        permissions = role_data.pop('permissions')
        
        # Check if role already exists
        if not TournamentStaffRole.objects.filter(slug=role_data['slug']).exists():
            TournamentStaffRole.objects.create(
                **role_data,
                **permissions,
                is_active=True,
            )
            created_count += 1
    
    if created_count > 0:
        print(f"✅ Created {created_count} default staff roles")


def remove_default_staff_roles(apps, schema_editor):
    """Reverse migration: Remove default staff roles."""
    TournamentStaffRole = apps.get_model('tournaments', 'TournamentStaffRole')
    
    default_slugs = [
        'participant-reviewer',
        'payment-verifier',
        'bracket-manager',
        'scorekeeper',
        'dispute-resolver',
        'support-staff',
        'social-media',
        'tournament-admin',
    ]
    
    deleted_count = TournamentStaffRole.objects.filter(slug__in=default_slugs, is_system_role=True).delete()[0]
    if deleted_count > 0:
        print(f"🗑️ Removed {deleted_count} default staff roles")


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournamentstaffrole_tournamentstaff'),
    ]

    operations = [
        migrations.RunPython(create_default_staff_roles, remove_default_staff_roles),
    ]
