# Generated by Django 5.2.8 on 2026-02-10 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0033_journey_milestone"),
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamregistrationpermissionrequest",
            name="team",
            field=models.ForeignKey(
                help_text="Team for which permission is requested",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_permission_requests",
                to="organizations.team",
            ),
        ),
    ]
