# Generated by Django 5.2.8 on 2025-11-08 09:28

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_fix_migration_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the check-in (owner, captain, or organizer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
