# Generated by Django 4.2.23 on 2025-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_paymentverification_add_payer_txid'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentverification',
            name='pv_payer_account_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentverification',
            name='pv_transaction_id_idx',
        ),
        migrations.AlterField(
            model_name='paymentverification',
            name='payer_account_number',
            field=models.CharField(blank=True, help_text='Your bKash/Nagad/Rocket account number (payer)', max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentverification',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID from bKash/Nagad/Rocket', max_length=64),
        ),
    ]
