# Generated by Django 5.2.8 on 2025-11-16 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_require_terms_acceptance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentStaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name (e.g., "Participant Reviewer")', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=60, unique=True)),
                ('description', models.TextField(help_text='Detailed description of this role and its responsibilities')),
                ('can_review_participants', models.BooleanField(default=False, help_text='Can review and approve/reject participant registrations')),
                ('can_verify_payments', models.BooleanField(default=False, help_text='Can verify payment proofs and mark payments as confirmed')),
                ('can_manage_brackets', models.BooleanField(default=False, help_text='Can create, edit, and manage tournament brackets')),
                ('can_manage_matches', models.BooleanField(default=False, help_text='Can schedule, reschedule, and configure matches')),
                ('can_enter_scores', models.BooleanField(default=False, help_text='Can enter and verify match scores and results')),
                ('can_handle_disputes', models.BooleanField(default=False, help_text='Can view, investigate, and resolve match disputes')),
                ('can_send_notifications', models.BooleanField(default=False, help_text='Can send notifications and announcements to participants')),
                ('can_manage_social_media', models.BooleanField(default=False, help_text='Can post updates and manage tournament social media')),
                ('can_access_support', models.BooleanField(default=False, help_text='Can access support tickets and communicate with participants')),
                ('can_modify_tournament', models.BooleanField(default=False, help_text='Can edit tournament settings and configuration (admin only)')),
                ('can_view_pii', models.BooleanField(default=False, help_text='Can view personally identifiable information (names, emails, phone numbers)')),
                ('can_view_payment_proofs', models.BooleanField(default=False, help_text='Can view uploaded payment proof images and bank details')),
                ('can_export_data', models.BooleanField(default=False, help_text='Can export participant data to CSV/Excel')),
                ('is_system_role', models.BooleanField(default=False, help_text='System-defined role (cannot be deleted or significantly modified)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is available for assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tournament Staff Role',
                'verbose_name_plural': 'Tournament Staff Roles',
                'db_table': 'tournaments_staff_role',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='tournaments_slug_e11e8a_idx'), models.Index(fields=['is_active'], name='tournaments_is_acti_880e08_idx')],
            },
        ),
        migrations.CreateModel(
            name='TournamentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this staff assignment is currently active')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this staff assignment (not visible to staff member)')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When this staff member was assigned')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When this assignment was deactivated', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Organizer who assigned this staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='Who deactivated this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments_deactivated', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(help_text='Tournament this staff member is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='tournaments.tournament')),
                ('user', models.ForeignKey(help_text='User assigned as staff', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_staff_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role and permissions for this staff member', on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='tournaments.tournamentstaffrole')),
            ],
            options={
                'verbose_name': 'Tournament Staff Assignment',
                'verbose_name_plural': 'Tournament Staff Assignments',
                'db_table': 'tournaments_staff_assignment',
                'ordering': ['tournament', 'role__name', 'user__username'],
                'indexes': [models.Index(fields=['tournament', 'is_active'], name='tournaments_tournam_508750_idx'), models.Index(fields=['user', 'is_active'], name='tournaments_user_id_52e2b7_idx'), models.Index(fields=['tournament', 'user'], name='tournaments_tournam_a3baa6_idx')],
                'unique_together': {('tournament', 'user', 'role')},
            },
        ),
    ]
