# Generated by Django 5.2.8 on 2026-02-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
        ("tournaments", "0003_alter_teamregistrationpermissionrequest_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationformtemplate",
            name="game",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific game this template is designed for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_templates",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="game",
            field=models.ForeignKey(
                blank=True,
                help_text="Game-specific question (null for global)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_questions",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="game",
            field=models.ForeignKey(
                help_text="Game being played in this tournament",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tournaments",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="tournamenttemplate",
            name="game",
            field=models.ForeignKey(
                blank=True,
                help_text="Game for this template (null = multi-game)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="games.game",
            ),
        ),
    ]
