# Generated by Django 5.2.8 on 2026-02-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_switch_game_fk_to_games_app"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={
                "managed": False,
                "ordering": ["name"],
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
            },
        ),
    ]
