# Generated by Django 5.2.8 on 2026-02-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0005_alter_game_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="game",
            table="games_game",
        ),
    ]
