# Generated by Django 5.2.8 on 2025-11-16 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_create_default_staff_roles'),
        ('tournaments', '0005_create_default_staff_roles'),
    ]

    operations = [
    ]
