# Generated by Django 5.2.8 on 2025-11-09 16:08
# Module 5.1: Winner Determination - Combined index for audit queries

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_result'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tournamentresult',
            index=models.Index(fields=['tournament', 'determination_method'], name='idx_result_tour_method'),
        ),
    ]
