# Generated by Django 5.2.8 on 2025-11-16 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_merge_20251117_0551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned announcements appear at the top', verbose_name='Pinned')),
                ('is_important', models.BooleanField(default=False, help_text='Important announcements are highlighted', verbose_name='Important')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tournaments.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Tournament Announcement',
                'verbose_name_plural': 'Tournament Announcements',
                'db_table': 'tournament_announcements',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['tournament', '-created_at'], name='tournament__tournam_303fb6_idx'), models.Index(fields=['is_pinned', '-created_at'], name='tournament__is_pinn_2a775f_idx')],
            },
        ),
    ]
