# Generated by Django 5.2.8 on 2025-11-10
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0006_add_combined_index_tournament_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='PrizeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('placement', models.CharField(choices=[('1st', '1st Place'), ('2nd', '2nd Place'), ('3rd', '3rd Place'), ('participation', 'Participation Reward')], help_text='Placement earned by participant', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Prize amount in Delta Coins', max_digits=10)),
                ('coin_transaction_id', models.IntegerField(blank=True, db_index=True, help_text='ID of DeltaCrownTransaction in apps.economy (reference only, not FK)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Current status of this prize transaction', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for manual adjustments or reconciliation')),
                ('participant', models.ForeignKey(help_text='Registration receiving this prize', on_delete=django.db.models.deletion.PROTECT, related_name='prize_transactions', to='tournaments.registration')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who triggered the payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_prize_transactions', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(help_text='Tournament awarding this prize', on_delete=django.db.models.deletion.CASCADE, related_name='prize_transactions', to='tournaments.tournament')),
            ],
            options={'verbose_name': 'Prize Transaction', 'verbose_name_plural': 'Prize Transactions', 'db_table': 'tournament_engine_prize_prizetransaction', 'ordering': ['-created_at', '-id']},
        ),
        migrations.AddIndex(model_name='prizetransaction', index=models.Index(fields=['tournament', 'status'], name='prize_tournament_status_idx')),
        migrations.AddIndex(model_name='prizetransaction', index=models.Index(fields=['participant'], name='prize_participant_idx')),
        migrations.AddIndex(model_name='prizetransaction', index=models.Index(fields=['coin_transaction_id'], name='prize_coin_tx_idx')),
        migrations.AddConstraint(model_name='prizetransaction', constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='prize_amount_positive', violation_error_message='Prize amount must be non-negative')),
        migrations.AddConstraint(model_name='prizetransaction', constraint=models.UniqueConstraint(fields=('tournament', 'participant', 'placement'), name='unique_prize_per_participant_placement', violation_error_message='Participant can only receive one prize per placement per tournament')),
    ]
