# Generated by Django 5.2.8 on 2026-02-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0006_alter_game_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Game",
        ),
    ]
