# Generated by Django 5.2.8 on 2025-11-10 03:53

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_prize_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('certificate_type', models.CharField(choices=[('winner', 'Winner Certificate'), ('runner_up', 'Runner-up Certificate'), ('third_place', 'Third Place Certificate'), ('participant', 'Participation Certificate')], help_text='Type of certificate (winner, runner-up, etc.)', max_length=20)),
                ('placement', models.CharField(blank=True, default='', help_text="Placement string (e.g., '1st', '2nd', '3rd') for display", max_length=20)),
                ('file_pdf', models.FileField(blank=True, help_text='Generated PDF certificate file', null=True, upload_to='certificates/pdf/%Y/%m/')),
                ('file_image', models.ImageField(blank=True, help_text='Generated PNG/JPEG certificate image', null=True, upload_to='certificates/images/%Y/%m/')),
                ('verification_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique verification code (UUID4) for public verification', unique=True)),
                ('certificate_hash', models.CharField(help_text='SHA-256 hash of PDF file for tamper detection (64 hex characters)', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When certificate was generated')),
                ('downloaded_at', models.DateTimeField(blank=True, help_text='First download timestamp', null=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times certificate has been downloaded')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When certificate was revoked (if applicable)', null=True)),
                ('revoked_reason', models.TextField(blank=True, default='', help_text="Reason for revocation (e.g., 'Result disputed and changed', 'Regenerated with corrections')")),
                ('participant', models.ForeignKey(help_text='Participant who received this certificate (via Registration)', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tournaments.registration')),
                ('tournament', models.ForeignKey(help_text='Tournament this certificate was awarded for', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'tournament_engine_certificate_certificate',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['tournament', 'certificate_type'], name='tournament__tournam_2379ee_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['participant'], name='tournament__partici_7878dd_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='tournament__verific_700652_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['revoked_at'], name='tournament__revoked_9ba592_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('tournament', 'participant', 'certificate_type'), name='unique_cert_per_type_per_participant'),
        ),
    ]
