# Generated by Django 5.2.8 on 2025-11-19 19:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teamotp'),
        ('tournaments', '0007_tournamentannouncement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text='e.g., "Group A", "Group B", or custom name', max_length=100, verbose_name='Group Name')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which groups are displayed (0 = first)', verbose_name='Display Order')),
                ('max_participants', models.PositiveIntegerField(help_text='Maximum number of participants in this group', validators=[django.core.validators.MinValueValidator(2)], verbose_name='Max Participants')),
                ('advancement_count', models.PositiveIntegerField(default=2, help_text='Number of top teams/players that advance to next phase', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Advancement Count')),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON config: points_system, tiebreaker_rules, match_format', verbose_name='Group Configuration')),
                ('is_finalized', models.BooleanField(default=False, help_text='Whether group assignments are finalized (can no longer edit)', verbose_name='Is Finalized')),
                ('draw_seed', models.CharField(blank=True, help_text='Random seed used for provable draw (transparency)', max_length=64, verbose_name='Draw Seed')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag', verbose_name='Is Deleted')),
                ('tournament', models.ForeignKey(help_text='Tournament this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'tournament_groups',
                'ordering': ['tournament', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('rank', models.PositiveIntegerField(default=0, help_text='Current rank in group (1 = first place)', verbose_name='Rank')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='Matches Played')),
                ('matches_won', models.PositiveIntegerField(default=0, verbose_name='Matches Won')),
                ('matches_drawn', models.PositiveIntegerField(default=0, verbose_name='Matches Drawn')),
                ('matches_lost', models.PositiveIntegerField(default=0, verbose_name='Matches Lost')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total points according to points system', max_digits=10, verbose_name='Points')),
                ('goals_for', models.PositiveIntegerField(default=0, help_text='Total goals scored (eFootball, FC Mobile, FIFA)', verbose_name='Goals For')),
                ('goals_against', models.PositiveIntegerField(default=0, help_text='Total goals conceded (eFootball, FC Mobile, FIFA)', verbose_name='Goals Against')),
                ('goal_difference', models.IntegerField(default=0, help_text='Goals For - Goals Against', verbose_name='Goal Difference')),
                ('rounds_won', models.PositiveIntegerField(default=0, help_text='Total rounds won (Valorant, CS2)', verbose_name='Rounds Won')),
                ('rounds_lost', models.PositiveIntegerField(default=0, help_text='Total rounds lost (Valorant, CS2)', verbose_name='Rounds Lost')),
                ('round_difference', models.IntegerField(default=0, help_text='Rounds Won - Rounds Lost', verbose_name='Round Difference')),
                ('total_kills', models.PositiveIntegerField(default=0, help_text='Total kills (PUBG Mobile, Free Fire, Mobile Legends, COD Mobile)', verbose_name='Total Kills')),
                ('total_deaths', models.PositiveIntegerField(default=0, help_text='Total deaths (Mobile Legends, COD Mobile)', verbose_name='Total Deaths')),
                ('placement_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Points from match placements (PUBG Mobile, Free Fire)', max_digits=10, verbose_name='Placement Points')),
                ('average_placement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average finishing position (PUBG Mobile, Free Fire)', max_digits=5, verbose_name='Average Placement')),
                ('total_assists', models.PositiveIntegerField(default=0, help_text='Total assists (Mobile Legends)', verbose_name='Total Assists')),
                ('kda_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(Kills + Assists) / Deaths (Mobile Legends)', max_digits=6, verbose_name='KDA Ratio')),
                ('total_score', models.PositiveIntegerField(default=0, help_text='Total match score (COD Mobile)', verbose_name='Total Score')),
                ('game_stats', models.JSONField(blank=True, default=dict, help_text='Additional game-specific statistics', verbose_name='Game-Specific Stats')),
                ('is_advancing', models.BooleanField(default=False, help_text='Whether this participant advances to next phase', verbose_name='Is Advancing')),
                ('is_eliminated', models.BooleanField(default=False, help_text='Whether this participant is eliminated', verbose_name='Is Eliminated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.group', verbose_name='Group')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_standings', to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_standings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Group Standing',
                'verbose_name_plural': 'Group Standings',
                'db_table': 'tournament_group_standings',
                'ordering': ['group', 'rank', '-points', '-goal_difference', '-goals_for'],
            },
        ),
        migrations.CreateModel(
            name='TournamentLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('check_in_opens_at', models.DateTimeField(blank=True, help_text='When check-in becomes available', null=True, verbose_name='Check-In Opens At')),
                ('check_in_closes_at', models.DateTimeField(blank=True, help_text='Check-in deadline (typically tournament start time)', null=True, verbose_name='Check-In Closes At')),
                ('check_in_required', models.BooleanField(default=True, help_text='Whether participants must check in to compete', verbose_name='Check-In Required')),
                ('auto_forfeit_no_show', models.BooleanField(default=True, help_text="Automatically forfeit participants who don't check in", verbose_name='Auto-Forfeit No-Shows')),
                ('lobby_message', models.TextField(blank=True, help_text='Welcome message shown to participants in lobby', verbose_name='Lobby Message')),
                ('bracket_visibility', models.CharField(choices=[('hidden', 'Hidden'), ('seeded_only', 'Seeded Only'), ('full', 'Full Bracket')], default='seeded_only', help_text='What participants can see before tournament starts', max_length=20, verbose_name='Bracket Visibility')),
                ('roster_visibility', models.CharField(choices=[('hidden', 'Hidden'), ('count_only', 'Count Only'), ('full', 'Full Roster')], default='full', help_text='Whether participants can see full roster', max_length=20, verbose_name='Roster Visibility')),
                ('rules_url', models.URLField(blank=True, help_text='Link to detailed rules document', verbose_name='Rules URL')),
                ('discord_server_url', models.URLField(blank=True, help_text='Optional Discord server for communication', verbose_name='Discord Server')),
                ('is_active', models.BooleanField(default=True, help_text='Whether lobby is currently accessible', verbose_name='Is Active')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional lobby settings', verbose_name='Lobby Configuration')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lobby', to='tournaments.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Tournament Lobby',
                'verbose_name_plural': 'Tournament Lobbies',
                'db_table': 'tournament_lobbies',
            },
        ),
        migrations.CreateModel(
            name='LobbyAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('urgent', 'Urgent'), ('success', 'Success')], default='info', max_length=20, verbose_name='Type')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned announcements appear at top', verbose_name='Is Pinned')),
                ('display_until', models.DateTimeField(blank=True, help_text='Auto-hide after this time (optional)', null=True, verbose_name='Display Until')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is Visible')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tournaments.tournamentlobby', verbose_name='Lobby')),
            ],
            options={
                'verbose_name': 'Lobby Announcement',
                'verbose_name_plural': 'Lobby Announcements',
                'db_table': 'tournament_lobby_announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_checked_in', models.BooleanField(default=False, help_text='Whether participant has checked in', verbose_name='Is Checked In')),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='Timestamp of check-in', null=True, verbose_name='Checked In At')),
                ('is_forfeited', models.BooleanField(default=False, help_text='Whether participant was forfeited for not checking in', verbose_name='Is Forfeited')),
                ('forfeited_at', models.DateTimeField(blank=True, null=True, verbose_name='Forfeited At')),
                ('forfeit_reason', models.CharField(blank=True, help_text='Why participant was forfeited', max_length=255, verbose_name='Forfeit Reason')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about check-in', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('checked_in_by', models.ForeignKey(blank=True, help_text='User who performed check-in (may be captain for teams)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Checked In By')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='tournaments.registration', verbose_name='Registration')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_check_ins', to='teams.team', verbose_name='Team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='tournaments.tournament', verbose_name='Tournament')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_check_ins', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Check-In',
                'verbose_name_plural': 'Check-Ins',
                'db_table': 'tournament_check_ins',
                'indexes': [models.Index(fields=['tournament', 'is_checked_in'], name='tournament__tournam_9b1ee1_idx'), models.Index(fields=['tournament', 'is_forfeited'], name='tournament__tournam_48ee90_idx'), models.Index(fields=['registration'], name='tournament__registr_5535aa_idx'), models.Index(fields=['user', 'tournament'], name='tournament__user_id_45beaf_idx'), models.Index(fields=['team', 'tournament'], name='tournament__team_id_cd3e44_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('team__isnull', True)), models.Q(('user__isnull', True), ('team__isnull', False)), _connector='OR'), name='check_in_user_or_team_xor')],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['tournament', 'is_deleted'], name='tournament__tournam_c29a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['tournament', 'display_order'], name='tournament__tournam_8645e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('max_participants__gte', 2)), name='group_min_participants'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('advancement_count__gte', 1)), name='group_min_advancement'),
        ),
        migrations.AddIndex(
            model_name='groupstanding',
            index=models.Index(fields=['group', 'is_deleted'], name='tournament__group_i_f1ecf5_idx'),
        ),
        migrations.AddIndex(
            model_name='groupstanding',
            index=models.Index(fields=['group', 'rank'], name='tournament__group_i_80c9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='groupstanding',
            index=models.Index(fields=['group', '-points', '-goal_difference'], name='tournament__group_i_0f377c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupstanding',
            index=models.Index(fields=['user', 'is_deleted'], name='tournament__user_id_4f5139_idx'),
        ),
        migrations.AddIndex(
            model_name='groupstanding',
            index=models.Index(fields=['team', 'is_deleted'], name='tournament__team_id_f2eb53_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupstanding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('team__isnull', True)), models.Q(('user__isnull', True), ('team__isnull', False)), _connector='OR'), name='group_standing_user_or_team_xor'),
        ),
        migrations.AddIndex(
            model_name='lobbyannouncement',
            index=models.Index(fields=['lobby', 'is_visible', 'is_deleted'], name='tournament__lobby_i_548773_idx'),
        ),
        migrations.AddIndex(
            model_name='lobbyannouncement',
            index=models.Index(fields=['lobby', '-is_pinned', '-created_at'], name='tournament__lobby_i_d10432_idx'),
        ),
    ]
