# Generated by Django 5.2.8 on 2026-02-17 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0008_decouple_cross_app_fks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="checkin",
            name="check_in_user_or_team_xor",
        ),
        migrations.RemoveConstraint(
            model_name="groupstanding",
            name="group_standing_user_or_team_xor",
        ),
        migrations.RemoveIndex(
            model_name="checkin",
            name="tournament__team_id_cd3e44_idx",
        ),
        migrations.RemoveIndex(
            model_name="groupstanding",
            name="tournament__team_id_f2eb53_idx",
        ),
        migrations.RemoveIndex(
            model_name="teamregistrationpermissionrequest",
            name="tournaments_team_id_228dde_idx",
        ),
        migrations.RemoveIndex(
            model_name="tournamentteaminvitation",
            name="team_inv_status_idx",
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["team_id", "tournament"], name="tournament__team_id_cd3e44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupstanding",
            index=models.Index(
                fields=["team_id", "is_deleted"], name="tournament__team_id_f2eb53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamregistrationpermissionrequest",
            index=models.Index(fields=["team_id", "status"], name="tournaments_team_id_228dde_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamentteaminvitation",
            index=models.Index(fields=["team_id", "status"], name="team_inv_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("team_id__isnull", True)),
                    models.Q(("user__isnull", True), ("team_id__isnull", False)),
                    _connector="OR",
                ),
                name="check_in_user_or_team_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupstanding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("team_id__isnull", True)),
                    models.Q(("user__isnull", True), ("team_id__isnull", False)),
                    _connector="OR",
                ),
                name="group_standing_user_or_team_xor",
            ),
        ),
    ]
