# Generated by Django 5.2.8 on 2025-11-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_group_groupstanding_tournamentlobby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='banner',
            field=models.ImageField(blank=True, help_text='Game banner image', null=True, upload_to='games/banners/'),
        ),
        migrations.AddField(
            model_name='game',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Game card/thumbnail image', null=True, upload_to='games/cards/'),
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, help_text='Game category (MOBA, FPS, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, help_text='Game logo image', null=True, upload_to='games/logos/'),
        ),
        migrations.AddField(
            model_name='game',
            name='max_team_size',
            field=models.PositiveIntegerField(default=5, help_text='Maximum team size'),
        ),
        migrations.AddField(
            model_name='game',
            name='min_team_size',
            field=models.PositiveIntegerField(default=1, help_text='Minimum team size'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, help_text='Platform (PC, Mobile, Console)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Primary brand color (hex)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='result_logic',
            field=models.JSONField(blank=True, default=dict, help_text='Result calculation logic (JSONB)'),
        ),
        migrations.AddField(
            model_name='game',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='Available roles for this game (JSONB array)'),
        ),
        migrations.AddField(
            model_name='game',
            name='roster_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Roster rules and structure (JSONB)'),
        ),
        migrations.AddField(
            model_name='game',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Secondary brand color (hex)', max_length=20, null=True),
        ),
    ]
