"""
Migration: Create tournament_analytics_summary materialized view

Module 6.2: Materialized Views for Analytics
Phase 6 Sprint 1

Implements: PHASE_6_IMPLEMENTATION_PLAN.md#module-62-materialized-views-for-analytics

Performance optimization for large tournament analytics queries.
Pre-aggregates participant counts, check-in rates, match stats, and prize totals.

Refresh Strategy:
- Hourly via Celery beat (jittered)
- On-demand via management command (organizer/admin)
- Concurrent refresh (safe for production)

Expected Performance Gain:
- Baseline: 400-600ms for 500+ participant tournaments
- Optimized: <100ms (query materialized view only)
"""
# Generated by Django 5.2.8 on 2025-11-10 (Module 6.2)

from django.db import migrations


class Migration(migrations.Migration):
    
    dependencies = [
        ('tournaments', '0008_certificate'),  # Last migration from Module 5.3
    ]
    
    operations = [
        migrations.RunSQL(
            sql="""
            -- Module 6.2: Create materialized view for tournament analytics
            CREATE MATERIALIZED VIEW IF NOT EXISTS tournament_analytics_summary AS
            SELECT
                t.id AS tournament_id,
                t.status AS tournament_status,
                
                -- Participant metrics
                COUNT(DISTINCT r.id) FILTER (WHERE r.status = 'confirmed') AS total_participants,
                COUNT(DISTINCT r.id) FILTER (WHERE r.status = 'confirmed' AND r.checked_in = TRUE) AS checked_in_count,
                CASE 
                    WHEN COUNT(DISTINCT r.id) FILTER (WHERE r.status = 'confirmed') > 0 
                    THEN ROUND(
                        CAST(COUNT(DISTINCT r.id) FILTER (WHERE r.status = 'confirmed' AND r.checked_in = TRUE) AS NUMERIC) / 
                        NULLIF(COUNT(DISTINCT r.id) FILTER (WHERE r.status = 'confirmed'), 0),
                        4
                    )
                    ELSE 0.0
                END AS check_in_rate,
                
                -- Match metrics
                COUNT(DISTINCT m.id) AS total_matches,
                COUNT(DISTINCT m.id) FILTER (WHERE m.state = 'COMPLETED') AS completed_matches,
                COUNT(DISTINCT m.id) FILTER (WHERE m.state = 'DISPUTED') AS disputed_matches,
                CASE 
                    WHEN COUNT(DISTINCT m.id) > 0 
                    THEN ROUND(
                        CAST(COUNT(DISTINCT m.id) FILTER (WHERE m.state = 'DISPUTED') AS NUMERIC) / 
                        NULLIF(COUNT(DISTINCT m.id), 0),
                        4
                    )
                    ELSE 0.0
                END AS dispute_rate,
                
                -- Match duration (average in minutes)
                ROUND(
                    CAST(
                        EXTRACT(EPOCH FROM AVG(m.updated_at - m.created_at) FILTER (WHERE m.state = 'COMPLETED')) / 60 
                        AS NUMERIC
                    ), 
                    4
                ) AS avg_match_duration_minutes,
                
                -- Prize metrics
                COALESCE(t.prize_pool, 0.00) AS prize_pool_total,
                COALESCE(SUM(pt.amount) FILTER (WHERE pt.status = 'COMPLETED'), 0.00) AS prizes_distributed,
                COUNT(DISTINCT pt.id) FILTER (WHERE pt.status = 'COMPLETED') AS payout_count,
                
                -- Metadata
                t.tournament_start AS started_at,
                CASE 
                    WHEN t.status = 'COMPLETED' THEN t.updated_at
                    ELSE NULL
                END AS concluded_at,
                
                -- Freshness tracking
                NOW() AS last_refresh_at
                
            FROM tournaments_tournament t
            LEFT JOIN tournaments_registration r ON r.tournament_id = t.id
            LEFT JOIN tournament_engine_match_match m ON m.tournament_id = t.id
            LEFT JOIN tournament_engine_prize_prizetransaction pt ON pt.tournament_id = t.id
            GROUP BY t.id, t.status, t.prize_pool, t.tournament_start, t.updated_at;
            
            -- Module 6.2: Create unique index for fast tournament lookups
            CREATE UNIQUE INDEX IF NOT EXISTS idx_tournament_analytics_summary 
            ON tournament_analytics_summary (tournament_id);
            
            -- Module 6.2: Create index on freshness for stale check
            CREATE INDEX IF NOT EXISTS idx_tournament_analytics_freshness 
            ON tournament_analytics_summary (last_refresh_at DESC);
            
            -- Module 6.2: Create index on status for active tournament filtering
            CREATE INDEX IF NOT EXISTS idx_tournament_analytics_status 
            ON tournament_analytics_summary (tournament_status, tournament_id);
            """,
            reverse_sql="""
            -- Module 6.2: Drop materialized view and indexes
            DROP INDEX IF EXISTS idx_tournament_analytics_status;
            DROP INDEX IF EXISTS idx_tournament_analytics_freshness;
            DROP INDEX IF EXISTS idx_tournament_analytics_summary;
            DROP MATERIALIZED VIEW IF EXISTS tournament_analytics_summary;
            """
        ),
    ]
