# Generated by Django 5.2.8 on 2026-02-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0009_remove_checkin_check_in_user_or_team_xor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="lineup_snapshot",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Frozen team roster at registration: [{user_id, username, game_id, role}, ...]",
            ),
        ),
    ]
