# Generated by Django 5.2.8 on 2025-11-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_analytics_materialized_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='migrated_to_s3_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='When certificate files were migrated to S3 (backfill tracking)'
            ),
        ),
    ]
