# Generated by Django 5.2.8 on 2025-11-25 17:30

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_game'),
        ('tournaments', '0009_game_banner_game_card_image_game_category_game_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Valorant Solo Registration')", max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=220, unique=True)),
                ('description', models.TextField(blank=True, help_text='What makes this template special?')),
                ('participation_type', models.CharField(choices=[('solo', 'Solo Player'), ('team', 'Team'), ('duo', 'Duo/Squad')], db_index=True, help_text='Type of registration this template supports', max_length=20)),
                ('form_schema', models.JSONField(default=dict, help_text='Complete form configuration including sections, fields, validation')),
                ('icon', models.CharField(blank=True, help_text="Emoji or icon class (e.g., '🎮' or 'fa-gamepad')", max_length=50)),
                ('thumbnail', models.ImageField(blank=True, help_text='Preview image for template selection', null=True, upload_to='form_templates/thumbnails/')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this template visible to organizers?')),
                ('is_system_template', models.BooleanField(db_index=True, default=False, help_text='Created by DeltaCrown staff (cannot be edited)')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Show in featured templates section')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of tournaments using this template', validators=[django.core.validators.MinValueValidator(0)])),
                ('average_completion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Average % of users who complete registration', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for search/filtering (e.g., ['valorant', 'apac', 'ranked'])")),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_templates', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(blank=True, help_text='Specific game this template is designed for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates', to='tournaments.game')),
            ],
            options={
                'verbose_name': 'Registration Form Template',
                'verbose_name_plural': 'Registration Form Templates',
                'db_table': 'tournaments_registration_form_template',
                'ordering': ['-is_featured', '-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_schema', models.JSONField(default=dict, help_text='Complete form configuration (editable copy from template)')),
                ('enable_multi_step', models.BooleanField(default=True, help_text='Split form into multiple steps/pages')),
                ('enable_autosave', models.BooleanField(default=True, help_text='Auto-save draft responses in browser')),
                ('enable_progress_bar', models.BooleanField(default=True, help_text='Show progress indicator during registration')),
                ('allow_edits_after_submit', models.BooleanField(default=False, help_text='Let users edit their registration after submission')),
                ('require_email_verification', models.BooleanField(default=False, help_text='Send verification email before accepting registration')),
                ('enable_captcha', models.BooleanField(default=True, help_text='Require CAPTCHA on submission')),
                ('rate_limit_per_ip', models.IntegerField(default=5, help_text='Max submissions per IP per hour', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('success_message', models.TextField(blank=True, help_text='Custom success message after registration')),
                ('redirect_url', models.URLField(blank=True, help_text='Redirect to external URL after success (optional)')),
                ('send_confirmation_email', models.BooleanField(default=True, help_text='Send email confirmation to participant')),
                ('conditional_rules', models.JSONField(blank=True, default=dict, help_text='Show/hide fields based on other field values')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Custom validation rules beyond field-level validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_views', models.IntegerField(default=0, help_text='Number of times form was loaded', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_starts', models.IntegerField(default=0, help_text='Number of users who started filling the form', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_completions', models.IntegerField(default=0, help_text='Number of submitted registrations', validators=[django.core.validators.MinValueValidator(0)])),
                ('based_on_template', models.ForeignKey(blank=True, help_text='Template this form was created from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_forms', to='tournaments.registrationformtemplate')),
                ('tournament', models.OneToOneField(help_text='Tournament this form belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='registration_form', to='tournaments.tournament')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last user who edited this form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tournament_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournament Registration Form',
                'verbose_name_plural': 'Tournament Registration Forms',
                'db_table': 'tournaments_registration_form',
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(default=dict, help_text='Complete form responses as JSON')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Current registration status', max_length=20)),
                ('has_paid', models.BooleanField(db_index=True, default=False)),
                ('payment_verified', models.BooleanField(db_index=True, default=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid (if entry fee exists)', max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=200)),
                ('payment_proof', models.FileField(blank=True, help_text='Screenshot of payment', null=True, upload_to='registration_payments/')),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to participant)')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (visible to participant)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('submission_duration', models.IntegerField(blank=True, help_text='Time taken to complete form (seconds)', null=True)),
                ('payment_verified_by', models.ForeignKey(blank=True, help_text='Admin who verified payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_verified_payments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Team (if team tournament)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_tournament_registrations', to='teams.team')),
                ('tournament', models.ForeignKey(help_text='Tournament this registration is for', on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='tournaments.tournament')),
                ('user', models.ForeignKey(help_text='User who submitted the registration', on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to=settings.AUTH_USER_MODEL)),
                ('registration_form', models.ForeignKey(help_text='Form version used for this registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='tournaments.tournamentregistrationform')),
            ],
            options={
                'verbose_name': 'Form Response',
                'verbose_name_plural': 'Form Responses',
                'db_table': 'tournaments_form_response',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='registrationformtemplate',
            index=models.Index(fields=['participation_type', 'game'], name='formtpl_type_game_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationformtemplate',
            index=models.Index(fields=['is_active', 'is_system_template'], name='formtpl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationformtemplate',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='formtpl_tags_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['tournament', 'status'], name='formresp_tourn_status_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['user', 'tournament'], name='formresp_user_tourn_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['status', 'payment_verified'], name='formresp_status_pay_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formresponse',
            unique_together={('tournament', 'user')},
        ),
    ]
