# Generated by Django 5.2.8 on 2026-02-19 17:42

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def populate_registration_numbers(apps, schema_editor):
    """Backfill registration_number for existing rows."""
    Registration = apps.get_model("tournaments", "Registration")
    year_suffix = timezone.now().strftime("%y")
    prefix = f"DC-{year_suffix}"
    seq = 0
    for reg in Registration.objects.filter(registration_number="").order_by("created_at"):
        seq += 1
        reg.registration_number = f"{prefix}-{seq:04d}"
        reg.save(update_fields=["registration_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0010_add_lineup_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registration",
            name="registration_valid_status",
        ),
        # Step 1: Add field without unique/index constraint
        migrations.AddField(
            model_name="registration",
            name="registration_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-generated registration number: DC-{SLUG}-{SEQ:04d}",
                max_length=30,
            ),
        ),
        # Step 2: Populate existing rows
        migrations.RunPython(
            populate_registration_numbers,
            migrations.RunPython.noop,
        ),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name="registration",
            name="registration_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-generated registration number: DC-{SLUG}-{SEQ:04d}",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "draft",
                            "submitted",
                            "pending",
                            "auto_approved",
                            "needs_review",
                            "payment_submitted",
                            "confirmed",
                            "rejected",
                            "cancelled",
                            "waitlisted",
                            "no_show",
                        ],
                    )
                ),
                name="registration_valid_status",
            ),
        ),
    ]
