# Generated by Django 5.2.8 on 2025-11-12 20:48

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_paymentverification_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Guarded index removal - only drop if exists (avoids CI failures)
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS idx_result_tour_method;',
            reverse_sql='CREATE INDEX IF NOT EXISTS idx_result_tour_method ON tournaments_tournamentresult(tournament_id, determination_method);',
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_refunded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered determination (or verified manually)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournament_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='requires_review',
            field=models.BooleanField(default=False, help_text='Flag indicating organizer review needed (e.g., forfeit chain, tie-breaking failures)'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='rules_applied',
            field=models.JSONField(default=dict, help_text='JSONB audit trail of determination logic. Contains ordered list of rules applied, intermediate scores, and reasoning for winner selection.'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='third_place',
            field=models.ForeignKey(blank=True, help_text='Third place participant (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='third_place_tournaments', to='tournaments.registration'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='winner',
            field=models.ForeignKey(help_text='Winner participant (Registration record)', on_delete=django.db.models.deletion.PROTECT, related_name='won_tournaments', to='tournaments.registration'),
        ),
    ]
