# Generated by Django 5.2.8 on 2026-02-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0011_add_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="refund_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_refund", "No Refunds"),
                    ("refund_until_checkin", "Refund Until Check-In"),
                    ("refund_until_bracket", "Refund Until Bracket Generation"),
                    ("full_refund", "Full Refund Anytime"),
                    ("custom", "Custom Policy"),
                ],
                default="no_refund",
                help_text="Refund policy for entry fees",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="refund_policy_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Custom refund policy text (shown to registrants when policy is "custom")',
            ),
        ),
    ]
