# Generated by Django 5.2.8 on 2025-11-25 19:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_create_webhook_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ratinghelpful',
            name='unique_rating_user_helpful',
        ),
        migrations.RemoveConstraint(
            model_name='templaterating',
            name='unique_template_user_tournament_rating',
        ),
        migrations.RemoveIndex(
            model_name='formwebhook',
            name='webhook_form_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookdelivery',
            name='delivery_webhook_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookdelivery',
            name='delivery_created_idx',
        ),
        migrations.RenameIndex(
            model_name='ratinghelpful',
            new_name='tournaments_rating__b740bf_idx',
            old_name='rating_helpful_idx',
        ),
        migrations.RenameIndex(
            model_name='ratinghelpful',
            new_name='tournaments_user_id_514de3_idx',
            old_name='user_helpful_idx',
        ),
        migrations.RenameIndex(
            model_name='templaterating',
            new_name='tournaments_templat_9ccf9c_idx',
            old_name='template_rating_idx',
        ),
        migrations.RenameIndex(
            model_name='templaterating',
            new_name='tournaments_templat_bac5e2_idx',
            old_name='template_helpful_idx',
        ),
        migrations.RenameIndex(
            model_name='templaterating',
            new_name='tournaments_user_id_f6fc69_idx',
            old_name='user_ratings_idx',
        ),
        migrations.RenameIndex(
            model_name='templaterating',
            new_name='tournaments_created_3d4d69_idx',
            old_name='recent_ratings_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ratinghelpful',
            unique_together={('rating', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='templaterating',
            unique_together={('template', 'user', 'tournament')},
        ),
    ]
