# Generated by Django 5.2.8 on 2026-02-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0012_add_refund_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="is_guest_team",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this registration is for a guest (unregistered) team",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_guest_teams",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of guest team registrations allowed (0 = disabled)",
            ),
        ),
    ]
