# Generated by Django 5.2.8 on 2025-11-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_add_registration_constraints'),
        ('tournaments', '0013_remove_ratinghelpful_unique_rating_user_helpful_and_more'),
    ]

    operations = [
    ]
