# Generated by Django 5.2.8 on 2026-02-20 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0014_add_display_name_override"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="payment_status_valid",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount_bdt",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Payment amount in BDT (integer, from PaymentVerification)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Idempotency key to prevent duplicate payments",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="last_action_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Audit trail for last staff action taken",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="note",
            field=models.CharField(
                blank=True, default="", help_text="Registrant note for payment", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured notes for staff actions (reason codes, metadata)",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payer_account_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Payer bKash/Nagad/Rocket account number",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="proof_image",
            field=models.ImageField(
                blank=True,
                help_text="Payment proof screenshot/receipt image",
                null=True,
                upload_to="payments/proofs/",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_at",
            field=models.DateTimeField(
                blank=True, help_text="When payment was refunded", null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who processed the refund",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunded_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reject_reason",
            field=models.TextField(
                blank=True, default="", help_text="Reason for payment rejection"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="rejected_at",
            field=models.DateTimeField(
                blank=True, help_text="When payment was rejected", null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who rejected the payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="payment_deadline_hours",
            field=models.PositiveIntegerField(
                default=48,
                help_text="Hours after registration to submit payment before auto-expiry (0 = no deadline)",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("submitted", "Submitted"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("refunded", "Refunded"),
                    ("waived", "Fee Waived"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="pending",
                help_text="Current payment status",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["pending", "submitted", "verified", "rejected", "refunded", "expired"],
                    )
                ),
                name="payment_status_valid",
            ),
        ),
    ]
