# Generated by Django 5.2.8 on 2025-11-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0014_merge_20251126_0313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[("IMAGE", "Image"), ("PDF", "PDF Document")],
                default="",
                help_text="Type of uploaded proof file",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="resubmission_count",
            field=models.IntegerField(
                default=0, help_text="Number of times payment was resubmitted after rejection"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("submitted", "Submitted"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("refunded", "Refunded"),
                    ("waived", "Fee Waived"),
                ],
                db_index=True,
                default="pending",
                help_text="Current payment status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="waive_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reason for fee waiver (e.g., 'Top-ranked team', 'Sponsor invitation')",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="waived",
            field=models.BooleanField(
                default=False, help_text="Fee waived by organizer (for top teams, sponsors, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="waitlist_position",
            field=models.IntegerField(
                blank=True, help_text="Position in waitlist queue (FIFO order)", null=True
            ),
        ),
    ]
