# Generated by Django 5.2.8 on 2025-11-14 11:57
"""
Module 9.1: Performance Optimization - Database Indexes

Adds composite indexes for common query patterns identified in performance audit.
Planning reference: PART_5.2_BACKEND_INTEGRATION_TESTING_DEPLOYMENT.md Section 4.4

Indexes added:
1. Tournament (game_id, status, is_deleted) - Tournament discovery/filtering
2. Registration (tournament_id, user_id) - Duplicate registration checks
3. Match (tournament_id, status) - Match listings/bracket generation
4. PaymentVerification (registration_id, status) - Payment lookup/verification

Expected impact:
- 50-70% faster tournament discovery queries
- 80-90% faster duplicate registration checks
- 60-80% faster match listings
- 70-85% faster payment verification lookups
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_tournament_template'),
    ]

    operations = [
        # 1. Tournament discovery optimization
        # Common query: Tournament.objects.filter(game_id=X, status=Y, is_deleted=False)
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(
                fields=['game', 'status', 'is_deleted'],
                name='tournament_game_status_idx'
            ),
        ),
        
        # 2. Registration duplicate check optimization
        # Common query: Registration.objects.filter(tournament_id=X, user_id=Y)
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(
                fields=['tournament', 'user'],
                name='registration_tournament_user_idx'
            ),
        ),
        
        # 3. Match listing optimization
        # Common query: Match.objects.filter(tournament_id=X, state=Y)
        migrations.AddIndex(
            model_name='match',
            index=models.Index(
                fields=['tournament', 'state'],
                name='match_tournament_state_idx'
            ),
        ),
        
        # 4. Payment verification optimization
        # Common query: Payment.objects.filter(registration_id=X, status=Y)
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['registration', 'status'],
                name='payment_registration_status_idx'
            ),
        ),
    ]
