# Generated by Django 5.2.8 on 2025-11-26 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_alter_payment_file_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentFormConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('default_solo', 'Default Solo Registration'), ('default_team', 'Default Team Registration'), ('custom', 'Custom Registration Form')], default='default_solo', help_text='Type of registration form to use', max_length=20)),
                ('enable_age_field', models.BooleanField(default=False, help_text='Ask for participant age (13+ validation)')),
                ('enable_country_field', models.BooleanField(default=False, help_text='Ask for country/region selection')),
                ('enable_platform_field', models.BooleanField(default=False, help_text='Ask for platform/server (e.g., APAC, NA, EU)')),
                ('enable_rank_field', models.BooleanField(default=False, help_text='Ask for current game rank (optional)')),
                ('enable_phone_field', models.BooleanField(default=False, help_text='Ask for WhatsApp/phone number')),
                ('enable_discord_field', models.BooleanField(default=False, help_text='Ask for Discord username')),
                ('enable_preferred_contact_field', models.BooleanField(default=False, help_text='Ask for preferred contact method')),
                ('enable_team_logo_field', models.BooleanField(default=False, help_text='Allow team logo upload')),
                ('enable_team_region_field', models.BooleanField(default=False, help_text='Ask for team region')),
                ('enable_captain_display_name_field', models.BooleanField(default=False, help_text='Ask for captain nickname/display name')),
                ('enable_captain_whatsapp_field', models.BooleanField(default=False, help_text='Ask for captain WhatsApp number')),
                ('enable_captain_phone_field', models.BooleanField(default=False, help_text='Ask for captain phone number')),
                ('enable_captain_discord_field', models.BooleanField(default=False, help_text='Ask for captain Discord username')),
                ('enable_roster_display_names', models.BooleanField(default=False, help_text='Ask for display names for all team members')),
                ('enable_roster_emails', models.BooleanField(default=False, help_text='Ask for email addresses for all team members')),
                ('enable_payment_mobile_number_field', models.BooleanField(default=False, help_text='Ask for mobile number used for payment')),
                ('enable_payment_screenshot_field', models.BooleanField(default=True, help_text='Allow payment screenshot upload')),
                ('enable_payment_notes_field', models.BooleanField(default=False, help_text='Allow optional payment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_form', models.ForeignKey(blank=True, help_text='Custom form template (if form_type is custom)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_configurations', to='tournaments.registrationformtemplate')),
                ('tournament', models.OneToOneField(help_text='Tournament this form configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='form_configuration', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Form Configuration',
                'verbose_name_plural': 'Tournament Form Configurations',
                'db_table': 'tournaments_form_configuration',
                'ordering': ['-created_at'],
            },
        ),
    ]
