# Generated by Django 5.2.8 on 2025-11-26 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_game'),
        ('tournaments', '0016_add_form_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistrationPermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the request', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from requester to captain')),
                ('response_message', models.TextField(blank=True, help_text='Response from captain/manager')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the request was approved/rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(help_text='Team member requesting permission', on_delete=django.db.models.deletion.CASCADE, related_name='registration_permission_requests', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, help_text='Captain/manager who responded to the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_requests_responded', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='Team for which permission is requested', on_delete=django.db.models.deletion.CASCADE, related_name='registration_permission_requests', to='teams.team')),
                ('tournament', models.ForeignKey(help_text='Tournament the member wants to register for', on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Team Registration Permission Request',
                'verbose_name_plural': 'Team Registration Permission Requests',
                'db_table': 'tournaments_team_permission_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='tournaments_status_e9028f_idx'), models.Index(fields=['team', 'status'], name='tournaments_team_id_228dde_idx'), models.Index(fields=['requester', 'status'], name='tournaments_request_35bd76_idx')],
                'unique_together': {('team', 'tournament', 'requester', 'status')},
            },
        ),
    ]
