# Generated by Django 5.2.8 on 2026-02-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0017_add_invite_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="allow_roster_editing",
            field=models.BooleanField(
                default=True,
                help_text="Allow the coordinator to edit lineup (swap starters/subs, reorder) during registration.",
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="communication_channels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Organizer-defined communication channels for the registration form. Schema: [{"key":"discord","label":"Discord ID","placeholder":"Username#0000","icon":"discord","required":true,"type":"text"}]. Leave empty to use built-in defaults (Phone + Discord).',
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="coordinator_help_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom help text explaining what a Match Coordinator does. Shown as an info tooltip.",
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="coordinator_role_choices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Custom role options. Schema: [{"key":"captain","label":"Captain / IGL","description":"Leads in-game strategy"}]. Leave empty to use defaults.',
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="enable_coordinator_role",
            field=models.BooleanField(
                default=True,
                help_text="Show coordinator role selector (IGL, Captain, Manager, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="enable_preferred_communication",
            field=models.BooleanField(
                default=False,
                help_text='Show "Preferred Communication Method" dropdown in the form.',
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="enable_team_banner_upload",
            field=models.BooleanField(
                default=False, help_text="Allow team to upload/replace banner during registration."
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="enable_team_bio",
            field=models.BooleanField(default=False, help_text="Show team bio/motto text field."),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="enable_team_logo_upload",
            field=models.BooleanField(
                default=False, help_text="Allow team to upload/replace logo during registration."
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="member_custom_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Additional per-member fields defined by organizer. Schema: [{"key":"jersey_number","label":"Jersey Number","type":"text","required":false}].',
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="require_member_age",
            field=models.BooleanField(
                default=False, help_text="Require age / date of birth for each roster member."
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="require_member_email",
            field=models.BooleanField(
                default=False, help_text="Require email address for each roster member."
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="require_member_national_id",
            field=models.BooleanField(
                default=False,
                help_text="Require national ID / passport number for each member (LAN tournaments).",
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="require_member_photo",
            field=models.BooleanField(
                default=False,
                help_text="Require photo for each roster member (common for LAN/official).",
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="require_member_real_name",
            field=models.BooleanField(
                default=False, help_text="Require real name for each roster member."
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="show_member_game_ids",
            field=models.BooleanField(
                default=True, help_text="Display each member's game ID in the roster panel."
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="show_member_ranks",
            field=models.BooleanField(
                default=True, help_text="Display each member's current rank in the roster panel."
            ),
        ),
    ]
