# Generated by Django 5.2.8 on 2025-11-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0017_add_permission_request_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="templaterating",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="templaterating",
            name="template",
        ),
        migrations.RemoveField(
            model_name="templaterating",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="templaterating",
            name="user",
        ),
        migrations.DeleteModel(
            name="RatingHelpful",
        ),
        migrations.DeleteModel(
            name="TemplateRating",
        ),
    ]
