# Generated by Django 5.2.8 on 2026-02-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0018_form_config_dynamic_channels_roster"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="custom_fair_play_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom fair play / code of conduct text. If blank, a default DeltaCrown fair play agreement is shown.",
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="custom_registration_rules",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom registration-specific rules provided by the organizer. Shown in the Review & Submit step. If blank, only the tournament's main rules field is shown. Supports plain text with line breaks.",
            ),
        ),
        migrations.AddField(
            model_name="tournamentformconfiguration",
            name="custom_tos_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom terms of service text for this tournament. If blank, the default DeltaCrown ToS is shown.",
            ),
        ),
    ]
