# Generated by Django 5.2.8 on 2026-02-22 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0019_rules_agreements_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Organizer contact email for participants",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="social_discord",
            field=models.URLField(blank=True, default="", help_text="Discord server invite URL"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="social_instagram",
            field=models.URLField(
                blank=True, default="", help_text="Organizer Instagram profile URL"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="social_twitter",
            field=models.URLField(
                blank=True, default="", help_text="Organizer X (Twitter) profile URL"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="social_website",
            field=models.URLField(
                blank=True, default="", help_text="Organizer official website URL"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="social_youtube",
            field=models.URLField(
                blank=True, default="", help_text="Organizer YouTube channel URL"
            ),
        ),
        migrations.CreateModel(
            name="PrizeClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated"
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("deltacoin", "DeltaCoin Wallet"),
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("rocket", "Rocket"),
                            ("bank", "Bank Transfer"),
                        ],
                        default="deltacoin",
                        help_text="Preferred payout method",
                        max_length=20,
                    ),
                ),
                (
                    "payout_destination",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Masked account number or wallet ID for payout",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current claim status",
                        max_length=20,
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the claim was submitted"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When the payout was completed", null=True
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, default="", help_text="Internal notes from admin during review"
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        help_text="User who initiated the claim",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prize_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prize_transaction",
                    models.OneToOneField(
                        help_text="The prize transaction being claimed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim",
                        to="tournaments.prizetransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prize Claim",
                "verbose_name_plural": "Prize Claims",
                "db_table": "tournaments_prize_claim",
                "ordering": ["-claimed_at"],
                "indexes": [
                    models.Index(fields=["status", "claimed_at"], name="idx_prize_claim_status"),
                    models.Index(fields=["claimed_by"], name="idx_prize_claim_user"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TournamentSponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated"
                    ),
                ),
                ("name", models.CharField(help_text="Sponsor display name", max_length=200)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("title", "Title Sponsor"),
                            ("gold", "Gold Sponsor"),
                            ("silver", "Silver Sponsor"),
                            ("bronze", "Bronze Sponsor"),
                            ("partner", "Partner"),
                        ],
                        db_index=True,
                        default="silver",
                        help_text="Sponsorship tier (affects display size and placement)",
                        max_length=20,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        help_text="Sponsor logo (recommended: 400x200, transparent PNG)",
                        upload_to="tournaments/sponsors/",
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True, default="", help_text="Sponsor website URL (opens in new tab)"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional wide banner (1200x300) for title/gold sponsors",
                        null=True,
                        upload_to="tournaments/sponsors/banners/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional sponsor video URL (YouTube/Vimeo)",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Display order within tier (lower = first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this sponsor is currently displayed",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        help_text="Tournament this sponsor belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Sponsor",
                "verbose_name_plural": "Tournament Sponsors",
                "db_table": "tournaments_sponsor",
                "ordering": ["tier", "display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["tournament", "tier", "is_active"],
                        name="idx_sponsor_tournament_tier",
                    )
                ],
            },
        ),
    ]
