# Generated by Django 5.2.8 on 2025-11-29 16:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_add_platform_mode_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('lan', 'LAN'), ('hybrid', 'Hybrid (Online + LAN Finals)')], db_index=True, default='online', help_text='Tournament mode - affects location requirements', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='platform',
            field=models.CharField(choices=[('pc', 'PC'), ('mobile', 'Mobile'), ('ps5', 'PlayStation 5'), ('xbox', 'Xbox Series X/S'), ('switch', 'Nintendo Switch')], db_index=True, default='pc', help_text='Gaming platform for this tournament', max_length=20),
        ),
    ]
