# Generated by Django 5.2.8 on 2025-11-29 21:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_add_roster_slot_field'),
        ('tournaments', '0020_add_registration_form_overrides'),
        ('user_profile', '0008_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Registration form completion progress (0-100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='registration',
            name='current_step',
            field=models.PositiveIntegerField(default=1, help_text='Current step in the registration wizard (1-3)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='Time spent on registration process in seconds'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_form_overrides',
            field=models.JSONField(default=dict, help_text='Form configuration overrides for this tournament (JSONB)'),
        ),
        migrations.CreateModel(
            name='TournamentTeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled by Organizer')], db_index=True, default='PENDING', max_length=16)),
                ('message', models.TextField(blank=True, help_text='Optional message from organizer to team')),
                ('invited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the invitation expires (if set)', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When team responded (accepted/declined)', null=True)),
                ('response_message', models.TextField(blank=True, help_text='Optional message from team when responding')),
                ('auto_register_on_accept', models.BooleanField(default=True, help_text='Automatically create tournament registration when invitation is accepted')),
                ('invited_by', models.ForeignKey(help_text='Organizer/staff who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tournament_invitations', to='user_profile.userprofile')),
                ('registration', models.OneToOneField(blank=True, help_text='Registration created when invitation was accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_invitation', to='tournaments.registration')),
                ('responded_by', models.ForeignKey(blank=True, help_text='Team member who responded to invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_tournament_invitations', to='user_profile.userprofile')),
                ('team', models.ForeignKey(help_text='Team being invited', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_invitations', to='teams.team')),
                ('tournament', models.ForeignKey(help_text='Tournament extending the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Team Invitation',
                'verbose_name_plural': 'Tournament Team Invitations',
                'ordering': ['-invited_at'],
                'indexes': [models.Index(fields=['tournament', 'status'], name='tournament_inv_status_idx'), models.Index(fields=['team', 'status'], name='team_inv_status_idx'), models.Index(fields=['invited_at'], name='tournaments_invited_fae84c_idx'), models.Index(fields=['expires_at'], name='tournaments_expires_587c66_idx')],
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
