# Generated by Django 5.2.8 on 2026-02-22 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0020_add_social_fields_sponsor_prizeclaim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tournamentsponsor",
            name="idx_sponsor_tournament_tier",
        ),
        migrations.RenameIndex(
            model_name="prizeclaim",
            new_name="idx_prizeclaim_status_date",
            old_name="idx_prize_claim_status",
        ),
        migrations.RenameIndex(
            model_name="prizeclaim",
            new_name="idx_prizeclaim_user",
            old_name="idx_prize_claim_user",
        ),
        migrations.RemoveField(
            model_name="tournamentsponsor",
            name="video_url",
        ),
        migrations.AddField(
            model_name="tournamentsponsor",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short description shown on hover or under the logo",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="prizeclaim",
            name="admin_notes",
            field=models.TextField(
                blank=True, default="", help_text="Internal notes from organizer/admin"
            ),
        ),
        migrations.AlterField(
            model_name="prizeclaim",
            name="claimed_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the user submitted the claim"
            ),
        ),
        migrations.AlterField(
            model_name="prizeclaim",
            name="claimed_by",
            field=models.ForeignKey(
                help_text="User who claimed the prize",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prize_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="prizeclaim",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, help_text="When the payout was executed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="prizeclaim",
            name="payout_destination",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Masked payout target (e.g., 017****678)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="prizeclaim",
            name="payout_method",
            field=models.CharField(
                choices=[
                    ("deltacoin", "DeltaCoin Wallet"),
                    ("bkash", "bKash"),
                    ("nagad", "Nagad"),
                    ("rocket", "Rocket"),
                    ("bank", "Bank Transfer"),
                ],
                default="deltacoin",
                help_text="Chosen payout method",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prizeclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                help_text="Current claim lifecycle state",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="social_instagram",
            field=models.URLField(blank=True, default="", help_text="Organizer Instagram URL"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="social_website",
            field=models.URLField(blank=True, default="", help_text="Organizer website URL"),
        ),
        migrations.AlterField(
            model_name="tournamentsponsor",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Wide banner image for premium placements (16:9 or 4:1)",
                null=True,
                upload_to="tournaments/sponsors/banners/",
            ),
        ),
        migrations.AlterField(
            model_name="tournamentsponsor",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Sort order within same tier (lower = first)"
            ),
        ),
        migrations.AlterField(
            model_name="tournamentsponsor",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this sponsor is visible in the Hub"
            ),
        ),
        migrations.AlterField(
            model_name="tournamentsponsor",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Sponsor logo (square or landscape, min 200×200)",
                null=True,
                upload_to="tournaments/sponsors/",
            ),
        ),
        migrations.AlterField(
            model_name="tournamentsponsor",
            name="name",
            field=models.CharField(help_text="Sponsor brand name", max_length=200),
        ),
        migrations.AlterField(
            model_name="tournamentsponsor",
            name="tier",
            field=models.CharField(
                choices=[
                    ("title", "Title Sponsor"),
                    ("gold", "Gold Sponsor"),
                    ("silver", "Silver Sponsor"),
                    ("bronze", "Bronze Sponsor"),
                    ("partner", "Partner"),
                ],
                db_index=True,
                default="partner",
                help_text="Sponsor tier — controls display size and prominence",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tournamentsponsor",
            name="tournament",
            field=models.ForeignKey(
                help_text="Tournament this sponsor is associated with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsors",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentsponsor",
            index=models.Index(
                fields=["tournament", "tier", "display_order"], name="idx_sponsor_t_tier_order"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentsponsor",
            index=models.Index(fields=["tournament", "is_active"], name="idx_sponsor_t_active"),
        ),
    ]
