# Generated by Django 5.2.8 on 2026-02-24 07:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_id_label_fields"),
        ("teams", "0102_alter_chatreadreceipt_unique_together_and_more"),
        ("tournaments", "0021_hub_social_fields_sponsor_prize_claim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileTrophy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True, verbose_name="Name")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="trophy",
                        help_text="Lucide icon name or URL.",
                        max_length=100,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                (
                    "criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Auto-award criteria (e.g. {type: 'wins', threshold: 10}).",
                        verbose_name="Criteria",
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                        verbose_name="Rarity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Trophy",
                "verbose_name_plural": "Profile Trophies",
                "db_table": "toc_profile_trophy",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="tournament",
            name="max_participants",
            field=models.PositiveIntegerField(
                default=16,
                help_text="Maximum number of participants/teams",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(256),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="registration_form_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Form configuration overrides for this tournament (JSONB)",
            ),
        ),
        migrations.CreateModel(
            name="BroadcastStation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("stream_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("idle", "Idle"), ("live", "Live"), ("offline", "Offline")],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcast_station",
                        to="tournaments.match",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_stations",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "toc_broadcast_station",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Template Name")),
                (
                    "template_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTML with {{variable}} placeholders.",
                        verbose_name="Template HTML",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of variable names available for substitution.",
                        verbose_name="Available Variables",
                    ),
                ),
                ("is_default", models.BooleanField(default=False, verbose_name="Default Template")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_templates",
                        to="tournaments.tournament",
                        verbose_name="Tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Template",
                "verbose_name_plural": "Certificate Templates",
                "db_table": "toc_certificate_template",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencySubRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Captain's explanation for the substitution."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dropping_player",
                    models.ForeignKey(
                        help_text="Player being removed from the roster.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_sub_dropped",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        help_text="The team registration this substitution is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_sub_requests",
                        to="tournaments.registration",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Captain who submitted the request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_sub_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organizer/staff who reviewed the request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_sub_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "substitute_player",
                    models.ForeignKey(
                        help_text="Player being added to the roster.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_sub_incoming",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_sub_requests",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Sub Request",
                "verbose_name_plural": "Emergency Sub Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameMatchConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "default_match_format",
                    models.CharField(
                        choices=[
                            ("bo1", "Best of 1"),
                            ("bo3", "Best of 3"),
                            ("bo5", "Best of 5"),
                            ("bo7", "Best of 7"),
                            ("rr", "Round Robin"),
                            ("ffa", "Free for All"),
                        ],
                        default="bo1",
                        max_length=10,
                        verbose_name="Default Match Format",
                    ),
                ),
                (
                    "scoring_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Game-specific scoring configuration (JSON).",
                        verbose_name="Scoring Rules",
                    ),
                ),
                (
                    "match_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Overtime rules, map rotation, side-swap, etc.",
                        verbose_name="Match Settings",
                    ),
                ),
                (
                    "enable_veto",
                    models.BooleanField(default=False, verbose_name="Enable Map/Ban Veto"),
                ),
                (
                    "veto_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("standard", "Standard Ban/Pick"),
                            ("blind_pick", "Blind Pick"),
                            ("captain_draft", "Captain Draft"),
                        ],
                        default="standard",
                        max_length=30,
                        verbose_name="Veto Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_configs",
                        to="games.game",
                        verbose_name="Game",
                    ),
                ),
                (
                    "tournament",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_match_config",
                        to="tournaments.tournament",
                        verbose_name="Tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Match Config",
                "verbose_name_plural": "Game Match Configs",
                "db_table": "toc_game_match_config",
            },
        ),
        migrations.CreateModel(
            name="BRScoringMatrix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "placement_points",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map of placement position → points.",
                        verbose_name="Placement Points",
                    ),
                ),
                (
                    "kill_points",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=6, verbose_name="Points per Kill"
                    ),
                ),
                (
                    "tiebreaker_rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of tiebreaker criteria.",
                        verbose_name="Tiebreaker Rules",
                    ),
                ),
                (
                    "config",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="br_scoring",
                        to="tournaments.gamematchconfig",
                        verbose_name="Game Config",
                    ),
                ),
            ],
            options={
                "verbose_name": "BR Scoring Matrix",
                "verbose_name_plural": "BR Scoring Matrices",
                "db_table": "toc_br_scoring_matrix",
            },
        ),
        migrations.CreateModel(
            name="KYCSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID (NID)"),
                            ("passport", "Passport"),
                            ("student_id", "Student ID"),
                            ("mfs_account", "MFS Account Screenshot"),
                            ("selfie_with_id", "Selfie with ID"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "document_front",
                    models.FileField(
                        help_text="Front of document (image/PDF).", upload_to="kyc/documents/"
                    ),
                ),
                (
                    "document_back",
                    models.FileField(
                        blank=True,
                        help_text="Back of document (for NID).",
                        null=True,
                        upload_to="kyc/documents/",
                    ),
                ),
                (
                    "selfie_image",
                    models.ImageField(
                        blank=True, help_text="Selfie with ID.", null=True, upload_to="kyc/selfies/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Verification valid until (default: 6 months from approval).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prize_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyc_submissions",
                        to="tournaments.prizeclaim",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament_kyc_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_submissions",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC Submission",
                "verbose_name_plural": "KYC Submissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("uploaded_by_id", models.PositiveIntegerField()),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("screenshot", "Screenshot"),
                            ("video", "Video"),
                            ("replay", "Replay"),
                            ("other", "Other"),
                        ],
                        default="screenshot",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="match_media/")),
                ("url", models.URLField(blank=True, max_length=500)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "is_evidence",
                    models.BooleanField(default=False, help_text="Flagged as dispute evidence"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="tournaments.match",
                    ),
                ),
            ],
            options={
                "db_table": "toc_match_media",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchServerSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("region", models.CharField(max_length=50)),
                ("server_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("server_name", models.CharField(blank=True, max_length=200)),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_selection",
                        to="tournaments.match",
                    ),
                ),
            ],
            options={
                "db_table": "toc_match_server_selection",
            },
        ),
        migrations.CreateModel(
            name="MatchVetoSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "veto_type",
                    models.CharField(default="standard", max_length=30, verbose_name="Veto Type"),
                ),
                (
                    "sequence",
                    models.JSONField(blank=True, default=list, verbose_name="Veto Sequence"),
                ),
                ("picks", models.JSONField(blank=True, default=list, verbose_name="Picks")),
                (
                    "current_step",
                    models.PositiveIntegerField(default=0, verbose_name="Current Step"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veto_session",
                        to="tournaments.match",
                        verbose_name="Match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Veto Session",
                "verbose_name_plural": "Match Veto Sessions",
                "db_table": "toc_match_veto_session",
            },
        ),
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("single_elimination", "Single Elimination"),
                            ("double_elimination", "Double Elimination"),
                            ("round_robin", "Round Robin"),
                            ("swiss", "Swiss"),
                            ("group_playoff", "Group Stage + Playoff"),
                        ],
                        max_length=30,
                    ),
                ),
                ("max_teams", models.PositiveIntegerField(default=0, help_text="0 = unlimited")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Stage order within pipeline (0 = first)."
                    ),
                ),
                (
                    "tournament_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_stages",
                        to="tournaments.tournamentstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Stage",
                "verbose_name_plural": "Pipeline Stages",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "criteria",
                    models.CharField(
                        choices=[
                            ("top_n", "Top N"),
                            ("top_n_per_group", "Top N per Group"),
                            ("points_threshold", "Points Threshold"),
                            ("manual", "Manual Selection"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="N for top_n/top_n_per_group, min points for threshold.",
                    ),
                ),
                (
                    "auto_promote",
                    models.BooleanField(
                        default=False, help_text="Automatically promote when stage completes."
                    ),
                ),
                (
                    "from_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_rules_out",
                        to="tournaments.pipelinestage",
                    ),
                ),
                (
                    "to_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_rules_in",
                        to="tournaments.pipelinestage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Rule",
                "verbose_name_plural": "Promotion Rules",
                "ordering": ["from_stage__order"],
            },
        ),
        migrations.CreateModel(
            name="QualifierPipeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifier_pipelines",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualifier Pipeline",
                "verbose_name_plural": "Qualifier Pipelines",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="pipelinestage",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="tournaments.qualifierpipeline",
            ),
        ),
        migrations.CreateModel(
            name="RescheduleRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "requested_by_id",
                    models.PositiveIntegerField(help_text="User ID who requested the reschedule"),
                ),
                ("old_time", models.DateTimeField(blank=True, null=True)),
                ("new_time", models.DateTimeField()),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_by_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reschedule_requests",
                        to="tournaments.match",
                    ),
                ),
            ],
            options={
                "db_table": "toc_reschedule_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RulebookVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text='e.g. "1.0", "2.1-draft"', max_length=30, verbose_name="Version"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown or HTML content of the rulebook.",
                        verbose_name="Content",
                    ),
                ),
                ("changelog", models.TextField(blank=True, default="", verbose_name="Changelog")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active / Published"),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rulebook_versions",
                        to="tournaments.tournament",
                        verbose_name="Tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rulebook Version",
                "verbose_name_plural": "Rulebook Versions",
                "db_table": "toc_rulebook_version",
                "ordering": ["-created_at"],
                "unique_together": {("tournament", "version")},
            },
        ),
        migrations.CreateModel(
            name="TournamentBounty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Bounty display name, e.g. "Tournament MVP".', max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Bounty criteria / description."
                    ),
                ),
                (
                    "bounty_type",
                    models.CharField(
                        choices=[
                            ("mvp", "MVP"),
                            ("stat_leader", "Stat Leader"),
                            ("community_vote", "Community Vote"),
                            ("special_achievement", "Special Achievement"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=30,
                    ),
                ),
                (
                    "prize_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Prize amount for this bounty.", max_digits=12
                    ),
                ),
                (
                    "prize_currency",
                    models.CharField(default="BDT", help_text="BDT or deltacoin.", max_length=20),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("prize_pool", "Prize Pool"),
                            ("sponsor", "Sponsor"),
                            ("platform", "Platform"),
                        ],
                        default="prize_pool",
                        max_length=20,
                    ),
                ),
                (
                    "sponsor_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sponsor name if source == sponsor.",
                        max_length=200,
                    ),
                ),
                ("is_assigned", models.BooleanField(default=False)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment_reason",
                    models.TextField(
                        blank=True, default="", help_text="Justification for assigning."
                    ),
                ),
                (
                    "claim_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("paid_out", "Paid Out"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bounties_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bounty_wins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to_registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bounty_awards",
                        to="tournaments.registration",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bounties",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Bounty",
                "verbose_name_plural": "Tournament Bounties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "rendered_html",
                    models.TextField(blank=True, default="", verbose_name="Rendered HTML"),
                ),
                (
                    "generated_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="Generated PDF",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of variables used for rendering.",
                        verbose_name="Context Data",
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_records",
                        to="tournaments.tournament",
                        verbose_name="Tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="tournaments.certificatetemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Record",
                "verbose_name_plural": "Certificate Records",
                "db_table": "toc_certificate_record",
                "ordering": ["-issued_at"],
                "unique_together": {("user", "tournament", "template")},
            },
        ),
        migrations.CreateModel(
            name="FreeAgentRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("drafted", "Drafted"),
                            ("assigned", "Assigned"),
                            ("self_formed", "Self-Formed"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='In-game role, e.g. "IGL", "Entry Fragger", "Support".',
                        max_length=100,
                    ),
                ),
                (
                    "rank_info",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Self-reported rank, e.g. "Diamond 3", "Heroic".',
                        max_length=100,
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", help_text="Short pitch text.")),
                (
                    "availability_notes",
                    models.TextField(blank=True, default="", help_text="Schedule constraints."),
                ),
                (
                    "game_id",
                    models.CharField(
                        blank=True, default="", help_text="In-game name / IGN.", max_length=200
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to_team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team the FA was assigned to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="free_agent_assignments",
                        to="teams.team",
                    ),
                ),
                (
                    "drafted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Captain who drafted this FA.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafted_free_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        help_text="Created once assigned to a team.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="free_agent_source",
                        to="tournaments.registration",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_agent_registrations",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_agent_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Free Agent Registration",
                "verbose_name_plural": "Free Agent Registrations",
                "ordering": ["-created_at"],
                "unique_together": {("tournament", "user")},
            },
        ),
        migrations.CreateModel(
            name="MapPoolEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("map_name", models.CharField(max_length=120, verbose_name="Map Name")),
                (
                    "map_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Internal/game code for the map.",
                        max_length=60,
                        verbose_name="Map Code",
                    ),
                ),
                ("image", models.URLField(blank=True, default="", verbose_name="Map Image URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_pool",
                        to="tournaments.gamematchconfig",
                        verbose_name="Game Config",
                    ),
                ),
            ],
            options={
                "verbose_name": "Map Pool Entry",
                "verbose_name_plural": "Map Pool Entries",
                "db_table": "toc_map_pool_entry",
                "ordering": ["order", "map_name"],
                "unique_together": {("config", "map_name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="pipelinestage",
            unique_together={("pipeline", "order")},
        ),
        migrations.CreateModel(
            name="RulebookConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("consented_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rulebook_consents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "rulebook_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="tournaments.rulebookversion",
                        verbose_name="Rulebook Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rulebook Consent",
                "verbose_name_plural": "Rulebook Consents",
                "db_table": "toc_rulebook_consent",
                "unique_together": {("user", "rulebook_version")},
            },
        ),
        migrations.CreateModel(
            name="ServerRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Region Name")),
                (
                    "code",
                    models.CharField(
                        help_text='e.g. "us-east", "eu-west"',
                        max_length=20,
                        verbose_name="Region Code",
                    ),
                ),
                (
                    "ping_endpoint",
                    models.URLField(blank=True, default="", verbose_name="Ping Endpoint"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_regions",
                        to="tournaments.tournament",
                        verbose_name="Tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Server Region",
                "verbose_name_plural": "Server Regions",
                "db_table": "toc_server_region",
                "ordering": ["name"],
                "unique_together": {("tournament", "code")},
            },
        ),
        migrations.CreateModel(
            name="TrustEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("match_played", "Match Played"),
                            ("match_won", "Match Won"),
                            ("forfeit", "Forfeit"),
                            ("no_show", "No Show"),
                            ("dispute_filed", "Dispute Filed"),
                            ("dispute_lost", "Dispute Lost"),
                            ("dispute_won", "Dispute Won"),
                            ("cheating", "Cheating Confirmed"),
                            ("good_conduct", "Good Conduct"),
                            ("manual", "Manual Adjustment"),
                        ],
                        max_length=30,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "delta",
                    models.IntegerField(
                        default=0,
                        help_text="Positive = trust increase, negative = decrease.",
                        verbose_name="Delta",
                    ),
                ),
                ("reason", models.TextField(blank=True, default="", verbose_name="Reason")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_events",
                        to="tournaments.tournament",
                        verbose_name="Tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Event",
                "verbose_name_plural": "Trust Events",
                "db_table": "toc_trust_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="toc_trust_e_user_id_94ed32_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTrophy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_trophies",
                        to="tournaments.tournament",
                        verbose_name="Tournament",
                    ),
                ),
                (
                    "trophy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="tournaments.profiletrophy",
                        verbose_name="Trophy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trophies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Trophy",
                "verbose_name_plural": "User Trophies",
                "db_table": "toc_user_trophy",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "trophy", "tournament")},
            },
        ),
    ]
