# Generated by Django 5.2.8 on 2025-12-08 18:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_registration_completion_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(default='Group Stage', help_text='Name of this group stage phase', max_length=100, verbose_name='Stage Name')),
                ('num_groups', models.PositiveIntegerField(help_text='Total number of groups in this stage', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Groups')),
                ('group_size', models.PositiveIntegerField(help_text='Number of participants per group', validators=[django.core.validators.MinValueValidator(2)], verbose_name='Group Size')),
                ('format', models.CharField(choices=[('round_robin', 'Round Robin'), ('double_round_robin', 'Double Round Robin')], default='round_robin', help_text='Match format within groups', max_length=20, verbose_name='Format')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', help_text='Current state of the group stage', max_length=20, verbose_name='State')),
                ('advancement_count_per_group', models.PositiveIntegerField(default=2, help_text='Number of teams that advance from each group', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Teams Advancing Per Group')),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON config: points_system, tiebreaker_rules, seeding_method', verbose_name='Configuration')),
                ('tournament', models.ForeignKey(help_text='Tournament this group stage belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='group_stages', to='tournaments.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Group Stage',
                'verbose_name_plural': 'Group Stages',
                'db_table': 'tournament_group_stages',
                'ordering': ['tournament', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text='Name of this stage (e.g., "Group Stage", "Playoffs", "Grand Finals")', max_length=100, verbose_name='Stage Name')),
                ('order', models.PositiveIntegerField(help_text='Sequential order of this stage (1 = first stage, 2 = second, etc.)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Order')),
                ('format', models.CharField(choices=[('round_robin', 'Round Robin'), ('single_elim', 'Single Elimination'), ('double_elim', 'Double Elimination'), ('swiss', 'Swiss System')], help_text='Tournament format for this stage', max_length=20, verbose_name='Format')),
                ('start_date', models.DateTimeField(blank=True, help_text='Scheduled start date/time for this stage', null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Scheduled or actual end date/time for this stage', null=True, verbose_name='End Date')),
                ('advancement_count', models.PositiveIntegerField(default=0, help_text='Number of participants advancing to next stage (0 = final stage)', verbose_name='Advancement Count')),
                ('advancement_criteria', models.CharField(choices=[('top_n', 'Top N Overall'), ('top_n_per_group', 'Top N Per Group'), ('all', 'All Participants')], default='top_n', help_text='How participants advance to next stage', max_length=20, verbose_name='Advancement Criteria')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', help_text='Current state of this stage', max_length=20, verbose_name='State')),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON config: seeding_rules, tiebreakers, bracket_options', verbose_name='Configuration')),
                ('group_stage', models.OneToOneField(blank=True, help_text='Link to GroupStage if this stage uses group format', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_stage', to='tournaments.groupstage', verbose_name='Group Stage')),
                ('tournament', models.ForeignKey(help_text='Tournament this stage belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournaments.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Tournament Stage',
                'verbose_name_plural': 'Tournament Stages',
                'db_table': 'tournament_stages',
                'ordering': ['tournament', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='groupstage',
            index=models.Index(fields=['tournament', 'state'], name='tournament__tournam_149f52_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupstage',
            constraint=models.CheckConstraint(condition=models.Q(('num_groups__gte', 1)), name='groupstage_min_groups'),
        ),
        migrations.AddConstraint(
            model_name='groupstage',
            constraint=models.CheckConstraint(condition=models.Q(('group_size__gte', 2)), name='groupstage_min_group_size'),
        ),
        migrations.AddConstraint(
            model_name='groupstage',
            constraint=models.CheckConstraint(condition=models.Q(('advancement_count_per_group__gte', 1)), name='groupstage_min_advancement'),
        ),
        migrations.AddIndex(
            model_name='tournamentstage',
            index=models.Index(fields=['tournament', 'order'], name='tournament__tournam_1b0228_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentstage',
            index=models.Index(fields=['tournament', 'state'], name='tournament__tournam_d6c7b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentstage',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='stage_min_order'),
        ),
        migrations.AddConstraint(
            model_name='tournamentstage',
            constraint=models.CheckConstraint(condition=models.Q(('advancement_count__gte', 0)), name='stage_min_advancement'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentstage',
            unique_together={('tournament', 'order')},
        ),
    ]
