# Generated by Django 5.2.8 on 2025-12-09 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_add_group_stage_and_tournament_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.IntegerField(blank=True, help_text='TournamentStage ID (nullable for cross-stage operations)', null=True)),
                ('operation', models.CharField(choices=[('swap', 'Swap Participants'), ('move', 'Move Participant'), ('remove', 'Remove Participant'), ('repair', 'Repair Bracket'), ('validate', 'Validate Bracket')], help_text='Type of bracket edit operation', max_length=20)),
                ('match_ids', models.JSONField(default=list, help_text='List of affected match IDs')),
                ('participant_ids', models.JSONField(blank=True, default=list, help_text='List of affected participant IDs (optional)')),
                ('old_data', models.JSONField(default=dict, help_text='State before edit (JSON)')),
                ('new_data', models.JSONField(default=dict, help_text='State after edit (JSON)')),
                ('user_id', models.IntegerField(blank=True, help_text='User who performed edit (nullable for system edits)', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When edit was performed')),
            ],
            options={
                'verbose_name': 'Bracket Edit Log',
                'verbose_name_plural': 'Bracket Edit Logs',
                'db_table': 'tournament_bracket_edit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stage_id', '-timestamp'], name='tournament__stage_i_8883ca_idx'), models.Index(fields=['operation', '-timestamp'], name='tournament__operati_90aadd_idx'), models.Index(fields=['user_id', '-timestamp'], name='tournament__user_id_c12f89_idx')],
            },
        ),
    ]
