# Generated by Django 4.2.23 on 2025-09-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_allow_null_round_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Organizer-defined custom fields data'),
        ),
    ]
