# Generated by Django 5.2.8 on 2026-03-02 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0023_drop_groupstanding_team_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="groupstanding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("user__isnull", False)),
                fields=("group", "user"),
                name="unique_active_group_user_standing",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupstanding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("team_id__isnull", False)),
                fields=("group", "team_id"),
                name="unique_active_group_team_standing",
            ),
        ),
    ]
