# Generated by Django 5.2.8 on 2025-12-09 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_bracketeditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('auto_approved', 'Auto Approved'), ('needs_review', 'Needs Review'), ('payment_submitted', 'Payment Submitted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('waitlisted', 'Waitlisted'), ('no_show', 'No Show')], db_index=True, default='pending', help_text='Current registration status', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistrationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('slug', models.SlugField(help_text='Machine-readable key: rank, region, discord_username', max_length=100)),
                ('text', models.TextField(help_text='Question label shown to user')),
                ('help_text', models.TextField(blank=True, help_text='Additional help text for users')),
                ('type', models.CharField(choices=[('text', 'Text Input'), ('select', 'Single Select'), ('multi_select', 'Multi Select'), ('boolean', 'Yes/No'), ('number', 'Number'), ('file', 'File Upload'), ('date', 'Date')], default='text', max_length=20)),
                ('scope', models.CharField(choices=[('team', 'Team Level'), ('player', 'Player Level')], default='player', max_length=10)),
                ('is_required', models.BooleanField(default=False, help_text='Question must be answered')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Question configuration: {options: [], min: 0, max: 100, regex: "pattern", ...}')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('show_if', models.JSONField(blank=True, default=dict, help_text='Conditional display: {tournament_type: "team", age: {"gte": 18}}')),
                ('is_built_in', models.BooleanField(default=False, help_text='System-provided question (cannot be deleted)')),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(blank=True, help_text='Game-specific question (null for global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_questions', to='tournaments.game')),
                ('tournament', models.ForeignKey(blank=True, help_text='Tournament-specific question (null for global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_questions', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('value', models.JSONField(help_text='Answer value: string, number, boolean, list, or dict')),
                ('normalized_value', models.TextField(blank=True, help_text='Normalized value for search/filtering')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tournaments.registration')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tournaments.registrationquestion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text='Rule description: "Auto-approve verified Immortal+ players"', max_length=200)),
                ('rule_type', models.CharField(choices=[('auto_approve', 'Auto Approve'), ('auto_reject', 'Auto Reject'), ('flag_for_review', 'Flag for Review')], max_length=20)),
                ('condition', models.JSONField(help_text='Condition expression: {"rank": {"in": ["Immortal", "Radiant"]}, "email_verified": true}')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower = higher priority (evaluated first)')),
                ('is_active', models.BooleanField(default=True)),
                ('reason_template', models.TextField(blank=True, help_text='Reason shown to user if rule triggers: "Registration auto-approved (verified Immortal player)"')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_rules', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Universal draft ID for cross-device resume', unique=True)),
                ('registration_number', models.CharField(help_text='Human-readable: VCT-2025-001234', max_length=20, unique=True)),
                ('team_id', models.IntegerField(blank=True, db_index=True, help_text='Team ID (IntegerField to avoid circular dependency)', null=True)),
                ('form_data', models.JSONField(default=dict, help_text='All form fields: {riot_id, discord, phone, answers: {...}}')),
                ('auto_filled_fields', models.JSONField(default=list, help_text='Fields auto-filled: ["riot_id", "email"]')),
                ('locked_fields', models.JSONField(default=list, help_text='Fields locked (verified): ["email", "riot_id"]')),
                ('current_step', models.CharField(choices=[('player_info', 'Player Information'), ('team_info', 'Team Information'), ('questions', 'Additional Questions'), ('review', 'Review & Confirm'), ('payment', 'Payment')], default='player_info', max_length=20)),
                ('completion_percentage', models.PositiveIntegerField(default=0, help_text='0-100')),
                ('submitted', models.BooleanField(default=False, help_text='Draft converted to registration')),
                ('last_saved_at', models.DateTimeField(auto_now=True, help_text='Auto-updated on every save (for auto-save tracking)')),
                ('expires_at', models.DateTimeField(help_text='Draft expires 7 days after creation')),
                ('registration', models.OneToOneField(blank=True, help_text='Created after draft submission', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.registration')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_drafts', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['uuid'], name='tournaments_uuid_5b9ded_idx'), models.Index(fields=['registration_number'], name='tournaments_registr_3c3301_idx'), models.Index(fields=['expires_at'], name='tournaments_expires_437943_idx')],
                'unique_together': {('user', 'tournament')},
            },
        ),
        migrations.AddIndex(
            model_name='registrationquestion',
            index=models.Index(fields=['tournament', 'order'], name='tournaments_tournam_8f69ad_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationquestion',
            index=models.Index(fields=['game', 'order'], name='tournaments_game_id_f4dffb_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationquestion',
            index=models.Index(fields=['slug'], name='tournaments_slug_28527a_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationanswer',
            index=models.Index(fields=['registration'], name='tournaments_registr_69595e_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationanswer',
            index=models.Index(fields=['question'], name='tournaments_questio_2d7e06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registrationanswer',
            unique_together={('registration', 'question')},
        ),
        migrations.AddIndex(
            model_name='registrationrule',
            index=models.Index(fields=['tournament', 'is_active', 'priority'], name='tournaments_tournam_f4f1d7_idx'),
        ),
    ]
