# Generated by Django 5.2.8 on 2026-03-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0024_add_unique_group_standing_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Organizer phone number for participants (WhatsApp-enabled)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="social_facebook",
            field=models.URLField(
                blank=True, default="", help_text="Organizer Facebook page/group URL"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="social_tiktok",
            field=models.URLField(blank=True, default="", help_text="Organizer TikTok profile URL"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="support_info",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom support/dispute instructions for participants (shown in Hub)",
            ),
        ),
    ]
