# Generated by Django 5.2.8 on 2025-12-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_teammembership_is_role_custom_and_more'),
        ('tournaments', '0025_result_submission_phase6_epic61'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultverificationlog',
            name='step',
            field=models.CharField(choices=[('schema_validation', 'Schema Validation'), ('scoring_calculation', 'Scoring Calculation'), ('organizer_review', 'Organizer Review'), ('finalization', 'Finalization'), ('opponent_confirm', 'Opponent Confirmation'), ('opponent_dispute', 'Opponent Dispute'), ('dispute_escalated', 'Dispute Escalated'), ('dispute_resolved', 'Dispute Resolved')], help_text='Verification step performed', max_length=30),
        ),
        migrations.CreateModel(
            name='DisputeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_for_submitter', 'Resolved - Submitter Wins'), ('resolved_for_opponent', 'Resolved - Opponent Wins'), ('cancelled', 'Cancelled'), ('escalated', 'Escalated')], db_index=True, default='open', help_text='Current dispute status', max_length=32)),
                ('reason_code', models.CharField(choices=[('score_mismatch', 'Score Mismatch'), ('wrong_winner', 'Wrong Winner Declared'), ('cheating_suspicion', 'Cheating Suspicion'), ('incorrect_map', 'Incorrect Map/Details'), ('match_not_played', 'Match Not Played'), ('other', 'Other')], default='other', help_text='Categorized reason for dispute', max_length=32)),
                ('description', models.TextField(help_text='Detailed description of the dispute from opponent')),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Internal notes explaining the resolution decision')),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the dispute was opened')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, help_text='When the dispute was resolved', null=True)),
                ('escalated_at', models.DateTimeField(blank=True, help_text='When the dispute was escalated', null=True)),
                ('opened_by_team', models.ForeignKey(blank=True, help_text='Team representing the disputer (if team tournament)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='teams.team')),
                ('opened_by_user', models.ForeignKey(help_text='User who opened the dispute', on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by_user', models.ForeignKey(blank=True, help_text='User who made the final resolution decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(help_text='The result submission being disputed', on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='tournaments.matchresultsubmission')),
            ],
            options={
                'db_table': 'tournaments_dispute_record',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('video', 'Video Recording'), ('chat_log', 'Chat Log'), ('other', 'Other')], default='screenshot', help_text='Type of evidence', max_length=32)),
                ('url', models.URLField(help_text='URL to external resource (imgur, Discord CDN, S3, etc.)', max_length=500)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional context or notes about this evidence')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the evidence was uploaded')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the evidence', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_dispute_evidence', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(help_text='The dispute this evidence belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='tournaments.disputerecord')),
            ],
            options={
                'db_table': 'tournaments_dispute_evidence',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='disputerecord',
            index=models.Index(fields=['submission', 'status'], name='idx_dispute_submission_status'),
        ),
        migrations.AddIndex(
            model_name='disputerecord',
            index=models.Index(fields=['opened_at'], name='idx_dispute_opened_at'),
        ),
        migrations.AddIndex(
            model_name='disputerecord',
            index=models.Index(fields=['resolved_at'], name='idx_dispute_resolved_at'),
        ),
        migrations.AddIndex(
            model_name='disputerecord',
            index=models.Index(fields=['status'], name='idx_dispute_status'),
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['dispute'], name='idx_evidence_dispute'),
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['created_at'], name='idx_evidence_created_at'),
        ),
    ]
