# Generated by Django 5.2.8 on 2025-12-09 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_dispute_phase6_epic62'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name of the role (e.g., 'Tournament Referee')", max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text="Short identifier (e.g., 'referee', 'admin')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of role responsibilities')),
                ('capabilities', models.JSONField(default=dict, help_text="Capability flags as JSON (e.g., {'can_schedule': true, 'can_resolve_disputes': true})")),
                ('is_referee_role', models.BooleanField(default=False, help_text='True if this role can be assigned to referee matches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
                'db_table': 'tournament_staff_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='False if assignment has been revoked')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(help_text='Organizer who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epic73_staff_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Staff role assigned', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tournaments.staffrole')),
                ('stage', models.ForeignKey(blank=True, help_text='Optional: limit assignment to specific stage', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epic73_staff_assignments', to='tournaments.tournamentstage')),
                ('tournament', models.ForeignKey(help_text='Tournament this assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='epic73_staff_assignments', to='tournaments.tournament')),
                ('user', models.ForeignKey(help_text='User assigned to staff role', on_delete=django.db.models.deletion.CASCADE, related_name='epic73_tournament_staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournament Staff Assignment',
                'verbose_name_plural': 'Tournament Staff Assignments',
                'db_table': 'tournament_staff_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchRefereeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='True for primary referee, False for backup/secondary')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this referee assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(help_text='Organizer who assigned this referee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epic73_referee_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(help_text='Match being refereed', on_delete=django.db.models.deletion.CASCADE, related_name='epic73_referee_assignments', to='tournaments.match')),
                ('staff_assignment', models.ForeignKey(help_text='Staff assignment (must have referee role)', on_delete=django.db.models.deletion.CASCADE, related_name='epic73_match_assignments', to='tournaments.tournamentstaffassignment')),
            ],
            options={
                'verbose_name': 'Match Referee Assignment',
                'verbose_name_plural': 'Match Referee Assignments',
                'db_table': 'match_referee_assignments',
                'ordering': ['-is_primary', '-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tournamentstaffassignment',
            index=models.Index(fields=['tournament', 'is_active'], name='tournament__tournam_8d0a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentstaffassignment',
            index=models.Index(fields=['user', 'is_active'], name='tournament__user_id_64f712_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentstaffassignment',
            index=models.Index(fields=['role', 'is_active'], name='tournament__role_id_b751ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentstaffassignment',
            unique_together={('tournament', 'user', 'role')},
        ),
        migrations.AddIndex(
            model_name='matchrefereeassignment',
            index=models.Index(fields=['match', 'is_primary'], name='match_refer_match_i_6a7d06_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrefereeassignment',
            index=models.Index(fields=['staff_assignment'], name='match_refer_staff_a_1c2e52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchrefereeassignment',
            unique_together={('match', 'staff_assignment')},
        ),
    ]
