# Generated by Django 4.2.23 on 2025-09-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_remove_duplicate_entry_fee_from_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentverification',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Internal reference number for payment tracking', max_length=64, null=True),
        ),
    ]
