# Generated by Django 5.2.8 on 2026-03-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0027_add_discord_webhook_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="enable_no_show_timer",
            field=models.BooleanField(
                default=False,
                help_text="Automatically forfeit matches when both teams fail to start within the timeout window",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="no_show_timeout_minutes",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Minutes after scheduled start before a no-show forfeit is issued (requires enable_no_show_timer)",
            ),
        ),
    ]
