# Generated by Django 5.2.8 on 2025-12-09 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0027_add_staff_role_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchModeratorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_user_id', models.IntegerField(help_text='User ID of staff/referee who wrote the note')),
                ('content', models.TextField(help_text='Note content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the note was created')),
                ('match', models.ForeignKey(help_text='Match this note applies to', on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notes', to='tournaments.match')),
            ],
            options={
                'db_table': 'match_moderator_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['match', 'created_at'], name='match_moder_match_i_0b3733_idx'), models.Index(fields=['author_user_id', 'created_at'], name='match_moder_author__b7bd70_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_user_id', models.IntegerField(help_text='User ID of staff/referee who performed the operation')),
                ('operation_type', models.CharField(choices=[('LIVE', 'Match Marked Live'), ('PAUSED', 'Match Paused'), ('RESUMED', 'Match Resumed'), ('FORCE_COMPLETED', 'Match Force Completed'), ('NOTE_ADDED', 'Moderator Note Added'), ('OVERRIDE_RESULT', 'Result Overridden'), ('OVERRIDE_REFEREE', 'Referee Assignment Overridden')], help_text='Type of operation performed', max_length=50)),
                ('payload', models.JSONField(blank=True, help_text='Additional metadata about the operation (previous state, overrides, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the operation was performed')),
                ('match', models.ForeignKey(help_text='Match this operation was performed on', on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='tournaments.match')),
            ],
            options={
                'db_table': 'match_operation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['match', 'created_at'], name='match_opera_match_i_f2124c_idx'), models.Index(fields=['operation_type', 'created_at'], name='match_opera_operati_c45d02_idx'), models.Index(fields=['operator_user_id', 'created_at'], name='match_opera_operato_2d5df3_idx')],
            },
        ),
    ]
