# Generated by Django 5.2.8 on 2026-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0028_add_no_show_timer_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="timezone_name",
            field=models.CharField(
                blank=True,
                default="Asia/Dhaka",
                help_text="IANA timezone name for display (e.g. Asia/Dhaka, UTC). Does not affect stored UTC datetimes.",
                max_length=64,
            ),
        ),
    ]
