# Generated by Django 5.2.8 on 2025-12-09 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0028_add_match_ops_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='after_state',
            field=models.JSONField(blank=True, help_text='State after action (for change tracking, Epic 7.5)', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='before_state',
            field=models.JSONField(blank=True, help_text='State before action (for change tracking, Epic 7.5)', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Request correlation ID for distributed tracing (Epic 7.5)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='match_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Match ID for match-scoped actions (Epic 7.5)', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tournament_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Tournament ID for tournament-scoped actions (Epic 7.5)', null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tournament_id', 'timestamp'], name='tournaments_tournam_6d0f12_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['match_id', 'timestamp'], name='tournaments_match_i_2383e4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['correlation_id'], name='tournaments_correla_e1e6fb_idx'),
        ),
    ]
