# Generated by Django 5.2.8 on 2026-03-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0029_add_timezone_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="best_of",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "BO1"), (3, "BO3"), (5, "BO5")],
                default=1,
                help_text="Series format: 1 = single game, 3 = first to 2, 5 = first to 3",
                verbose_name="Best Of",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="game_scores",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Per-game scores for BO3/BO5 series. List of {"game": N, "p1": X, "p2": Y, "winner_slot": 1|2} objects.',
                verbose_name="Game Scores",
            ),
        ),
    ]
