# Generated by Django 5.2.8 on 2025-12-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0029_add_audit_log_epic75_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_featured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this tournament is featured on the homepage",
            ),
        ),
    ]
