# Generated by Django 4.2.23 on 2025-10-03 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0030_registration_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed')], default='DRAFT', help_text='Tournament lifecycle status. DRAFT=hidden, PUBLISHED=visible, RUNNING=active, COMPLETED=finished', max_length=16),
        ),
        migrations.CreateModel(
            name='TournamentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_open_at', models.DateTimeField(blank=True, help_text='When participants can start registering', null=True, verbose_name='Registration Opens At')),
                ('reg_close_at', models.DateTimeField(blank=True, help_text='When registration deadline ends', null=True, verbose_name='Registration Closes At')),
                ('start_at', models.DateTimeField(blank=True, help_text='When matches begin', null=True, verbose_name='Tournament Starts At')),
                ('end_at', models.DateTimeField(blank=True, help_text='Expected tournament completion time', null=True, verbose_name='Tournament Ends At')),
                ('check_in_open_mins', models.PositiveIntegerField(blank=True, default=60, help_text='How many minutes before tournament start should check-in open', null=True, verbose_name='Check-in Opens (minutes before start)')),
                ('check_in_close_mins', models.PositiveIntegerField(blank=True, default=10, help_text='How many minutes before tournament start should check-in close', null=True, verbose_name='Check-in Closes (minutes before start)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.OneToOneField(help_text='Tournament this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Schedule',
                'verbose_name_plural': 'Tournament Schedules',
                'db_table': 'tournaments_schedule',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reg_open_at', 'reg_close_at'], name='idx_reg_window'), models.Index(fields=['start_at', 'end_at'], name='idx_tournament_window')],
            },
        ),
    ]
