# Generated by Django 5.2.8 on 2026-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0030_add_series_best_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="cancellation_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reason for tournament cancellation (shown to participants)",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, help_text="When tournament was cancelled", null=True
            ),
        ),
    ]
