# Generated by Django 5.2.8 on 2026-03-06 16:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0031_add_cancellation_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchMapPlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated"
                    ),
                ),
                (
                    "team_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Team this player played for",
                        null=True,
                        verbose_name="Team ID",
                    ),
                ),
                (
                    "map_number",
                    models.PositiveSmallIntegerField(
                        help_text="Map number in the series (1, 2, 3...)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Map Number",
                    ),
                ),
                (
                    "map_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Map name (e.g., Ascent, Haven)",
                        max_length=50,
                        verbose_name="Map Name",
                    ),
                ),
                (
                    "agent",
                    models.CharField(blank=True, default="", max_length=30, verbose_name="Agent"),
                ),
                ("kills", models.PositiveIntegerField(default=0, verbose_name="Kills")),
                ("deaths", models.PositiveIntegerField(default=0, verbose_name="Deaths")),
                ("assists", models.PositiveIntegerField(default=0, verbose_name="Assists")),
                (
                    "acs",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=7, verbose_name="ACS"
                    ),
                ),
                (
                    "adr",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=7, verbose_name="ADR"
                    ),
                ),
                (
                    "headshot_pct",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="HS%",
                    ),
                ),
                ("first_kills", models.PositiveIntegerField(default=0, verbose_name="FK")),
                ("first_deaths", models.PositiveIntegerField(default=0, verbose_name="FD")),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_player_stats",
                        to="tournaments.match",
                        verbose_name="Match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_match_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Map Player Stat",
                "verbose_name_plural": "Match Map Player Stats",
                "db_table": "tournament_match_map_player_stat",
                "ordering": ["map_number", "-acs"],
                "indexes": [
                    models.Index(
                        fields=["match", "map_number", "team_id"], name="idx_mmps_match_map_team"
                    )
                ],
                "unique_together": {("match", "player", "map_number")},
            },
        ),
        migrations.CreateModel(
            name="MatchPlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated"
                    ),
                ),
                (
                    "team_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Team this player played for in this match",
                        null=True,
                        verbose_name="Team ID",
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Primary agent played (Valorant-specific)",
                        max_length=30,
                        verbose_name="Agent",
                    ),
                ),
                ("kills", models.PositiveIntegerField(default=0, verbose_name="Kills")),
                ("deaths", models.PositiveIntegerField(default=0, verbose_name="Deaths")),
                ("assists", models.PositiveIntegerField(default=0, verbose_name="Assists")),
                (
                    "acs",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Average Combat Score",
                        max_digits=7,
                        verbose_name="ACS",
                    ),
                ),
                (
                    "adr",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Average Damage per Round",
                        max_digits=7,
                        verbose_name="ADR",
                    ),
                ),
                (
                    "headshot_pct",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Headshot percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="HS%",
                    ),
                ),
                (
                    "first_kills",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="First bloods / opening kills",
                        verbose_name="First Kills",
                    ),
                ),
                (
                    "first_deaths",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Times died first in a round",
                        verbose_name="First Deaths",
                    ),
                ),
                (
                    "clutches",
                    models.PositiveIntegerField(
                        default=0, help_text="Clutch rounds won", verbose_name="Clutches"
                    ),
                ),
                (
                    "multi_kills",
                    models.PositiveIntegerField(
                        default=0, help_text="Rounds with 3+ kills", verbose_name="Multi-kills"
                    ),
                ),
                (
                    "plants",
                    models.PositiveIntegerField(
                        default=0, help_text="Spike plants", verbose_name="Plants"
                    ),
                ),
                (
                    "defuses",
                    models.PositiveIntegerField(
                        default=0, help_text="Spike defuses", verbose_name="Defuses"
                    ),
                ),
                (
                    "kd_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Kill/Death ratio (cached)",
                        max_digits=5,
                        verbose_name="K/D",
                    ),
                ),
                (
                    "kast_pct",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Kill/Assist/Survive/Trade percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="KAST%",
                    ),
                ),
                (
                    "is_mvp",
                    models.BooleanField(
                        default=False, help_text="Match MVP designation", verbose_name="MVP"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="tournaments.match",
                        verbose_name="Match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Player Stat",
                "verbose_name_plural": "Match Player Stats",
                "db_table": "tournament_match_player_stat",
                "ordering": ["-acs"],
                "indexes": [
                    models.Index(fields=["match", "team_id"], name="idx_mps_match_team"),
                    models.Index(fields=["player", "-acs"], name="idx_mps_player_acs"),
                    models.Index(fields=["match", "-acs"], name="idx_mps_match_acs"),
                ],
                "unique_together": {("match", "player")},
            },
        ),
    ]
