# Generated by Django 5.2.8 on 2026-03-07 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0032_match_player_stats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="payment_status_valid",
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="evidence_file",
            field=models.FileField(
                blank=True,
                help_text="Direct file upload (screenshot, video clip). Max 10MB recommended.",
                null=True,
                upload_to="disputes/evidence/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="matchresultsubmission",
            name="proof_screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Direct file upload of proof screenshot. Max 10MB recommended.",
                null=True,
                upload_to="matches/evidence/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="disputeevidence",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to external resource (imgur, Discord CDN, S3, etc.)",
                max_length=500,
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending",
                            "submitted",
                            "verified",
                            "rejected",
                            "refunded",
                            "expired",
                            "waived",
                        ],
                    )
                ),
                name="payment_status_valid",
            ),
        ),
    ]
