# Generated by Django 5.2.8 on 2026-03-14 23:39

from django.conf import settings
from django.db import migrations, models


def _normalize_dispute_statuses_forward(apps, schema_editor):
    DisputeRecord = apps.get_model("tournaments", "DisputeRecord")
    DisputeRecord.objects.filter(status="cancelled").update(status="dismissed")
    DisputeRecord.objects.filter(status="auto_resolved").update(status="dismissed")


def _normalize_dispute_statuses_backward(apps, schema_editor):
    DisputeRecord = apps.get_model("tournaments", "DisputeRecord")
    DisputeRecord.objects.filter(status="dismissed").update(status="cancelled")
    DisputeRecord.objects.filter(status="resolved_custom").update(status="resolved_for_submitter")


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0033_add_evidence_file_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="matchresultsubmission",
            name="ingested_at",
            field=models.DateTimeField(
                blank=True, help_text="When an automated source ingested this submission", null=True
            ),
        ),
        migrations.AddField(
            model_name="matchresultsubmission",
            name="ingestion_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Deterministic dedupe key for automated ingestion sources",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="matchresultsubmission",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Submission"),
                    ("riot_api", "Riot API Ingestion"),
                    ("admin_override", "Admin Override"),
                ],
                db_index=True,
                default="manual",
                help_text="Submission source for canonical ingestion provenance",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            code=_normalize_dispute_statuses_forward,
            reverse_code=_normalize_dispute_statuses_backward,
        ),
        migrations.AlterField(
            model_name="disputerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("under_review", "Under Review"),
                    ("escalated", "Escalated"),
                    ("resolved_for_submitter", "Resolved - Submitter Wins"),
                    ("resolved_for_opponent", "Resolved - Opponent Wins"),
                    ("resolved_custom", "Resolved - Custom Organizer Ruling"),
                    ("dismissed", "Dismissed"),
                ],
                db_index=True,
                default="open",
                help_text="Current dispute status",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="disputerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "open",
                            "under_review",
                            "escalated",
                            "resolved_for_submitter",
                            "resolved_for_opponent",
                            "resolved_custom",
                            "dismissed",
                        ],
                    )
                ),
                name="chk_dispute_record_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchresultsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending",
                            "confirmed",
                            "disputed",
                            "auto_confirmed",
                            "finalized",
                            "rejected",
                        ],
                    )
                ),
                name="chk_submission_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchresultsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["manual", "riot_api", "admin_override"])),
                name="chk_submission_source_valid",
            ),
        ),
    ]
