# Generated by Django 5.2.8 on 2026-03-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0036_ddl_drop_and_retarget_team_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="disputerecord",
            name="flagged_by_system",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when this dispute was raised automatically by the integrity check pipeline",
            ),
        ),
        migrations.AlterField(
            model_name="matchresultsubmission",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Submission"),
                    ("riot_api", "Riot API Ingestion"),
                    ("steam_api", "Steam API Ingestion"),
                    ("admin_override", "Admin Override"),
                ],
                db_index=True,
                default="manual",
                help_text="Submission source for canonical ingestion provenance",
                max_length=32,
            ),
        ),
    ]
