# Generated by Django 5.2.8 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0037_add_source_steam_api_and_flagged_by_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="auto_forfeit_no_shows",
            field=models.BooleanField(
                default=False,
                help_text="Automatically issue no-show forfeits for non-started matches when organizer policy allows",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_waitlist_size",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum waitlist size (0 means unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="waitlist_auto_promote",
            field=models.BooleanField(
                default=False,
                help_text="Automatically promote waitlisted registrations when slots become available",
            ),
        ),
    ]
