# Generated by Django 5.2.8 on 2026-03-23 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0038_add_waitlist_policy_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournamentsponsor",
            options={
                "ordering": [
                    models.Case(
                        models.When(then=models.Value(0), tier="title"),
                        models.When(then=models.Value(1), tier="gold"),
                        models.When(then=models.Value(2), tier="silver"),
                        models.When(then=models.Value(3), tier="bronze"),
                        models.When(then=models.Value(4), tier="partner"),
                        default=models.Value(99),
                        output_field=models.IntegerField(),
                    ),
                    "display_order",
                    "name",
                ],
                "verbose_name": "Tournament Sponsor",
                "verbose_name_plural": "Tournament Sponsors",
            },
        ),
        migrations.CreateModel(
            name="HubSupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "team_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Team ID for team registrations (if applicable).",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("dispute", "Match Dispute"),
                            ("technical", "Technical Issue"),
                            ("payment", "Payment / Prize"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("match_ref", models.CharField(blank=True, default="", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In Review"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("organizer_notes", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hub_support_tickets",
                        to="tournaments.registration",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_hub_support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_support_tickets",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hub Support Ticket",
                "verbose_name_plural": "Hub Support Tickets",
                "db_table": "tournaments_hub_support_ticket",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tournament", "created_at"], name="idx_hub_ticket_tour_created"
                    ),
                    models.Index(
                        fields=["created_by", "created_at"], name="idx_hub_ticket_user_created"
                    ),
                    models.Index(
                        fields=["registration", "status"], name="idx_hub_ticket_reg_status"
                    ),
                    models.Index(fields=["team_id", "status"], name="idx_hub_ticket_team_status"),
                ],
            },
        ),
    ]
