# Generated by Django 5.2.8 on 2026-03-29 16:09

from django.db import migrations


REQUIRED_RESCHEDULE_COLUMNS = {
    "proposer_side",
    "reviewed_at",
    "response_note",
    "expires_at",
}


def assert_reschedule_negotiation_columns(apps, schema_editor):
    """Fail fast if expected participant-reschedule columns are missing."""
    RescheduleRequest = apps.get_model("tournaments", "RescheduleRequest")
    table_name = RescheduleRequest._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        table_description = schema_editor.connection.introspection.get_table_description(cursor, table_name)

    present_columns = {
        (getattr(col, "name", None) or col[0])
        for col in table_description
    }
    missing = sorted(REQUIRED_RESCHEDULE_COLUMNS.difference(present_columns))
    if missing:
        raise RuntimeError(
            "Reschedule schema verification failed for %s. Missing columns: %s"
            % (table_name, ", ".join(missing))
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0041_add_reschedule_negotiation_fields"),
    ]

    operations = [
        migrations.RunPython(assert_reschedule_negotiation_columns, migrations.RunPython.noop),
    ]
