# Generated by Django 5.2.8 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0042_ensure_reschedule_negotiation_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="match_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Game-specific match configuration rendered in match lobby rules (JSONB)",
            ),
        ),
    ]
