# Generated by Django 5.2.8 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0043_add_tournament_match_settings"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="match",
            name="chk_match_completed_has_winner",
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(state="completed", winner_id__isnull=False, loser_id__isnull=False)
                    | models.Q(
                        state="completed",
                        winner_id__isnull=True,
                        loser_id__isnull=True,
                        participant1_score=models.F("participant2_score"),
                    )
                    | ~models.Q(state="completed")
                ),
                name="chk_match_completed_has_winner",
            ),
        ),
    ]
