# Generated by Django 5.2.8 on 2026-04-01 01:51

import apps.tournaments.models.dispute
import apps.tournaments.models.result_submission
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0044_allow_completed_draw_without_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disputeevidence",
            name="evidence_file",
            field=models.FileField(
                blank=True,
                help_text="Direct file upload (screenshot, video clip). Max 10MB recommended.",
                null=True,
                upload_to=apps.tournaments.models.dispute._dispute_evidence_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp", "mp4", "webm"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="matchresultsubmission",
            name="proof_screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Direct file upload of proof screenshot. Max 10MB recommended.",
                null=True,
                upload_to=apps.tournaments.models.result_submission._proof_screenshot_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
            ),
        ),
    ]
