# Generated by Django 4.2.24 on 2025-10-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0045_gameconfiguration_playerroleconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.CharField(choices=[('valorant', 'VALORANT'), ('cs2', 'Counter-Strike 2'), ('dota2', 'Dota 2'), ('mlbb', 'Mobile Legends: Bang Bang'), ('pubg', 'PUBG: Battlegrounds'), ('freefire', 'Free Fire'), ('efootball', 'eFootball'), ('fc26', 'FC 26 (EA Sports)')], max_length=20),
        ),
    ]
