# Generated by Django 5.2.8 on 2026-04-01 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0045_alter_disputeevidence_evidence_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lobbyannouncement",
            name="lobby",
        ),
        migrations.RemoveField(
            model_name="lobbyannouncement",
            name="posted_by",
        ),
        migrations.AlterUniqueTogether(
            name="tournamentstaff",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tournamentstaff",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="tournamentstaff",
            name="deactivated_by",
        ),
        migrations.RemoveField(
            model_name="tournamentstaff",
            name="role",
        ),
        migrations.RemoveField(
            model_name="tournamentstaff",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="tournamentstaff",
            name="user",
        ),
        migrations.DeleteModel(
            name="Dispute",
        ),
        migrations.DeleteModel(
            name="LobbyAnnouncement",
        ),
        migrations.DeleteModel(
            name="TournamentStaff",
        ),
    ]
