# Generated by Django 5.2.8 on 2026-04-01 09:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0046_remove_lobbyannouncement_lobby_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="damage_dealt",
            field=models.PositiveIntegerField(default=0, verbose_name="Damage"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="extra_stats",
            field=models.JSONField(blank=True, default=dict, verbose_name="Extra Stats"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="goals",
            field=models.PositiveIntegerField(default=0, verbose_name="Goals"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="gpm",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=7, verbose_name="GPM"
            ),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="healing",
            field=models.PositiveIntegerField(default=0, verbose_name="Healing"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="hero_damage",
            field=models.PositiveIntegerField(default=0, verbose_name="Hero Dmg"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="hero_played",
            field=models.CharField(blank=True, default="", max_length=60, verbose_name="Hero"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="passes",
            field=models.PositiveIntegerField(default=0, verbose_name="Passes"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="placement",
            field=models.PositiveIntegerField(default=0, verbose_name="Placement"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="possession_pct",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Possession %",
            ),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="revives",
            field=models.PositiveIntegerField(default=0, verbose_name="Revives"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="saves",
            field=models.PositiveIntegerField(default=0, verbose_name="Saves"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="shots",
            field=models.PositiveIntegerField(default=0, verbose_name="Shots"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="shots_on_target",
            field=models.PositiveIntegerField(default=0, verbose_name="On Target"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="survival_time_seconds",
            field=models.PositiveIntegerField(default=0, verbose_name="Survival (s)"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="tackles",
            field=models.PositiveIntegerField(default=0, verbose_name="Tackles"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="tower_damage",
            field=models.PositiveIntegerField(default=0, verbose_name="Tower Dmg"),
        ),
        migrations.AddField(
            model_name="matchmapplayerstat",
            name="xpm",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=7, verbose_name="XPM"
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="damage_dealt",
            field=models.PositiveIntegerField(
                default=0, help_text="Total damage dealt", verbose_name="Damage"
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="extra_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Overflow JSON for game-specific fields not covered above.",
                verbose_name="Extra Stats",
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="goals",
            field=models.PositiveIntegerField(default=0, verbose_name="Goals"),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="gpm",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Gold per minute",
                max_digits=7,
                verbose_name="GPM",
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="healing",
            field=models.PositiveIntegerField(
                default=0, help_text="Total healing done", verbose_name="Healing"
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="hero_damage",
            field=models.PositiveIntegerField(
                default=0, help_text="Total hero damage dealt", verbose_name="Hero Dmg"
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="hero_played",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Primary hero/champion played",
                max_length=60,
                verbose_name="Hero",
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="passes",
            field=models.PositiveIntegerField(default=0, verbose_name="Passes"),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="placement",
            field=models.PositiveIntegerField(
                default=0, help_text="Final placement position", verbose_name="Placement"
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="possession_pct",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Possession %",
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="revives",
            field=models.PositiveIntegerField(
                default=0, help_text="Teammates revived", verbose_name="Revives"
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="saves",
            field=models.PositiveIntegerField(
                default=0, help_text="Goalkeeper saves or RL saves", verbose_name="Saves"
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="shots",
            field=models.PositiveIntegerField(default=0, verbose_name="Shots"),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="shots_on_target",
            field=models.PositiveIntegerField(default=0, verbose_name="On Target"),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="survival_time_seconds",
            field=models.PositiveIntegerField(
                default=0, help_text="Survival time in seconds", verbose_name="Survival (s)"
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="tackles",
            field=models.PositiveIntegerField(default=0, verbose_name="Tackles"),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="tower_damage",
            field=models.PositiveIntegerField(
                default=0, help_text="Total tower/objective damage", verbose_name="Tower Dmg"
            ),
        ),
        migrations.AddField(
            model_name="matchplayerstat",
            name="xpm",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Experience per minute",
                max_digits=7,
                verbose_name="XPM",
            ),
        ),
        migrations.CreateModel(
            name="MatchIntegrityCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "manual_payload",
                    models.JSONField(
                        default=dict,
                        help_text="Score data from player-submitted results.",
                        verbose_name="Manual Submission",
                    ),
                ),
                (
                    "api_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw data fetched from the external game API.",
                        verbose_name="API Response",
                    ),
                ),
                (
                    "diff",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Field-level differences between manual and API data.",
                        verbose_name="Diff",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("riot", "Riot Games API"),
                            ("steam", "Steam / Valve API"),
                            ("faceit", "FACEIT API"),
                            ("manual", "Admin manual override"),
                        ],
                        default="riot",
                        max_length=20,
                        verbose_name="API Source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending API fetch"),
                            ("match", "Scores match"),
                            ("mismatch", "Score mismatch — flagged"),
                            ("api_error", "API fetch failed"),
                            ("skipped", "No API available for this game"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, default="", verbose_name="Review Notes"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fetched_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="API Fetched At"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_check",
                        to="tournaments.match",
                        verbose_name="Match",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Integrity Check",
                "verbose_name_plural": "Match Integrity Checks",
                "db_table": "tournament_match_integrity_check",
                "ordering": ["-created_at"],
            },
        ),
    ]
