# Generated by Django 5.2.8 on 2026-04-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0049_soft_delete_group_paymentverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="no_show_timeout_minutes",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Minutes after scheduled start before a no-show forfeit is issued (requires enable_no_show_timer)",
            ),
        ),
    ]
