# Generated by Django 5.2.8 on 2026-04-11 08:28

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brackets", "0003_alter_bracketnode_deleted_by"),
        ("tournaments", "0050_change_no_show_timeout_default_5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="disputeevidence",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="disputerecord",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="disputerecord",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="disputerecord",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="tournamentbounty",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="tournamentbounty",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamentbounty",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="file_image",
            field=models.ImageField(
                blank=True,
                help_text="Generated PNG/JPEG certificate image",
                null=True,
                upload_to="certificates/images/%Y/%m/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="file_pdf",
            field=models.FileField(
                blank=True,
                help_text="Generated PDF certificate file",
                null=True,
                upload_to="certificates/pdf/%Y/%m/",
                validators=[apps.common.validators.validate_document_upload],
            ),
        ),
        migrations.AlterField(
            model_name="formresponse",
            name="payment_proof",
            field=models.FileField(
                blank=True,
                help_text="Screenshot of payment",
                null=True,
                upload_to="registration_payments/",
                validators=[apps.common.validators.validate_payment_proof_upload],
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymentverification",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymentverification",
            name="proof_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="payments/proofs/",
                validators=[apps.common.validators.validate_payment_proof_upload],
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registrationformtemplate",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Preview image for template selection",
                null=True,
                upload_to="form_templates/thumbnails/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Tournament banner image",
                null=True,
                upload_to="tournaments/banners/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="rules_pdf",
            field=models.FileField(
                blank=True,
                help_text="Tournament rules PDF file",
                null=True,
                upload_to="tournaments/rules/",
                validators=[apps.common.validators.validate_document_upload],
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="terms_pdf",
            field=models.FileField(
                blank=True,
                help_text="Terms & Conditions PDF document (optional)",
                null=True,
                upload_to="tournaments/terms/",
                validators=[apps.common.validators.validate_document_upload],
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True,
                help_text="Tournament thumbnail for listings",
                null=True,
                upload_to="tournaments/thumbnails/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="tournamentresult",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tournamenttemplate",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="groupstanding",
            index=models.Index(
                fields=["group", "user", "team_id"], name="idx_standing_group_participant"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["tournament", "state", "scheduled_time"], name="idx_match_tourn_state_sched"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["state", "is_deleted", "scheduled_time"], name="idx_match_state_del_sched"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["is_deleted", "status"], name="payment_del_stat_idx"),
        ),
    ]
