# Generated by Django 5.2.8 on 2026-04-20 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0051_disputeevidence_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentFanPredictionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('poll_id', models.CharField(db_index=True, help_text='Stable poll question identifier from widget config.', max_length=64)),
                ('option_id', models.CharField(help_text='Selected option identifier within the poll question.', max_length=64)),
                ('tournament', models.ForeignKey(help_text='Tournament this vote belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='fan_prediction_votes', to='tournaments.tournament')),
                ('user', models.ForeignKey(help_text='Viewer who submitted this prediction.', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_fan_prediction_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournament Fan Prediction Vote',
                'verbose_name_plural': 'Tournament Fan Prediction Votes',
                'db_table': 'tournaments_fan_prediction_vote',
                'unique_together': {('tournament', 'user', 'poll_id')},
            },
        ),
        migrations.AddIndex(
            model_name='tournamentfanpredictionvote',
            index=models.Index(fields=['tournament', 'poll_id'], name='idx_fanvote_t_poll'),
        ),
        migrations.AddIndex(
            model_name='tournamentfanpredictionvote',
            index=models.Index(fields=['tournament', 'poll_id', 'option_id'], name='idx_fanvote_t_poll_opt'),
        ),
    ]
