# Generated by Django 5.2.8 on 2026-04-21 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0052_tournamentfanpredictionvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCenterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('show_timeline', models.BooleanField(default=True)),
                ('show_media', models.BooleanField(default=True)),
                ('show_stats', models.BooleanField(default=True)),
                ('show_fan_pulse', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('cyber', 'Cyber'), ('tactical', 'Tactical'), ('arena', 'Arena')], default='cyber', max_length=24)),
                ('poll_question', models.CharField(default='Who takes the series?', max_length=180)),
                ('poll_option_a', models.CharField(default='Team A', max_length=80)),
                ('poll_option_b', models.CharField(default='Team B', max_length=80)),
                ('auto_refresh_seconds', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('match_overrides', models.JSONField(blank=True, default=dict, help_text='Per-match overrides keyed by match id as string.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_center_config', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Match Center Configuration',
                'verbose_name_plural': 'Match Center Configurations',
                'db_table': 'toc_match_center_config',
            },
        ),
    ]
