# Generated by Django 5.2.8 on 2026-04-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0054_tournamentresult_fourth_place_and_standings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organizer_access_expires_at',
            field=models.DateTimeField(blank=True, help_text='When organizer TOC access expires (auto-set to 7 days post-completion). Null = no expiry.', null=True),
        ),
    ]
