# Generated by Django 5.2.8 on 2026-04-30 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0056_prizeclaim_claim_details_and_other"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="format",
            field=models.CharField(
                choices=[
                    ("single_elimination", "Single Elimination"),
                    ("double_elimination", "Double Elimination"),
                    ("round_robin", "Round Robin"),
                    ("swiss", "Swiss"),
                    ("group_playoff", "Group Stage + Playoff"),
                    ("battle_royale", "Battle Royale / Lobby Leaderboard"),
                ],
                default="single_elimination",
                help_text="Bracket format for the tournament",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="TournamentHostingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hosting_fee_dc",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Amount in DeltaCoin charged to any user who creates a tournament. Staff/superuser accounts are always exempt. Set to 0 for free hosting.",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Hosting Fee (DeltaCoin)",
                    ),
                ),
                (
                    "hosting_fee_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to make tournament creation free for everyone (overrides the DC amount above).",
                        verbose_name="Hosting Fee Enabled",
                    ),
                ),
                (
                    "staff_bypass_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When checked, staff & superuser accounts never pay the hosting fee.",
                        verbose_name="Staff Bypass",
                    ),
                ),
                (
                    "organizer_access_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Number of days an organiser retains full TOC access after the tournament ends. After this period read-only mode kicks in (like Faceit / Toornament).",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Organiser Access Duration (days)",
                    ),
                ),
                (
                    "tier_free_label",
                    models.CharField(
                        blank=True, default="Starter", max_length=64, verbose_name="Free Tier Label"
                    ),
                ),
                (
                    "tier_free_description",
                    models.TextField(
                        blank=True,
                        default="Community tournament — up to 32 slots, basic bracket, public listing.",
                        verbose_name="Free Tier Description",
                    ),
                ),
                (
                    "tier_standard_label",
                    models.CharField(
                        blank=True,
                        default="Standard",
                        max_length=64,
                        verbose_name="Standard Tier Label",
                    ),
                ),
                (
                    "tier_standard_description",
                    models.TextField(
                        blank=True,
                        default="Up to 128 slots, all formats, prize pool support, custom branding & TOC access for 90 days.",
                        verbose_name="Standard Tier Description",
                    ),
                ),
                (
                    "tier_premium_label",
                    models.CharField(
                        blank=True,
                        default="Premium",
                        max_length=64,
                        verbose_name="Premium Tier Label",
                    ),
                ),
                (
                    "tier_premium_description",
                    models.TextField(
                        blank=True,
                        default="Unlimited slots, featured listing, dedicated support, extended TOC access, sponsor integration.",
                        verbose_name="Premium Tier Description",
                    ),
                ),
                (
                    "tier_premium_dc",
                    models.PositiveIntegerField(
                        default=2000,
                        help_text="Future premium tier price — not yet enforced, for display only.",
                        verbose_name="Premium Tier Fee (DC)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes — not shown to users.",
                        verbose_name="Admin Notes",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hosting & Pricing Configuration",
                "verbose_name_plural": "Hosting & Pricing Configuration",
            },
        ),
    ]
