# Generated by Django 5.2.8 on 2026-04-30 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0057_hosting_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="active_promo",
            field=models.CharField(
                choices=[
                    ("none", "No promotion active"),
                    ("time", "Free until a specific date"),
                    ("first_users", "Free for the first N registered users"),
                    ("first_tournaments", "Free for the first N tournaments created"),
                    ("always_free", "Always free (Beta / Launch mode)"),
                ],
                default="none",
                help_text="Choose which promotion is active. Only one promo runs at a time. Each type has its own configuration section below.",
                max_length=24,
                verbose_name="Active Promotion",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="official_tournaments_require_staff",
            field=models.BooleanField(
                default=True,
                help_text="Enforce that only staff/superuser accounts can publish under the 'Official Tournament' badge. Mirrors user_can_create_official.",
                verbose_name="Official Tournaments Require Staff Account",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="promo_description",
            field=models.TextField(
                blank=True,
                default="We're in beta — host your first tournament completely free. Limited spots.",
                help_text="Longer text shown below the banner. Explain the promo to potential organisers.",
                verbose_name="Promo Description",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="promo_first_n_tournaments_limit",
            field=models.PositiveIntegerField(
                default=500,
                help_text="[First-N Tournaments] The first this-many tournaments ever created on the platform are free (regardless of who creates them).",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="First-N Tournaments Limit",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="promo_first_n_tournaments_used",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Auto-incremented each time a tournament is created under this promo.",
                verbose_name="First-N Tournaments Used (auto-tracked)",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="promo_first_n_users_limit",
            field=models.PositiveIntegerField(
                default=100,
                help_text="[First-N Users] The first this-many users who create a tournament get it free. Tracking counter is below (read-only).",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="First-N Users Limit",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="promo_first_n_users_used",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Auto-incremented each time a user gets a free hosting under this promo. Do not edit manually.",
                verbose_name="First-N Users Used (auto-tracked)",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="promo_free_until",
            field=models.DateTimeField(
                blank=True,
                help_text="[Time-Based Promo] Tournament creation is free for EVERYONE until this date and time. Leave blank if not using time-based promo.",
                null=True,
                verbose_name="Free Until (date/time)",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="promo_label",
            field=models.CharField(
                blank=True,
                default="🎉 Beta Launch — Host Free!",
                help_text="Short headline shown on the tournament creation wizard (e.g. '🎉 Beta Launch — Host Free!').",
                max_length=128,
                verbose_name="Promo Banner Label",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="signup_bonus_dc_amount",
            field=models.PositiveIntegerField(
                default=500,
                help_text="DC credited to new organisers on their first tournament creation (if bonus is enabled).",
                verbose_name="Signup Bonus Amount (DC)",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="signup_bonus_dc_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Award DeltaCoin to every new user on their first tournament creation.",
                verbose_name="New User Signup Bonus Enabled",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="staff_can_waive_fee",
            field=models.BooleanField(
                default=True,
                help_text="Allow staff to manually grant a free hosting pass to a specific user.",
                verbose_name="Staff Can Waive Fee for Any User",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="staff_max_slots_override",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Max participants staff accounts can set. 0 = no limit.",
                verbose_name="Staff Slot Override (0 = unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="user_allowed_formats_json",
            field=models.TextField(
                blank=True,
                default='["single_elimination","double_elimination","round_robin","swiss","group_playoff"]',
                help_text='JSON list of allowed format values. e.g. ["single_elimination","round_robin"]. Leave as full list to allow all formats. Available: single_elimination, double_elimination, round_robin, swiss, group_playoff.',
                verbose_name="Allowed Formats for Regular Users (JSON list)",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="user_can_charge_entry_fee",
            field=models.BooleanField(
                default=True,
                help_text="Allow non-staff organisers to set a real-currency entry fee (bKash, Nagad, etc.).",
                verbose_name="Regular Users Can Charge Real-Money Entry Fee",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="user_can_create_official",
            field=models.BooleanField(
                default=False,
                help_text="Allow regular (non-staff) users to tick the 'Official Tournament' checkbox. Keep OFF to reserve the Official badge for staff-created events.",
                verbose_name="Regular Users Can Mark as Official",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="user_can_feature_tournament",
            field=models.BooleanField(
                default=False,
                help_text="Allow regular users to set is_featured=True on their tournaments.",
                verbose_name="Regular Users Can Feature Their Tournament",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="user_can_set_deltacoin_prize",
            field=models.BooleanField(
                default=True,
                help_text="Allow regular organisers to add a DC prize pool to their tournament. Turn OFF to reserve prize-pool tournaments for official events.",
                verbose_name="Regular Users Can Set a DeltaCoin Prize Pool",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="user_max_active_tournaments",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Max number of non-completed, non-cancelled tournaments a regular user can have at once. 0 = unlimited.",
                verbose_name="Max Active Tournaments Per User",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="user_max_deltacoin_prize",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cap on DC prize pool for non-staff organisers. 0 = unlimited.",
                verbose_name="Max DeltaCoin Prize Pool for Regular Users",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthostingconfig",
            name="user_max_participants",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Hard cap on max_participants for non-staff tournament creation. 0 = no cap (unlimited). e.g. 128 to cap community events.",
                verbose_name="Max Participants Cap (Regular Users)",
            ),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Never shown to users.", verbose_name="Admin Notes (internal)"
            ),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="hosting_fee_dc",
            field=models.PositiveIntegerField(
                default=500,
                help_text="Amount charged when no promotion applies. Staff/superuser are always exempt when Staff Bypass is on. Set to 0 for free hosting without turning off the fee engine.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Base Hosting Fee (DeltaCoin)",
            ),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="hosting_fee_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Master switch. Uncheck to make tournament creation free for EVERYONE, ignoring the DC amount and all promotions.",
                verbose_name="Hosting Fee Enabled",
            ),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="organizer_access_days",
            field=models.PositiveIntegerField(
                default=90,
                help_text="Days after tournament end that the organiser retains full TOC access. After this, the console switches to read-only mode.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Organiser TOC Access Duration (days)",
            ),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="staff_bypass_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When on, staff and superuser accounts always host for free.",
                verbose_name="Staff / Superuser Bypass",
            ),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="tier_free_description",
            field=models.TextField(
                blank=True,
                default="Community tournament — up to 32 slots, basic bracket, public listing.",
            ),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="tier_free_label",
            field=models.CharField(blank=True, default="Starter", max_length=64),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="tier_premium_dc",
            field=models.PositiveIntegerField(
                default=2000,
                help_text="Future premium tier price — not yet enforced.",
                verbose_name="Premium Tier Fee (DC) — display only",
            ),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="tier_premium_description",
            field=models.TextField(
                blank=True,
                default="Unlimited slots, featured listing, dedicated support, sponsor integration.",
            ),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="tier_premium_label",
            field=models.CharField(blank=True, default="Premium", max_length=64),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="tier_standard_description",
            field=models.TextField(
                blank=True,
                default="Up to 128 slots, all formats, prize pool support, custom branding & 90-day TOC access.",
            ),
        ),
        migrations.AlterField(
            model_name="tournamenthostingconfig",
            name="tier_standard_label",
            field=models.CharField(blank=True, default="Standard", max_length=64),
        ),
    ]
