# Generated by Django 5.2.8 on 2026-05-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0058_hosting_config_advanced"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_api_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True = this game uses an official API integration for score verification (e.g. Valorant via Riot API). False = manual/screenshot-based result submission (e.g. eFootball). Used by the escrow service to enforce wager caps: manual games are capped at 1000 DC per side to mitigate dispute fraud.",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="require_kyc_for_prizes",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If True, winners must pass KYC verification before a PrizeClaim ticket can be marked PAID. Organizers toggle this per tournament. Recommended for prize pools above the KYC threshold.",
            ),
        ),
    ]
