# Generated by Django 5.2.8 on 2026-05-17 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0061_submission_game_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchresultsubmission",
            name="ocr_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Overall extraction confidence 0..1. Null when not run.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="matchresultsubmission",
            name="ocr_extracted",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Game-specific extracted data (score / KDA / agents / etc.).",
            ),
        ),
        migrations.CreateModel(
            name="DisputeNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("internal_staff", "Internal staff"),
                            ("participant_safe", "Participant safe"),
                        ],
                        db_index=True,
                        default="participant_safe",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament_dispute_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="tournaments.disputerecord",
                    ),
                ),
            ],
            options={
                "db_table": "tournaments_dispute_note",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["dispute", "created_at"], name="disp_note_dispute_created_idx"
                    ),
                    models.Index(fields=["visibility"], name="disp_note_visibility_idx"),
                ],
            },
        ),
    ]
