# Generated by Django 5.2.8 on 2026-05-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0062_dispute_notes"),
        ("tournaments", "0062_submission_soft_archive"),
    ]

    operations = []
