# Generated by Django 5.2.8 on 2026-05-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0063_merge_0062_dispute_notes_0062_submission_soft_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchresultsubmission",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when the submission was archived.", null=True
            ),
        ),
    ]
