# Generated by Django 5.2.8 on 2026-05-18 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0064_alter_matchresultsubmission_archived_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Tournament description and overview"
            ),
        ),
        migrations.CreateModel(
            name="TournamentHostingFeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount_dc",
                    models.PositiveIntegerField(default=0, help_text="DC charged (0 for waived)."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waived", "Waived (free / staff exempt)"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("disputed", "Disputed / Under Review"),
                        ],
                        db_index=True,
                        default="waived",
                        max_length=16,
                    ),
                ),
                (
                    "wallet_transaction_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="DeltaCrownTransaction.id for this debit. Null for waived records.",
                        null=True,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Idempotency key used for the wallet debit transaction.",
                        max_length=128,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Admin / system notes about this payment record.",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tournament",
                    models.OneToOneField(
                        blank=True,
                        help_text="Created tournament. Null while creation is in flight.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosting_fee_payment",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Organiser who initiated tournament creation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hosting_fee_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who manually verified this payment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_hosting_fee_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Hosting Fee Payment",
                "verbose_name_plural": "Tournament Hosting Fee Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="tournaments_status_258b10_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="tournaments_user_id_ed3fc9_idx"
                    ),
                ],
            },
        ),
    ]
