# Generated by Django 5.2.8 on 2026-05-06 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("economy", "0012_phase_d_fortress_pin_hash"),
        ("games", "0007_gametournamentconfig_credential_schema_and_more"),
        ("tournaments", "0059_prize_claim_playbook_compliance_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoyaleLobby",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        db_index=True,
                        help_text="Stable reference (e.g. 'RY-FF-A1B2C3').",
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Player-facing lobby title (e.g. 'Friday Night Bermuda Drop').",
                        max_length=120,
                    ),
                ),
                (
                    "slot_capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum number of paid slots in this lobby."
                    ),
                ),
                (
                    "entry_fee_dc",
                    models.PositiveIntegerField(
                        default=0, help_text="DeltaCoins each player locks to reserve a slot."
                    ),
                ),
                (
                    "prize_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-placement payout config.  See model docstring.",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        help_text="UTC time the match begins (room ID is revealed at this time)."
                    ),
                ),
                (
                    "registration_opens_at",
                    models.DateTimeField(
                        blank=True, help_text="When slot reservations open.", null=True
                    ),
                ),
                (
                    "registration_closes_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When slot reservations close (typically scheduled_at).",
                        null=True,
                    ),
                ),
                (
                    "room_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom-room ID, surfaced to confirmed entries at match time.",
                        max_length=64,
                    ),
                ),
                (
                    "room_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom-room password (treat as semi-secret).",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANNOUNCED", "Announced — Reservations not yet open"),
                            ("FILLING", "Filling — Reservations open"),
                            ("FULL", "Full — All slots reserved"),
                            ("LIVE", "Live — Match in progress"),
                            ("SCORING", "Scoring — Awaiting placement results"),
                            ("SETTLED", "Settled — Prizes paid"),
                            ("CANCELLED", "Cancelled — Refunded all reservations"),
                        ],
                        db_index=True,
                        default="ANNOUNCED",
                        max_length=20,
                    ),
                ),
                (
                    "closure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not closed"),
                            ("SETTLED_NORMAL", "Match completed and prizes paid"),
                            ("CANCELLED_BY_ADMIN", "Cancelled by admin"),
                            ("CANCELLED_INSUFFICIENT", "Cancelled — insufficient reservations"),
                            ("CANCELLED_GAME_OUTAGE", "Cancelled — upstream game outage"),
                            ("VOIDED_DISPUTE", "Voided — unresolved scoring dispute"),
                        ],
                        db_index=True,
                        default="",
                        help_text="Why the lobby closed.  UI must surface this rather than a bare countdown.",
                        max_length=32,
                    ),
                ),
                (
                    "closure_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form admin/system note for the closure.",
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="royale_lobbies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="royale_lobbies",
                        to="games.game",
                    ),
                ),
                (
                    "tournament",
                    models.OneToOneField(
                        help_text="The Tournament row that owns the bracket / check-in flow.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="royale_lobby",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Royale Lobby",
                "verbose_name_plural": "Royale Lobbies",
                "db_table": "royale_lobby",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="RoyaleEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Reserved — Slot held, entry fee locked"),
                            ("CONFIRMED", "Confirmed — Player checked in for the match"),
                            ("SCORED", "Scored — Final placement recorded"),
                            ("NO_SHOW", "No-show — Did not check in"),
                            ("REFUNDED", "Refunded — Reservation cancelled"),
                            ("VOIDED", "Voided — Admin remediation"),
                        ],
                        db_index=True,
                        default="RESERVED",
                        max_length=20,
                    ),
                ),
                (
                    "placement",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Final placement (1 = winner).  Set during scoring.",
                        null=True,
                    ),
                ),
                (
                    "kills",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Kill count from the match (used for tie-breakers).",
                        null=True,
                    ),
                ),
                (
                    "closure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not closed"),
                            ("SETTLED_PRIZE", "Settled — placement prize paid"),
                            ("SETTLED_NO_PRIZE", "Settled — placement out of prize tier"),
                            ("REFUNDED_BY_USER", "Cancelled by user — refunded"),
                            ("REFUNDED_LOBBY", "Lobby cancelled — refunded"),
                            ("FORFEIT_NO_SHOW", "No-show — entry fee forfeited"),
                            ("VOIDED_DISPUTE", "Voided — unresolved scoring dispute"),
                        ],
                        db_index=True,
                        default="",
                        help_text="Why the entry closed.  UI surfaces this on the entry card.",
                        max_length=32,
                    ),
                ),
                (
                    "closure_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form admin/system note for the entry closure.",
                    ),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("scored_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "escrow_lock_txn",
                    models.ForeignKey(
                        blank=True,
                        help_text="Player's entry-fee lock transaction.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="economy.deltacrowntransaction",
                    ),
                ),
                (
                    "payout_txn",
                    models.ForeignKey(
                        blank=True,
                        help_text="Settlement transaction (payout or refund).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="economy.deltacrowntransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="royale_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lobby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="royale.royalelobby",
                    ),
                ),
            ],
            options={
                "verbose_name": "Royale Entry",
                "verbose_name_plural": "Royale Entries",
                "db_table": "royale_entry",
                "ordering": ["lobby", "placement", "reserved_at"],
            },
        ),
        migrations.AddIndex(
            model_name="royalelobby",
            index=models.Index(
                fields=["status", "scheduled_at"], name="royale_lobb_status_441571_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royalelobby",
            index=models.Index(
                fields=["game", "status", "-scheduled_at"], name="royale_lobb_game_id_d0a1d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royaleentry",
            index=models.Index(fields=["lobby", "status"], name="royale_entr_lobby_i_960770_idx"),
        ),
        migrations.AddIndex(
            model_name="royaleentry",
            index=models.Index(
                fields=["user", "-reserved_at"], name="royale_entr_user_id_3003f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royaleentry",
            index=models.Index(
                fields=["lobby", "placement"], name="royale_entr_lobby_i_1460e6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="royaleentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["RESERVED", "CONFIRMED", "SCORED"])),
                fields=("lobby", "user"),
                name="one_open_entry_per_user_lobby",
            ),
        ),
    ]
