# Generated by Django 5.2.8 on 2026-01-31 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0012_alter_membership_invite_team_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameRankingConfig",
            fields=[
                (
                    "game_id",
                    models.CharField(
                        help_text="Game identifier (e.g., 'LOL', 'VAL', 'CS2')",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "game_name",
                    models.CharField(
                        help_text="Human-readable game name (e.g., 'League of Legends')",
                        max_length=100,
                    ),
                ),
                (
                    "scoring_weights",
                    models.JSONField(
                        default=dict,
                        help_text="Point values for different activities. Example: {tournament_win: 500, verified_match_win: 10, challenge_completion: 50, activity_participation: 5}",
                    ),
                ),
                (
                    "tier_thresholds",
                    models.JSONField(
                        default=dict,
                        help_text="Score thresholds for each tier. Example: {DIAMOND: 2000, PLATINUM: 1200, GOLD: 600, SILVER: 250, BRONZE: 100, UNRANKED: 0}",
                    ),
                ),
                (
                    "decay_policy",
                    models.JSONField(
                        default=dict,
                        help_text="Inactivity decay settings. Example: {enabled: true, inactivity_threshold_days: 30, decay_rate_per_day: 0.01}",
                    ),
                ),
                (
                    "verification_rules",
                    models.JSONField(
                        default=dict,
                        help_text="Match verification requirements. Example: {require_opponent_confirmation: true, auto_verify_after_hours: 72, provisional_weight: 0.3}",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this game is currently accepting match reports",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Game Ranking Config",
                "verbose_name_plural": "Game Ranking Configs",
                "db_table": "competition_game_ranking_config",
                "ordering": ["game_name"],
            },
        ),
        migrations.CreateModel(
            name="MatchReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "game_id",
                    models.CharField(
                        db_index=True,
                        help_text="Game this match was played in (e.g., 'LOL', 'VAL')",
                        max_length=10,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("CASUAL", "Casual Match"),
                            ("RANKED", "Ranked Match"),
                            ("CHALLENGE", "Challenge Match"),
                            ("SCRIM", "Scrim / Practice"),
                            ("TOURNAMENT", "Tournament Match"),
                        ],
                        default="CASUAL",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("WIN", "Win"), ("LOSS", "Loss"), ("DRAW", "Draw")], max_length=10
                    ),
                ),
                (
                    "evidence_url",
                    models.URLField(
                        blank=True,
                        help_text="Screenshot, VOD, or match history link",
                        max_length=500,
                    ),
                ),
                (
                    "evidence_notes",
                    models.TextField(
                        blank=True, help_text="Additional context or notes about the match"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("played_at", models.DateTimeField(help_text="When the match was actually played")),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="User who submitted this report (must be team1 member)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_match_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team1_id",
                    models.ForeignKey(
                        help_text="Reporting team (always the submitter)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_reports_as_team1",
                        to="organizations.team",
                    ),
                ),
                (
                    "team2_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opponent team",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_reports_as_team2",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Report",
                "verbose_name_plural": "Match Reports",
                "db_table": "competition_match_report",
                "ordering": ["-played_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamGameRankingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "game_id",
                    models.CharField(
                        help_text="Game identifier (e.g., 'LOL', 'VAL', 'CS2')", max_length=10
                    ),
                ),
                (
                    "score",
                    models.IntegerField(default=0, help_text="Total ranking score for this game"),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("DIAMOND", "Diamond"),
                            ("PLATINUM", "Platinum"),
                            ("GOLD", "Gold"),
                            ("SILVER", "Silver"),
                            ("BRONZE", "Bronze"),
                            ("UNRANKED", "Unranked"),
                        ],
                        default="UNRANKED",
                        max_length=10,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        blank=True, help_text="Global rank for this game (1 = best)", null=True
                    ),
                ),
                (
                    "percentile",
                    models.FloatField(default=0.0, help_text="Percentile ranking (0.0 to 100.0)"),
                ),
                (
                    "verified_match_count",
                    models.IntegerField(
                        default=0, help_text="Number of verified matches contributing to this rank"
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("STABLE", "Stable"),
                            ("ESTABLISHED", "Established"),
                            ("PROVISIONAL", "Provisional"),
                        ],
                        default="PROVISIONAL",
                        max_length=15,
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Score breakdown by source. Example: {tournament_wins: 1500, verified_matches: 450, challenges: 200, decay_penalty: -50}",
                    ),
                ),
                (
                    "last_match_at",
                    models.DateTimeField(
                        blank=True, help_text="When team last played this game", null=True
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        auto_now=True, help_text="When this snapshot was last updated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_ranking_snapshots",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Game Ranking Snapshot",
                "verbose_name_plural": "Team Game Ranking Snapshots",
                "db_table": "competition_team_game_ranking_snapshot",
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="TeamGlobalRankingSnapshot",
            fields=[
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="global_ranking_snapshot",
                        serialize=False,
                        to="organizations.team",
                    ),
                ),
                (
                    "global_score",
                    models.IntegerField(default=0, help_text="Aggregate score across all games"),
                ),
                (
                    "global_tier",
                    models.CharField(
                        choices=[
                            ("DIAMOND", "Diamond"),
                            ("PLATINUM", "Platinum"),
                            ("GOLD", "Gold"),
                            ("SILVER", "Silver"),
                            ("BRONZE", "Bronze"),
                            ("UNRANKED", "Unranked"),
                        ],
                        default="UNRANKED",
                        max_length=10,
                    ),
                ),
                (
                    "global_rank",
                    models.IntegerField(
                        blank=True, help_text="Global rank across all teams (1 = best)", null=True
                    ),
                ),
                (
                    "games_played",
                    models.IntegerField(
                        default=0, help_text="Number of games this team has ranked in"
                    ),
                ),
                (
                    "game_contributions",
                    models.JSONField(
                        default=dict,
                        help_text="Per-game score breakdown. Example: {LOL: 2500, VAL: 1800, CS2: 1200}",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        auto_now=True, help_text="When this snapshot was last updated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Team Global Ranking Snapshot",
                "verbose_name_plural": "Team Global Ranking Snapshots",
                "db_table": "competition_team_global_ranking_snapshot",
                "ordering": ["-global_score"],
                "indexes": [
                    models.Index(fields=["-global_score"], name="competition_global__c81028_idx"),
                    models.Index(
                        fields=["global_tier", "-global_score"],
                        name="competition_global__abaaa6_idx",
                    ),
                    models.Index(fields=["games_played"], name="competition_games_p_3d2477_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchVerification",
            fields=[
                (
                    "match_report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="verification",
                        serialize=False,
                        to="competition.matchreport",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("CONFIRMED", "Confirmed by Opponent"),
                            ("DISPUTED", "Disputed by Opponent"),
                            ("ADMIN_VERIFIED", "Admin Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Confidence"),
                            ("MEDIUM", "Medium Confidence"),
                            ("LOW", "Low Confidence"),
                            ("NONE", "No Confidence"),
                        ],
                        default="LOW",
                        help_text="Confidence level affects ranking weight",
                        max_length=10,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When status changed to CONFIRMED/ADMIN_VERIFIED",
                        null=True,
                    ),
                ),
                (
                    "dispute_reason",
                    models.TextField(
                        blank=True, help_text="Reason for dispute (if status=DISPUTED)"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal notes for admin review"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who verified (opponent or admin)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Verification",
                "verbose_name_plural": "Match Verifications",
                "db_table": "competition_match_verification",
            },
        ),
        migrations.AddIndex(
            model_name="matchreport",
            index=models.Index(
                fields=["game_id", "-played_at"], name="competition_game_id_5227ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchreport",
            index=models.Index(
                fields=["team1_id", "-played_at"], name="competition_team1_i_51bdae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchreport",
            index=models.Index(
                fields=["team2_id", "-played_at"], name="competition_team2_i_36f687_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamgamerankingsnapshot",
            index=models.Index(fields=["game_id", "-score"], name="competition_game_id_7e35de_idx"),
        ),
        migrations.AddIndex(
            model_name="teamgamerankingsnapshot",
            index=models.Index(fields=["tier", "-score"], name="competition_tier_40151d_idx"),
        ),
        migrations.AddIndex(
            model_name="teamgamerankingsnapshot",
            index=models.Index(fields=["confidence_level"], name="competition_confide_296205_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="teamgamerankingsnapshot",
            unique_together={("team", "game_id")},
        ),
        migrations.AddIndex(
            model_name="matchverification",
            index=models.Index(
                fields=["status", "-created_at"], name="competition_status_dbc7b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchverification",
            index=models.Index(fields=["confidence_level"], name="competition_confide_655de6_idx"),
        ),
    ]
