# Generated by Django 5.2.8 on 2026-02-01 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0002_rename_match_report_fk_columns"),
        ("organizations", "0012_alter_membership_invite_team_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="matchreport",
            name="competition_team1_i_51bdae_idx",
        ),
        migrations.RemoveIndex(
            model_name="matchreport",
            name="competition_team2_i_36f687_idx",
        ),
        migrations.AlterField(
            model_name="matchreport",
            name="team1",
            field=models.ForeignKey(
                db_column="team1_id",
                help_text="Reporting team (always the submitter)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_reports_as_team1",
                to="organizations.team",
            ),
        ),
        migrations.AlterField(
            model_name="matchreport",
            name="team2",
            field=models.ForeignKey(
                blank=True,
                db_column="team2_id",
                help_text="Opponent team",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_reports_as_team2",
                to="organizations.team",
            ),
        ),
        migrations.AddIndex(
            model_name="matchreport",
            index=models.Index(
                fields=["team1", "-played_at"], name="competition_team1_i_bfa2ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchreport",
            index=models.Index(
                fields=["team2", "-played_at"], name="competition_team2_i_dae8ef_idx"
            ),
        ),
    ]
