# Generated by Django 5.2.8 on 2026-02-10 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0003_remove_matchreport_competition_team1_i_51bdae_idx_and_more"),
        ("games", "0002_initial"),
        ("organizations", "0033_journey_milestone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bounty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        db_index=True,
                        help_text="Short reference code, e.g. 'BN-VAL-X1Y2Z3'",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active — Open for claims"),
                            ("CLAIMED", "Claimed — Awaiting verification"),
                            ("VERIFIED", "Verified — Claim confirmed"),
                            ("PAID", "Paid — Reward distributed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled by issuer"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "bounty_type",
                    models.CharField(
                        choices=[
                            ("BEAT_US", "Beat Us — Defeat the issuer team"),
                            ("WIN_STREAK", "Win Streak — Win N consecutive matches"),
                            ("FIRST_BLOOD", "First Blood — First team to complete a task"),
                            ("TOURNAMENT_WIN", "Tournament Win — Win a specific tournament"),
                            ("CUSTOM", "Custom — Free-form achievement criteria"),
                        ],
                        default="BEAT_US",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Bounty headline (e.g., 'Can You Beat the Kings?')",
                        max_length=120,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed criteria, rules, and context"),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=dict,
                        help_text='Machine-readable achievement criteria. Examples:\nBEAT_US:       {"format": "BO3", "must_win": true}\nWIN_STREAK:    {"streak_count": 5, "match_type": "RANKED"}\nFIRST_BLOOD:   {"task": "ace_round", "game": "VAL"}\nTOURNAMENT_WIN:{"tournament_id": "uuid"}\nCUSTOM:        {"description": "Score 50 kills in a BR lobby"}',
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("CP", "Crown Points"),
                            ("USD", "Cash (USD)"),
                            ("BADGE", "Exclusive Badge"),
                            ("GLORY", "Glory / Reputation"),
                        ],
                        default="CP",
                        max_length=10,
                    ),
                ),
                (
                    "reward_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Reward value (0 for non-monetary rewards)",
                        max_digits=10,
                    ),
                ),
                (
                    "reward_description",
                    models.CharField(
                        blank=True, help_text="Human-readable reward description", max_length=200
                    ),
                ),
                (
                    "max_claims",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum number of teams that can claim this bounty"
                    ),
                ),
                (
                    "claim_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Current number of successful claims"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, help_text="Bounty expiration date", null=True),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_bounties_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game this bounty applies to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_bounties",
                        to="games.game",
                    ),
                ),
                (
                    "issuer_team",
                    models.ForeignKey(
                        help_text="Team that posted this bounty",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_bounties_issued",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bounty",
                "verbose_name_plural": "Bounties",
                "db_table": "competition_bounty",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        db_index=True,
                        help_text="Short reference code, e.g. 'CH-VAL-A1B2C3'",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open — Awaiting opponent"),
                            ("ACCEPTED", "Accepted — Awaiting schedule"),
                            ("SCHEDULED", "Scheduled — Match time set"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed — Result submitted"),
                            ("SETTLED", "Settled — Result verified & rewards distributed"),
                            ("DECLINED", "Declined by opponent"),
                            ("EXPIRED", "Expired — Deadline passed"),
                            ("CANCELLED", "Cancelled by issuer"),
                            ("DISPUTED", "Disputed — Requires admin review"),
                            ("ADMIN_RESOLVED", "Admin Resolved"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct Challenge — Named opponent"),
                            ("OPEN", "Open Challenge — Any team can accept"),
                            ("RANKED", "Ranked Challenge — Affects rankings"),
                            ("WAGER", "Wager Match — Prize pool at stake"),
                            ("SCRIM", "Scrim / Practice — No ranking impact"),
                        ],
                        default="DIRECT",
                        max_length=20,
                    ),
                ),
                (
                    "best_of",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "BO1 — Single game"),
                            (3, "BO3 — Best of 3"),
                            (5, "BO5 — Best of 5"),
                            (7, "BO7 — Best of 7"),
                        ],
                        default=1,
                        help_text="Series format (BO1/BO3/BO5/BO7)",
                    ),
                ),
                (
                    "game_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Game-specific format settings. Examples:\nFPS:    {"map_pool": ["Ascent", "Bind"], "map_pick_ban": true, "overtime": true}\nMOBA:   {"pick_mode": "DRAFT", "ban_count": 5}\nBR:     {"scoring": "KILL_RACE", "num_rounds": 3, "placement_points": true}\nSPORTS: {"half_length": 6, "extra_time": true}',
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Required platform: PC, Mobile, Console, or blank for any",
                        max_length=20,
                    ),
                ),
                (
                    "server_region",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Preferred server region (e.g., 'NA-East', 'EU-West', 'SEA')",
                        max_length=30,
                    ),
                ),
                (
                    "prize_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No Prize"),
                            ("CP", "Crown Points"),
                            ("USD", "Cash (USD)"),
                            ("GLORY", "Glory / Bragging Rights"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "prize_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Prize value (0 for no-prize challenges)",
                        max_digits=10,
                    ),
                ),
                (
                    "prize_description",
                    models.CharField(
                        blank=True,
                        help_text="Optional human-readable prize description",
                        max_length=200,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Challenge headline (e.g., 'Weekly Duel — BO3 Ascent')",
                        max_length=120,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Rules, trash talk, or additional context"
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, help_text="When the match is scheduled to take place", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Deadline to accept the challenge", null=True
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CHALLENGER_WIN", "Challenger won"),
                            ("CHALLENGED_WIN", "Challenged team won"),
                            ("DRAW", "Draw"),
                            ("FORFEIT_CHALLENGER", "Forfeit by challenger"),
                            ("FORFEIT_CHALLENGED", "Forfeit by challenged"),
                            ("NO_SHOW", "No-show — Neither team appeared"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "score_details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Detailed per-game/round scores"
                    ),
                ),
                (
                    "evidence_url",
                    models.URLField(
                        blank=True,
                        help_text="Screenshot, VOD, or match history link",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Whether this challenge appears in public feeds"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Staff-promoted highlight challenge"
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who accepted on behalf of challenged team",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_challenges_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenged_team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific team challenged (null = open challenge)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_challenges_received",
                        to="organizations.team",
                    ),
                ),
                (
                    "challenger_team",
                    models.ForeignKey(
                        help_text="Team that created and issued the challenge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_challenges_issued",
                        to="organizations.team",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the challenge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_challenges_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game this challenge is played in",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_challenges",
                        to="games.game",
                    ),
                ),
                (
                    "match_report",
                    models.ForeignKey(
                        blank=True,
                        help_text="Generated MatchReport for ranking integration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_challenge_source",
                        to="competition.matchreport",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who resolved a dispute",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_challenges_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge",
                "verbose_name_plural": "Challenges",
                "db_table": "competition_challenge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BountyClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("VERIFIED", "Verified — Criteria met"),
                            ("REJECTED", "Rejected — Criteria not met"),
                            ("PAID", "Paid — Reward distributed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("evidence_url", models.URLField(blank=True, max_length=500)),
                ("evidence_notes", models.TextField(blank=True)),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "bounty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="competition.bounty",
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_bounty_claims_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claiming_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_bounty_claims",
                        to="organizations.team",
                    ),
                ),
                (
                    "match_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_bounty_claims",
                        to="competition.matchreport",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_bounty_claims_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        help_text="Challenge that triggered this bounty claim",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_bounty_claims",
                        to="competition.challenge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bounty Claim",
                "verbose_name_plural": "Bounty Claims",
                "db_table": "competition_bounty_claim",
                "ordering": ["-claimed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(
                fields=["status", "-created_at"], name="competition_status_5f1772_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(
                fields=["issuer_team", "status"], name="competition_issuer__8fa698_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(fields=["game", "status"], name="competition_game_id_cc5613_idx"),
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(
                fields=["bounty_type", "status"], name="competition_bounty__353e1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(fields=["-expires_at"], name="competition_expires_b78b0a_idx"),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["status", "-created_at"], name="competition_status_710284_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["challenger_team", "status"], name="competition_challen_328f21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["challenged_team", "status"], name="competition_challen_f14c81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["game", "status", "-created_at"], name="competition_game_id_57fe89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["challenge_type", "status"], name="competition_challen_95a937_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(fields=["-expires_at"], name="competition_expires_1eba98_idx"),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("challenger_team", models.F("challenged_team")), _negated=True),
                name="challenge_teams_different",
            ),
        ),
        migrations.AddIndex(
            model_name="bountyclaim",
            index=models.Index(fields=["bounty", "status"], name="competition_bounty__b72c75_idx"),
        ),
        migrations.AddIndex(
            model_name="bountyclaim",
            index=models.Index(
                fields=["claiming_team", "-claimed_at"], name="competition_claimin_27cf83_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bountyclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "VERIFIED"])),
                fields=("bounty", "claiming_team"),
                name="unique_bounty_claim_per_team",
            ),
        ),
    ]
