# Generated by Django 5.2.8 on 2026-03-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0004_bounty_challenge_bountyclaim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamerankingconfig",
            name="tier_thresholds",
            field=models.JSONField(
                default=dict,
                help_text="Score thresholds for each tier. Example: {THE_CROWN: 30000, LEGEND: 8000, MASTER: 2000, ELITE: 500, CHALLENGER: 100, ROOKIE: 0}",
            ),
        ),
    ]
