# Generated by Django 5.2.8 on 2026-04-11 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0005_alter_gamerankingconfig_tier_thresholds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="bountyclaim",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="bountyclaim",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bountyclaim",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
    ]
