# Generated by Django 5.2.8 on 2026-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0006_bounty_deleted_at_bounty_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="escrow_locked",
            field=models.BooleanField(
                default=False, help_text="True once the issuer's DC have been locked into escrow."
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="reward_amount_dc",
            field=models.PositiveIntegerField(
                default=0,
                help_text="DeltaCoins locked in escrow by the bounty issuer. 0 = non-DC reward.",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="escrow_locked",
            field=models.BooleanField(
                default=False,
                help_text="True once ALL participants have had their escrow funds locked.",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="wager_amount_dc",
            field=models.PositiveIntegerField(
                default=0, help_text="DeltaCoins each team must lock into escrow. 0 = no wager."
            ),
        ),
    ]
