# Generated by Django 5.2.8 on 2026-05-06 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0007_phase4_escrow_reasons_and_model_fields"),
        ("economy", "0012_phase_d_fortress_pin_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="challenged_lock_txn",
            field=models.ForeignKey(
                blank=True,
                help_text="Challenged-side escrow lock transaction.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="economy.deltacrowntransaction",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="challenger_lock_txn",
            field=models.ForeignKey(
                blank=True,
                help_text="Challenger-side escrow lock transaction.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="economy.deltacrowntransaction",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="closure_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Free-form admin/system note explaining the closure (e.g. dispute outcome).",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="closure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not closed"),
                    ("NORMAL", "Match completed normally"),
                    ("OPPONENT_NO_SHOW", "Opponent failed to join in time"),
                    ("CHALLENGER_NO_SHOW", "Challenger failed to join in time"),
                    ("BOTH_NO_SHOW", "Neither side joined"),
                    ("CANCELLED_BY_ISSUER", "Cancelled by issuer"),
                    ("DECLINED_BY_OPPONENT", "Declined by opponent"),
                    ("EXPIRED", "Expired before acceptance"),
                    ("ADMIN_VOID", "Voided by admin"),
                    ("DISPUTE_RESOLVED", "Resolved via admin dispute"),
                ],
                db_index=True,
                default="",
                help_text="Why the lobby closed. UI must surface this rather than a bare countdown.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="entry_fee_dc",
            field=models.PositiveIntegerField(
                default=0,
                help_text="DeltaCoins each participant locks into escrow. 0 = no entry fee.",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="payout_txn",
            field=models.ForeignKey(
                blank=True,
                help_text="Winner payout transaction (set on settle).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="economy.deltacrowntransaction",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="wager_amount_dc",
            field=models.PositiveIntegerField(
                default=0,
                help_text="[Legacy] Replaced by entry_fee_dc for new Crown Clash matches.",
            ),
        ),
    ]
