# Generated by Django 5.2.8 on 2026-05-06 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0008_crown_clash_escrow_fields"),
        ("economy", "0012_phase_d_fortress_pin_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="challenger_entry_fee_dc",
            field=models.PositiveIntegerField(
                default=0,
                help_text="DC each challenger team locks per claim attempt (Hitlist only).",
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="closure_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Free-form admin/system note for the closure (e.g. dispute outcome).",
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="closure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not closed"),
                    ("CLAIMED", "Claimed — reward paid out"),
                    ("CANCELLED_BY_ISSUER", "Cancelled by issuer"),
                    ("EXPIRED", "Expired before claim"),
                    ("ADMIN_VOID", "Voided by admin"),
                ],
                db_index=True,
                default="",
                help_text="Why the bounty closed. UI must surface this rather than a bare countdown.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="is_hitlist",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if this bounty is published on The Hitlist (paid challenges).",
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="issuer_lock_txn",
            field=models.ForeignKey(
                blank=True,
                help_text="Issuer's escrow lock transaction (set when reward_amount_dc > 0).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="economy.deltacrowntransaction",
            ),
        ),
        migrations.AddField(
            model_name="bountyclaim",
            name="closure_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Free-form admin/system note for the claim closure.",
            ),
        ),
        migrations.AddField(
            model_name="bountyclaim",
            name="closure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not closed"),
                    ("VERIFIED_PAID", "Challenger won — reward paid"),
                    ("REJECTED", "Challenger lost — entry fee forfeited"),
                    ("VOIDED", "Voided by admin"),
                    ("EXPIRED", "Expired before verification"),
                ],
                db_index=True,
                default="",
                help_text="Why the claim closed.  UI surfaces this on the claim card.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="bountyclaim",
            name="entry_fee_lock_txn",
            field=models.ForeignKey(
                blank=True,
                help_text="Challenger's entry-fee lock transaction (Hitlist only).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="economy.deltacrowntransaction",
            ),
        ),
        migrations.AddField(
            model_name="bountyclaim",
            name="outcome_txn",
            field=models.ForeignKey(
                blank=True,
                help_text="Settlement transaction — payout or refund — recorded on resolution.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="economy.deltacrowntransaction",
            ),
        ),
    ]
