# Generated by Django 5.2.8 on 2026-05-07 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0009_hitlist_escrow_fields"),
        ("tournaments", "0059_prize_claim_playbook_compliance_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="funded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User whose personal wallet funded the bounty reward.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bountyclaim",
            name="funded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User whose personal wallet funded the challenger entry fee.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bountyclaim",
            name="match",
            field=models.ForeignKey(
                blank=True,
                help_text="Match Room spawned when this Hitlist claim was submitted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tournaments.match",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="funded_by_challenged",
            field=models.ForeignKey(
                blank=True,
                help_text="User whose personal wallet funded the challenged team's stake.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="funded_by_challenger",
            field=models.ForeignKey(
                blank=True,
                help_text="User whose personal wallet funded the challenger team's stake.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="match",
            field=models.ForeignKey(
                blank=True,
                help_text="Match Room spawned when this Crown Clash is accepted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tournaments.match",
            ),
        ),
    ]
