# Generated by Django 5.2.8 on 2026-05-15 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0010_phase10_rbac_audit_match"),
        ("organizations", "0044_alter_organization_badge_alter_organization_banner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeResultSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CHALLENGER_WIN", "Challenger won"),
                            ("CHALLENGED_WIN", "Challenged team won"),
                            ("DRAW", "Draw"),
                            ("FORFEIT_CHALLENGER", "Forfeit by challenger"),
                            ("FORFEIT_CHALLENGED", "Forfeit by challenged"),
                            ("NO_SHOW", "No-show — Neither team appeared"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score_details", models.JSONField(blank=True, default=dict)),
                ("evidence_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_submissions",
                        to="competition.challenge",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenge_result_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_result_submissions",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge Result Submission",
                "verbose_name_plural": "Challenge Result Submissions",
                "db_table": "competition_challenge_result_submission",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["challenge", "team"], name="competition_challen_cb52b2_idx"
                    ),
                    models.Index(
                        fields=["team", "-created_at"], name="competition_team_id_713d86_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("challenge", "team"),
                        name="unique_result_submission_per_challenge_team",
                    )
                ],
            },
        ),
    ]
