# Generated by Django 5.2.8 on 2026-05-15 10:38

from django.db import migrations, models
from django.db.models import Count


def move_pending_completed_rows_forward(apps, schema_editor):
    Challenge = apps.get_model("competition", "Challenge")
    (
        Challenge.objects
        .filter(status="COMPLETED", settled_at__isnull=True)
        .annotate(submission_count=Count("result_submissions"))
        .filter(submission_count=1)
        .update(status="PENDING_CONFIRMATION")
    )


def move_pending_completed_rows_backward(apps, schema_editor):
    Challenge = apps.get_model("competition", "Challenge")
    Challenge.objects.filter(status="PENDING_CONFIRMATION").update(status="COMPLETED")


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0011_challengeresultsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open — Awaiting opponent"),
                    ("ACCEPTED", "Accepted — Awaiting schedule"),
                    ("SCHEDULED", "Scheduled — Match time set"),
                    ("IN_PROGRESS", "In Progress"),
                    ("PENDING_CONFIRMATION", "Pending confirmation — Result submitted"),
                    ("COMPLETED", "Completed — Result confirmed"),
                    ("SETTLED", "Settled — Result verified & rewards distributed"),
                    ("DECLINED", "Declined by opponent"),
                    ("EXPIRED", "Expired — Deadline passed"),
                    ("CANCELLED", "Cancelled by issuer"),
                    ("DISPUTED", "Disputed — Requires admin review"),
                    ("ADMIN_RESOLVED", "Admin Resolved"),
                ],
                db_index=True,
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            move_pending_completed_rows_forward,
            move_pending_completed_rows_backward,
        ),
    ]
