# Generated by Django 5.2.8 on 2026-05-17 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0012_alter_challenge_status"),
        ("economy", "0012_phase_d_fortress_pin_hash"),
        ("tournaments", "0064_alter_matchresultsubmission_archived_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bounty",
            name="challenger_entry_fee_dc",
            field=models.PositiveIntegerField(
                default=0, help_text="DC each challenger team locks per Bounty claim attempt."
            ),
        ),
        migrations.AlterField(
            model_name="bounty",
            name="is_hitlist",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if this bounty is published on the Bounty board.",
            ),
        ),
        migrations.AlterField(
            model_name="bountyclaim",
            name="entry_fee_lock_txn",
            field=models.ForeignKey(
                blank=True,
                help_text="Challenger's entry-fee lock transaction (Bounty board only).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="economy.deltacrowntransaction",
            ),
        ),
        migrations.AlterField(
            model_name="bountyclaim",
            name="match",
            field=models.ForeignKey(
                blank=True,
                help_text="Match Room spawned when this Bounty claim was submitted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tournaments.match",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("DIRECT", "Direct Challenge — Named opponent"),
                    ("OPEN", "Open Challenge — Any team can accept"),
                    ("RANKED", "Ranked Challenge — Affects rankings"),
                    ("WAGER", "Reward Match — Entry fee locked"),
                    ("SCRIM", "Scrim / Practice — No ranking impact"),
                ],
                default="DIRECT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="funded_by_challenged",
            field=models.ForeignKey(
                blank=True,
                help_text="User whose personal wallet funded the challenged team's locked entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="funded_by_challenger",
            field=models.ForeignKey(
                blank=True,
                help_text="User whose personal wallet funded the challenger team's locked entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="match",
            field=models.ForeignKey(
                blank=True,
                help_text="Match Room spawned when this Showdown is accepted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tournaments.match",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="wager_amount_dc",
            field=models.PositiveIntegerField(
                default=0, help_text="[Legacy] Replaced by entry_fee_dc for new Showdown matches."
            ),
        ),
    ]
