"""
Factory Boy fixtures for apps.organizations models.

These factories generate test data for the Team & Organization vNext system.
All factories use realistic defaults to minimize boilerplate in tests.

Usage Example:
    # Create an organization with default values
    org = OrganizationFactory()

    # Create an organization with custom values
    org = OrganizationFactory(name="Evil Geniuses", is_verified=True)

    # Create a team owned by an organization
    team = TeamFactory(organization=org, owner=None)

    # Create an independent team (owned by a user)
    team = TeamFactory(owner=user, organization=None)

    # Create a team with memberships in one call
    team = TeamFactory.create_with_members(member_count=5)

Performance Note:
- Factories create minimal database objects by default
- Use SubFactory sparingly (creates related objects, increases test time)
- Use build() instead of create() when database persistence not needed
"""
import factory
from factory.django import DjangoModelFactory
from django.contrib.auth import get_user_model

from apps.organizations.models import (
    Organization,
    OrganizationMembership,
    Team,
    TeamMembership,
    TeamRanking,
    OrganizationRanking,
    TeamMigrationMap,
    TeamActivityLog,
)
from apps.teams.models import Team as LegacyTeam
from apps.organizations.choices import (
    TeamStatus,
    MembershipStatus,
    MembershipRole,
    RosterSlot,
    RankingTier,
    ActivityActionType,
)

User = get_user_model()


class UserFactory(DjangoModelFactory):
    """Factory for User model (Django auth.User)."""
    
    class Meta:
        model = User
        django_get_or_create = ("username",)  # Avoid unique constraint violations
    
    username = factory.Sequence(lambda n: f"testuser{n}")
    email = factory.LazyAttribute(lambda obj: f"{obj.username}@example.com")
    first_name = factory.Faker("first_name")
    last_name = factory.Faker("last_name")
    is_active = True
    is_staff = False


class OrganizationFactory(DjangoModelFactory):
    """Factory for Organization model."""
    
    class Meta:
        model = Organization
    
    name = factory.Sequence(lambda n: f"Test Organization {n}")
    # slug auto-generated by model.save()
    ceo = factory.SubFactory(UserFactory)
    description = factory.Faker("text", max_nb_chars=200)
    is_verified = False
    enforce_brand = False
    revenue_split_config = factory.LazyFunction(lambda: {
        "org_cut": 20,
        "player_cut": 80,
    })
    
    @factory.post_generation
    def with_members(self, create, extracted, **kwargs):
        """
        Create organization memberships after organization creation.
        
        Usage:
            org = OrganizationFactory.create(with_members=3)  # Creates 3 members
        """
        if not create:
            return
        
        if extracted:
            for _ in range(extracted):
                OrganizationMembershipFactory.create(organization=self)


class OrganizationMembershipFactory(DjangoModelFactory):
    """Factory for OrganizationMembership model."""
    
    class Meta:
        model = OrganizationMembership
    
    organization = factory.SubFactory(OrganizationFactory)
    user = factory.SubFactory(UserFactory)
    role = MembershipRole.MANAGER  # Default to MANAGER (not CEO - that's org.ceo)
    permissions = factory.LazyFunction(lambda: {
        "can_create_teams": True,
        "can_view_financials": False,
    })


class TeamFactory(DjangoModelFactory):
    """
    Factory for Team model.
    
    IMPORTANT: Team must have organization XOR created_by (not both, not neither).
    By default, creates an organization-owned team.
    
    Usage:
        # Organization-owned team (default)
        team = TeamFactory()
        
        # Independent team (user-owned)
        user = UserFactory()
        team = TeamFactory(organization=None, created_by=user)
        
        # With memberships
        team = TeamFactory.create_with_members(member_count=5)
    """
    
    class Meta:
        model = Team
    
    name = factory.Sequence(lambda n: f"Test Team {n}")
    # slug auto-generated by model.save()
    organization = factory.SubFactory(OrganizationFactory)
    created_by = None  # Default: organization-owned team (created_by=None)
    game_id = 1  # Default game (e.g., Valorant)
    region = "NA"
    status = TeamStatus.ACTIVE
    description = factory.Faker("text", max_nb_chars=200)
    is_temporary = False
    
    @classmethod
    def create_independent(cls, **kwargs):
        """
        Helper to create an independent team (user-owned, no organization).
        
        Usage:
            team = TeamFactory.create_independent(created_by=user)
            team = TeamFactory.create_independent(owner=user)  # Legacy alias
        """
        created_by = kwargs.pop("created_by", None) or kwargs.pop("owner", None) or UserFactory.create()
        return cls.create(organization=None, created_by=created_by, **kwargs)
    
    @classmethod
    def create_with_members(cls, member_count=5, **kwargs):
        """
        Create a team with specified number of members.
        
        Usage:
            team = TeamFactory.create_with_members(member_count=5)
        """
        team = cls.create(**kwargs)
        for i in range(member_count):
            role = MembershipRole.OWNER if i == 0 else MembershipRole.PLAYER
            TeamMembershipFactory.create(
                team=team,
                role=role,
                roster_slot=RosterSlot.STARTER if i < 5 else RosterSlot.SUBSTITUTE,
            )
        return team


class TeamMembershipFactory(DjangoModelFactory):
    """Factory for TeamMembership model."""
    
    class Meta:
        model = TeamMembership
    
    team = factory.SubFactory(TeamFactory)
    user = factory.SubFactory(UserFactory)
    status = MembershipStatus.ACTIVE
    role = MembershipRole.PLAYER
    roster_slot = RosterSlot.STARTER
    is_tournament_captain = False
    
    @classmethod
    def create_captain(cls, **kwargs):
        """
        Helper to create a tournament captain.
        
        Usage:
            captain = TeamMembershipFactory.create_captain(team=team, user=user)
        """
        return cls.create(
            is_tournament_captain=True,
            role=MembershipRole.OWNER,
            **kwargs
        )


class LegacyTeamFactory(DjangoModelFactory):
    """Factory for legacy teams.Team – used by TeamRanking FK."""

    class Meta:
        model = LegacyTeam

    name = factory.Sequence(lambda n: f"Legacy Team {n}")
    tag = factory.Sequence(lambda n: f"LT{n:04d}")
    region = "NA"


class TeamRankingFactory(DjangoModelFactory):
    """Factory for TeamRanking model."""
    
    class Meta:
        model = TeamRanking
    
    team = factory.SubFactory(LegacyTeamFactory)
    current_cp = 1000
    season_cp = 1000
    all_time_cp = 1000
    tier = RankingTier.SILVER
    global_rank = None
    is_hot_streak = False
    streak_count = 0


class OrganizationRankingFactory(DjangoModelFactory):
    """Factory for OrganizationRanking model."""
    
    class Meta:
        model = OrganizationRanking
    
    organization = factory.SubFactory(OrganizationFactory)
    empire_score = 5000
    global_rank = None
    total_trophies = 0


class TeamMigrationMapFactory(DjangoModelFactory):
    """Factory for TeamMigrationMap model."""
    
    class Meta:
        model = TeamMigrationMap
    
    legacy_team_id = factory.Sequence(lambda n: 10000 + n)  # Start from 10000 to avoid conflicts
    vnext_team_id = factory.Sequence(lambda n: 1 + n)
    legacy_slug = factory.Sequence(lambda n: f"legacy-team-{n}")
    verified = False
    migrated_by = None  # Nullable


class TeamActivityLogFactory(DjangoModelFactory):
    """Factory for TeamActivityLog model."""
    
    class Meta:
        model = TeamActivityLog
    
    team = factory.SubFactory(TeamFactory)
    action_type = ActivityActionType.UPDATE
    actor_id = factory.SelfAttribute("team.organization.ceo.id")
    actor_username = factory.SelfAttribute("team.organization.ceo.username")
    description = factory.Faker("sentence")
    metadata = factory.LazyFunction(lambda: {"source": "test"})
