# Generated by Django 5.2.8 on 2026-01-23 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunityPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends Only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "game",
                    models.CharField(
                        blank=True, help_text="Game this post is related to", max_length=100
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("shares_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityPostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityPostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="CommunityPostMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video"), ("gif", "GIF")],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="community/posts/%Y/%m/%d/")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="community/thumbnails/%Y/%m/%d/"),
                ),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityPostShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Optional comment when sharing"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HelpContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier (e.g., 'results_inbox_intro')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        db_index=True,
                        help_text="Context/page where this help applies (e.g., 'organizer_results_inbox')",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(help_text="Markdown or plain text content")),
                (
                    "html_body",
                    models.TextField(
                        blank=True, help_text="Pre-rendered HTML (optional, for performance)"
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("organizer", "Organizer"),
                            ("referee", "Referee"),
                            ("player", "Player"),
                            ("global", "Global/All Users"),
                        ],
                        default="global",
                        help_text="Who should see this help content",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this content is currently shown"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order when multiple help items exist for same scope",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Help Content",
                "verbose_name_plural": "Help Content Items",
                "ordering": ["scope", "display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="HelpOverlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "page_id",
                    models.CharField(
                        db_index=True,
                        help_text="Page identifier (e.g., 'results_inbox', 'scheduling')",
                        max_length=100,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("top-right", "Top Right"),
                            ("right", "Right"),
                            ("bottom-right", "Bottom Right"),
                            ("bottom", "Bottom"),
                            ("bottom-left", "Bottom Left"),
                            ("left", "Left"),
                            ("top-left", "Top Left"),
                            ("center", "Center"),
                        ],
                        default="top-right",
                        help_text="Where the overlay should appear on screen",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Advanced configuration (trigger, animation, etc.)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Help Overlay",
                "verbose_name_plural": "Help Overlays",
                "ordering": ["page_id", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hero_badge_text",
                    models.CharField(
                        default="Bangladesh's #1 Esports Platform",
                        help_text="Badge text above hero title",
                        max_length=100,
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="From the Delta to the Crown",
                        help_text="Main hero headline",
                        max_length=200,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Where Champions Rise",
                        help_text="Hero subtitle/tagline",
                        max_length=200,
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        default="Building a world where geography does not define destiny—where a gamer in Bangladesh has the same trusted path to global glory as a pro on the main stage.",
                        help_text="Hero description paragraph",
                    ),
                ),
                ("primary_cta_text", models.CharField(default="Join Tournament", max_length=50)),
                ("primary_cta_url", models.CharField(default="/tournaments/", max_length=200)),
                ("primary_cta_icon", models.CharField(blank=True, default="🏆", max_length=10)),
                ("secondary_cta_text", models.CharField(default="Explore Teams", max_length=50)),
                ("secondary_cta_url", models.CharField(default="/teams/", max_length=200)),
                ("secondary_cta_icon", models.CharField(blank=True, default="👥", max_length=10)),
                (
                    "hero_highlights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of stat highlights: [{"label": "Active Players", "value": "12,500+", "icon": "👥", "source": "DB_COUNT"}]. source can be "DB_COUNT" or "STATIC"',
                    ),
                ),
                ("problem_section_enabled", models.BooleanField(default=True)),
                (
                    "problem_title",
                    models.CharField(
                        default="The Esports Gap",
                        help_text="Problem section headline",
                        max_length=200,
                    ),
                ),
                (
                    "problem_subtitle",
                    models.TextField(
                        default="Most platforms solve one problem. DeltaCrown solves the entire esports lifecycle.",
                        help_text="Problem section description",
                    ),
                ),
                (
                    "comparison_table",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Comparison items: [{"traditional": "One-time tournaments", "deltacrown": "Persistent competitive history"}]',
                    ),
                ),
                ("pillars_section_enabled", models.BooleanField(default=True)),
                (
                    "ecosystem_pillars_title",
                    models.CharField(
                        default="Complete Esports Ecosystem",
                        help_text="Ecosystem section headline",
                        max_length=200,
                    ),
                ),
                (
                    "ecosystem_pillars_description",
                    models.TextField(
                        default="Eight interconnected domains, one unified platform",
                        help_text="Ecosystem section description",
                    ),
                ),
                (
                    "ecosystem_pillars",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of pillars: [{"icon": "🏆", "title": "Tournaments", "description": "...", "link": "/tournaments/"}]',
                    ),
                ),
                ("games_section_enabled", models.BooleanField(default=True)),
                (
                    "games_section_title",
                    models.CharField(
                        default="11 Games, One Platform",
                        help_text="Games section headline",
                        max_length=200,
                    ),
                ),
                (
                    "games_section_description",
                    models.TextField(
                        default="From mobile to PC, tactical shooters to sports—game-agnostic by design",
                        help_text="Games section description",
                    ),
                ),
                (
                    "games_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of games: [{"slug": "cod-mobile", "name": "Call of Duty®: Mobile", "tagline": "Tactical FPS", "platforms": ["Mobile"], "color": "#FF6B00"}]. Phase 1: JSON. Phase 2: Migrate to Game model FK.',
                    ),
                ),
                ("tournaments_section_enabled", models.BooleanField(default=True)),
                (
                    "tournaments_section_title",
                    models.CharField(
                        default="Active Tournaments",
                        help_text="Tournaments section headline",
                        max_length=200,
                    ),
                ),
                (
                    "tournaments_section_description",
                    models.TextField(
                        default="Join verified competitions with real prizes",
                        help_text="Tournaments section description",
                    ),
                ),
                ("teams_section_enabled", models.BooleanField(default=True)),
                (
                    "teams_section_title",
                    models.CharField(
                        default="Top Teams", help_text="Teams section headline", max_length=200
                    ),
                ),
                (
                    "teams_section_description",
                    models.TextField(
                        default="Professional organizations competing for glory",
                        help_text="Teams section description",
                    ),
                ),
                ("payments_section_enabled", models.BooleanField(default=True)),
                (
                    "payments_section_title",
                    models.CharField(
                        default="Local Payment Partners",
                        help_text="Payments section headline",
                        max_length=200,
                    ),
                ),
                (
                    "payments_section_description",
                    models.TextField(
                        default="Bangladesh-first infrastructure—we support the payment methods you already trust",
                        help_text="Payments section description",
                    ),
                ),
                (
                    "payment_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of payment methods: [{"name": "bKash", "icon": "💳", "color": "#E2136E", "description": "Mobile money leader"}]',
                    ),
                ),
                (
                    "payments_trust_message",
                    models.TextField(
                        default="No credit cards required. No barriers to entry. Built for South Asian markets.",
                        help_text="Trust message for payment methods",
                    ),
                ),
                ("deltacoin_section_enabled", models.BooleanField(default=True)),
                (
                    "deltacoin_section_title",
                    models.CharField(
                        default="DeltaCoin Economy",
                        help_text="DeltaCoin section headline",
                        max_length=200,
                    ),
                ),
                (
                    "deltacoin_section_description",
                    models.TextField(
                        default="Earn by competing. Spend on upgrades. Build your legacy.",
                        help_text="DeltaCoin section description",
                    ),
                ),
                (
                    "deltacoin_earn_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of earn methods: ["Participating in tournaments", "Winning matches"]',
                    ),
                ),
                (
                    "deltacoin_spend_options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of spend options: ["Store purchases", "Premium subscriptions"]',
                    ),
                ),
                ("community_section_enabled", models.BooleanField(default=True)),
                (
                    "community_section_title",
                    models.CharField(
                        default="Join the Community",
                        help_text="Community section headline",
                        max_length=200,
                    ),
                ),
                (
                    "community_section_description",
                    models.TextField(
                        default="Strategy guides, match highlights, esports news—all in one home",
                        help_text="Community section description",
                    ),
                ),
                ("roadmap_section_enabled", models.BooleanField(default=True)),
                (
                    "roadmap_section_title",
                    models.CharField(
                        default="The Vision Ahead",
                        help_text="Roadmap section headline",
                        max_length=200,
                    ),
                ),
                (
                    "roadmap_section_description",
                    models.TextField(
                        default="Evolving toward global scale while staying rooted in emerging markets",
                        help_text="Roadmap section description",
                    ),
                ),
                (
                    "roadmap_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of roadmap items: [{"status": "COMPLETED", "title": "...", "description": "..."}]. status: COMPLETED, IN_PROGRESS, PLANNED',
                    ),
                ),
                ("final_cta_section_enabled", models.BooleanField(default=True)),
                (
                    "final_cta_title",
                    models.CharField(
                        default="Ready to Compete?", help_text="Final CTA headline", max_length=200
                    ),
                ),
                (
                    "final_cta_description",
                    models.TextField(
                        default="Join thousands of gamers building their esports careers on DeltaCrown",
                        help_text="Final CTA description",
                    ),
                ),
                (
                    "final_cta_primary_text",
                    models.CharField(default="Create Account", max_length=50),
                ),
                (
                    "final_cta_primary_url",
                    models.CharField(default="/account/register/", max_length=200),
                ),
                (
                    "final_cta_secondary_text",
                    models.CharField(default="Explore Platform", max_length=50),
                ),
                ("final_cta_secondary_url", models.CharField(default="/about/", max_length=200)),
                (
                    "platform_tagline",
                    models.CharField(
                        default="From the Delta to the Crown — Where Champions Rise.",
                        help_text="Platform tagline for footer/about sections",
                        max_length=200,
                    ),
                ),
                (
                    "platform_founded_year",
                    models.PositiveIntegerField(
                        default=2025, help_text="Year DeltaCrown was founded"
                    ),
                ),
                (
                    "platform_founder",
                    models.CharField(
                        default="Redwanul Rashik", help_text="Founder name", max_length=100
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Homepage Content",
                "verbose_name_plural": "Homepage Content",
                "db_table": "siteui_homepage_content",
            },
        ),
        migrations.CreateModel(
            name="OrganizerOnboardingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "step_key",
                    models.CharField(
                        help_text="Onboarding step identifier (e.g., 'results_inbox_intro')",
                        max_length=100,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the user completed this step", null=True
                    ),
                ),
                (
                    "dismissed",
                    models.BooleanField(
                        default=False, help_text="Whether user dismissed/skipped this step"
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the user dismissed this step", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organizer Onboarding State",
                "verbose_name_plural": "Organizer Onboarding States",
            },
        ),
    ]
