# Generated by Django 5.2.8 on 2026-01-23 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("siteui", "0001_initial"),
        ("tournaments", "0001_initial"),
        ("user_profile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_posts",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="communitypostcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_comments",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="communitypostcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="siteui.communitypostcomment",
            ),
        ),
        migrations.AddField(
            model_name="communitypostcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="siteui.communitypost",
            ),
        ),
        migrations.AddField(
            model_name="communitypostlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="siteui.communitypost",
            ),
        ),
        migrations.AddField(
            model_name="communitypostlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_likes",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="communitypostmedia",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="siteui.communitypost",
            ),
        ),
        migrations.AddField(
            model_name="communitypostshare",
            name="original_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="siteui.communitypost",
            ),
        ),
        migrations.AddField(
            model_name="communitypostshare",
            name="shared_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_shares",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="helpcontent",
            index=models.Index(fields=["scope", "is_active"], name="siteui_help_scope_e63c6d_idx"),
        ),
        migrations.AddIndex(
            model_name="helpcontent",
            index=models.Index(
                fields=["audience", "is_active"], name="siteui_help_audienc_cf67a5_idx"
            ),
        ),
        migrations.AddField(
            model_name="helpoverlay",
            name="help_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overlays",
                to="siteui.helpcontent",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last user who updated homepage content",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homepage_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizeronboardingstate",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, onboarding is tournament-specific",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_states",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="organizeronboardingstate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizer_onboarding_states",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(fields=["-created_at"], name="siteui_comm_created_99314b_idx"),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["visibility", "-created_at"], name="siteui_comm_visibil_46a111_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(fields=["game", "-created_at"], name="siteui_comm_game_de1795_idx"),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["is_featured", "-created_at"], name="siteui_comm_is_feat_b67045_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitypostcomment",
            index=models.Index(
                fields=["post", "created_at"], name="siteui_comm_post_id_98f13c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitypostlike",
            index=models.Index(fields=["post"], name="siteui_comm_post_id_07d9f5_idx"),
        ),
        migrations.AddIndex(
            model_name="communitypostlike",
            index=models.Index(fields=["user"], name="siteui_comm_user_id_98ae1a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="communitypostlike",
            unique_together={("post", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="communitypostshare",
            unique_together={("original_post", "shared_by")},
        ),
        migrations.AddIndex(
            model_name="helpoverlay",
            index=models.Index(
                fields=["page_id", "is_active"], name="siteui_help_page_id_682e8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizeronboardingstate",
            index=models.Index(
                fields=["user", "tournament"], name="siteui_orga_user_id_9675a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizeronboardingstate",
            index=models.Index(fields=["user", "step_key"], name="siteui_orga_user_id_f38f79_idx"),
        ),
        migrations.AddConstraint(
            model_name="organizeronboardingstate",
            constraint=models.UniqueConstraint(
                fields=("user", "tournament", "step_key"),
                name="unique_onboarding_state_per_user_tournament_step",
            ),
        ),
    ]
