# Generated by Django 5.2.8 on 2025-12-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siteui", "0002_help_and_onboarding_epic76"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="helpcontent",
            new_name="siteui_help_scope_e63c6d_idx",
            old_name="siteui_help_scope_active_idx",
        ),
        migrations.RenameIndex(
            model_name="helpcontent",
            new_name="siteui_help_audienc_cf67a5_idx",
            old_name="siteui_help_audience_active_idx",
        ),
        migrations.RenameIndex(
            model_name="helpoverlay",
            new_name="siteui_help_page_id_682e8f_idx",
            old_name="siteui_overlay_page_active_idx",
        ),
        migrations.RenameIndex(
            model_name="organizeronboardingstate",
            new_name="siteui_orga_user_id_9675a3_idx",
            old_name="siteui_onboard_user_tourn_idx",
        ),
        migrations.RenameIndex(
            model_name="organizeronboardingstate",
            new_name="siteui_orga_user_id_f38f79_idx",
            old_name="siteui_onboard_user_step_idx",
        ),
    ]
