# Generated by Django 5.2.8 on 2026-02-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0035_add_team_to_communitypost"),
        ("siteui", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this post is published on behalf of the team",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="community_posts",
                to="organizations.team",
            ),
        ),
    ]
