# Generated by Django 5.2.8 on 2026-04-11 08:28

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteui", "0003_add_team_to_communitypost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypostmedia",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                upload_to="community/thumbnails/%Y/%m/%d/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
    ]
