# Generated by Django 5.2.8 on 2025-12-14 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "siteui",
            "0003_rename_siteui_help_scope_active_idx_siteui_help_scope_e63c6d_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hero_badge_text",
                    models.CharField(
                        default="Bangladesh's #1 Esports Platform",
                        help_text="Badge text above hero title",
                        max_length=100,
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="From the Delta to the Crown",
                        help_text="Main hero headline",
                        max_length=200,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Where Champions Rise",
                        help_text="Hero subtitle/tagline",
                        max_length=200,
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        default="Building a world where geography does not define destiny—where a gamer in Bangladesh has the same trusted path to global glory as a pro on the main stage.",
                        help_text="Hero description paragraph",
                    ),
                ),
                ("primary_cta_text", models.CharField(default="Join Tournament", max_length=50)),
                ("primary_cta_url", models.CharField(default="/tournaments/", max_length=200)),
                ("primary_cta_icon", models.CharField(blank=True, default="🏆", max_length=10)),
                ("secondary_cta_text", models.CharField(default="Explore Teams", max_length=50)),
                ("secondary_cta_url", models.CharField(default="/teams/", max_length=200)),
                ("secondary_cta_icon", models.CharField(blank=True, default="👥", max_length=10)),
                (
                    "hero_highlights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of stat highlights: [{"label": "Active Players", "value": "12,500+", "icon": "👥", "source": "DB_COUNT"}]. source can be "DB_COUNT" or "STATIC"',
                    ),
                ),
                ("problem_section_enabled", models.BooleanField(default=True)),
                (
                    "problem_title",
                    models.CharField(
                        default="The Esports Gap",
                        help_text="Problem section headline",
                        max_length=200,
                    ),
                ),
                (
                    "problem_subtitle",
                    models.TextField(
                        default="Most platforms solve one problem. DeltaCrown solves the entire esports lifecycle.",
                        help_text="Problem section description",
                    ),
                ),
                (
                    "comparison_table",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Comparison items: [{"traditional": "One-time tournaments", "deltacrown": "Persistent competitive history"}]',
                    ),
                ),
                ("pillars_section_enabled", models.BooleanField(default=True)),
                (
                    "ecosystem_pillars_title",
                    models.CharField(
                        default="Complete Esports Ecosystem",
                        help_text="Ecosystem section headline",
                        max_length=200,
                    ),
                ),
                (
                    "ecosystem_pillars_description",
                    models.TextField(
                        default="Eight interconnected domains, one unified platform",
                        help_text="Ecosystem section description",
                    ),
                ),
                (
                    "ecosystem_pillars",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of pillars: [{"icon": "🏆", "title": "Tournaments", "description": "...", "link": "/tournaments/"}]',
                    ),
                ),
                ("games_section_enabled", models.BooleanField(default=True)),
                (
                    "games_section_title",
                    models.CharField(
                        default="11 Games, One Platform",
                        help_text="Games section headline",
                        max_length=200,
                    ),
                ),
                (
                    "games_section_description",
                    models.TextField(
                        default="From mobile to PC, tactical shooters to sports—game-agnostic by design",
                        help_text="Games section description",
                    ),
                ),
                (
                    "games_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of games: [{"slug": "cod-mobile", "name": "Call of Duty®: Mobile", "tagline": "Tactical FPS", "platforms": ["Mobile"], "color": "#FF6B00"}]. Phase 1: JSON. Phase 2: Migrate to Game model FK.',
                    ),
                ),
                ("tournaments_section_enabled", models.BooleanField(default=True)),
                (
                    "tournaments_section_title",
                    models.CharField(
                        default="Active Tournaments",
                        help_text="Tournaments section headline",
                        max_length=200,
                    ),
                ),
                (
                    "tournaments_section_description",
                    models.TextField(
                        default="Join verified competitions with real prizes",
                        help_text="Tournaments section description",
                    ),
                ),
                ("teams_section_enabled", models.BooleanField(default=True)),
                (
                    "teams_section_title",
                    models.CharField(
                        default="Top Teams", help_text="Teams section headline", max_length=200
                    ),
                ),
                (
                    "teams_section_description",
                    models.TextField(
                        default="Professional organizations competing for glory",
                        help_text="Teams section description",
                    ),
                ),
                ("payments_section_enabled", models.BooleanField(default=True)),
                (
                    "payments_section_title",
                    models.CharField(
                        default="Local Payment Partners",
                        help_text="Payments section headline",
                        max_length=200,
                    ),
                ),
                (
                    "payments_section_description",
                    models.TextField(
                        default="Bangladesh-first infrastructure—we support the payment methods you already trust",
                        help_text="Payments section description",
                    ),
                ),
                (
                    "payment_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of payment methods: [{"name": "bKash", "icon": "💳", "color": "#E2136E", "description": "Mobile money leader"}]',
                    ),
                ),
                (
                    "payments_trust_message",
                    models.TextField(
                        default="No credit cards required. No barriers to entry. Built for South Asian markets.",
                        help_text="Trust message for payment methods",
                    ),
                ),
                ("deltacoin_section_enabled", models.BooleanField(default=True)),
                (
                    "deltacoin_section_title",
                    models.CharField(
                        default="DeltaCoin Economy",
                        help_text="DeltaCoin section headline",
                        max_length=200,
                    ),
                ),
                (
                    "deltacoin_section_description",
                    models.TextField(
                        default="Earn by competing. Spend on upgrades. Build your legacy.",
                        help_text="DeltaCoin section description",
                    ),
                ),
                (
                    "deltacoin_earn_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of earn methods: ["Participating in tournaments", "Winning matches"]',
                    ),
                ),
                (
                    "deltacoin_spend_options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of spend options: ["Store purchases", "Premium subscriptions"]',
                    ),
                ),
                ("community_section_enabled", models.BooleanField(default=True)),
                (
                    "community_section_title",
                    models.CharField(
                        default="Join the Community",
                        help_text="Community section headline",
                        max_length=200,
                    ),
                ),
                (
                    "community_section_description",
                    models.TextField(
                        default="Strategy guides, match highlights, esports news—all in one home",
                        help_text="Community section description",
                    ),
                ),
                ("roadmap_section_enabled", models.BooleanField(default=True)),
                (
                    "roadmap_section_title",
                    models.CharField(
                        default="The Vision Ahead",
                        help_text="Roadmap section headline",
                        max_length=200,
                    ),
                ),
                (
                    "roadmap_section_description",
                    models.TextField(
                        default="Evolving toward global scale while staying rooted in emerging markets",
                        help_text="Roadmap section description",
                    ),
                ),
                (
                    "roadmap_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of roadmap items: [{"status": "COMPLETED", "title": "...", "description": "..."}]. status: COMPLETED, IN_PROGRESS, PLANNED',
                    ),
                ),
                ("final_cta_section_enabled", models.BooleanField(default=True)),
                (
                    "final_cta_title",
                    models.CharField(
                        default="Ready to Compete?", help_text="Final CTA headline", max_length=200
                    ),
                ),
                (
                    "final_cta_description",
                    models.TextField(
                        default="Join thousands of gamers building their esports careers on DeltaCrown",
                        help_text="Final CTA description",
                    ),
                ),
                (
                    "final_cta_primary_text",
                    models.CharField(default="Create Account", max_length=50),
                ),
                (
                    "final_cta_primary_url",
                    models.CharField(default="/account/register/", max_length=200),
                ),
                (
                    "final_cta_secondary_text",
                    models.CharField(default="Explore Platform", max_length=50),
                ),
                ("final_cta_secondary_url", models.CharField(default="/about/", max_length=200)),
                (
                    "platform_tagline",
                    models.CharField(
                        default="From the Delta to the Crown — Where Champions Rise.",
                        help_text="Platform tagline for footer/about sections",
                        max_length=200,
                    ),
                ),
                (
                    "platform_founded_year",
                    models.PositiveIntegerField(
                        default=2025, help_text="Year DeltaCrown was founded"
                    ),
                ),
                (
                    "platform_founder",
                    models.CharField(
                        default="Redwanul Rashik", help_text="Founder name", max_length=100
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last user who updated homepage content",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homepage_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Content",
                "verbose_name_plural": "Homepage Content",
                "db_table": "siteui_homepage_content",
            },
        ),
    ]
