# Generated by Django 5.2.8 on 2026-04-20 11:57

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteui", "0004_alter_communitypostmedia_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArenaGlobalWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "badge_label",
                    models.CharField(
                        default="Fan Pulse",
                        help_text="Small badge label shown at the top of the widget",
                        max_length=60,
                    ),
                ),
                (
                    "meta_label",
                    models.CharField(
                        default="Global Widget",
                        help_text="Meta label on the top-right of the widget",
                        max_length=60,
                    ),
                ),
                (
                    "tournament_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tournament or context label above the question",
                        max_length=120,
                    ),
                ),
                (
                    "prompt_text",
                    models.CharField(
                        default="Who wins the Grand Final?",
                        help_text="Primary prediction question shown to users",
                        max_length=220,
                    ),
                ),
                ("option_a_label", models.CharField(default="Team A", max_length=120)),
                (
                    "option_a_percent",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="Displayed percentage for option A",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("option_b_label", models.CharField(default="Team B", max_length=120)),
                (
                    "option_b_percent",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="Displayed percentage for option B",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "vote_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Signal/vote count displayed below options"
                    ),
                ),
                (
                    "vote_count_label",
                    models.CharField(
                        default="Signals Intercepted",
                        help_text="Suffix shown after vote count",
                        max_length=80,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Arena Global Widget",
                "verbose_name_plural": "Arena Global Widgets",
                "ordering": ["display_order", "-updated_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="siteui_aren_is_acti_8368e8_idx"
                    ),
                    models.Index(
                        fields=["starts_at", "ends_at"], name="siteui_aren_starts__1f194f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ArenaHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, default="", max_length=180)),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Target URL opened when users click the highlight",
                    ),
                ),
                (
                    "duration_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short duration label (e.g. 0:32)",
                        max_length=20,
                    ),
                ),
                (
                    "views_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short view counter text (e.g. 2.4k views)",
                        max_length=60,
                    ),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="arena/highlights/%Y/%m/%d/",
                        validators=[apps.common.validators.validate_image_upload],
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional external thumbnail URL (fallback if image is not uploaded)",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Arena Highlight",
                "verbose_name_plural": "Arena Highlights",
                "ordering": ["display_order", "-updated_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="siteui_aren_is_acti_08fd94_idx"
                    )
                ],
            },
        ),
    ]
