# Generated by Django 5.2.8 on 2026-04-20 13:16

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_gametournamentconfig_credential_schema_and_more"),
        ("siteui", "0005_arenaglobalwidget_arenahighlight"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArenaGlobalWidgetVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "voter_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Anonymous/session voter fingerprint for one-vote enforcement",
                        max_length=64,
                    ),
                ),
                (
                    "selected_option",
                    models.CharField(choices=[("A", "Option A"), ("B", "Option B")], max_length=1),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arena_widget_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="siteui.arenaglobalwidget",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["widget", "selected_option"], name="siteui_aren_widget__8cae1d_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("widget", "user"),
                        name="siteui_arena_vote_unique_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("voter_key__gt", "")),
                        fields=("widget", "voter_key"),
                        name="siteui_arena_vote_unique_key",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ArenaStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, default="", max_length=180)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("twitch", "Twitch"),
                            ("facebook", "Facebook"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "stream_url",
                    models.URLField(
                        help_text="Watch URL for YouTube/Twitch/Facebook/other platforms"
                    ),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="arena/streams/%Y/%m/%d/",
                        validators=[apps.common.validators.validate_image_upload],
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True, default="")),
                ("channel_name", models.CharField(blank=True, default="", max_length=120)),
                ("game_label", models.CharField(blank=True, default="", max_length=100)),
                ("is_live", models.BooleanField(db_index=True, default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("featured", models.BooleanField(db_index=True, default=False)),
                ("viewers_label", models.CharField(blank=True, default="", max_length=60)),
                ("viewer_count", models.PositiveIntegerField(blank=True, null=True)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arena_streams",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["-featured", "display_order", "-updated_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_live", "featured", "display_order"],
                        name="siteui_aren_is_acti_f7b208_idx",
                    ),
                    models.Index(
                        fields=["starts_at", "ends_at"], name="siteui_aren_starts__efa984_idx"
                    ),
                ],
            },
        ),
    ]
