# Generated by Django 5.2.8 on 2026-04-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siteui", "0006_arenaglobalwidgetvote_arenastream"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arenaglobalwidgetvote",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Arena Vote",
                "verbose_name_plural": "Arena Votes",
            },
        ),
        migrations.AlterModelOptions(
            name="arenastream",
            options={
                "ordering": ["-featured", "display_order", "-updated_at", "id"],
                "verbose_name": "Arena Stream",
                "verbose_name_plural": "Arena Streams",
            },
        ),
    ]
