# Generated by Django 5.2.8 on 2026-04-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_gametournamentconfig_credential_schema_and_more"),
        ("siteui", "0007_alter_arenaglobalwidgetvote_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="arenahighlight",
            old_name="title",
            new_name="fetched_title",
        ),
        migrations.RenameField(
            model_name="arenahighlight",
            old_name="video_url",
            new_name="source_url",
        ),
        migrations.RenameField(
            model_name="arenahighlight",
            old_name="thumbnail_image",
            new_name="custom_thumbnail",
        ),
        migrations.RenameField(
            model_name="arenahighlight",
            old_name="thumbnail_url",
            new_name="fetched_thumbnail_url",
        ),
        migrations.RenameField(
            model_name="arenastream",
            old_name="title",
            new_name="fetched_title",
        ),
        migrations.RenameField(
            model_name="arenastream",
            old_name="platform",
            new_name="provider",
        ),
        migrations.RenameField(
            model_name="arenastream",
            old_name="stream_url",
            new_name="source_url",
        ),
        migrations.RenameField(
            model_name="arenastream",
            old_name="thumbnail_image",
            new_name="custom_thumbnail",
        ),
        migrations.RenameField(
            model_name="arenastream",
            old_name="thumbnail_url",
            new_name="fetched_thumbnail_url",
        ),
        migrations.AddField(
            model_name="arenahighlight",
            name="custom_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="arenahighlight",
            name="embed_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="arenahighlight",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="arena_highlights",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="arenahighlight",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("youtube", "YouTube"),
                    ("twitch", "Twitch"),
                    ("facebook", "Facebook"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="arenastream",
            name="custom_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="arenastream",
            name="embed_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="arenahighlight",
            name="fetched_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="arenahighlight",
            name="fetched_thumbnail_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="arenahighlight",
            name="source_url",
            field=models.URLField(help_text="Primary media source URL (YouTube/Twitch/Facebook/other)"),
        ),
        migrations.AlterField(
            model_name="arenastream",
            name="fetched_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="arenastream",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("youtube", "YouTube"),
                    ("twitch", "Twitch"),
                    ("facebook", "Facebook"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="arenastream",
            name="source_url",
            field=models.URLField(help_text="Primary media source URL"),
        ),
    ]
