# Generated by Django 5.2.8 on 2026-05-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteui", "0009_community_post_types"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="communitypollvote",
            new_name="siteui_comm_post_id_9252af_idx",
            old_name="siteui_comm_pollvote_post_idx",
        ),
        migrations.RenameIndex(
            model_name="communitypost",
            new_name="siteui_comm_post_ty_e9afe0_idx",
            old_name="siteui_comm_post_ty_idx",
        ),
        migrations.AlterField(
            model_name="communitypollvote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="game",
            field=models.CharField(
                blank=True, help_text="Game slug this post is related to", max_length=100
            ),
        ),
    ]
