# Generated by Django 5.2.8 on 2026-06-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "siteui",
            "0010_rename_siteui_comm_pollvote_post_idx_siteui_comm_post_id_9252af_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagecontent",
            name="hero_badge_text",
            field=models.CharField(
                default="Competitive Gaming Platform",
                help_text="Badge text above hero title",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="hero_description",
            field=models.TextField(
                default="DeltaCrown connects tournaments, teams, player profiles, rankings, and competitive operations for gaming communities in Bangladesh and beyond.",
                help_text="Hero description paragraph",
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="payments_section_description",
            field=models.TextField(
                default="Local payment support for familiar payment methods and platform workflows",
                help_text="Payments section description",
            ),
        ),
    ]
