# Generated by Django 4.2.23 on 2025-09-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_remove_paymentverification_pv_payer_account_idx_and_more'),
        ('game_valorant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorantTeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=80)),
                ('team_tag', models.CharField(max_length=5)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='valorant/team_logos/')),
                ('region', models.CharField(max_length=40)),
                ('agree_captain_consent', models.BooleanField(default=False)),
                ('agree_rules', models.BooleanField(default=False)),
                ('agree_no_cheat', models.BooleanField(default=False)),
                ('agree_enforcement', models.BooleanField(default=False)),
                ('payment_method', models.CharField(max_length=32)),
                ('payment_reference', models.CharField(max_length=128)),
                ('amount_bdt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='valorant/payment_proofs/')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valorant_team_info', to='tournaments.registration')),
            ],
            options={
                'verbose_name': 'Valorant Team Registration Info',
                'verbose_name_plural': 'Valorant Team Registration Info',
            },
        ),
        migrations.CreateModel(
            name='ValorantPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('riot_id', models.CharField(max_length=32)),
                ('riot_tagline', models.CharField(max_length=16)),
                ('discord', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('starter', 'Starter'), ('sub', 'Substitute')], max_length=10)),
                ('team_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game_valorant.valorantteaminfo')),
            ],
        ),
    ]
