# Generated by Django 4.2.23 on 2025-09-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_valorant', '0005_restore_info_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorantteaminfo',
            name='registration',
        ),
        migrations.DeleteModel(
            name='ValorantPlayer',
        ),
        migrations.DeleteModel(
            name='ValorantTeamInfo',
        ),
    ]
