# Generated by Django 4.2.24 on 2025-09-17 17:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_valorant', '0007_alter_valorantconfig_best_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorantconfig',
            name='additional_rules_richtext',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Additional rules'),
        ),
        migrations.AlterField(
            model_name='valorantconfig',
            name='map_pool',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='valorantconfig',
            name='overtime_rules',
            field=models.CharField(blank=True, help_text='e.g. MR3 OT, win by 2', max_length=120, null=True),
        ),
    ]
