# Generated by Django 5.2.8 on 2025-11-16 19:00

import apps.user_profile.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('region', models.CharField(choices=[('BD', 'Bangladesh'), ('SA', 'South Asia'), ('AS', 'Asia (Other)'), ('EU', 'Europe'), ('NA', 'North America')], default='BD', max_length=2)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.user_profile.models.user_avatar_path)),
                ('bio', models.TextField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('twitch_link', models.URLField(blank=True)),
                ('preferred_games', models.JSONField(blank=True, default=list, null=True)),
                ('discord_id', models.CharField(blank=True, max_length=64)),
                ('riot_id', models.CharField(blank=True, help_text='Riot ID (Name#TAG) for Valorant', max_length=100)),
                ('riot_tagline', models.CharField(blank=True, help_text='Riot Tagline (part after #)', max_length=50)),
                ('efootball_id', models.CharField(blank=True, help_text='eFootball User ID', max_length=100)),
                ('steam_id', models.CharField(blank=True, help_text='Steam ID for Dota 2, CS2', max_length=100)),
                ('mlbb_id', models.CharField(blank=True, help_text='Mobile Legends Game ID', max_length=100)),
                ('mlbb_server_id', models.CharField(blank=True, help_text='Mobile Legends Server ID', max_length=50)),
                ('pubg_mobile_id', models.CharField(blank=True, help_text='PUBG Mobile Character/Player ID', max_length=100)),
                ('free_fire_id', models.CharField(blank=True, help_text='Free Fire User/Player ID', max_length=100)),
                ('ea_id', models.CharField(blank=True, help_text='EA ID for FC 24', max_length=100)),
                ('codm_uid', models.CharField(blank=True, help_text='Call of Duty Mobile UID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False, help_text='Hide entire profile from public.')),
                ('show_email', models.BooleanField(default=False, help_text='Allow showing my email on public profile.')),
                ('show_phone', models.BooleanField(default=False, help_text='Allow showing my phone on public profile.')),
                ('show_socials', models.BooleanField(default=True, help_text='Allow showing my social links/IDs on public profile.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'indexes': [models.Index(fields=['region'], name='user_profil_region_1d3f95_idx')],
            },
        ),
    ]
