# Generated by Django 4.2.23 on 2025-09-03 12:12

import apps.user_profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('region', models.CharField(choices=[('BD', 'Bangladesh'), ('SA', 'South Asia'), ('AS', 'Asia (Other)'), ('EU', 'Europe'), ('NA', 'North America')], default='BD', max_length=2)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.user_profile.models.user_avatar_path)),
                ('bio', models.TextField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('twitch_link', models.URLField(blank=True)),
                ('preferred_games', models.JSONField(blank=True, default=list)),
                ('discord_id', models.CharField(blank=True, max_length=64)),
                ('riot_id', models.CharField(blank=True, max_length=100)),
                ('efootball_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'indexes': [models.Index(fields=['region'], name='user_profil_region_1d3f95_idx')],
            },
        ),
    ]
