# Generated by Django 5.2.8 on 2025-11-26 00:41

import apps.user_profile.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Street address for correspondence and prize shipping', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible metadata for future features (jersey size, dietary restrictions for LANs, etc.)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, help_text='Profile banner image', null=True, upload_to=apps.user_profile.models.user_banner_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City of residence', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country of residence (for regional tournaments)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age verification and tournament eligibility', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deltacoin_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current DeltaCoin balance (read-only, managed by wallet)', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', help_text='Emergency contact full name', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', help_text='Emergency contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, default='', help_text='Relationship to emergency contact (e.g., Parent, Spouse, Guardian)', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='game_profiles',
            field=models.JSONField(blank=True, default=list, help_text='\n        JSON structure for infinite game support:\n        [\n            {\n                "game": "valorant",\n                "ign": "Player#TAG",\n                "role": "Duelist",\n                "rank": "Immortal 3",\n                "platform": "PC",\n                "is_verified": false,\n                "metadata": {}\n            }\n        ]\n        '),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='', help_text='Gender identity (optional, for demographics and gender-specific events)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inventory_items',
            field=models.JSONField(blank=True, default=list, help_text='Digital assets (profile frames, chat colors, etc.)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', help_text='KYC verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when KYC was verified', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1, help_text='User level based on platform activity'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lifetime_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value of prizes won (bragging rights)', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, default='', help_text='Nationality/citizenship (may differ from country of residence)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Primary phone number (international format preferred: +8801XXXXXXXXX)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pinned_badges',
            field=models.JSONField(blank=True, default=list, help_text='List of pinned badge IDs for showcase (max 5)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, default='', help_text='Postal/ZIP code', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='real_full_name',
            field=models.CharField(blank=True, default='', help_text='Full legal name for official tournament registration and certificates', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reputation_score',
            field=models.IntegerField(default=100, help_text='Fair play karma rating (anti-toxicity)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_address',
            field=models.BooleanField(default=False, help_text='Display address on public profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_age',
            field=models.BooleanField(default=True, help_text='Display age (calculated from DOB) on public profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_country',
            field=models.BooleanField(default=True, help_text='Display country on public profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_gender',
            field=models.BooleanField(default=False, help_text='Display gender on public profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_real_name',
            field=models.BooleanField(default=False, help_text='Display real full name on public profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill_rating',
            field=models.IntegerField(default=1000, help_text='Platform-calculated ELO/MMR for dynamic seeding'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Custom URL slug (e.g., deltacrown.com/u/legend)', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stream_status',
            field=models.BooleanField(default=False, help_text='Automatically indicates if user is currently live on linked Twitch/YouTube'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='system_settings',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences (theme, notifications, language)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tiktok',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public unique identifier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0, help_text='Experience points'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Profile bio/headline'),
        ),
    ]
