# Generated by Django 5.2.8 on 2026-01-23 18:08

import apps.user_profile.models_main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_alter_verificationrecord_id_document_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_back",
            field=models.ImageField(
                blank=True,
                help_text="Back side of government-issued ID",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_front",
            field=models.ImageField(
                blank=True,
                help_text="Front side of government-issued ID (NID, Passport, Driver's License)",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="selfie_with_id",
            field=models.ImageField(
                blank=True,
                help_text="Selfie holding the ID document for liveness verification",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.CreateModel(
            name="PublicIDCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Year (YY format, e.g., 25 for 2025)", unique=True
                    ),
                ),
                (
                    "counter",
                    models.IntegerField(default=0, help_text="Sequential counter for this year"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Public ID Counter",
                "verbose_name_plural": "Public ID Counters",
                "db_table": "user_profile_publicidcounter",
                "indexes": [models.Index(fields=["year"], name="idx_publicid_year")],
            },
        ),
    ]
