# Generated by Django 5.2.8 on 2025-11-26 00:46

from django.db import migrations
import uuid
from django.utils.text import slugify


def populate_uuid_and_slug(apps, schema_editor):
    """Populate uuid and slug fields with unique values"""
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    
    profiles = UserProfile.objects.all()
    used_slugs = set()
    
    for profile in profiles:
        # ALWAYS generate new unique UUID (don't check if exists)
        profile.uuid = uuid.uuid4()
        
        # Generate unique slug from display_name if not set
        if not profile.slug:
            base_slug = slugify(profile.display_name) or f'user-{profile.id}'
            slug = base_slug
            counter = 1
            
            # Ensure uniqueness
            while slug in used_slugs or UserProfile.objects.filter(slug=slug).exclude(id=profile.id).exists():
                slug = f'{base_slug}-{counter}'
                counter += 1
            
            profile.slug = slug
            used_slugs.add(slug)
        
        profile.save(update_fields=['uuid', 'slug'])


def reverse_populate(apps, schema_editor):
    """Reverse operation - clear uuid and slug"""
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    UserProfile.objects.all().update(uuid=None, slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_address_userprofile_attributes_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_uuid_and_slug, reverse_populate),
    ]
