# Generated by Django 4.2.23 on 2025-09-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_add_privacy_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_socials',
        ),
    ]
