# Generated by Django 5.2.8 on 2025-11-26 01:06

import apps.user_profile.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_populate_uuid_and_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Custom URL slug (e.g., deltacrown.com/u/legend)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True),
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_real_name', models.BooleanField(default=False, help_text='Show real full name on public profile')),
                ('show_phone', models.BooleanField(default=False, help_text='Show phone number on public profile')),
                ('show_email', models.BooleanField(default=False, help_text='Show email address on public profile')),
                ('show_age', models.BooleanField(default=True, help_text='Show age (calculated from date of birth)')),
                ('show_gender', models.BooleanField(default=False, help_text='Show gender on public profile')),
                ('show_country', models.BooleanField(default=True, help_text='Show country of residence')),
                ('show_address', models.BooleanField(default=False, help_text='Show full address on public profile')),
                ('show_game_ids', models.BooleanField(default=True, help_text='Show gaming IDs (Riot ID, Steam ID, etc.)')),
                ('show_match_history', models.BooleanField(default=True, help_text='Show tournament match history')),
                ('show_teams', models.BooleanField(default=True, help_text='Show team memberships')),
                ('show_achievements', models.BooleanField(default=True, help_text='Show badges and achievements')),
                ('show_inventory_value', models.BooleanField(default=False, help_text='Show total inventory/cosmetics value')),
                ('show_level_xp', models.BooleanField(default=True, help_text='Show player level and XP')),
                ('show_social_links', models.BooleanField(default=True, help_text='Show social media links (Facebook, Instagram, etc.)')),
                ('allow_team_invites', models.BooleanField(default=True, help_text='Allow receiving team invitations')),
                ('allow_friend_requests', models.BooleanField(default=True, help_text='Allow receiving friend requests')),
                ('allow_direct_messages', models.BooleanField(default=True, help_text='Allow receiving direct messages from other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(help_text='User profile these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'Privacy Settings',
                'verbose_name_plural': 'Privacy Settings',
            },
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_front', models.ImageField(blank=True, help_text="Front side of government-issued ID (NID, Passport, Driver's License)", null=True, upload_to=apps.user_profile.models.kyc_document_path)),
                ('id_document_back', models.ImageField(blank=True, help_text='Back side of government-issued ID', null=True, upload_to=apps.user_profile.models.kyc_document_path)),
                ('selfie_with_id', models.ImageField(blank=True, help_text='Selfie holding the ID document for liveness verification', null=True, upload_to=apps.user_profile.models.kyc_document_path)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', help_text='Current verification status', max_length=20)),
                ('verified_name', models.CharField(blank=True, default='', help_text='Full name as shown on ID document', max_length=200)),
                ('verified_dob', models.DateField(blank=True, help_text='Date of birth from ID document', null=True)),
                ('verified_nationality', models.CharField(blank=True, default='', help_text='Nationality from ID document', max_length=100)),
                ('id_number', models.CharField(blank=True, default='', help_text='ID document number (encrypted in production)', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When user submitted documents for review', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When staff reviewed the submission', null=True)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Reason for rejection (shown to user)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff member who reviewed this verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews_performed', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(help_text='User profile being verified', on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'Verification Record',
                'verbose_name_plural': 'Verification Records',
                'ordering': ['-updated_at'],
            },
        ),
    ]
