# Generated by Django 5.2.8 on 2025-11-26 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_slug_alter_userprofile_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(help_text='What this badge represents')),
                ('icon', models.CharField(default='🏆', help_text='Emoji or icon identifier', max_length=50)),
                ('color', models.CharField(default='#FFD700', help_text='Hex color code for badge display', max_length=7)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('category', models.CharField(choices=[('achievement', 'Achievement'), ('tournament', 'Tournament'), ('milestone', 'Milestone'), ('special', 'Special Event'), ('community', 'Community')], default='achievement', max_length=20)),
                ('criteria', models.JSONField(default=dict, help_text='\n        Earning criteria:\n        {\n            "type": "match_wins",\n            "threshold": 10,\n            "game": "valorant"  // optional\n        }\n        ')),
                ('xp_reward', models.IntegerField(default=0, help_text='XP awarded when badge is earned')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this badge can still be earned')),
                ('is_hidden', models.BooleanField(default=False, help_text="Hidden badges don't show in badge list until earned")),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['category', 'rarity'], name='user_profil_categor_14e389_idx'), models.Index(fields=['is_active', 'is_hidden'], name='user_profil_is_acti_bbbbcc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.JSONField(default=dict, help_text='\n        Progress toward earning badge:\n        {\n            "current": 5,\n            "required": 10,\n            "updated_at": "2025-11-26T12:00:00Z"\n        }\n        ')),
                ('context', models.JSONField(blank=True, default=dict, help_text='\n        Context about how badge was earned:\n        {\n            "tournament_id": 123,\n            "match_id": 456,\n            "game": "valorant"\n        }\n        ')),
                ('is_pinned', models.BooleanField(default=False, help_text='Whether this badge is pinned to profile showcase')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='user_profile.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', '-earned_at'], name='user_profil_user_id_49ae4e_idx'), models.Index(fields=['badge', '-earned_at'], name='user_profil_badge_i_c3e700_idx'), models.Index(fields=['user', 'is_pinned'], name='user_profil_user_id_8250d3_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
