# Generated by Django 4.2.23 on 2025-09-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_add_privacy_flags_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_games',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
