# Generated by Django 5.2.8 on 2025-11-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_badge_userbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(help_text='The user who is following', on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='user_profile.userprofile')),
                ('following', models.ForeignKey(help_text='The user being followed', on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'User Follow',
                'verbose_name_plural': 'User Follows',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', '-created_at'], name='user_profil_followe_b46ac6_idx'), models.Index(fields=['following', '-created_at'], name='user_profil_followi_c9a679_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
