# Generated by Django 5.2.8 on 2025-11-26 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0006_add_user_follow_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pronouns",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pronouns (e.g., he/him, she/her, they/them)",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Achievement name", max_length=100)),
                ("description", models.TextField(help_text="Achievement description")),
                (
                    "emoji",
                    models.CharField(
                        default="🏆", help_text="Emoji icon for display", max_length=10
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(blank=True, default="", help_text="Optional custom icon URL"),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        help_text="Achievement rarity",
                        max_length=20,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context data (tournament_id, placement, etc.)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Certificate title", max_length=200)),
                ("tournament_name", models.CharField(help_text="Tournament name", max_length=200)),
                (
                    "tournament_id",
                    models.IntegerField(blank=True, help_text="Tournament ID reference", null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Full certificate image", upload_to="certificates/"
                    ),
                ),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Thumbnail URL (auto-generated if empty)",
                        max_length=500,
                    ),
                ),
                ("issued_at", models.DateTimeField(help_text="When certificate was issued")),
                (
                    "verification_code",
                    models.CharField(
                        help_text="Unique verification code", max_length=50, unique=True
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=True, help_text="Whether certificate is verified"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional certificate data (placement, prize, etc.)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="GameProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "game",
                    models.CharField(
                        choices=[
                            ("valorant", "VALORANT"),
                            ("csgo", "CS:GO"),
                            ("cs2", "Counter-Strike 2"),
                            ("lol", "League of Legends"),
                            ("dota2", "Dota 2"),
                            ("overwatch", "Overwatch 2"),
                            ("apex", "Apex Legends"),
                            ("fortnite", "Fortnite"),
                            ("pubg", "PUBG"),
                            ("r6", "Rainbow Six Siege"),
                            ("rocket_league", "Rocket League"),
                            ("mlbb", "Mobile Legends"),
                            ("codm", "Call of Duty Mobile"),
                            ("pubgm", "PUBG Mobile"),
                            ("freefire", "Free Fire"),
                            ("fc24", "FC 24"),
                        ],
                        help_text="Game identifier",
                        max_length=20,
                    ),
                ),
                (
                    "game_display_name",
                    models.CharField(
                        editable=False, help_text="Auto-filled from choices", max_length=100
                    ),
                ),
                (
                    "in_game_name",
                    models.CharField(
                        help_text="In-game username (e.g., Player#TAG)", max_length=100
                    ),
                ),
                (
                    "rank_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Current rank (e.g., Diamond 2, Global Elite)",
                        max_length=50,
                    ),
                ),
                (
                    "rank_image",
                    models.ImageField(
                        blank=True,
                        help_text="Rank badge image",
                        null=True,
                        upload_to="rank_images/",
                    ),
                ),
                (
                    "rank_points",
                    models.IntegerField(blank=True, help_text="LP/RR/MMR points", null=True),
                ),
                (
                    "rank_tier",
                    models.IntegerField(
                        default=0, help_text="Numeric rank tier (for sorting/comparison)"
                    ),
                ),
                (
                    "peak_rank",
                    models.CharField(
                        blank=True, default="", help_text="Highest rank achieved", max_length=50
                    ),
                ),
                (
                    "matches_played",
                    models.IntegerField(default=0, help_text="Total matches played"),
                ),
                (
                    "win_rate",
                    models.IntegerField(default=0, help_text="Win rate percentage (0-100)"),
                ),
                (
                    "kd_ratio",
                    models.FloatField(blank=True, help_text="Kill/Death ratio", null=True),
                ),
                (
                    "hours_played",
                    models.IntegerField(blank=True, help_text="Total hours played", null=True),
                ),
                (
                    "main_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Main role/position (e.g., Duelist, Support, Mid)",
                        max_length=50,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this profile has been verified via game API",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Profile",
                "verbose_name_plural": "Game Profiles",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("game_name", models.CharField(help_text="Game name", max_length=100)),
                (
                    "mode",
                    models.CharField(
                        default="Competitive",
                        help_text="Game mode (Competitive, Ranked, Casual)",
                        max_length=50,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("win", "Win"), ("loss", "Loss"), ("draw", "Draw")],
                        help_text="Match result",
                        max_length=10,
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        blank=True, default="", help_text="Match score (e.g., 13-11)", max_length=20
                    ),
                ),
                (
                    "kda",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Kill/Death/Assist (e.g., 24/12/8)",
                        max_length=30,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Match duration in minutes", null=True
                    ),
                ),
                ("played_at", models.DateTimeField(help_text="When the match was played")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional match data (map, characters, tournament_id, etc.)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["-played_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitch", "Twitch"),
                            ("youtube", "YouTube"),
                            ("twitter", "Twitter"),
                            ("discord", "Discord"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("facebook", "Facebook"),
                        ],
                        help_text="Social media platform",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(help_text="Full URL to profile", max_length=500)),
                (
                    "handle",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Display name or handle (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this link has been verified by platform API",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["platform"],
            },
        ),
        migrations.DeleteModel(
            name="UserFollow",
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["user", "-earned_at"], name="user_profil_user_id_9f19cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["rarity", "-earned_at"], name="user_profil_rarity_30abc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["user", "-issued_at"], name="user_profil_user_id_01722a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["verification_code"], name="user_profil_verific_878acb_idx"),
        ),
        migrations.AddIndex(
            model_name="gameprofile",
            index=models.Index(fields=["user", "game"], name="user_profil_user_id_8b5bc8_idx"),
        ),
        migrations.AddIndex(
            model_name="gameprofile",
            index=models.Index(fields=["game", "-rank_tier"], name="user_profil_game_6957c4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="gameprofile",
            unique_together={("user", "game")},
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["user", "-played_at"], name="user_profil_user_id_3206ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["game_name", "-played_at"], name="user_profil_game_na_f70389_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["result", "-played_at"], name="user_profil_result_ffb8f8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sociallink",
            unique_together={("user", "platform")},
        ),
    ]
