# Generated by Django 4.2.24 on 2025-10-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_fix_user_fk_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codm_uid',
            field=models.CharField(blank=True, help_text='Call of Duty Mobile UID', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ea_id',
            field=models.CharField(blank=True, help_text='EA ID for FC 24', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='free_fire_id',
            field=models.CharField(blank=True, help_text='Free Fire User/Player ID', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mlbb_id',
            field=models.CharField(blank=True, help_text='Mobile Legends Game ID', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mlbb_server_id',
            field=models.CharField(blank=True, help_text='Mobile Legends Server ID', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pubg_mobile_id',
            field=models.CharField(blank=True, help_text='PUBG Mobile Character/Player ID', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='riot_tagline',
            field=models.CharField(blank=True, help_text='Riot Tagline (part after #)', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='steam_id',
            field=models.CharField(blank=True, help_text='Steam ID for Dota 2, CS2', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='efootball_id',
            field=models.CharField(blank=True, help_text='eFootball User ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='riot_id',
            field=models.CharField(blank=True, help_text='Riot ID (Name#TAG) for Valorant', max_length=100),
        ),
    ]
