# Generated by Django 5.2.8 on 2025-12-16 19:39
# MODIFIED: Made idempotent with DROP COLUMN IF EXISTS

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0011_remove_legacy_game_id_fields"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE user_profile_userprofile DROP COLUMN IF EXISTS codm_uid;
            ALTER TABLE user_profile_userprofile DROP COLUMN IF EXISTS ea_id;
            ALTER TABLE user_profile_userprofile DROP COLUMN IF EXISTS efootball_id;
            ALTER TABLE user_profile_userprofile DROP COLUMN IF EXISTS free_fire_id;
            ALTER TABLE user_profile_userprofile DROP COLUMN IF EXISTS mlbb_id;
            ALTER TABLE user_profile_userprofile DROP COLUMN IF EXISTS mlbb_server_id;
            ALTER TABLE user_profile_userprofile DROP COLUMN IF EXISTS pubg_mobile_id;
            ALTER TABLE user_profile_userprofile DROP COLUMN IF EXISTS riot_id;
            ALTER TABLE user_profile_userprofile DROP COLUMN IF EXISTS riot_tagline;
            ALTER TABLE user_profile_userprofile DROP COLUMN IF EXISTS steam_id;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
