# Generated by Django 5.2.8 on 2025-12-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0011_remove_legacy_game_id_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="codm_uid",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="ea_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="efootball_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="free_fire_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="mlbb_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="mlbb_server_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="pubg_mobile_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="riot_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="riot_tagline",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="steam_id",
        ),
    ]
