# Generated by Django 5.2.8 on 2025-12-23 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0012_remove_userprofile_codm_uid_remove_userprofile_ea_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicIDCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(help_text="Allocation year (e.g., 2025)", unique=True),
                ),
                (
                    "counter",
                    models.IntegerField(
                        default=0, help_text="Last allocated sequential number for this year"
                    ),
                ),
            ],
            options={
                "verbose_name": "Public ID Counter",
                "verbose_name_plural": "Public ID Counters",
                "db_table": "user_profile_publicicounter",
                "ordering": ["-year"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="public_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Human-readable public identifier (DC-YY-NNNNNN format, e.g., DC-25-000042)",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Legacy UUID identifier (deprecated, use public_id)",
                unique=True,
            ),
        ),
    ]
