# Generated by Django 5.2.8 on 2025-12-23 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0013_add_public_id_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tournament_registered", "Registered for Tournament"),
                            ("tournament_joined", "Tournament Started"),
                            ("tournament_completed", "Tournament Finished"),
                            ("tournament_won", "Won Tournament (1st)"),
                            ("tournament_runner_up", "Runner-Up (2nd)"),
                            ("tournament_top4", "Top 4 Placement"),
                            ("match_played", "Played Match"),
                            ("match_won", "Won Match"),
                            ("match_lost", "Lost Match"),
                            ("coins_earned", "Earned DeltaCoins"),
                            ("coins_spent", "Spent DeltaCoins"),
                            ("achievement_unlocked", "Unlocked Achievement"),
                            ("team_created", "Created Team"),
                            ("team_joined", "Joined Team"),
                            ("team_left", "Left Team"),
                        ],
                        db_index=True,
                        help_text="Type of event (tournament_won, match_played, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the event occurred (immutable)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event-specific data (tournament_id, match_id, amount, etc.)",
                    ),
                ),
                (
                    "source_model",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Model name that triggered event (Registration, Match, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Primary key of source model instance",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Event creation timestamp"),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "db_table": "user_profile_useractivity",
                "ordering": ["-timestamp"],
                "permissions": [
                    ("view_activity_feed", "Can view user activity feed"),
                    ("export_activity_data", "Can export activity data (GDPR)"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfileStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tournaments_played",
                    models.IntegerField(
                        default=0,
                        help_text="Total tournaments participated in (TOURNAMENT_JOINED events)",
                    ),
                ),
                (
                    "tournaments_won",
                    models.IntegerField(
                        default=0, help_text="Total tournament victories (TOURNAMENT_WON events)"
                    ),
                ),
                (
                    "tournaments_top3",
                    models.IntegerField(
                        default=0,
                        help_text="Total top 3 finishes (TOURNAMENT_PLACED events with placement <= 3)",
                    ),
                ),
                (
                    "matches_played",
                    models.IntegerField(
                        default=0, help_text="Total matches played (MATCH_PLAYED events)"
                    ),
                ),
                (
                    "matches_won",
                    models.IntegerField(
                        default=0, help_text="Total matches won (MATCH_WON events)"
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total coins earned (sum of COINS_EARNED events)",
                        max_digits=12,
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total coins spent (sum of COINS_SPENT events)",
                        max_digits=12,
                    ),
                ),
                (
                    "first_tournament_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of first tournament participation",
                        null=True,
                    ),
                ),
                (
                    "last_tournament_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of most recent tournament participation",
                        null=True,
                    ),
                ),
                (
                    "last_match_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of most recent match", null=True
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When these stats were last recomputed from events"
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile Stats",
                "verbose_name_plural": "User Profile Stats",
                "db_table": "user_profile_stats",
            },
        ),
        migrations.DeleteModel(
            name="PublicIDCounter",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Public unique identifier",
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["public_id"], name="idx_profile_public_id"),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                help_text="User who performed the action",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofilestats",
            name="user_profile",
            field=models.OneToOneField(
                help_text="Profile these stats belong to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["user", "-timestamp"], name="idx_activity_user_time"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["event_type", "-timestamp"], name="idx_activity_type_time"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["user", "event_type"], name="idx_activity_user_type"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["source_model", "source_id"], name="idx_activity_source"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["timestamp"], name="idx_activity_timestamp"),
        ),
        migrations.AddConstraint(
            model_name="useractivity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_id__isnull", False), ("source_model__isnull", False)),
                fields=("source_model", "source_id", "event_type"),
                name="unique_source_event",
                violation_error_message="Event already exists for this source",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofilestats",
            index=models.Index(fields=["-tournaments_won"], name="idx_stats_tournaments_won"),
        ),
        migrations.AddIndex(
            model_name="userprofilestats",
            index=models.Index(fields=["-matches_won"], name="idx_stats_matches_won"),
        ),
        migrations.AddIndex(
            model_name="userprofilestats",
            index=models.Index(fields=["computed_at"], name="idx_stats_computed_at"),
        ),
    ]
