# Generated by Django 5.2.8 on 2025-12-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0014_useractivity_userprofilestats_delete_publicidcounter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("tournament_registered", "Registered for Tournament"),
                    ("tournament_joined", "Tournament Started"),
                    ("tournament_completed", "Tournament Finished"),
                    ("tournament_won", "Won Tournament (1st)"),
                    ("tournament_runner_up", "Runner-Up (2nd)"),
                    ("tournament_top4", "Top 4 Placement"),
                    ("tournament_placed", "Placed in Tournament"),
                    ("match_played", "Played Match"),
                    ("match_won", "Won Match"),
                    ("match_lost", "Lost Match"),
                    ("coins_earned", "Earned DeltaCoins"),
                    ("coins_spent", "Spent DeltaCoins"),
                    ("achievement_unlocked", "Unlocked Achievement"),
                    ("team_created", "Created Team"),
                    ("team_joined", "Joined Team"),
                    ("team_left", "Left Team"),
                ],
                db_index=True,
                help_text="Type of event (tournament_won, match_played, etc.)",
                max_length=50,
            ),
        ),
    ]
