# Generated by Django 5.2.8 on 2025-12-23 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0016_restore_publicidcounter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("public_id_assigned", "Public ID Assigned"),
                            ("public_id_backfilled", "Public ID Backfilled"),
                            ("economy_sync", "Economy Sync"),
                            ("economy_drift_corrected", "Economy Drift Corrected"),
                            ("stats_recomputed", "Stats Recomputed"),
                            ("stats_backfilled", "Stats Backfilled"),
                            ("profile_created", "Profile Created"),
                            ("profile_updated", "Profile Updated"),
                            ("privacy_settings_changed", "Privacy Settings Changed"),
                            ("admin_override", "Admin Override"),
                            ("system_reconcile", "System Reconcile"),
                        ],
                        db_index=True,
                        help_text="Type of event",
                        max_length=50,
                    ),
                ),
                (
                    "source_app",
                    models.CharField(
                        db_index=True,
                        help_text="Source app (user_profile, economy, tournaments, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        help_text="Type of object changed (UserProfile, UserProfileStats, DeltaCrownWallet, etc.)",
                        max_length=100,
                    ),
                ),
                ("object_id", models.BigIntegerField(help_text="ID of object changed")),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Request ID for correlation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="Idempotency key for deduplication",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of requester", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="User agent string", max_length=500, null=True
                    ),
                ),
                (
                    "before_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="State before change (privacy-safe fields only)",
                        null=True,
                    ),
                ),
                (
                    "after_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="State after change (privacy-safe fields only)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (reason, source command, etc.)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When event occurred",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null for system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        help_text="User whose data was affected",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Audit Event",
                "verbose_name_plural": "User Audit Events",
                "db_table": "user_profile_audit_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userauditevent",
            index=models.Index(fields=["subject_user", "-created_at"], name="idx_audit_subject"),
        ),
        migrations.AddIndex(
            model_name="userauditevent",
            index=models.Index(fields=["actor_user", "-created_at"], name="idx_audit_actor"),
        ),
        migrations.AddIndex(
            model_name="userauditevent",
            index=models.Index(fields=["event_type", "-created_at"], name="idx_audit_event_type"),
        ),
        migrations.AddIndex(
            model_name="userauditevent",
            index=models.Index(fields=["source_app", "-created_at"], name="idx_audit_source"),
        ),
        migrations.AddIndex(
            model_name="userauditevent",
            index=models.Index(fields=["object_type", "object_id"], name="idx_audit_object"),
        ),
    ]
