# Generated by Django 5.2.8 on 2025-12-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0017_userauditevent_delete_publicidcounter_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PublicIDCounter",
        ),
    ]
