# Generated by Django 5.2.8 on 2026-02-09 14:58

import apps.user_profile.models_main
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0027_discord_integration"),
        ("user_profile", "0020_alter_verificationrecord_id_document_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="primary_team",
            field=models.ForeignKey(
                blank=True,
                help_text="User's primary/main team (auto-syncs primary_game to team's game)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_members",
                to="organizations.team",
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_back",
            field=models.ImageField(
                blank=True,
                help_text="Back side of government-issued ID",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_front",
            field=models.ImageField(
                blank=True,
                help_text="Front side of government-issued ID (NID, Passport, Driver's License)",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="selfie_with_id",
            field=models.ImageField(
                blank=True,
                help_text="Selfie holding the ID document for liveness verification",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
    ]
