# Generated by Django 5.2.8 on 2025-12-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0020_restore_publicidcounter_for_tests"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PublicIDCounter",
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="show_activity_feed",
            field=models.BooleanField(default=True, help_text="Show activity feed on profile"),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="show_tournaments",
            field=models.BooleanField(
                default=True, help_text="Show tournament participation history"
            ),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="visibility_preset",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public - Everyone can see everything"),
                    ("PROTECTED", "Protected - Show limited info to non-friends"),
                    ("PRIVATE", "Private - Minimal public visibility"),
                ],
                default="PUBLIC",
                help_text="Quick privacy preset that sets multiple toggles",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("twitch", "Twitch"),
                    ("youtube", "YouTube"),
                    ("kick", "Kick"),
                    ("facebook_gaming", "Facebook Gaming"),
                    ("twitter", "Twitter/X"),
                    ("discord", "Discord"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("facebook", "Facebook"),
                    ("steam", "Steam"),
                    ("riot", "Riot Games"),
                    ("github", "GitHub"),
                ],
                help_text="Social media platform",
                max_length=20,
            ),
        ),
    ]
