# Generated by Django 5.2.8 on 2025-12-24 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0021_gp_stabilize_add_timestamps_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameprofile",
            options={
                "ordering": ["-is_pinned", "-pinned_order", "sort_order", "-updated_at"],
                "verbose_name": "Game Passport",
                "verbose_name_plural": "Game Passports",
            },
        ),
        migrations.RenameIndex(
            model_name="gameprofilealias",
            new_name="user_profil_game_pr_da10dd_idx",
            old_name="user_profil_game_pr_idx",
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="identity_key",
            field=models.CharField(
                db_index=True,
                help_text="Normalized identity for uniqueness (lowercase, trimmed)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="is_lft",
            field=models.BooleanField(default=False, help_text="Looking for team flag"),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="is_pinned",
            field=models.BooleanField(
                default=False, help_text="Whether this passport is pinned to profile"
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="is_verified",
            field=models.BooleanField(
                default=False, editable=False, help_text="DEPRECATED: Verification removed in GP-0"
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="locked_until",
            field=models.DateTimeField(
                blank=True, help_text="Identity cannot be changed until this date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-game extras (e.g., MLBB zone_id, region codes)",
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="pinned_order",
            field=models.SmallIntegerField(
                blank=True, help_text="Order for pinned passports (1-N)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="region",
            field=models.CharField(
                blank=True, default="", help_text="Player region (for join gating)", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="sort_order",
            field=models.SmallIntegerField(default=0, help_text="General sort order"),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended")],
                default="ACTIVE",
                help_text="Passport status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PROTECTED", "Protected"), ("PRIVATE", "Private")],
                default="PUBLIC",
                help_text="Privacy level for this passport",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gameprofilealias",
            name="changed_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the identity was changed"
            ),
        ),
        migrations.AlterField(
            model_name="gameprofilealias",
            name="changed_by_user_id",
            field=models.IntegerField(
                blank=True, help_text="User ID who made the change (nullable for system)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gameprofilealias",
            name="game_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="user_profile.gameprofile",
            ),
        ),
        migrations.AlterField(
            model_name="gameprofilealias",
            name="old_in_game_name",
            field=models.CharField(help_text="Previous in-game name", max_length=100),
        ),
        migrations.AlterField(
            model_name="gameprofilealias",
            name="reason",
            field=models.CharField(
                blank=True, default="", help_text="Reason for identity change", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="gameprofileconfig",
            name="allow_id_change",
            field=models.BooleanField(
                default=True, help_text="Whether users can change identities"
            ),
        ),
        migrations.AlterField(
            model_name="gameprofileconfig",
            name="cooldown_days",
            field=models.IntegerField(
                default=30, help_text="Days before identity can be changed again"
            ),
        ),
        migrations.AlterField(
            model_name="gameprofileconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="gameprofileconfig",
            name="enable_ip_smurf_detection",
            field=models.BooleanField(default=False, help_text="Enable IP-based smurf detection"),
        ),
        migrations.AlterField(
            model_name="gameprofileconfig",
            name="max_pinned_games",
            field=models.IntegerField(
                default=3, help_text="Maximum number of games a user can pin"
            ),
        ),
        migrations.AlterField(
            model_name="gameprofileconfig",
            name="require_region",
            field=models.BooleanField(
                default=False, help_text="Whether region is required for passports"
            ),
        ),
        migrations.AlterField(
            model_name="gameprofileconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="game_profiles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="DEPRECATED: Use GameProfile model and GamePassportService instead. See GP-0 documentation.",
            ),
        ),
        migrations.AddIndex(
            model_name="gameprofile",
            index=models.Index(fields=["game", "identity_key"], name="user_profil_game_9bbb91_idx"),
        ),
        migrations.AddIndex(
            model_name="gameprofile",
            index=models.Index(
                fields=["-is_pinned", "-pinned_order"], name="user_profil_is_pinn_21c49c_idx"
            ),
        ),
    ]
