# Generated by Django 5.2.8 on 2025-12-25 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_make_tiebreakers_optional"),
        ("user_profile", "0022_alter_gameprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameprofile",
            name="game_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="Game from registry (source of truth) - migration field",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="passports",
                to="games.game",
            ),
        ),
        migrations.CreateModel(
            name="GamePassportSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identity_fields",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Required identity fields for this game.\n        Format: {\n            "riot_name": {"label": "Riot ID", "required": True, "max_length": 50},\n            "tagline": {"label": "Tagline", "required": True, "max_length": 5}\n        }\n        ',
                    ),
                ),
                (
                    "identity_format",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Format template (e.g., '{riot_name}#{tagline}' for Riot games)",
                        max_length=200,
                    ),
                ),
                (
                    "identity_key_format",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Normalization format for uniqueness check (e.g., '{riot_name_lower}#{tagline_lower}')",
                        max_length=200,
                    ),
                ),
                (
                    "region_choices",
                    models.JSONField(
                        default=list,
                        help_text='\n        Allowed region choices for this game.\n        Format: [\n            {"value": "NA", "label": "North America"},\n            {"value": "EU", "label": "Europe"}\n        ]\n        ',
                    ),
                ),
                (
                    "region_required",
                    models.BooleanField(
                        default=False, help_text="Whether region selection is mandatory"
                    ),
                ),
                (
                    "role_choices",
                    models.JSONField(
                        default=list,
                        help_text='\n        Available role choices for this game.\n        Format: [\n            {"value": "duelist", "label": "Duelist"},\n            {"value": "controller", "label": "Controller"}\n        ]\n        ',
                    ),
                ),
                (
                    "rank_system",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Rank system identifier (e.g., 'valorant_competitive', 'dota2_mmr')",
                        max_length=50,
                    ),
                ),
                (
                    "rank_choices",
                    models.JSONField(
                        default=list,
                        help_text='\n        Available rank choices for this game.\n        Format: [\n            {"value": "iron", "label": "Iron", "tier": 1},\n            {"value": "bronze", "label": "Bronze", "tier": 2}\n        ]\n        ',
                    ),
                ),
                (
                    "normalization_rules",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Rules for normalizing identity values.\n        Format: {\n            "riot_name": {"lowercase": true, "strip": true, "max_length": 50},\n            "tagline": {"lowercase": true, "strip": true, "max_length": 5}\n        }\n        ',
                    ),
                ),
                (
                    "platform_specific",
                    models.BooleanField(
                        default=False,
                        help_text="Whether identity is platform-specific (PC, Mobile, Console)",
                    ),
                ),
                (
                    "requires_verification",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this game requires external verification (for Phase 2+)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Admin notes about this schema configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.OneToOneField(
                        help_text="Game this schema applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport_schema",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Passport Schema",
                "verbose_name_plural": "Game Passport Schemas",
                "ordering": ["game__name"],
            },
        ),
    ]
