# Generated by Django 5.2.8 on 2025-12-25 04:59

from django.db import migrations


def populate_game_fk(apps, schema_editor):
    """
    Populate game_fk from existing game CharField values.
    Maps CharField slugs to Game.slug.
    """
    GameProfile = apps.get_model('user_profile', 'GameProfile')
    Game = apps.get_model('games', 'Game')
    
    # Get all GameProfile records with game CharField
    profiles = GameProfile.objects.all()
    
    updated_count = 0
    orphaned_count = 0
    
    for profile in profiles:
        game_slug = profile.game  # CharField value (e.g., 'valorant', 'cs2')
        
        try:
            # Find matching Game by slug
            game_obj = Game.objects.get(slug=game_slug)
            profile.game_fk = game_obj
            profile.save(update_fields=['game_fk'])
            updated_count += 1
        except Game.DoesNotExist:
            orphaned_count += 1
            print(f"WARNING: GameProfile {profile.id} has game='{game_slug}' but no matching Game record found")
    
    print(f"✅ Populated game_fk for {updated_count} GameProfile records")
    if orphaned_count > 0:
        print(f"⚠️  {orphaned_count} GameProfile records have orphaned game values (no matching Game)")


def reverse_populate(apps, schema_editor):
    """
    Reverse migration: clear game_fk values
    """
    GameProfile = apps.get_model('user_profile', 'GameProfile')
    GameProfile.objects.all().update(game_fk=None)


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_make_tiebreakers_optional"),
        ("user_profile", "0023_gp1_step1_add_schema_and_game_fk"),
    ]

    operations = [
        migrations.RunPython(populate_game_fk, reverse_populate),
    ]
