# Generated by Django 5.2.8 on 2025-12-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_make_tiebreakers_optional"),
        ("user_profile", "0024_gp1_step2_populate_game_fk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gameprofile",
            new_name="user_profil_user_id_4c45ec_idx",
            old_name="user_profil_user_id_8b5bc8_idx",
        ),
        migrations.RenameIndex(
            model_name="gameprofile",
            new_name="user_profil_game_id_0efce4_idx",
            old_name="user_profil_game_9bbb91_idx",
        ),
        migrations.RenameIndex(
            model_name="gameprofile",
            new_name="user_profil_game_id_2d881f_idx",
            old_name="user_profil_game_6957c4_idx",
        ),
        migrations.RemoveField(
            model_name="gameprofile",
            name="game_fk",
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="game",
            field=models.ForeignKey(
                help_text="Game from registry (source of truth)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="passports",
                to="games.game",
            ),
        ),
    ]
