# Generated by Django 5.2.8 on 2025-12-28 17:40

from django.db import migrations


def migrate_legacy_privacy_to_settings(apps, schema_editor):
    """
    Migrate any remaining legacy privacy field values to PrivacySettings.
    This is a safety migration - PrivacySettings should already be canonical.
    """
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    PrivacySettings = apps.get_model('user_profile', 'PrivacySettings')
    
    for profile in UserProfile.objects.all():
        privacy, created = PrivacySettings.objects.get_or_create(user_profile=profile)
        
        # Only migrate if PrivacySettings was just created (first time)
        if created:
            # Map legacy boolean fields to PrivacySettings granular fields
            privacy.show_real_name = getattr(profile, 'show_real_name', False)
            privacy.show_phone = getattr(profile, 'show_phone', False)
            privacy.show_email = getattr(profile, 'show_email', False)
            privacy.show_age = getattr(profile, 'show_age', True)
            privacy.show_gender = getattr(profile, 'show_gender', False)
            privacy.show_country = getattr(profile, 'show_country', True)
            privacy.show_social_links = getattr(profile, 'show_socials', True)
            
            # Set profile_visibility based on is_private
            if getattr(profile, 'is_private', False):
                privacy.profile_visibility = 'PRIVATE'
            else:
                privacy.profile_visibility = 'PUBLIC'
            
            privacy.save()


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0028_ensure_legacy_fields_removed_idempotent"),
    ]

    operations = [
        # Migrate data first (safety check)
        migrations.RunPython(
            migrate_legacy_privacy_to_settings,
            reverse_code=migrations.RunPython.noop,
        ),
        
        # Remove legacy privacy fields
        migrations.RemoveField(
            model_name='userprofile',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_socials',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_real_name',
        ),
    ]
