# Generated by Django 5.2.8 on 2025-12-28 17:40

from django.db import migrations


def migrate_legacy_privacy_to_settings(apps, schema_editor):
    """
    Migrate any remaining legacy privacy field values to PrivacySettings.
    This is a safety migration - PrivacySettings should already be canonical.
    
    UP-PHASE12: Use .only() to avoid querying dropped columns (riot_id was dropped in 0028).
    """
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    PrivacySettings = apps.get_model('user_profile', 'PrivacySettings')
    
    # UP-PHASE12: Specify only the fields we need to avoid querying dropped columns
    for profile in UserProfile.objects.only('id', 'user_id').all():
        privacy, created = PrivacySettings.objects.get_or_create(user_profile=profile)
        
        # UP-PHASE12: Legacy fields were already removed in 0028 - this is just a safety check
        # Since fields don't exist anymore, we skip the migration logic
        # PrivacySettings should already have correct defaults from model definition
        if created:
            # Just save with defaults - no legacy data to migrate
            privacy.save()


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0028_ensure_legacy_fields_removed_idempotent"),
    ]

    operations = [
        # Migrate data first (safety check)
        migrations.RunPython(
            migrate_legacy_privacy_to_settings,
            reverse_code=migrations.RunPython.noop,
        ),
        
        # Remove legacy privacy fields
        migrations.RemoveField(
            model_name='userprofile',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_socials',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_real_name',
        ),
    ]
