# Generated by Django 5.2.8 on 2025-12-29 04:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0029_remove_legacy_privacy_fields"),
    ]

    operations = [
        # NOTE: Removed RemoveField operations for game ID fields (codm_uid, ea_id, etc.)
        # These fields don't exist in the database - they were removed in earlier migrations
        # Keeping this comment for clarity on why operations list starts with AddField
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("bn", "Bengali (Coming Soon)")],
                default="en",
                help_text="Preferred UI language",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="dark",
                help_text="UI theme preference",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="time_format",
            field=models.CharField(
                choices=[("12h", "12-hour (3:00 PM)"), ("24h", "24-hour (15:00)")],
                default="12h",
                help_text="Preferred time display format",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone_pref",
            field=models.CharField(
                default="Asia/Dhaka",
                help_text="User's preferred timezone for displaying times (e.g., 'Asia/Dhaka', 'UTC')",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email_tournament_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Send email reminders for upcoming tournaments you're registered for",
                    ),
                ),
                (
                    "email_match_results",
                    models.BooleanField(
                        default=True,
                        help_text="Send email notifications when match results are published",
                    ),
                ),
                (
                    "email_team_invites",
                    models.BooleanField(
                        default=True, help_text="Send email when invited to join a team"
                    ),
                ),
                (
                    "email_achievements",
                    models.BooleanField(
                        default=False,
                        help_text="Send email when you unlock new achievements or badges",
                    ),
                ),
                (
                    "email_platform_updates",
                    models.BooleanField(
                        default=True,
                        help_text="Send email about platform updates, new features, and announcements",
                    ),
                ),
                (
                    "notify_tournament_start",
                    models.BooleanField(
                        default=True,
                        help_text="Show notification when a tournament you're in starts",
                    ),
                ),
                (
                    "notify_team_messages",
                    models.BooleanField(
                        default=True, help_text="Show notification for new team messages"
                    ),
                ),
                (
                    "notify_follows",
                    models.BooleanField(
                        default=True, help_text="Show notification when someone follows you"
                    ),
                ),
                (
                    "notify_achievements",
                    models.BooleanField(
                        default=True,
                        help_text="Show notification popup when unlocking achievements",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        help_text="User profile these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preferences",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "user_profile_notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="WalletSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "bkash_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable bKash as withdrawal method"
                    ),
                ),
                (
                    "bkash_account",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="bKash account number (11-digit BD mobile number)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Bangladeshi mobile number (e.g., 01712345678)",
                                regex="^01[3-9]\\d{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "nagad_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable Nagad as withdrawal method"
                    ),
                ),
                (
                    "nagad_account",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nagad account number (11-digit BD mobile number)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Bangladeshi mobile number (e.g., 01712345678)",
                                regex="^01[3-9]\\d{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "rocket_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable Rocket as withdrawal method"
                    ),
                ),
                (
                    "rocket_account",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Rocket account number (11-digit BD mobile number)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Bangladeshi mobile number (e.g., 01712345678)",
                                regex="^01[3-9]\\d{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "auto_withdrawal_threshold",
                    models.IntegerField(
                        default=0,
                        help_text="Automatically withdraw when balance reaches this threshold (DeltaCoins). 0 = manual withdrawals only",
                    ),
                ),
                (
                    "auto_convert_to_usd",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically convert DeltaCoins to USD when withdrawing (subject to conversion rates)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        help_text="User profile these wallet settings belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_settings",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Settings",
                "verbose_name_plural": "Wallet Settings",
                "db_table": "user_profile_wallet_settings",
            },
        ),
    ]
