# Generated by Django 5.2.8 on 2025-12-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0030_phase6c_settings_models"),
    ]

    operations = [
        # UP-PHASE14C: Add ProfileShowcase model for Facebook-style About section
        migrations.CreateModel(
            name="ProfileShowcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "enabled_sections",
                    models.JSONField(
                        default=list,
                        help_text="List of enabled About subsections: ['identity', 'demographics', 'contact', 'gaming', 'social', 'competitive']",
                    ),
                ),
                (
                    "featured_team_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of featured team (if user wants to highlight their current team)",
                        null=True,
                    ),
                ),
                (
                    "featured_team_role",
                    models.CharField(
                        blank=True,
                        help_text="Role in featured team (e.g., 'Team Captain', 'IGL', 'Fragger')",
                        max_length=50,
                    ),
                ),
                (
                    "featured_passport_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of featured game passport (user's main game)",
                        null=True,
                    ),
                ),
                (
                    "highlights",
                    models.JSONField(
                        default=list,
                        help_text="List of highlight items: [{'type': 'tournament', 'id': 123, 'label': 'Champions 2024 Winner', 'icon': '🏆'}]",
                    ),
                ),
                (
                    "section_order",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Custom section order if user wants non-default arrangement",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showcase",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Showcase",
                "verbose_name_plural": "Profile Showcases",
                "db_table": "user_profile_showcase",
            },
        ),
    ]
