# Generated by Django 5.2.8 on 2025-12-29 17:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0031_add_profile_showcase_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="codm_uid",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="ea_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="efootball_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="free_fire_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="mlbb_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="mlbb_server_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="pubg_mobile_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="riot_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="riot_tagline",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="steam_id",
        ),
        migrations.CreateModel(
            name="ProfileAboutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when this record was last updated"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("team", "Team Role"),
                            ("game", "Game Passport"),
                            ("achievement", "Achievement"),
                            ("stat", "Stat Highlight"),
                            ("bio", "Bio Line"),
                            ("custom", "Custom Text"),
                        ],
                        help_text="Type of About item",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("followers_only", "Followers Only"),
                            ("private", "Private (Only Me)"),
                        ],
                        default="public",
                        help_text="Who can see this item",
                        max_length=20,
                    ),
                ),
                (
                    "source_model",
                    models.CharField(
                        blank=True,
                        help_text="Source model name (Team, GameProfile, UserBadge, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="Source object ID", null=True
                    ),
                ),
                (
                    "display_text",
                    models.CharField(
                        help_text="Text to display (auto-generated or user-provided)",
                        max_length=200,
                    ),
                ),
                (
                    "icon_emoji",
                    models.CharField(
                        blank=True,
                        help_text="Optional emoji icon (🎮, 🏆, 💼, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (0 = first)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is currently visible"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        help_text="Profile this About item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_items",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile About Item",
                "verbose_name_plural": "Profile About Items",
                "db_table": "user_profile_about_item",
                "ordering": ["user_profile", "order_index", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_profile", "is_active", "order_index"],
                        name="user_profil_user_pr_c20dce_idx",
                    ),
                    models.Index(
                        fields=["user_profile", "item_type"], name="user_profil_user_pr_d7c270_idx"
                    ),
                ],
            },
        ),
    ]
