# Generated by Django 5.2.8 on 2026-03-12 11:06

import apps.user_profile.models_main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0031_fix_tournament_field_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwareloadout",
            name="loadout_public",
            field=models.BooleanField(default=True, help_text="Show loadout on public profile"),
        ),
        migrations.AddField(
            model_name="hardwareloadout",
            name="mouse_dpi",
            field=models.PositiveIntegerField(
                blank=True, help_text="Mouse DPI setting (e.g., 800)", null=True
            ),
        ),
        migrations.AddField(
            model_name="hardwareloadout",
            name="sensitivity",
            field=models.CharField(
                blank=True,
                default="",
                help_text="In-game sensitivity (e.g., '0.45')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_back",
            field=models.ImageField(
                blank=True,
                help_text="Back side of government-issued ID",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_front",
            field=models.ImageField(
                blank=True,
                help_text="Front side of government-issued ID (NID, Passport, Driver's License)",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="selfie_with_id",
            field=models.ImageField(
                blank=True,
                help_text="Selfie holding the ID document for liveness verification",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
    ]
