# Generated by Django 5.2.8 on 2026-03-12 13:26

import apps.user_profile.models_main
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_id_label_fields"),
        ("organizations", "0037_add_team_follower"),
        ("tournaments", "0033_add_evidence_file_fields"),
        ("user_profile", "0032_add_loadout_dpi_sensitivity_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="acceptor_team",
            field=models.ForeignKey(
                blank=True,
                help_text="Acceptor's team (set on accept for team bounties)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_bounties",
                to="organizations.team",
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="challenge_type",
            field=models.CharField(
                choices=[("solo", "Player vs Player"), ("team", "Team vs Team")],
                db_index=True,
                default="solo",
                help_text="Solo (1v1) or Team (roster vs roster)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="creator_team",
            field=models.ForeignKey(
                blank=True,
                help_text="Creator's team (required for team bounties)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bounties",
                to="organizations.team",
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="target_team",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, only this team can accept (private team challenge)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_bounties",
                to="organizations.team",
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_back",
            field=models.ImageField(
                blank=True,
                help_text="Back side of government-issued ID",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_front",
            field=models.ImageField(
                blank=True,
                help_text="Front side of government-issued ID (NID, Passport, Driver's License)",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="selfie_with_id",
            field=models.ImageField(
                blank=True,
                help_text="Selfie holding the ID document for liveness verification",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(
                fields=["challenge_type", "status"], name="user_profil_challen_8605ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(
                fields=["creator_team", "status"], name="user_profil_creator_3239a8_idx"
            ),
        ),
    ]
