# Generated by Django 5.2.8 on 2025-12-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0032_add_profile_about_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="stream_status",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if user is currently streaming (grants XP bonuses)",
            ),
        ),
    ]
