# Generated by Django 5.2.8 on 2025-12-31 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_game_available_ranks_game_has_rank_system_and_more"),
        ("user_profile", "0033_alter_userprofile_stream_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HighlightClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "clip_url",
                    models.URLField(
                        help_text="YouTube, Twitch clip, or Medal.tv URL", max_length=500
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("twitch", "Twitch"),
                            ("medal", "Medal.tv"),
                        ],
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        editable=False, help_text="Video/clip identifier", max_length=200
                    ),
                ),
                (
                    "embed_url",
                    models.URLField(
                        editable=False,
                        help_text="Safe iframe embed URL (auto-generated)",
                        max_length=500,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        editable=False,
                        help_text="Video thumbnail (auto-generated)",
                        max_length=500,
                    ),
                ),
                ("title", models.CharField(help_text="Clip title/description", max_length=200)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Display order on profile (lower = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        help_text="Game featured in this clip",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="highlight_clips",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlight_clips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Highlight Clip",
                "verbose_name_plural": "Highlight Clips",
                "db_table": "user_profile_highlight_clip",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PinnedHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pinned_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this clip was pinned"),
                ),
                (
                    "clip",
                    models.ForeignKey(
                        help_text="The highlighted clip being pinned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_by",
                        to="user_profile.highlightclip",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who pinned this clip",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_highlight",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pinned Highlight",
                "verbose_name_plural": "Pinned Highlights",
                "db_table": "user_profile_pinned_highlight",
            },
        ),
        migrations.CreateModel(
            name="StreamConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "stream_url",
                    models.URLField(
                        help_text="Twitch, YouTube, or Facebook stream URL", max_length=500
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitch", "Twitch"),
                            ("youtube", "YouTube"),
                            ("facebook", "Facebook Gaming"),
                        ],
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        editable=False, help_text="Username or channel identifier", max_length=200
                    ),
                ),
                (
                    "embed_url",
                    models.URLField(
                        editable=False,
                        help_text="Safe iframe embed URL (auto-generated)",
                        max_length=500,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", help_text="Optional stream title", max_length=200
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show stream on profile"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stream Configuration",
                "verbose_name_plural": "Stream Configurations",
                "db_table": "user_profile_stream_config",
            },
        ),
        migrations.AddIndex(
            model_name="highlightclip",
            index=models.Index(
                fields=["user", "display_order"], name="user_profil_user_id_70caa8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="highlightclip",
            index=models.Index(fields=["platform"], name="user_profil_platfor_1975d9_idx"),
        ),
        migrations.AddIndex(
            model_name="highlightclip",
            index=models.Index(fields=["game"], name="user_profil_game_id_7b125a_idx"),
        ),
        migrations.AddIndex(
            model_name="pinnedhighlight",
            index=models.Index(fields=["user"], name="user_profil_user_id_25f975_idx"),
        ),
        migrations.AddIndex(
            model_name="streamconfig",
            index=models.Index(fields=["user", "is_active"], name="user_profil_user_id_20ffb5_idx"),
        ),
        migrations.AddIndex(
            model_name="streamconfig",
            index=models.Index(fields=["platform"], name="user_profil_platfor_b46305_idx"),
        ),
    ]
