# Generated by Django 5.2.8 on 2025-12-31 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_game_available_ranks_game_has_rank_system_and_more"),
        ("user_profile", "0034_p0_media_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict,
                        help_text="Game-specific configuration (sensitivity, crosshair, keybinds, etc.)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Show on public profile (owner-only if False)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this config (e.g., 'Tournament setup')",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game this configuration applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_configs",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Configuration",
                "verbose_name_plural": "Game Configurations",
                "db_table": "user_profile_game_config",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["user", "game"], name="user_profil_user_id_37aa2b_idx"),
                    models.Index(
                        fields=["game", "is_public"], name="user_profil_game_id_458c33_idx"
                    ),
                    models.Index(
                        fields=["user", "is_public"], name="user_profil_user_id_2786f2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "game"), name="unique_game_config_per_user_per_game"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HardwareGear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MOUSE", "Mouse"),
                            ("KEYBOARD", "Keyboard"),
                            ("HEADSET", "Headset"),
                            ("MONITOR", "Monitor"),
                            ("MOUSEPAD", "Mousepad"),
                        ],
                        help_text="Hardware category (mouse, keyboard, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Brand name (e.g., Logitech, Razer, SteelSeries)", max_length=100
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Product model (e.g., G Pro X Superlight)", max_length=200
                    ),
                ),
                (
                    "specs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Hardware specifications (DPI, polling rate, weight, etc.)",
                    ),
                ),
                (
                    "purchase_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional purchase link (affiliate URL)",
                        max_length=500,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Show on public profile (owner-only if False)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware_gear",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hardware Gear",
                "verbose_name_plural": "Hardware Gear",
                "db_table": "user_profile_hardware_gear",
                "ordering": ["category", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "category"], name="user_profil_user_id_d9c6d8_idx"
                    ),
                    models.Index(fields=["brand", "model"], name="user_profil_brand_27f9b7_idx"),
                    models.Index(
                        fields=["category", "is_public"], name="user_profil_categor_e82a23_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "category"), name="unique_hardware_per_category_per_user"
                    )
                ],
            },
        ),
    ]
