# Generated by Django 5.2.8 on 2025-12-31 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0035_p0_loadout_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrophyShowcaseConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "border",
                    models.CharField(
                        choices=[
                            ("none", "No Border"),
                            ("bronze", "Bronze Border"),
                            ("silver", "Silver Border"),
                            ("gold", "Gold Border"),
                            ("platinum", "Platinum Border"),
                            ("diamond", "Diamond Border"),
                            ("master", "Master Border"),
                        ],
                        default="none",
                        help_text="Selected profile border (must be unlocked)",
                        max_length=20,
                    ),
                ),
                (
                    "frame",
                    models.CharField(
                        choices=[
                            ("none", "No Frame"),
                            ("competitor", "Competitor Frame"),
                            ("finalist", "Finalist Frame"),
                            ("champion", "Champion Frame"),
                            ("grand_champion", "Grand Champion Frame"),
                            ("legend", "Legend Frame"),
                        ],
                        default="none",
                        help_text="Selected profile frame (must be unlocked)",
                        max_length=20,
                    ),
                ),
                (
                    "pinned_badge_ids",
                    models.JSONField(
                        default=list, help_text="List of UserBadge IDs to display (max 5)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trophy_showcase",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trophy Showcase Config",
                "verbose_name_plural": "Trophy Showcase Configs",
                "db_table": "user_profile_trophy_showcase",
            },
        ),
    ]
