# Generated by Django 5.2.8 on 2025-12-31 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0030_add_is_featured_to_tournament"),
        ("user_profile", "0036_p0_trophy_showcase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EndorsementOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When endorsement window closes (24 hours after match completion)",
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Player has given endorsement for this match",
                        verbose_name="Used",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When player gave endorsement",
                        null=True,
                        verbose_name="Used At",
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(
                        default=False,
                        help_text="Player was notified of endorsement opportunity",
                        verbose_name="Notified",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When notification was sent",
                        null=True,
                        verbose_name="Notified At",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsement_opportunities",
                        to="tournaments.match",
                        verbose_name="Match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        help_text="Player who can give endorsement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsement_opportunities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endorsement Opportunity",
                "verbose_name_plural": "Endorsement Opportunities",
                "db_table": "user_profile_endorsement_opportunity",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["expires_at", "is_used"], name="user_profil_expires_630798_idx"
                    ),
                    models.Index(
                        fields=["player", "is_used", "expires_at"],
                        name="user_profil_player__6b9b5a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "player"), name="unique_opportunity_per_match_player"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SkillEndorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        choices=[
                            ("shotcalling", "Shotcalling"),
                            ("aim", "Aim"),
                            ("clutch", "Clutch"),
                            ("support", "Support"),
                            ("igl", "IGL (In-Game Leader)"),
                            ("entry_fragging", "Entry Fragging"),
                        ],
                        db_index=True,
                        help_text="Recognized skill category",
                        max_length=20,
                        verbose_name="Skill",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional endorsement message (max 500 chars)",
                        max_length=500,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When endorsement was awarded",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of endorser (for fraud detection)",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser user agent (for fraud detection)",
                        max_length=500,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        default=False,
                        help_text="Endorsement flagged for review (spam/manipulation)",
                        verbose_name="Flagged",
                    ),
                ),
                (
                    "flag_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for flagging (moderator notes)",
                        verbose_name="Flag Reason",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When endorsement was reviewed",
                        null=True,
                        verbose_name="Reviewed At",
                    ),
                ),
                (
                    "endorser",
                    models.ForeignKey(
                        help_text="Player who gave the endorsement (teammate)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Endorser",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        help_text="Tournament match where skill was recognized",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_endorsements",
                        to="tournaments.match",
                        verbose_name="Match",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="Player who received the endorsement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderator who reviewed flagged endorsement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endorsements_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Endorsement",
                "verbose_name_plural": "Skill Endorsements",
                "db_table": "user_profile_skill_endorsement",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["receiver", "-created_at"], name="user_profil_receive_a4e8c9_idx"
                    ),
                    models.Index(
                        fields=["match", "created_at"], name="user_profil_match_i_8b9e49_idx"
                    ),
                    models.Index(
                        fields=["receiver", "skill_name"], name="user_profil_receive_2d9b44_idx"
                    ),
                    models.Index(
                        fields=["is_flagged", "created_at"], name="user_profil_is_flag_148abd_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "endorser"), name="unique_endorsement_per_match_endorser"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("endorser", models.F("receiver")), _negated=True),
                        name="no_self_endorsement",
                    ),
                ],
            },
        ),
    ]
