# Generated by Django 5.2.8 on 2025-12-31 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0030_add_is_featured_to_tournament"),
        ("user_profile", "0037_p0_skill_endorsements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bounty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Challenge title (e.g., 'First to 100k in Gridshot')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed challenge requirements and rules"
                    ),
                ),
                (
                    "stake_amount",
                    models.IntegerField(help_text="DeltaCoins locked in escrow (creator's stake)"),
                ),
                (
                    "payout_amount",
                    models.IntegerField(
                        blank=True, help_text="Actual payout to winner (stake * 0.95)", null=True
                    ),
                ),
                (
                    "platform_fee",
                    models.IntegerField(
                        blank=True, help_text="Platform fee retained (stake * 0.05)", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("pending_result", "Pending Result"),
                            ("disputed", "Disputed"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When match started (IN_PROGRESS)", null=True
                    ),
                ),
                ("result_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="Auto-refund if still OPEN after this timestamp"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "acceptor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who accepted the challenge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_bounties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User who created and funded the bounty",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_bounties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game for this challenge",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tournaments.game",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to tournament match if used",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bounties",
                        to="tournaments.match",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, only this user can accept (private challenge)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_bounties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Final winner after verification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_bounties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bounty",
                "verbose_name_plural": "Bounties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BountyProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "proof_url",
                    models.URLField(
                        help_text="Screenshot or video URL (Imgur, YouTube, etc.)", max_length=500
                    ),
                ),
                (
                    "proof_type",
                    models.CharField(
                        choices=[
                            ("screenshot", "Screenshot"),
                            ("video", "Video"),
                            ("replay", "Replay File"),
                        ],
                        default="screenshot",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Additional context for proof"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "bounty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="user_profile.bounty",
                    ),
                ),
                (
                    "claimed_winner",
                    models.ForeignKey(
                        help_text="User claimed as winner in this proof",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bounty_win_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bounty_proofs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bounty Proof",
                "verbose_name_plural": "Bounty Proofs",
                "ordering": ["submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="BountyAcceptance",
            fields=[
                (
                    "bounty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="acceptance",
                        serialize=False,
                        to="user_profile.bounty",
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "acceptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bounty_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bounty Acceptance",
                "verbose_name_plural": "Bounty Acceptances",
            },
        ),
        migrations.CreateModel(
            name="BountyDispute",
            fields=[
                (
                    "bounty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="dispute",
                        serialize=False,
                        to="user_profile.bounty",
                    ),
                ),
                ("reason", models.TextField(help_text="Why the result is disputed")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("resolved_confirm", "Resolved - Confirmed Winner"),
                            ("resolved_reverse", "Resolved - Reversed Winner"),
                            ("resolved_void", "Resolved - Match Voided"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("moderator_notes", models.TextField(blank=True)),
                (
                    "resolution",
                    models.TextField(
                        blank=True, help_text="Moderator's final decision explanation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_moderator",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_bounty_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disputer",
                    models.ForeignKey(
                        help_text="User who raised the dispute",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bounty_disputes_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bounty Dispute",
                "verbose_name_plural": "Bounty Disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(
                fields=["status", "expires_at"], name="user_profil_status_c29cf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(fields=["creator", "status"], name="user_profil_creator_46af72_idx"),
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(
                fields=["acceptor", "status"], name="user_profil_accepto_c96449_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(fields=["game", "status"], name="user_profil_game_id_a39717_idx"),
        ),
        migrations.AddIndex(
            model_name="bountyproof",
            index=models.Index(
                fields=["bounty", "submitted_at"], name="user_profil_bounty__92928e_idx"
            ),
        ),
    ]
