# Generated by Django 5.2.8 on 2025-12-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0038_p0_bounty_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trophyshowcaseconfig",
            name="pinned_badge_ids",
            field=models.JSONField(
                blank=True, default=list, help_text="List of UserBadge IDs to display (max 5)"
            ),
        ),
    ]
