# Generated by Django 5.2.8 on 2025-12-31 14:17

from django.db import migrations


def normalize_null_badge_ids(apps, schema_editor):
    """
    Normalize NULL pinned_badge_ids to empty arrays.
    
    This fixes existing TrophyShowcaseConfig rows that may have
    NULL values in pinned_badge_ids, which would cause validation errors.
    """
    TrophyShowcaseConfig = apps.get_model('user_profile', 'TrophyShowcaseConfig')
    
    # Update all rows where pinned_badge_ids is None or not a list
    for showcase in TrophyShowcaseConfig.objects.all():
        if showcase.pinned_badge_ids is None or not isinstance(showcase.pinned_badge_ids, list):
            showcase.pinned_badge_ids = []
            showcase.save(update_fields=['pinned_badge_ids'])


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0039_fix_trophy_showcase_blank_badges"),
    ]

    operations = [
        migrations.RunPython(
            normalize_null_badge_ids,
            reverse_code=migrations.RunPython.noop
        ),
    ]
