# Generated by Django 5.2.8 on 2025-12-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0040_normalize_trophy_showcase_null_badges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highlightclip",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                editable=False,
                help_text="Video thumbnail (auto-generated, may be NULL if unavailable)",
                max_length=500,
                null=True,
            ),
        ),
    ]
