# Generated by Django 5.2.8 on 2026-03-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0040_reset_verification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameprofile",
            name="preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User-controlled preferences (main_role, preferred_region, display options). Never populated by automated sync jobs.",
            ),
        ),
        migrations.AddField(
            model_name="gameprofile",
            name="provider_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Verified data written exclusively by OAuth/API services. Fields here are locked from user editing. Namespaced by provider key: {'steam': {...}, 'riot': {...}}.",
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="DEPRECATED for identity storage. Use provider_data for OAuth fields and preferences for user choices.",
            ),
        ),
    ]
