# Generated by Django 5.2.8 on 2026-03-19 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0041_gameprofile_provider_data_preferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("riot", "Riot Games"),
                            ("steam", "Steam"),
                            ("epic", "Epic Games"),
                        ],
                        db_index=True,
                        help_text="OAuth provider name",
                        max_length=32,
                    ),
                ),
                (
                    "provider_account_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stable provider-side account identifier (Steam64 ID, Riot PUUID, etc.)",
                        max_length=191,
                    ),
                ),
                (
                    "provider_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw verified provider profile data (persona_name, avatar, etc.).",
                    ),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Provider Account",
                "verbose_name_plural": "Provider Accounts",
                "db_table": "user_profile_provider_account",
            },
        ),
        migrations.RemoveIndex(
            model_name="gameoauthconnection",
            name="user_profil_passpor_b3b121_idx",
        ),
        migrations.RemoveField(
            model_name="gameoauthconnection",
            name="provider_account_id",
        ),
        migrations.AddField(
            model_name="gameoauthconnection",
            name="game_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked game passport (Phase 2+)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth_connections",
                to="user_profile.gameprofile",
            ),
        ),
        migrations.AlterField(
            model_name="gameoauthconnection",
            name="passport",
            field=models.OneToOneField(
                blank=True,
                help_text="DEPRECATED — use game_profile. Kept nullable for backward compatibility.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oauth_connection",
                to="user_profile.gameprofile",
            ),
        ),
        migrations.AlterField(
            model_name="gameoauthconnection",
            name="provider",
            field=models.CharField(
                choices=[("riot", "Riot Games"), ("steam", "Steam"), ("epic", "Epic Games")],
                db_index=True,
                help_text="OAuth provider name (denormalized from ProviderAccount for fast filtering)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="provideraccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gameoauthconnection",
            name="provider_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Provider identity anchor",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_connections",
                to="user_profile.provideraccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameoauthconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("game_profile__isnull", False), ("provider_account__isnull", False)
                ),
                fields=("provider_account", "game_profile"),
                name="user_profil_prov_game_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="provideraccount",
            index=models.Index(fields=["user", "provider"], name="user_profil_prov_user_prov_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="provideraccount",
            unique_together={("provider", "provider_account_id")},
        ),
    ]
