# Generated by Django 5.2.8 on 2025-12-31 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0030_add_is_featured_to_tournament"),
        ("user_profile", "0041_make_highlight_thumbnail_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="skillendorsement",
            name="unique_endorsement_per_match_endorser",
        ),
        migrations.AddField(
            model_name="skillendorsement",
            name="bounty",
            field=models.ForeignKey(
                blank=True,
                help_text="Bounty match where skill was recognized",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_endorsements",
                to="user_profile.bounty",
                verbose_name="Bounty",
            ),
        ),
        migrations.AlterField(
            model_name="skillendorsement",
            name="match",
            field=models.ForeignKey(
                blank=True,
                help_text="Tournament match where skill was recognized",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_endorsements",
                to="tournaments.match",
                verbose_name="Match",
            ),
        ),
        migrations.AddIndex(
            model_name="skillendorsement",
            index=models.Index(
                fields=["bounty", "created_at"], name="user_profil_bounty__56048f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="skillendorsement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("match__isnull", False)),
                fields=("match", "endorser"),
                name="unique_endorsement_per_match_endorser",
            ),
        ),
        migrations.AddConstraint(
            model_name="skillendorsement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bounty__isnull", False)),
                fields=("bounty", "endorser"),
                name="unique_endorsement_per_bounty_endorser",
            ),
        ),
        migrations.AddConstraint(
            model_name="skillendorsement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("bounty__isnull", True), ("match__isnull", False)),
                    models.Q(("bounty__isnull", False), ("match__isnull", True)),
                    _connector="OR",
                ),
                name="endorsement_has_match_or_bounty",
            ),
        ),
    ]
