# Generated by Django 5.2.8 on 2026-04-11 08:28

import apps.common.validators
import apps.user_profile.models_main
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0042_provideraccount_oauth_connection_m2m"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="image",
            field=models.ImageField(
                help_text="Full certificate image",
                upload_to="certificates/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="rank_image",
            field=models.ImageField(
                blank=True,
                help_text="Rank badge image",
                null=True,
                upload_to="rank_images/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="document_back",
            field=models.ImageField(
                blank=True,
                help_text="Back side of the identity document (if applicable)",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="document_front",
            field=models.ImageField(
                help_text="Front side of the identity document",
                upload_to=apps.user_profile.models_main.kyc_document_path,
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="selfie_with_document",
            field=models.ImageField(
                blank=True,
                help_text="Selfie holding the document for verification",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.user_profile.models_main.user_avatar_path,
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Profile banner image",
                null=True,
                upload_to=apps.user_profile.models_main.user_banner_path,
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_back",
            field=models.ImageField(
                blank=True,
                help_text="Back side of government-issued ID",
                null=True,
                upload_to=apps.user_profile.models_main.verification_kyc_document_path,
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_front",
            field=models.ImageField(
                blank=True,
                help_text="Front side of government-issued ID (NID, Passport, Driver's License)",
                null=True,
                upload_to=apps.user_profile.models_main.verification_kyc_document_path,
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="selfie_with_id",
            field=models.ImageField(
                blank=True,
                help_text="Selfie holding the ID document for liveness verification",
                null=True,
                upload_to=apps.user_profile.models_main.verification_kyc_document_path,
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
    ]
