# Generated by Django 5.2.8 on 2026-01-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0043_add_follower_privacy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privacysettings",
            name="followers_list_visibility",
        ),
        migrations.RemoveField(
            model_name="privacysettings",
            name="following_list_visibility",
        ),
        migrations.RemoveField(
            model_name="privacysettings",
            name="show_followers_count",
        ),
        migrations.RemoveField(
            model_name="privacysettings",
            name="show_following_count",
        ),
    ]
