# Generated by Django 5.2.8 on 2026-01-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0044_remove_privacysettings_followers_list_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privacysettings",
            name="show_followers_count",
            field=models.BooleanField(default=True, help_text="Show follower count on profile"),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="show_followers_list",
            field=models.BooleanField(default=True, help_text="Allow viewing list of followers"),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="show_following_count",
            field=models.BooleanField(default=True, help_text="Show following count on profile"),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="show_following_list",
            field=models.BooleanField(
                default=True, help_text="Allow viewing list of users being followed"
            ),
        ),
    ]
