# Generated by Django 5.2.8 on 2026-05-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0044_gameprofile_riot_verification_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameprofile",
            name="verification_error",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User-safe error reason for failed/unavailable verification. Never expose raw API errors here.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Verification"),
                    ("VERIFIED", "Verified"),
                    ("FLAGGED", "Flagged for Review"),
                    ("FAILED", "Failed — Invalid ID"),
                    ("API_UNAVAILABLE", "API Unavailable — Retry Queued"),
                    ("RATE_LIMITED", "Rate Limited — Retry Queued"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Verification pipeline status: PENDING → VERIFIED or FLAGGED",
                max_length=20,
            ),
        ),
    ]
