# Generated by Django 5.2.8 on 2026-01-02 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0045_add_follower_privacy_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "career_status",
                    models.CharField(
                        choices=[
                            ("SIGNED", "Signed to Team"),
                            ("FREE_AGENT", "Free Agent"),
                            ("LOOKING", "Actively Looking"),
                            ("NOT_LOOKING", "Not Looking"),
                        ],
                        default="NOT_LOOKING",
                        help_text="Current recruitment status",
                        max_length=20,
                    ),
                ),
                (
                    "lft_enabled",
                    models.BooleanField(
                        default=False, help_text="Show 'Looking for Team' badge on profile"
                    ),
                ),
                (
                    "primary_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Primary esports roles (IGL, Duelist, Support, etc.)",
                    ),
                ),
                (
                    "secondary_roles",
                    models.JSONField(
                        blank=True, default=list, help_text="Secondary roles willing to play"
                    ),
                ),
                (
                    "preferred_region",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Preferred region for teams (e.g., NA, EU, AS)",
                        max_length=10,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("WEEKENDS", "Weekends Only"),
                            ("CUSTOM", "Custom Schedule"),
                        ],
                        default="PART_TIME",
                        help_text="Time commitment availability",
                        max_length=20,
                    ),
                ),
                (
                    "salary_expectation_min",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimum monthly salary expectation (in local currency or DC)",
                        null=True,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("TEAM", "Team Contract"),
                            ("ORG", "Organization Contract"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("STREAMING", "Streaming/Content"),
                        ],
                        default="TEAM",
                        help_text="Preferred contract type",
                        max_length=20,
                    ),
                ),
                (
                    "recruiter_visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public (Anyone)"),
                            ("VERIFIED_SCOUTS", "Verified Scouts Only"),
                            ("PRIVATE", "Private (Hidden)"),
                        ],
                        default="PUBLIC",
                        help_text="Who can view career profile",
                        max_length=20,
                    ),
                ),
                (
                    "allow_direct_contracts",
                    models.BooleanField(
                        default=True, help_text="Allow managers to send draft contracts via DM"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_profile",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Career Profile",
                "verbose_name_plural": "Career Profiles",
                "db_table": "user_profile_career_profile",
            },
        ),
        migrations.CreateModel(
            name="MatchmakingPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Accept matchmaking/bounty challenges"
                    ),
                ),
                (
                    "games_enabled",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of game slugs enabled for matchmaking (e.g., ['valorant', 'cs2'])",
                    ),
                ),
                (
                    "preferred_modes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Preferred game modes (e.g., ['ranked', '1v1', 'team'])",
                    ),
                ),
                (
                    "min_bounty",
                    models.IntegerField(
                        blank=True, help_text="Minimum bounty amount (DC) to consider", null=True
                    ),
                ),
                (
                    "max_bounty",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum bounty amount (DC) - for risk management",
                        null=True,
                    ),
                ),
                (
                    "auto_accept",
                    models.BooleanField(
                        default=False, help_text="Auto-accept challenges meeting criteria"
                    ),
                ),
                (
                    "auto_reject_below_min",
                    models.BooleanField(
                        default=False, help_text="Auto-reject challenges below min_bounty"
                    ),
                ),
                (
                    "region_lock",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Only accept challenges from specific region (empty = any)",
                        max_length=10,
                    ),
                ),
                (
                    "skill_range_min",
                    models.IntegerField(
                        blank=True, help_text="Minimum skill rating of opponents", null=True
                    ),
                ),
                (
                    "skill_range_max",
                    models.IntegerField(
                        blank=True, help_text="Maximum skill rating of opponents", null=True
                    ),
                ),
                (
                    "allow_team_bounties",
                    models.BooleanField(
                        default=True, help_text="Accept team vs team bounty challenges"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchmaking_prefs",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matchmaking Preferences",
                "verbose_name_plural": "Matchmaking Preferences",
                "db_table": "user_profile_matchmaking_preferences",
            },
        ),
    ]
