# Generated by Django 5.2.8 on 2026-05-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_rename_games_media_status_elig_idx_games_media_status_21cd18_idx_and_more"),
        ("user_profile", "0045_alter_gameprofile_verification_error_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLoadoutProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "primary_platform",
                    models.CharField(
                        choices=[
                            ("PC", "PC"),
                            ("MOBILE", "Mobile"),
                            ("CONSOLE", "Console"),
                            ("HYBRID", "Hybrid / Multiple"),
                        ],
                        default="PC",
                        max_length=10,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                        default="PUBLIC",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pro_loadout",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pro Loadout Profile",
                "db_table": "user_profile_user_loadout_profile",
            },
        ),
        migrations.CreateModel(
            name="LoadoutDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MOUSE", "Mouse"),
                            ("KEYBOARD", "Keyboard"),
                            ("HEADSET", "Headset"),
                            ("MONITOR", "Monitor"),
                            ("CONTROLLER", "Controller"),
                            ("MOBILE_DEVICE", "Mobile Device"),
                            ("TABLET", "Tablet"),
                            ("CONSOLE", "Console"),
                            ("MICROPHONE", "Microphone"),
                            ("CHAIR", "Chair"),
                            ("MOUSEPAD", "Mousepad"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                ("model_name", models.CharField(blank=True, default="", max_length=200)),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loadout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="user_profile.userloadoutprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loadout Device",
                "db_table": "user_profile_loadout_device",
                "ordering": ["order", "category"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievementPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "registration_id",
                    models.PositiveIntegerField(
                        help_text="ID of the Tournament Registration that produced this achievement"
                    ),
                ),
                ("game_slug", models.CharField(blank=True, default="", max_length=50)),
                (
                    "is_hidden",
                    models.BooleanField(default=False, help_text="Hide from public profile"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Show in sidebar Trophy Cabinet"),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_preferences",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement Preference",
                "db_table": "user_profile_user_achievement_preference",
                "ordering": ["display_order", "-created_at"],
                "unique_together": {("user_profile", "registration_id")},
            },
        ),
        migrations.CreateModel(
            name="GameLoadoutSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("PC", "PC"), ("MOBILE", "Mobile"), ("CONSOLE", "Console")],
                        default="PC",
                        max_length=10,
                    ),
                ),
                ("mouse_dpi", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "in_game_sensitivity",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
                ),
                (
                    "scoped_sensitivity",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
                ),
                (
                    "ads_sensitivity",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
                ),
                ("crosshair_code", models.CharField(blank=True, default="", max_length=200)),
                ("resolution", models.CharField(blank=True, default="", max_length=20)),
                ("refresh_rate", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("fps_cap", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("graphics_quality", models.CharField(blank=True, default="", max_length=50)),
                ("gyro_enabled", models.BooleanField(blank=True, null=True)),
                (
                    "gyro_sensitivity",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("hud_code", models.CharField(blank=True, default="", max_length=200)),
                ("claw_style", models.CharField(blank=True, default="", max_length=50)),
                ("controller_model", models.CharField(blank=True, default="", max_length=100)),
                ("horizontal_sensitivity", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("vertical_sensitivity", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "deadzone_left",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                (
                    "deadzone_right",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("aim_assist", models.CharField(blank=True, default="", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                        default="PUBLIC",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pro_loadout_settings",
                        to="games.game",
                    ),
                ),
                (
                    "loadout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_settings",
                        to="user_profile.userloadoutprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Loadout Setting",
                "db_table": "user_profile_game_loadout_setting",
                "ordering": ["game__name", "platform"],
                "unique_together": {("loadout", "game", "platform")},
            },
        ),
    ]
