# Generated by Django 5.2.8 on 2026-01-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0046_careerprofile_matchmakingpreferences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationpreferences",
            name="email_achievements",
        ),
        migrations.RemoveField(
            model_name="notificationpreferences",
            name="email_match_results",
        ),
        migrations.RemoveField(
            model_name="notificationpreferences",
            name="email_platform_updates",
        ),
        migrations.RemoveField(
            model_name="notificationpreferences",
            name="email_team_invites",
        ),
        migrations.RemoveField(
            model_name="notificationpreferences",
            name="email_tournament_reminders",
        ),
        migrations.RemoveField(
            model_name="notificationpreferences",
            name="notify_achievements",
        ),
        migrations.RemoveField(
            model_name="notificationpreferences",
            name="notify_follows",
        ),
        migrations.RemoveField(
            model_name="notificationpreferences",
            name="notify_team_messages",
        ),
        migrations.RemoveField(
            model_name="notificationpreferences",
            name="notify_tournament_start",
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="email_enabled",
            field=models.BooleanField(default=True, help_text="Receive email notifications"),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="notif_bounties",
            field=models.BooleanField(
                default=True, help_text="Bounty updates (offers, acceptances, completions)"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="notif_messages",
            field=models.BooleanField(
                default=True, help_text="Direct messages and chat notifications"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="notif_system",
            field=models.BooleanField(
                default=True, help_text="System announcements and maintenance alerts"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="notif_teams",
            field=models.BooleanField(
                default=True, help_text="Team updates (invites, roster changes, promotions)"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="notif_tournaments",
            field=models.BooleanField(
                default=True, help_text="Tournament updates (registrations, matches, results)"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="push_enabled",
            field=models.BooleanField(
                default=True, help_text="Receive push notifications (browser/mobile)"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="quiet_hours_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable quiet hours (mute notifications during specified time)",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="quiet_hours_end",
            field=models.TimeField(
                blank=True, help_text="End time for quiet hours (e.g., 08:00)", null=True
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="quiet_hours_start",
            field=models.TimeField(
                blank=True, help_text="Start time for quiet hours (e.g., 22:00)", null=True
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="sms_enabled",
            field=models.BooleanField(
                default=False, help_text="Receive SMS notifications (requires phone verification)"
            ),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="inventory_visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Everyone"),
                    ("FRIENDS", "Friends Only"),
                    ("PRIVATE", "Only Me"),
                ],
                default="PUBLIC",
                help_text="Who can see your inventory and cosmetics collection",
                max_length=20,
            ),
        ),
    ]
