# Generated by Django 5.2.8 on 2026-01-02 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0047_phase2b_notifications_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="privacysettings",
            name="is_private_account",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, people must request to follow you (follow requests require approval)",
            ),
        ),
        migrations.CreateModel(
            name="FollowRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the follow request",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the follow request was created"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the request was approved or rejected", null=True
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User requesting to follow",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_follow_requests",
                        to="user_profile.userprofile",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="User whose approval is needed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_follow_requests",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow Request",
                "verbose_name_plural": "Follow Requests",
                "db_table": "user_profile_follow_request",
                "indexes": [
                    models.Index(
                        fields=["target", "status", "created_at"],
                        name="user_profil_target__663713_idx",
                    ),
                    models.Index(
                        fields=["requester", "status"], name="user_profil_request_59dc59_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="user_profil_status_19cb79_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("requester", models.F("target")), _negated=True),
                        name="follow_request_no_self_request",
                    )
                ],
                "unique_together": {("requester", "target", "status")},
            },
        ),
    ]
