# Generated by Django 5.2.8 on 2026-05-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0047_community_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypreferences",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
