# Generated by Django 5.2.8 on 2026-01-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0048_phase6a_private_account_and_follow_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("public_id_assigned", "Public ID Assigned"),
                    ("public_id_backfilled", "Public ID Backfilled"),
                    ("economy_sync", "Economy Sync"),
                    ("economy_drift_corrected", "Economy Drift Corrected"),
                    ("stats_recomputed", "Stats Recomputed"),
                    ("stats_backfilled", "Stats Backfilled"),
                    ("profile_created", "Profile Created"),
                    ("profile_updated", "Profile Updated"),
                    ("privacy_settings_changed", "Privacy Settings Changed"),
                    ("game_profile_created", "Game Profile Created"),
                    ("game_profile_updated", "Game Profile Updated"),
                    ("game_profile_deleted", "Game Profile Deleted"),
                    ("follow_created", "Follow Created"),
                    ("follow_deleted", "Follow Deleted"),
                    ("follow_requested", "Follow Request Created"),
                    ("follow_request_approved", "Follow Request Approved"),
                    ("follow_request_rejected", "Follow Request Rejected"),
                    ("admin_override", "Admin Override"),
                    ("system_reconcile", "System Reconcile"),
                ],
                db_index=True,
                help_text="Type of event",
                max_length=50,
            ),
        ),
    ]
