# Generated by Django 5.2.8 on 2026-01-03 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0049_add_follow_request_audit_event_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gameprofile",
            name="verification_notes",
            field=models.TextField(
                blank=True, default="", help_text="Admin notes for verification/flagging"
            ),
        ),
        migrations.AddField(
            model_name="gameprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Verification"),
                    ("VERIFIED", "Verified"),
                    ("FLAGGED", "Flagged for Review"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Verification pipeline status: PENDING → VERIFIED or FLAGGED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gameprofile",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when passport was verified", null=True
            ),
        ),
        migrations.AddField(
            model_name="gameprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who verified this passport",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_passports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gameprofile",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="DEPRECATED: Use verification_status instead",
            ),
        ),
    ]
