# Generated by Django 5.2.8 on 2026-01-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0051_fix_alias_columns_idempotent"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamepassportschema",
            name="division_choices",
            field=models.JSONField(
                default=list,
                help_text='\n        EA FC/eFootball division choices.\n        Format: ["div10", "div9", "div8", ..., "elite"]\n        ',
            ),
        ),
        migrations.AddField(
            model_name="gamepassportschema",
            name="mode_choices",
            field=models.JSONField(
                default=list,
                help_text='\n        Game mode choices (PUBG modes, Rocket League playlists, etc.).\n        Format: ["tpp", "fpp", "1v1", "2v2", "3v3", etc.]\n        ',
            ),
        ),
        migrations.AddField(
            model_name="gamepassportschema",
            name="platform_choices",
            field=models.JSONField(
                default=list,
                help_text='\n        Platform choices for cross-platform games.\n        Format: ["ps5", "xbox", "pc", "switch", "mobile"]\n        ',
            ),
        ),
        migrations.AddField(
            model_name="gamepassportschema",
            name="premier_rating_choices",
            field=models.JSONField(
                default=list,
                help_text='\n        CS2 Premier rating ranges.\n        Format: ["0-5000", "5000-10000", "10000-15000", etc.]\n        ',
            ),
        ),
        migrations.AddField(
            model_name="gamepassportschema",
            name="server_choices",
            field=models.JSONField(
                default=list,
                help_text='\n        Server/datacenter choices for games with server-based regions.\n        Format: ["use", "usw", "euw", "eue", "sea", "etc."]\n        ',
            ),
        ),
    ]
