# Generated by Django 5.2.8 on 2026-01-06 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_game_available_ranks_game_has_rank_system_and_more"),
        ("user_profile", "0052_add_2026_schema_choice_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePassportCooldown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cooldown_type",
                    models.CharField(
                        choices=[
                            ("POST_DELETE", "Post-Deletion Cooldown"),
                            ("IDENTITY_LOCK", "Identity Lock"),
                            ("ADMIN_OVERRIDE", "Admin Override"),
                        ],
                        default="POST_DELETE",
                        help_text="Type of cooldown restriction",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for cooldown (admin notes)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="When cooldown expires")),
                (
                    "overridden",
                    models.BooleanField(
                        default=False, help_text="Has this cooldown been overridden by admin?"
                    ),
                ),
                (
                    "overridden_at",
                    models.DateTimeField(
                        blank=True, help_text="When was cooldown overridden", null=True
                    ),
                ),
                (
                    "override_reason",
                    models.TextField(blank=True, help_text="Reason for overriding cooldown"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game affected by cooldown",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport_cooldowns",
                        to="games.game",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who overrode cooldown",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overridden_cooldowns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User with cooldown restriction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport_cooldowns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Passport Cooldown",
                "verbose_name_plural": "Game Passport Cooldowns",
                "db_table": "user_profile_gamepassport_cooldown",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "game", "-created_at"],
                        name="user_profil_user_id_13144b_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "overridden"], name="user_profil_expires_2bcb99_idx"
                    ),
                ],
                "unique_together": {("user", "game", "cooldown_type")},
            },
        ),
        migrations.CreateModel(
            name="GamePassportDeleteOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(help_text="6-digit OTP code", max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="OTP expires 10 minutes after creation"),
                ),
                ("used", models.BooleanField(default=False, help_text="Has this OTP been used?")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, help_text="When was OTP used", null=True),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of request", null=True
                    ),
                ),
                (
                    "passport",
                    models.ForeignKey(
                        help_text="Passport to be deleted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delete_otps",
                        to="user_profile.gameprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting deletion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport_delete_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Passport Delete OTP",
                "verbose_name_plural": "Game Passport Delete OTPs",
                "db_table": "user_profile_gamepassport_delete_otp",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "passport", "-created_at"],
                        name="user_profil_user_id_d11755_idx",
                    ),
                    models.Index(fields=["code", "expires_at"], name="user_profil_code_43345f_idx"),
                ],
            },
        ),
    ]
