# Generated by Django 5.2.8 on 2026-01-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0053_phase_9a27_otp_cooldown"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("whatsapp", "WhatsApp"),
                    ("discord", "Discord"),
                    ("facebook", "Facebook"),
                ],
                default="",
                help_text="User's preferred method of contact",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="secondary_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Public/secondary email for contact (primary email stays private)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="secondary_email_verified",
            field=models.BooleanField(
                default=False, help_text="Whether secondary email has been verified via OTP"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="WhatsApp number (can be different from phone, international format)",
                max_length=20,
            ),
        ),
    ]
