# Generated by Django 5.2.8 on 2026-01-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0054_userprofile_preferred_contact_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privacysettings",
            name="show_active_hours",
            field=models.BooleanField(default=True, help_text="Show active gaming hours"),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="show_device_platform",
            field=models.BooleanField(
                default=True, help_text="Show gaming device/platform (PC, Console, Mobile)"
            ),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="show_nationality",
            field=models.BooleanField(default=True, help_text="Show nationality on public profile"),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="show_play_style",
            field=models.BooleanField(
                default=True, help_text="Show play style (Casual, Competitive, Professional)"
            ),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="show_preferred_contact",
            field=models.BooleanField(
                default=False, help_text="Show preferred contact method publicly"
            ),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="show_pronouns",
            field=models.BooleanField(default=True, help_text="Show pronouns on public profile"),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="show_roles",
            field=models.BooleanField(
                default=True, help_text="Show competitive roles (main/secondary)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="active_hours",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Typical active gaming hours (e.g., '14:00-22:00 UTC' or '6PM-2AM local')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="communication_languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of languages for team communication (e.g., ['en', 'bn', 'hi'])",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="device_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PC", "PC"),
                    ("CONSOLE_PS", "PlayStation"),
                    ("CONSOLE_XBOX", "Xbox"),
                    ("MOBILE_ANDROID", "Mobile (Android)"),
                    ("MOBILE_IOS", "Mobile (iOS)"),
                ],
                default="",
                help_text="Primary gaming platform/device",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="lan_availability",
            field=models.BooleanField(
                default=False, help_text="Available for LAN tournaments and offline events"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="main_role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Primary competitive role (e.g., 'Entry Fragger', 'Support', 'IGL')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="play_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASUAL", "Casual Player"),
                    ("COMPETITIVE", "Competitive"),
                    ("PROFESSIONAL", "Professional"),
                    ("CONTENT_CREATOR", "Content Creator"),
                ],
                default="",
                help_text="Player's competitive intent and play style",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="secondary_role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Secondary competitive role for flexibility",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="HardwareLoadout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mouse_brand",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mouse brand/model (e.g., 'Logitech G Pro X Superlight')",
                        max_length=100,
                    ),
                ),
                (
                    "keyboard_brand",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Keyboard brand/model (e.g., 'Wooting 60HE')",
                        max_length=100,
                    ),
                ),
                (
                    "headset_brand",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Headset brand/model (e.g., 'HyperX Cloud II')",
                        max_length=100,
                    ),
                ),
                (
                    "monitor_brand",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Monitor brand/model (e.g., 'BenQ Zowie XL2546K 240Hz')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        help_text="User profile this hardware loadout belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware_loadout",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hardware Loadout",
                "verbose_name_plural": "Hardware Loadouts",
                "db_table": "user_profile_hardware_loadout",
            },
        ),
    ]
