# Generated by Django 5.2.8 on 2026-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0064_repair_gamepassport_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="discord_id",
            field=models.CharField(
                blank=True, help_text="DEPRECATED: Use SocialLink model", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="facebook",
            field=models.URLField(
                blank=True, default="", help_text="DEPRECATED: Use SocialLink model"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="instagram",
            field=models.URLField(
                blank=True, default="", help_text="DEPRECATED: Use SocialLink model"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tiktok",
            field=models.URLField(
                blank=True, default="", help_text="DEPRECATED: Use SocialLink model"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="twitch_link",
            field=models.URLField(blank=True, help_text="DEPRECATED: Use SocialLink model"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="twitter",
            field=models.URLField(
                blank=True, default="", help_text="DEPRECATED: Use SocialLink model"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="youtube_link",
            field=models.URLField(blank=True, help_text="DEPRECATED: Use SocialLink model"),
        ),
    ]
