# Generated by Django 5.2.8 on 2026-01-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0065_alter_userprofile_discord_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="discord_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="tiktok",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="twitch_link",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="youtube_link",
        ),
    ]
