# Generated by Django 5.2.8 on 2026-01-14 22:11

from django.db import migrations


def convert_country_names_to_iso(apps, schema_editor):
    """Convert full country names to ISO 2-letter codes before field type change"""
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    
    # Mapping of full names to ISO codes (extensible)
    country_mapping = {
        'Bangladesh': 'BD',
        'India': 'IN',
        'Pakistan': 'PK',
        'United States': 'US',
        'United Kingdom': 'GB',
        'Canada': 'CA',
        'Australia': 'AU',
        'Malaysia': 'MY',
        'Singapore': 'SG',
        'United Arab Emirates': 'AE',
        'Saudi Arabia': 'SA',
    }
    
    for profile in UserProfile.objects.exclude(country=''):
        if profile.country in country_mapping:
            profile.country = country_mapping[profile.country]
            profile.save(update_fields=['country'])


def reverse_conversion(apps, schema_editor):
    """Reverse migration - convert ISO codes back to full names"""
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    
    reverse_mapping = {
        'BD': 'Bangladesh',
        'IN': 'India',
        'PK': 'Pakistan',
        'US': 'United States',
        'GB': 'United Kingdom',
        'CA': 'Canada',
        'AU': 'Australia',
        'MY': 'Malaysia',
        'SG': 'Singapore',
        'AE': 'United Arab Emirates',
        'SA': 'Saudi Arabia',
    }
    
    for profile in UserProfile.objects.exclude(country=''):
        if profile.country in reverse_mapping:
            profile.country = reverse_mapping[profile.country]
            profile.save(update_fields=['country'])


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0066_remove_legacy_social_fields"),
    ]

    operations = [
        migrations.RunPython(convert_country_names_to_iso, reverse_conversion),
    ]
