# Generated by Django 5.2.8 on 2026-01-14 22:08

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_game_available_ranks_game_has_rank_system_and_more"),
        ("teams", "0024_repair_teammembership_left_at"),
        ("user_profile", "0067_convert_country_to_iso"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="primary_game",
            field=models.ForeignKey(
                blank=True,
                help_text="User's primary/signature game (auto-set from primary_team, or manual if no team)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_players",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="primary_team",
            field=models.ForeignKey(
                blank=True,
                help_text="User's primary/main team (auto-syncs primary_game to team's game)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_members",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_story",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed player story/background for About section",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Country of residence (for regional tournaments, with flag support)",
                max_length=2,
            ),
        ),
    ]
