# Generated by Django 5.2.8 on 2026-01-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0068_up3_extension_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="competitive_goal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short-term competitive goal or aspiration (120-160 characters)",
                max_length=160,
            ),
        ),
    ]
