# Generated by Django 5.2.8 on 2026-01-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0069_up3_hotfix3_competitive_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="lft_status",
            field=models.CharField(
                choices=[
                    ("NOT_LOOKING", "Not Looking"),
                    ("LFT_TEAM", "LFT Team"),
                    ("LFT_SCRIMS", "LFT Scrims"),
                ],
                default="NOT_LOOKING",
                help_text="Looking For Team/Scrims availability status",
                max_length=20,
            ),
        ),
    ]
