# Generated by Django 5.2.8 on 2026-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0070_up3_hotfix4_lft_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name_pronunciation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional pronunciation guide for your name (e.g., rah-sheek / রাশিক)",
                max_length=64,
            ),
        ),
    ]
