# Generated by Django 5.2.8 on 2026-01-16 09:32

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


def backfill_profile_locations(apps, schema_editor):
    """
    Data migration: Copy location data from UserProfile to ProfileLocation.
    
    This ensures existing users don't lose their location data when we move it
    to the new model.
    """
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    ProfileLocation = apps.get_model('user_profile', 'ProfileLocation')
    
    # Create ProfileLocation for each UserProfile with location data
    profiles_with_location = UserProfile.objects.exclude(
        country='', city='', postal_code='', address=''
    )
    
    locations_created = 0
    for profile in profiles_with_location:
        # Only create if at least one field has data
        if profile.country or profile.city or profile.postal_code or profile.address:
            ProfileLocation.objects.create(
                user_profile=profile,
                country=profile.country,
                city=profile.city or '',
                postal_code=profile.postal_code or '',
                address_line=profile.address or '',
            )
            locations_created += 1
    
    print(f"[MIGRATION] Created {locations_created} ProfileLocation records from existing UserProfiles")


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration: Copy data back from ProfileLocation to UserProfile.
    """
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    ProfileLocation = apps.get_model('user_profile', 'ProfileLocation')
    
    for location in ProfileLocation.objects.all():
        profile = location.user_profile
        profile.country = location.country
        profile.city = location.city
        profile.postal_code = location.postal_code
        profile.address = location.address_line
        profile.save(update_fields=['country', 'city', 'postal_code', 'address'])


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0071_add_name_pronunciation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="name_pronunciation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional pronunciation guide for your name (e.g., for-SAY-ken)",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="ProfileLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True,
                        help_text="Country of residence (for regional tournaments, with flag support)",
                        max_length=2,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", help_text="City of residence", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default="", help_text="Postal/ZIP code", max_length=20
                    ),
                ),
                (
                    "address_line",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Street address for correspondence and prize shipping",
                        max_length=300,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        help_text="Owner of this location data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Location",
                "verbose_name_plural": "Profile Locations",
                "db_table": "user_profile_location",
            },
        ),
        # Backfill existing location data
        migrations.RunPython(backfill_profile_locations, reverse_backfill),
    ]
