# Generated by Django 5.2.8 on 2026-01-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0072_create_profile_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privacysettings",
            name="show_pronouns",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="name_pronunciation",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="pronouns",
        ),
    ]
