# Generated by Django 5.2.8 on 2026-01-16 17:00

import apps.user_profile.models_main
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0073_remove_pronouns_name_pronunciation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_back",
            field=models.ImageField(
                blank=True,
                help_text="Back side of government-issued ID",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_front",
            field=models.ImageField(
                blank=True,
                help_text="Front side of government-issued ID (NID, Passport, Driver's License)",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="selfie_with_id",
            field=models.ImageField(
                blank=True,
                help_text="Selfie holding the ID document for liveness verification",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.CreateModel(
            name="KYCSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("nid", "National ID Card"),
                            ("passport", "Passport"),
                            ("driving_license", "Driving License"),
                            ("birth_certificate", "Birth Certificate"),
                        ],
                        help_text="Type of identity document",
                        max_length=30,
                    ),
                ),
                (
                    "document_front",
                    models.ImageField(
                        help_text="Front side of the identity document",
                        upload_to=apps.user_profile.models_main.kyc_document_path,
                    ),
                ),
                (
                    "document_back",
                    models.ImageField(
                        blank=True,
                        help_text="Back side of the identity document (if applicable)",
                        null=True,
                        upload_to=apps.user_profile.models_main.kyc_document_path,
                    ),
                ),
                (
                    "selfie_with_document",
                    models.ImageField(
                        blank=True,
                        help_text="Selfie holding the document for verification",
                        null=True,
                        upload_to=apps.user_profile.models_main.kyc_document_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current verification status",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason for rejection if status is rejected",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the KYC submission was created"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the submission was reviewed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal admin notes about the submission",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this submission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyc_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        help_text="User profile this KYC submission belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_submissions",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC Submission",
                "verbose_name_plural": "KYC Submissions",
                "db_table": "user_profile_kyc_submission",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["user_profile", "-submitted_at"],
                        name="user_profil_user_pr_75c7e1_idx",
                    ),
                    models.Index(
                        fields=["status", "-submitted_at"], name="user_profil_status_cf70b5_idx"
                    ),
                ],
            },
        ),
    ]
