# Generated by Django 5.2.8 on 2026-01-16 18:02

import apps.user_profile.models_main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0076_alter_verificationrecord_id_document_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pronouns",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preferred pronouns for casting/teammates (e.g., He/Him, She/Her, They/Them)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_back",
            field=models.ImageField(
                blank=True,
                help_text="Back side of government-issued ID",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_front",
            field=models.ImageField(
                blank=True,
                help_text="Front side of government-issued ID (NID, Passport, Driver's License)",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="selfie_with_id",
            field=models.ImageField(
                blank=True,
                help_text="Selfie holding the ID document for liveness verification",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
    ]
