# Generated by Django 5.2.8 on 2026-01-16 18:28

import apps.user_profile.models_main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0078_alter_verificationrecord_id_document_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="pronouns",
            field=models.CharField(
                blank=True,
                choices=[
                    ("he_him", "He/Him"),
                    ("she_her", "She/Her"),
                    ("they_them", "They/Them"),
                    ("she_they", "She/They"),
                    ("he_they", "He/They"),
                    ("other", "Other"),
                ],
                default="",
                help_text="Preferred pronouns",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_back",
            field=models.ImageField(
                blank=True,
                help_text="Back side of government-issued ID",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_front",
            field=models.ImageField(
                blank=True,
                help_text="Front side of government-issued ID (NID, Passport, Driver's License)",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="selfie_with_id",
            field=models.ImageField(
                blank=True,
                help_text="Selfie holding the ID document for liveness verification",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
    ]
