# Generated by Django 5.2.8 on 2026-01-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0084_alter_verificationrecord_id_document_back_and_more"),
    ]

    operations = [
        # Add Instagram-style granular privacy controls
        migrations.AddField(
            model_name='privacysettings',
            name='followers_list_visibility',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('everyone', 'Everyone'),
                    ('followers', 'Followers Only'),
                    ('only_me', 'Only Me'),
                ],
                default='everyone',
                help_text='Who can view your followers list'
            ),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='following_list_visibility',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('everyone', 'Everyone'),
                    ('followers', 'Followers Only'),
                    ('only_me', 'Only Me'),
                ],
                default='everyone',
                help_text='Who can view your following list'
            ),
        ),
    ]
