# Generated by Django 5.2.8 on 2026-01-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0085_add_instagram_privacy_controls"),
    ]

    operations = [
        # UP PHASE 8 CRASHFIX: Drop orphaned is_private column
        # The is_private column exists in DB with NOT NULL constraint but was removed from model in migration 0029.
        # This causes IntegrityError when signals try to create UserProfile without setting this field.
        # Solution: Drop the orphaned column entirely since Django model doesn't define it
        migrations.RunSQL(
            sql="""
                -- First set NULL values to prevent constraint violation during column drop
                UPDATE user_profile_userprofile
                SET is_private = FALSE
                WHERE is_private IS NULL;
                
                -- Drop the orphaned column
                ALTER TABLE user_profile_userprofile
                DROP COLUMN IF EXISTS is_private;
            """,
            reverse_sql="""
                -- Reverse: Re-add the column (though this shouldn't be needed)
                ALTER TABLE user_profile_userprofile
                ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT FALSE NOT NULL;
            """,
        ),
    ]
