# Generated by Django 5.2.8 on 2026-01-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0087_alter_verificationrecord_id_document_back_and_more"),
    ]

    operations = [
        # UP PHASE 8 CRASHFIX: Drop orphaned privacy fields from UserProfile table
        # These fields were supposed to be removed in migration 0029 but still exist in the database
        # causing IntegrityError: "null value in column show_email violates not-null constraint"
        # This migration forcefully drops them with CASCADE to fix signup permanently.
        migrations.RunSQL(
            sql="""
                -- Drop orphaned privacy columns from user_profile_userprofile table
                -- These fields now live in user_profile_privacysettings table
                DO $$
                BEGIN
                    -- Drop show_email if it exists
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'user_profile_userprofile' 
                        AND column_name = 'show_email'
                    ) THEN
                        ALTER TABLE user_profile_userprofile DROP COLUMN show_email CASCADE;
                        RAISE NOTICE 'Dropped show_email column';
                    END IF;
                    
                    -- Drop show_phone if it exists
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'user_profile_userprofile' 
                        AND column_name = 'show_phone'
                    ) THEN
                        ALTER TABLE user_profile_userprofile DROP COLUMN show_phone CASCADE;
                        RAISE NOTICE 'Dropped show_phone column';
                    END IF;
                    
                    -- Drop show_real_name if it exists
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'user_profile_userprofile' 
                        AND column_name = 'show_real_name'
                    ) THEN
                        ALTER TABLE user_profile_userprofile DROP COLUMN show_real_name CASCADE;
                        RAISE NOTICE 'Dropped show_real_name column';
                    END IF;
                    
                    -- Drop show_age if it exists
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'user_profile_userprofile' 
                        AND column_name = 'show_age'
                    ) THEN
                        ALTER TABLE user_profile_userprofile DROP COLUMN show_age CASCADE;
                        RAISE NOTICE 'Dropped show_age column';
                    END IF;
                    
                    -- Drop show_gender if it exists
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'user_profile_userprofile' 
                        AND column_name = 'show_gender'
                    ) THEN
                        ALTER TABLE user_profile_userprofile DROP COLUMN show_gender CASCADE;
                        RAISE NOTICE 'Dropped show_gender column';
                    END IF;
                    
                    -- Drop show_country if it exists
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'user_profile_userprofile' 
                        AND column_name = 'show_country'
                    ) THEN
                        ALTER TABLE user_profile_userprofile DROP COLUMN show_country CASCADE;
                        RAISE NOTICE 'Dropped show_country column';
                    END IF;
                    
                    -- Drop show_address if it exists
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'user_profile_userprofile' 
                        AND column_name = 'show_address'
                    ) THEN
                        ALTER TABLE user_profile_userprofile DROP COLUMN show_address CASCADE;
                        RAISE NOTICE 'Dropped show_address column';
                    END IF;
                    
                    -- Drop show_socials if it exists
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'user_profile_userprofile' 
                        AND column_name = 'show_socials'
                    ) THEN
                        ALTER TABLE user_profile_userprofile DROP COLUMN show_socials CASCADE;
                        RAISE NOTICE 'Dropped show_socials column';
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
