# Generated by Django 5.2.8 on 2026-01-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0099_alter_verificationrecord_id_document_back_and_more"),
        ("user_profile", "0099_harden_profile_defaults"),
    ]

    operations = []
