# Generated by Django 5.2.8 on 2026-01-20 14:50

import apps.user_profile.models_main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0100_merge_20260120_2049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_back",
            field=models.ImageField(
                blank=True,
                help_text="Back side of government-issued ID",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="id_document_front",
            field=models.ImageField(
                blank=True,
                help_text="Front side of government-issued ID (NID, Passport, Driver's License)",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="selfie_with_id",
            field=models.ImageField(
                blank=True,
                help_text="Selfie holding the ID document for liveness verification",
                null=True,
                upload_to=apps.user_profile.models_main.kyc_document_path,
            ),
        ),
    ]
