# Generated by Django 5.2.8 on 2025-11-11 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_profile_id', models.IntegerField(db_index=True)),
                ('subject_profile_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('ref_type', models.CharField(max_length=50)),
                ('ref_id', models.IntegerField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('priority', models.IntegerField(default=3)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'abuse_report',
                'ordering': ['-priority', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('priority__gte', 0), ('priority__lte', 5)), name='report_priority_bounds')],
            },
        ),
        migrations.CreateModel(
            name='ModerationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=100)),
                ('actor_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('subject_profile_id', models.IntegerField(blank=True, null=True)),
                ('ref_type', models.CharField(max_length=50)),
                ('ref_id', models.IntegerField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'moderation_audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ref_type', 'ref_id', 'created_at'], name='mod_audit_ref_idx'), models.Index(fields=['actor_id', 'created_at'], name='mod_audit_actor_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_profile_id', models.IntegerField(db_index=True)),
                ('type', models.CharField(choices=[('ban', 'Ban'), ('suspend', 'Suspend'), ('mute', 'Mute')], max_length=20)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('tournament', 'Tournament')], max_length=20)),
                ('scope_id', models.IntegerField(blank=True, null=True)),
                ('reason_code', models.CharField(max_length=100)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('issued_by', models.IntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'moderation_sanction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_profile_id', 'type', 'scope', 'scope_id', 'ends_at', 'revoked_at'], name='mod_sanction_query_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='sanction_ends_after_starts')],
            },
        ),
    ]
