# Generated by Django 4.2.23 on 2025-09-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_efootball', '0005_restore_info_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efootballsoloinfo',
            name='registration',
        ),
        migrations.DeleteModel(
            name='EfootballDuoInfo',
        ),
        migrations.DeleteModel(
            name='EfootballSoloInfo',
        ),
    ]
