# Generated by Django 4.2.24 on 2025-09-17 17:51

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_efootball', '0007_alter_efootballconfig_allow_extra_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efootballconfig',
            name='additional_rules_richtext',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Additional rules'),
        ),
    ]
