# Generated by Django 4.2.23 on 2025-09-04 16:07

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EfootballConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_type', models.CharField(choices=[('BO1', 'Best of 1'), ('BO2', 'Best of 2'), ('BO3', 'Best of 3'), ('BO5', 'Best of 5')], default='BO1', max_length=3)),
                ('match_duration_min', models.PositiveIntegerField(default=10, help_text='Per match, e.g., 10 minutes')),
                ('match_time_limit', models.DurationField(blank=True, null=True)),
                ('team_strength_cap', models.PositiveIntegerField(blank=True, help_text='e.g., 2700–3000', null=True)),
                ('allow_extra_time', models.BooleanField(default=False)),
                ('allow_penalties', models.BooleanField(default=True)),
                ('additional_rules_richtext', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Additional rules')),
            ],
            options={
                'verbose_name': 'eFootball Config',
                'verbose_name_plural': 'eFootball Configs',
            },
        ),
    ]
