# Generated by Django 4.2.23 on 2025-09-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_remove_paymentverification_pv_payer_account_idx_and_more'),
        ('game_efootball', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfootballSoloInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('ign', models.CharField(max_length=120, verbose_name='In-Game Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('personal_team_name', models.CharField(max_length=120)),
                ('team_strength', models.PositiveIntegerField()),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='efootball/team_logos/')),
                ('agree_rules', models.BooleanField(default=False)),
                ('agree_no_tools', models.BooleanField(default=False)),
                ('agree_no_double', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=32)),
                ('payment_reference', models.CharField(blank=True, max_length=128)),
                ('amount_bdt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efootball_solo_info', to='tournaments.registration')),
            ],
            options={
                'verbose_name': 'eFootball Solo Info',
                'verbose_name_plural': 'eFootball Solo Info',
            },
        ),
        migrations.CreateModel(
            name='EfootballDuoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='efootball/duo_team_logos/')),
                ('captain_full_name', models.CharField(max_length=120)),
                ('captain_ign', models.CharField(max_length=120)),
                ('captain_email', models.EmailField(max_length=254)),
                ('captain_phone', models.CharField(max_length=40)),
                ('mate_full_name', models.CharField(max_length=120)),
                ('mate_ign', models.CharField(max_length=120)),
                ('mate_email', models.EmailField(max_length=254)),
                ('mate_phone', models.CharField(max_length=40)),
                ('agree_consent', models.BooleanField(default=False)),
                ('agree_rules', models.BooleanField(default=False)),
                ('agree_no_tools', models.BooleanField(default=False)),
                ('agree_no_multi_team', models.BooleanField(default=False)),
                ('payment_method', models.CharField(max_length=32)),
                ('payment_reference', models.CharField(max_length=128)),
                ('amount_bdt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_proof', models.ImageField(upload_to='efootball/duo_payment_proofs/')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efootball_duo_info', to='tournaments.registration')),
            ],
            options={
                'verbose_name': 'eFootball Duo Info',
                'verbose_name_plural': 'eFootball Duo Info',
            },
        ),
    ]
