# Generated by Django 4.2.24 on 2025-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_efootball', '0006_remove_efootballsoloinfo_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efootballconfig',
            name='allow_extra_time',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efootballconfig',
            name='allow_penalties',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efootballconfig',
            name='format_type',
            field=models.CharField(blank=True, choices=[('BO1', 'Best of 1'), ('BO2', 'Best of 2'), ('BO3', 'Best of 3'), ('BO5', 'Best of 5')], help_text='Override the default match format (e.g., BO1, BO3).', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='efootballconfig',
            name='match_duration_min',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate duration per match in minutes.', null=True),
        ),
        migrations.AlterField(
            model_name='efootballconfig',
            name='team_strength_cap',
            field=models.PositiveIntegerField(blank=True, help_text='Optional cap on overall team strength (e.g., 2700).', null=True),
        ),
    ]
