# Generated by Django 5.2.8 on 2025-12-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event type identifier', max_length=255)),
                ('payload', models.JSONField(help_text='Event business data')),
                ('occurred_at', models.DateTimeField(help_text='When the event occurred (UTC)')),
                ('user_id', models.IntegerField(blank=True, help_text='User who triggered the event', null=True)),
                ('correlation_id', models.CharField(blank=True, help_text='Correlation ID for related events', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event context')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this log entry was created')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead Letter')], db_index=True, default='PENDING', help_text='Event processing status', max_length=20)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of processing attempts')),
                ('last_error', models.TextField(blank=True, help_text='Error message from most recent failure', null=True)),
                ('last_error_at', models.DateTimeField(blank=True, help_text='Timestamp of most recent error', null=True)),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', '-occurred_at'], name='evt_name_occurred'), models.Index(fields=['correlation_id'], name='evt_correlation'), models.Index(fields=['user_id', '-occurred_at'], name='evt_user_occurred'), models.Index(fields=['status', '-created_at'], name='evt_status_created'), models.Index(fields=['-occurred_at'], name='evt_occurred_desc')],
            },
        ),
    ]
