# Generated by Django 5.2.8 on 2026-02-10 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0030_team_platform_identity_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="", max_length=500)),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("wager", "Wager Match"),
                            ("bounty", "Community Bounty"),
                            ("scrim", "Scrim Challenge"),
                            ("duel", "1v1 Duel"),
                        ],
                        default="wager",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        default="BO3", help_text="e.g. BO1, BO3, BO5, 1v1", max_length=30
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. Scrim, Aim Duel, Ranked",
                        max_length=50,
                    ),
                ),
                ("prize_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "prize_currency",
                    models.CharField(
                        default="USD", help_text="USD or CP (Crown Points)", max_length=10
                    ),
                ),
                ("prize_description", models.CharField(blank=True, default="", max_length=200)),
                ("target_player_name", models.CharField(blank=True, default="", max_length=100)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("wins_by_challenger", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opponent_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges_accepted",
                        to="organizations.team",
                    ),
                ),
                (
                    "target_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bounties_targeted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges_issued",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["team", "status"], name="challenges__team_id_78385d_idx"),
                    models.Index(
                        fields=["status", "-created_at"], name="challenges__status_c48f5f_idx"
                    ),
                ],
            },
        ),
    ]
