# Generated by Django 4.2.23 on 2025-09-06 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_merge_0006_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarfeedtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pinnedtournament',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedmatchfilter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedmatchfilter',
            name='state',
            field=models.CharField(blank=True, choices=[('', 'Any'), ('scheduled', 'Scheduled'), ('reported', 'Reported'), ('verified', 'Verified'), ('live', 'Live'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='savedmatchfilter',
            name='tournament_id',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
