# Generated by Django 4.2.23 on 2025-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_merge_0009_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchattendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
