# Generated by Django 4.2.23 on 2025-09-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_automatic_scheduling_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsettings',
            name='automatic_scheduling_enabled',
            field=models.BooleanField(default=False, help_text='Automate match scheduling based on start time and durations.'),
        ),
    ]
