# Generated by Django 4.2.24 on 2025-09-17 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_allow_null_checkin_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsettings',
            name='allow_substitutes',
            field=models.BooleanField(blank=True, help_text='Allow teams to register substitute players.', null=True),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='auto_check_in',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='automatic_scheduling_enabled',
            field=models.BooleanField(blank=True, help_text='Automate match scheduling based on start time and durations.', null=True),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='bkash_receive_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('merchant', 'Merchant'), ('agent', 'Agent')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='bracket_visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('captains', 'Team Captains Only')], default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='custom_format_enabled',
            field=models.BooleanField(blank=True, help_text='Enable custom format JSON to override bracket settings.', null=True),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='invite_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='max_team_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum players per team.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='min_team_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum players per team.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='nagad_receive_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('merchant', 'Merchant'), ('agent', 'Agent')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='payment_gateway_enabled',
            field=models.BooleanField(blank=True, help_text='Leave OFF for manual verification (bKash/Nagad/Rocket).', null=True),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='prize_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash Prize'), ('gift_cards', 'Gift Cards'), ('gear', 'Gaming Gear'), ('sponsored', 'Sponsored Prizes')], default='cash', max_length=16),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='region_lock',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='rocket_receive_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('merchant', 'Merchant'), ('agent', 'Agent')], max_length=16, null=True),
        ),
    ]
