# Generated by Django 4.2.23 on 2025-09-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_registration_custom_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='custom_data',
        ),
    ]
