# Generated by Django 4.2.24 on 2025-09-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_remove_registration_custom_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentsettings',
            name='entry_fee_bdt',
        ),
    ]
