# Generated by Django 4.2.23 on 2025-09-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0027_paymentverification_reference_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentRegistrationPolicy',
        ),
    ]
