# Generated by Django 4.2.24 on 2025-10-01 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_fix_user_fk_constraint'),
        ('teams', '0038_add_ranking_system'),
        ('tournaments', '0029_registration_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message to the captain', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('response_message', models.TextField(blank=True, max_length=500)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Request expires if not responded to by this time')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests_received', to='user_profile.userprofile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests_sent', to='user_profile.userprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tournament', 'team', 'status'], name='tournaments_tournam_5e8047_idx'), models.Index(fields=['captain', 'status'], name='tournaments_captain_fb4800_idx'), models.Index(fields=['requester', 'status'], name='tournaments_request_b97876_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='registrationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('tournament', 'team', 'requester'), name='uq_one_pending_request_per_requester_team_tournament'),
        ),
    ]
