# Generated by Django 4.2.24 on 2025-10-03 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0032_migrate_schedule_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_size', models.PositiveIntegerField(help_text='Total number of slots/positions available (2-1024)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1024)], verbose_name='Total Slots')),
                ('max_teams', models.PositiveIntegerField(help_text='Maximum number of teams allowed (usually same as slot_size)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1024)], verbose_name='Maximum Teams')),
                ('min_team_size', models.PositiveIntegerField(default=1, help_text='Minimum number of players per team (1 for solo, 5 for Valorant, etc.)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Minimum Team Size')),
                ('max_team_size', models.PositiveIntegerField(default=10, help_text='Maximum number of players per team (including substitutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Maximum Team Size')),
                ('registration_mode', models.CharField(choices=[('open', 'Open Registration'), ('approval', 'Approval Required'), ('invite', 'Invite Only')], default='open', help_text='How teams can register for this tournament', max_length=20, verbose_name='Registration Mode')),
                ('waitlist_enabled', models.BooleanField(default=True, help_text='Allow teams to join waitlist when tournament is full', verbose_name='Enable Waitlist')),
                ('current_registrations', models.PositiveIntegerField(default=0, help_text='Cached count of active registrations (auto-updated)', verbose_name='Current Registrations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.OneToOneField(help_text='The tournament this capacity configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='tournaments.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Tournament Capacity',
                'verbose_name_plural': 'Tournament Capacities',
                'db_table': 'tournaments_capacity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['registration_mode'], name='tournaments_registr_d5ff66_idx'), models.Index(fields=['current_registrations'], name='tournaments_current_d6e7e4_idx')],
            },
        ),
    ]
