# Generated by Django 4.2.24 on 2025-10-03 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0036_migrate_finance_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, help_text='Main tournament banner (recommended: 1920x1080px)', null=True, upload_to='tournaments/banners/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail for cards and listings (recommended: 400x300px)', null=True, upload_to='tournaments/thumbnails/')),
                ('rules_pdf', models.FileField(blank=True, help_text='Tournament rules PDF document', null=True, upload_to='tournaments/rules/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('promotional_image_1', models.ImageField(blank=True, help_text='First promotional image', null=True, upload_to='tournaments/promotional/')),
                ('promotional_image_2', models.ImageField(blank=True, help_text='Second promotional image', null=True, upload_to='tournaments/promotional/')),
                ('promotional_image_3', models.ImageField(blank=True, help_text='Third promotional image', null=True, upload_to='tournaments/promotional/')),
                ('social_media_image', models.ImageField(blank=True, help_text='Optimized for social media sharing (recommended: 1200x630px)', null=True, upload_to='tournaments/social/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this media record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this media record was last updated')),
                ('tournament', models.OneToOneField(help_text='Associated tournament', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Media',
                'verbose_name_plural': 'Tournament Media',
                'db_table': 'tournament_media',
                'ordering': ['-updated_at'],
            },
        ),
    ]
