# Generated by Django 4.2.24 on 2025-10-03 18:23

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_fix_user_fk_constraint'),
        ('tournaments', '0042_migrate_archive_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinnedtournament',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedmatchfilter',
            name='user',
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed tournament description (supports rich text)', null=True, verbose_name='Full Description'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(blank=True, choices=[('SINGLE_ELIM', 'Single Elimination'), ('DOUBLE_ELIM', 'Double Elimination'), ('ROUND_ROBIN', 'Round Robin'), ('SWISS', 'Swiss System'), ('GROUP_STAGE', 'Group Stage'), ('HYBRID', 'Hybrid (Groups + Bracket)')], default='', help_text='Tournament format/structure', max_length=32),
        ),
        migrations.AddField(
            model_name='tournament',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা (Bengali)'), ('hi', 'हिन्दी (Hindi)'), ('multi', 'Multilingual')], default='en', help_text='Primary language for tournament communication', max_length=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='User or organization running this tournament', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_tournaments', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='platform',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline/LAN'), ('HYBRID', 'Hybrid')], default='ONLINE', help_text='Where the tournament takes place', max_length=32),
        ),
        migrations.AddField(
            model_name='tournament',
            name='region',
            field=models.CharField(blank=True, default='', help_text="Geographic region (e.g., 'Bangladesh', 'South Asia', 'Global')", max_length=64),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('TEAM', 'Team'), ('MIXED', 'Mixed (Solo & Team)')], default='TEAM', help_text='Type of tournament: Solo, Team, or Mixed', max_length=32),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='⚠️ DEPRECATED: Use TournamentSchedule.tournament_end instead. This field is kept for backward compatibility but will be removed in v2.0.', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='entry_fee_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='⚠️ DEPRECATED: Use TournamentFinance.entry_fee + currency instead. This field is kept for backward compatibility but will be removed in v2.0.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_pool_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='⚠️ DEPRECATED: Use TournamentFinance.prize_pool + prize_currency instead. This field is kept for backward compatibility but will be removed in v2.0.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reg_close_at',
            field=models.DateTimeField(blank=True, help_text='⚠️ DEPRECATED: Use TournamentSchedule.registration_end instead. This field is kept for backward compatibility but will be removed in v2.0.', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reg_open_at',
            field=models.DateTimeField(blank=True, help_text='⚠️ DEPRECATED: Use TournamentSchedule.registration_start instead. This field is kept for backward compatibility but will be removed in v2.0.', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slot_size',
            field=models.PositiveIntegerField(blank=True, help_text='⚠️ DEPRECATED: Use TournamentCapacity.max_teams instead. This field is kept for backward compatibility but will be removed in v2.0.', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='⚠️ DEPRECATED: Use TournamentSchedule.tournament_start instead. This field is kept for backward compatibility but will be removed in v2.0.', null=True),
        ),
        migrations.DeleteModel(
            name='CalendarFeedToken',
        ),
        migrations.DeleteModel(
            name='PinnedTournament',
        ),
        migrations.DeleteModel(
            name='SavedMatchFilter',
        ),
    ]
