# Generated by Django 4.2.24 on 2025-10-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0043_add_professional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentfinance',
            name='prize_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='Prize breakdown by position (JSON format)', null=True, verbose_name='Prize Distribution'),
        ),
    ]
