# Generated by Django 5.2.8 on 2025-12-15 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("TOURNAMENTS", "Tournaments"),
                            ("PAYMENTS", "Payments"),
                            ("TECHNICAL", "Technical Support"),
                            ("TEAMS", "Teams & Players"),
                            ("RULES", "Rules & Fair Play"),
                        ],
                        default="GENERAL",
                        help_text="Question category",
                        max_length=20,
                    ),
                ),
                ("question", models.CharField(help_text="The question text", max_length=500)),
                ("answer", models.TextField(help_text="The answer (HTML allowed)")),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers appear first)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Show on FAQ page")),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Show on homepage/footer"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (overrides user name if set)", max_length=100
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True,
                        help_text="Team affiliation (e.g., 'Dhaka Dragons')",
                        max_length=100,
                    ),
                ),
                (
                    "avatar_text",
                    models.CharField(
                        blank=True, help_text="1-2 letters for avatar (e.g., 'RA')", max_length=2
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                        help_text="Star rating (1-5)",
                    ),
                ),
                ("testimonial_text", models.TextField(help_text="The testimonial content")),
                (
                    "prize_won",
                    models.CharField(
                        blank=True,
                        help_text="Prize amount if applicable (e.g., '৳50,000')",
                        max_length=100,
                    ),
                ),
                (
                    "tournament_name",
                    models.CharField(
                        blank=True, help_text="Tournament won (optional)", max_length=200
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="Verified winner/user"),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(default=False, help_text="Display on homepage"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers appear first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
