# Generated by Django 4.2.23 on 2025-09-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corelib', '0001_idempotency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='corelib_ide_user_id_d8653e_idx',
            old_name='corelib_idem_user_scope_token_idx',
        ),
    ]
