# Generated by Django 5.2.8 on 2026-05-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobile_api", "0001_mobile_device_token"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mobiledevicetoken",
            new_name="mobile_api__user_id_74a009_idx",
            old_name="mobile_api_user_id_e17912_idx",
        ),
        migrations.RenameIndex(
            model_name="mobiledevicetoken",
            new_name="mobile_api__platfor_730164_idx",
            old_name="mobile_api_platfor_d82248_idx",
        ),
    ]
