# Generated by Django 5.2.8 on 2025-11-16 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Unique item SKU', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Item description')),
                ('price', models.IntegerField(help_text='Price in DeltaCoins (must be positive)', validators=[django.core.validators.MinValueValidator(1)])),
                ('active', models.BooleanField(default=True, help_text='Item available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shop_item',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='shop_item_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='ReservationHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Item SKU (denormalized)', max_length=100)),
                ('amount', models.IntegerField(help_text='Hold amount in DeltaCoins', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('authorized', 'Authorized'), ('captured', 'Captured'), ('released', 'Released'), ('expired', 'Expired')], db_index=True, default='authorized', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration timestamp (nullable)', null=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Idempotency key (nullable)', max_length=255, null=True)),
                ('captured_txn_id', models.IntegerField(blank=True, help_text='DeltaCrownTransaction ID if captured', null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wallet', models.ForeignKey(help_text='Wallet with reserved funds', on_delete=django.db.models.deletion.PROTECT, related_name='reservation_holds', to='economy.deltacrownwallet')),
            ],
            options={
                'db_table': 'shop_reservation_hold',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'status'], name='shop_hold_wallet_status_idx'), models.Index(fields=['expires_at'], name='shop_hold_expires_idx'), models.Index(fields=['created_at'], name='shop_hold_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='shop_hold_amount_positive'), models.CheckConstraint(condition=models.Q(('status__in', ['authorized', 'captured', 'released', 'expired'])), name='shop_hold_status_valid'), models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='shop_hold_idempotency_key_unique')],
            },
        ),
    ]
