# Generated by Django 5.2.8 on 2026-01-23 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("leaderboard_type", models.CharField(db_index=True, max_length=50)),
                ("rank", models.IntegerField()),
                ("points", models.IntegerField()),
            ],
            options={
                "db_table": "leaderboards_leaderboardsnapshot",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "season_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique season identifier (e.g., 'S1-2024', 'WINTER-2024')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Season 1 - 2024', 'Winter Championship 2024')",
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether season is currently active (only one active season per time)",
                    ),
                ),
                (
                    "decay_rules_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Decay rules: {'enabled': bool, 'days_inactive': int, 'decay_percentage': float, 'min_elo': int}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "db_table": "leaderboards_season",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TeamAnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "game_slug",
                    models.CharField(db_index=True, help_text="Game identifier", max_length=100),
                ),
                (
                    "elo_snapshot",
                    models.IntegerField(default=1200, help_text="Team ELO rating snapshot"),
                ),
                (
                    "elo_volatility",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="ELO volatility (standard deviation of recent changes)",
                        max_digits=6,
                    ),
                ),
                (
                    "avg_member_skill",
                    models.DecimalField(
                        decimal_places=2,
                        default=1200.0,
                        help_text="Average skill rating of active team members",
                        max_digits=8,
                    ),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Overall win rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "win_rate_7d",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Win rate in last 7 days",
                        max_digits=5,
                    ),
                ),
                (
                    "win_rate_30d",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Win rate in last 30 days",
                        max_digits=5,
                    ),
                ),
                (
                    "synergy_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Team synergy score (0-100, based on consistency)",
                        max_digits=5,
                    ),
                ),
                (
                    "activity_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Activity score (0-100, based on recent match participation)",
                        max_digits=5,
                    ),
                ),
                ("matches_last_7d", models.IntegerField(default=0)),
                ("matches_last_30d", models.IntegerField(default=0)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("diamond", "Diamond"),
                            ("crown", "Crown"),
                        ],
                        db_index=True,
                        default="bronze",
                        help_text="Assigned tier based on team ELO",
                        max_length=20,
                    ),
                ),
                (
                    "percentile_rank",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Percentile rank among all teams (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "recalculated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="When analytics were last computed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Team Analytics Snapshot",
                "verbose_name_plural": "Team Analytics Snapshots",
                "db_table": "leaderboards_teamanalyticssnapshot",
                "ordering": ["-elo_snapshot"],
            },
        ),
        migrations.CreateModel(
            name="TeamMatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "game_slug",
                    models.CharField(db_index=True, help_text="Game identifier", max_length=100),
                ),
                ("is_winner", models.BooleanField(default=False)),
                ("is_draw", models.BooleanField(default=False)),
                (
                    "opponent_team_id",
                    models.IntegerField(blank=True, help_text="Opponent team ID", null=True),
                ),
                (
                    "opponent_team_name",
                    models.CharField(
                        blank=True, help_text="Opponent team name (cached)", max_length=255
                    ),
                ),
                (
                    "score_summary",
                    models.CharField(
                        blank=True, help_text="Score summary for timeline display", max_length=100
                    ),
                ),
                (
                    "elo_before",
                    models.IntegerField(blank=True, help_text="Team ELO before match", null=True),
                ),
                (
                    "elo_after",
                    models.IntegerField(blank=True, help_text="Team ELO after match", null=True),
                ),
                (
                    "elo_change",
                    models.IntegerField(default=0, help_text="ELO rating change from match"),
                ),
                ("had_dispute", models.BooleanField(default=False)),
                ("is_forfeit", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Team Match History",
                "verbose_name_plural": "Team Match Histories",
                "db_table": "leaderboards_teammatchhistory",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "game_slug",
                    models.CharField(
                        db_index=True,
                        help_text="Game identifier for this ranking ladder",
                        max_length=100,
                    ),
                ),
                (
                    "elo_rating",
                    models.IntegerField(
                        default=1200, help_text="Current ELO rating (default 1200 for new teams)"
                    ),
                ),
                (
                    "peak_elo",
                    models.IntegerField(default=1200, help_text="Highest ELO rating achieved"),
                ),
                ("games_played", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                (
                    "rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Current rank position (1 = top team), computed via queries",
                        null=True,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Team Ranking",
                "verbose_name_plural": "Team Rankings",
                "db_table": "leaderboards_teamranking",
                "ordering": ["-elo_rating"],
            },
        ),
        migrations.CreateModel(
            name="TeamStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "game_slug",
                    models.CharField(
                        db_index=True,
                        help_text="Game identifier (e.g., 'valorant', 'csgo')",
                        max_length=100,
                    ),
                ),
                ("matches_played", models.IntegerField(default=0)),
                ("matches_won", models.IntegerField(default=0)),
                ("matches_lost", models.IntegerField(default=0)),
                ("matches_drawn", models.IntegerField(default=0)),
                ("tournaments_played", models.IntegerField(default=0)),
                ("tournaments_won", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Win percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                ("last_match_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team Stats",
                "verbose_name_plural": "Team Stats",
                "db_table": "leaderboards_teamstats",
            },
        ),
        migrations.CreateModel(
            name="UserAnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "game_slug",
                    models.CharField(db_index=True, help_text="Game identifier", max_length=100),
                ),
                (
                    "mmr_snapshot",
                    models.IntegerField(
                        default=1200,
                        help_text="MMR snapshot at calculation time (for MMR-based games)",
                    ),
                ),
                (
                    "elo_snapshot",
                    models.IntegerField(
                        default=1200,
                        help_text="ELO snapshot at calculation time (fallback/alternative)",
                    ),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Overall win rate percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "kda_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="(Kills + Assists) / Deaths ratio",
                        max_digits=6,
                    ),
                ),
                (
                    "matches_last_7d",
                    models.IntegerField(default=0, help_text="Matches played in last 7 days"),
                ),
                (
                    "matches_last_30d",
                    models.IntegerField(default=0, help_text="Matches played in last 30 days"),
                ),
                (
                    "win_rate_7d",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Win rate in last 7 days",
                        max_digits=5,
                    ),
                ),
                (
                    "win_rate_30d",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Win rate in last 30 days",
                        max_digits=5,
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0,
                        help_text="Current win/loss streak (positive = wins, negative = losses)",
                    ),
                ),
                (
                    "longest_win_streak",
                    models.IntegerField(default=0, help_text="Longest consecutive win streak"),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("diamond", "Diamond"),
                            ("crown", "Crown"),
                        ],
                        db_index=True,
                        default="bronze",
                        help_text="Assigned tier based on ELO/MMR",
                        max_length=20,
                    ),
                ),
                (
                    "percentile_rank",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Percentile rank (0-100, higher = better)",
                        max_digits=5,
                    ),
                ),
                (
                    "recalculated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="When analytics were last computed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Analytics Snapshot",
                "verbose_name_plural": "User Analytics Snapshots",
                "db_table": "leaderboards_useranalyticssnapshot",
                "ordering": ["-elo_snapshot"],
            },
        ),
        migrations.CreateModel(
            name="UserMatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "game_slug",
                    models.CharField(
                        db_index=True,
                        help_text="Game identifier (valorant, csgo, etc.)",
                        max_length=100,
                    ),
                ),
                ("is_winner", models.BooleanField(default=False)),
                ("is_draw", models.BooleanField(default=False)),
                (
                    "opponent_user_id",
                    models.IntegerField(
                        blank=True, help_text="Opponent user ID (for 1v1 matches)", null=True
                    ),
                ),
                (
                    "opponent_name",
                    models.CharField(
                        blank=True,
                        help_text="Opponent display name (cached for performance)",
                        max_length=255,
                    ),
                ),
                (
                    "score_summary",
                    models.CharField(
                        blank=True,
                        help_text="Score summary (e.g., '13-7', '2-1', etc.)",
                        max_length=100,
                    ),
                ),
                ("kills", models.IntegerField(default=0, help_text="Kills in match")),
                ("deaths", models.IntegerField(default=0, help_text="Deaths in match")),
                ("assists", models.IntegerField(default=0, help_text="Assists in match")),
                (
                    "had_dispute",
                    models.BooleanField(default=False, help_text="Whether match had dispute(s)"),
                ),
                (
                    "is_forfeit",
                    models.BooleanField(default=False, help_text="Whether match ended in forfeit"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        db_index=True, help_text="When match was completed/finalized"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Match History",
                "verbose_name_plural": "User Match Histories",
                "db_table": "leaderboards_usermatchhistory",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "game_slug",
                    models.CharField(
                        db_index=True,
                        help_text="Game identifier (e.g., 'valorant', 'csgo')",
                        max_length=100,
                    ),
                ),
                ("matches_played", models.IntegerField(default=0)),
                ("matches_won", models.IntegerField(default=0)),
                ("matches_lost", models.IntegerField(default=0)),
                ("matches_drawn", models.IntegerField(default=0)),
                ("tournaments_played", models.IntegerField(default=0)),
                ("tournaments_won", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Win percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "total_kills",
                    models.IntegerField(
                        default=0, help_text="Total eliminations across all matches"
                    ),
                ),
                (
                    "total_deaths",
                    models.IntegerField(default=0, help_text="Total deaths across all matches"),
                ),
                (
                    "kd_ratio",
                    models.DecimalField(
                        decimal_places=2, default=0.0, help_text="Kill/Death ratio", max_digits=6
                    ),
                ),
                ("last_match_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Stats",
                "verbose_name_plural": "User Stats",
                "db_table": "leaderboards_userstats",
            },
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("tournament", "Tournament"),
                            ("seasonal", "Seasonal"),
                            ("all_time", "All-Time"),
                            ("team", "Team"),
                            ("game_specific", "Game-Specific"),
                            ("mmr", "MMR Ranking"),
                            ("elo", "ELO Ranking"),
                            ("tier", "Tier Ranking"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("game", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("season", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Generic entity ID (user ID or team ID) - preferred over FK for performance",
                        null=True,
                    ),
                ),
                ("rank", models.IntegerField(db_index=True)),
                ("points", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("win_rate", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                (
                    "payload_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible payload: {'tier': str, 'percentile': float, 'streak': int, 'kda': float, ...}",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "computed_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="When leaderboard entry was last computed (Epic 8.5)",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leaderboards_leaderboardentry",
            },
        ),
    ]
