# Generated by Django 5.2.8 on 2025-11-16 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('tournament', 'Tournament'), ('seasonal', 'Seasonal'), ('all_time', 'All-Time'), ('team', 'Team'), ('game_specific', 'Game-Specific')], db_index=True, max_length=50)),
                ('game', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('season', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('rank', models.IntegerField(db_index=True)),
                ('points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='teams.team')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'leaderboards_leaderboardentry',
                'indexes': [models.Index(fields=['leaderboard_type', 'rank'], name='leaderboard_leaderb_35e213_idx'), models.Index(fields=['leaderboard_type', 'tournament', 'rank'], name='leaderboard_leaderb_aff9f0_idx'), models.Index(fields=['leaderboard_type', 'game', 'season', 'rank'], name='leaderboard_leaderb_afaebc_idx'), models.Index(fields=['player', 'leaderboard_type'], name='leaderboard_player__14c389_idx'), models.Index(fields=['team', 'leaderboard_type'], name='leaderboard_team_id_c5888f_idx'), models.Index(fields=['is_active', 'leaderboard_type', 'rank'], name='leaderboard_is_acti_1ef874_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('player__isnull', False), ('tournament__isnull', False)), fields=('leaderboard_type', 'tournament', 'player'), name='unique_tournament_player'), models.UniqueConstraint(condition=models.Q(('team__isnull', False), ('tournament__isnull', False)), fields=('leaderboard_type', 'tournament', 'team'), name='unique_tournament_team')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('leaderboard_type', models.CharField(db_index=True, max_length=50)),
                ('rank', models.IntegerField()),
                ('points', models.IntegerField()),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to='teams.team')),
            ],
            options={
                'db_table': 'leaderboards_leaderboardsnapshot',
                'indexes': [models.Index(fields=['player', 'date'], name='leaderboard_player__80423f_idx'), models.Index(fields=['team', 'date'], name='leaderboard_team_id_ce9d87_idx'), models.Index(fields=['date', 'leaderboard_type'], name='leaderboard_date_8eece9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('date', 'leaderboard_type', 'player'), name='unique_snapshot_player'), models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('date', 'leaderboard_type', 'team'), name='unique_snapshot_team')],
            },
        ),
    ]
