# Generated by Django 5.2.8 on 2025-12-09 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slug', models.CharField(db_index=True, help_text="Game identifier (e.g., 'valorant', 'csgo')", max_length=100)),
                ('matches_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('matches_drawn', models.IntegerField(default=0)),
                ('tournaments_played', models.IntegerField(default=0)),
                ('tournaments_won', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Win percentage (0-100)', max_digits=5)),
                ('total_kills', models.IntegerField(default=0, help_text='Total eliminations across all matches')),
                ('total_deaths', models.IntegerField(default=0, help_text='Total deaths across all matches')),
                ('kd_ratio', models.DecimalField(decimal_places=2, default=0.0, help_text='Kill/Death ratio', max_digits=6)),
                ('last_match_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
                'db_table': 'leaderboards_userstats',
                'indexes': [models.Index(fields=['user', 'game_slug'], name='leaderboard_user_id_d85fa1_idx'), models.Index(fields=['game_slug', 'matches_played'], name='leaderboard_game_sl_4e66a7_idx'), models.Index(fields=['game_slug', 'win_rate'], name='leaderboard_game_sl_75bbd5_idx'), models.Index(fields=['game_slug', 'kd_ratio'], name='leaderboard_game_sl_a5a385_idx'), models.Index(fields=['last_match_at'], name='leaderboard_last_ma_81def1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'game_slug'), name='unique_user_game_stats')],
            },
        ),
    ]
