# Generated by Django 5.2.8 on 2026-01-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False  # Changed from True - FK additions must run after initial batch

    dependencies = [
        ("leaderboards", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboard_entries",
                to="teams.team",
            ),
        ),
    ]
