# Generated by Django 5.2.8 on 2025-12-10 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_user_stats_epic82'),
        ('teams', '0020_teammembership_is_role_custom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slug', models.CharField(db_index=True, help_text='Game identifier for this ranking ladder', max_length=100)),
                ('elo_rating', models.IntegerField(default=1200, help_text='Current ELO rating (default 1200 for new teams)')),
                ('peak_elo', models.IntegerField(default=1200, help_text='Highest ELO rating achieved')),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, help_text='Current rank position (1 = top team), computed via queries', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rankings', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Ranking',
                'verbose_name_plural': 'Team Rankings',
                'db_table': 'leaderboards_teamranking',
                'ordering': ['-elo_rating'],
                'indexes': [models.Index(fields=['team', 'game_slug'], name='leaderboard_team_id_1c6ff3_idx'), models.Index(fields=['game_slug', '-elo_rating'], name='leaderboard_game_sl_865c00_idx'), models.Index(fields=['game_slug', 'rank'], name='leaderboard_game_sl_16edc7_idx'), models.Index(fields=['last_updated'], name='leaderboard_last_up_b91729_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'game_slug'), name='unique_team_game_ranking')],
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slug', models.CharField(db_index=True, help_text="Game identifier (e.g., 'valorant', 'csgo')", max_length=100)),
                ('matches_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('matches_drawn', models.IntegerField(default=0)),
                ('tournaments_played', models.IntegerField(default=0)),
                ('tournaments_won', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Win percentage (0-100)', max_digits=5)),
                ('last_match_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Stats',
                'verbose_name_plural': 'Team Stats',
                'db_table': 'leaderboards_teamstats',
                'indexes': [models.Index(fields=['team', 'game_slug'], name='leaderboard_team_id_81ffa2_idx'), models.Index(fields=['game_slug', 'matches_played'], name='leaderboard_game_sl_76fed4_idx'), models.Index(fields=['game_slug', 'win_rate'], name='leaderboard_game_sl_a0b775_idx'), models.Index(fields=['last_match_at'], name='leaderboard_last_ma_5224b7_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'game_slug'), name='unique_team_game_stats')],
            },
        ),
    ]
