# Generated by Django 5.2.8 on 2026-01-23 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leaderboards", "0002_initial"),
        ("teams", "0001_initial"),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboard_entries",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="leaderboardsnapshot",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboard_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaderboardsnapshot",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboard_snapshots",
                to="teams.team",
            ),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(
                fields=["is_active", "start_date"], name="leaderboard_is_acti_bccd35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(
                fields=["start_date", "end_date"], name="leaderboard_start_d_f0430a_idx"
            ),
        ),
        migrations.AddField(
            model_name="teamanalyticssnapshot",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_snapshots",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teammatchhistory",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_history_entries",
                to="tournaments.match",
            ),
        ),
        migrations.AddField(
            model_name="teammatchhistory",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_history",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teammatchhistory",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_match_history",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="teamranking",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_rankings",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_stats",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="useranalyticssnapshot",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usermatchhistory",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_history_entries",
                to="tournaments.match",
            ),
        ),
        migrations.AddField(
            model_name="usermatchhistory",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_match_history",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="usermatchhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userstats",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["leaderboard_type", "rank"], name="leaderboard_leaderb_35e213_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["leaderboard_type", "tournament", "rank"],
                name="leaderboard_leaderb_aff9f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["leaderboard_type", "game", "season", "rank"],
                name="leaderboard_leaderb_afaebc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["player", "leaderboard_type"], name="leaderboard_player__14c389_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["team", "leaderboard_type"], name="leaderboard_team_id_c5888f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["is_active", "leaderboard_type", "rank"],
                name="leaderboard_is_acti_1ef874_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["reference_id", "leaderboard_type"], name="leaderboard_referen_c42db6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["game", "leaderboard_type", "-points"], name="leaderboard_game_9389ce_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderboardentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("player__isnull", False), ("tournament__isnull", False)),
                fields=("leaderboard_type", "tournament", "player"),
                name="unique_tournament_player",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderboardentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("team__isnull", False), ("tournament__isnull", False)),
                fields=("leaderboard_type", "tournament", "team"),
                name="unique_tournament_team",
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardsnapshot",
            index=models.Index(fields=["player", "date"], name="leaderboard_player__80423f_idx"),
        ),
        migrations.AddIndex(
            model_name="leaderboardsnapshot",
            index=models.Index(fields=["team", "date"], name="leaderboard_team_id_ce9d87_idx"),
        ),
        migrations.AddIndex(
            model_name="leaderboardsnapshot",
            index=models.Index(
                fields=["date", "leaderboard_type"], name="leaderboard_date_8eece9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderboardsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("player__isnull", False)),
                fields=("date", "leaderboard_type", "player"),
                name="unique_snapshot_player",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderboardsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("team__isnull", False)),
                fields=("date", "leaderboard_type", "team"),
                name="unique_snapshot_team",
            ),
        ),
        migrations.AddIndex(
            model_name="teamanalyticssnapshot",
            index=models.Index(fields=["team", "game_slug"], name="leaderboard_team_id_a77cbf_idx"),
        ),
        migrations.AddIndex(
            model_name="teamanalyticssnapshot",
            index=models.Index(
                fields=["game_slug", "-elo_snapshot"], name="leaderboard_game_sl_a12ff8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamanalyticssnapshot",
            index=models.Index(
                fields=["game_slug", "tier", "-elo_snapshot"], name="leaderboard_game_sl_3d813b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamanalyticssnapshot",
            index=models.Index(
                fields=["game_slug", "-percentile_rank"], name="leaderboard_game_sl_b1407f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamanalyticssnapshot",
            index=models.Index(fields=["recalculated_at"], name="leaderboard_recalcu_6833bf_idx"),
        ),
        migrations.AddConstraint(
            model_name="teamanalyticssnapshot",
            constraint=models.UniqueConstraint(
                fields=("team", "game_slug"), name="unique_team_game_analytics"
            ),
        ),
        migrations.AddIndex(
            model_name="teammatchhistory",
            index=models.Index(
                fields=["team", "-completed_at"], name="leaderboard_team_id_692d3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammatchhistory",
            index=models.Index(
                fields=["tournament", "-completed_at"], name="leaderboard_tournam_c5ac57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammatchhistory",
            index=models.Index(
                fields=["game_slug", "-completed_at"], name="leaderboard_game_sl_e86182_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammatchhistory",
            index=models.Index(
                fields=["team", "game_slug", "-completed_at"], name="leaderboard_team_id_97fd93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamranking",
            index=models.Index(fields=["team", "game_slug"], name="leaderboard_team_id_1c6ff3_idx"),
        ),
        migrations.AddIndex(
            model_name="teamranking",
            index=models.Index(
                fields=["game_slug", "-elo_rating"], name="leaderboard_game_sl_865c00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamranking",
            index=models.Index(fields=["game_slug", "rank"], name="leaderboard_game_sl_16edc7_idx"),
        ),
        migrations.AddIndex(
            model_name="teamranking",
            index=models.Index(fields=["last_updated"], name="leaderboard_last_up_b91729_idx"),
        ),
        migrations.AddConstraint(
            model_name="teamranking",
            constraint=models.UniqueConstraint(
                fields=("team", "game_slug"), name="unique_team_game_ranking"
            ),
        ),
        migrations.AddIndex(
            model_name="teamstats",
            index=models.Index(fields=["team", "game_slug"], name="leaderboard_team_id_81ffa2_idx"),
        ),
        migrations.AddIndex(
            model_name="teamstats",
            index=models.Index(
                fields=["game_slug", "matches_played"], name="leaderboard_game_sl_76fed4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamstats",
            index=models.Index(
                fields=["game_slug", "win_rate"], name="leaderboard_game_sl_a0b775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamstats",
            index=models.Index(fields=["last_match_at"], name="leaderboard_last_ma_5224b7_idx"),
        ),
        migrations.AddConstraint(
            model_name="teamstats",
            constraint=models.UniqueConstraint(
                fields=("team", "game_slug"), name="unique_team_game_stats"
            ),
        ),
        migrations.AddIndex(
            model_name="useranalyticssnapshot",
            index=models.Index(fields=["user", "game_slug"], name="leaderboard_user_id_d6ec6f_idx"),
        ),
        migrations.AddIndex(
            model_name="useranalyticssnapshot",
            index=models.Index(
                fields=["game_slug", "-elo_snapshot"], name="leaderboard_game_sl_c0cb80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useranalyticssnapshot",
            index=models.Index(
                fields=["game_slug", "tier", "-elo_snapshot"], name="leaderboard_game_sl_4da4e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useranalyticssnapshot",
            index=models.Index(
                fields=["game_slug", "-percentile_rank"], name="leaderboard_game_sl_228280_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useranalyticssnapshot",
            index=models.Index(fields=["recalculated_at"], name="leaderboard_recalcu_930219_idx"),
        ),
        migrations.AddConstraint(
            model_name="useranalyticssnapshot",
            constraint=models.UniqueConstraint(
                fields=("user", "game_slug"), name="unique_user_game_analytics"
            ),
        ),
        migrations.AddIndex(
            model_name="usermatchhistory",
            index=models.Index(
                fields=["user", "-completed_at"], name="leaderboard_user_id_e48e32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermatchhistory",
            index=models.Index(
                fields=["tournament", "-completed_at"], name="leaderboard_tournam_e32a14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermatchhistory",
            index=models.Index(
                fields=["game_slug", "-completed_at"], name="leaderboard_game_sl_bf9a5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermatchhistory",
            index=models.Index(
                fields=["user", "game_slug", "-completed_at"], name="leaderboard_user_id_4c7d03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(fields=["user", "game_slug"], name="leaderboard_user_id_d85fa1_idx"),
        ),
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(
                fields=["game_slug", "matches_played"], name="leaderboard_game_sl_4e66a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(
                fields=["game_slug", "win_rate"], name="leaderboard_game_sl_75bbd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(
                fields=["game_slug", "kd_ratio"], name="leaderboard_game_sl_a5a385_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(fields=["last_match_at"], name="leaderboard_last_ma_81def1_idx"),
        ),
        migrations.AddConstraint(
            model_name="userstats",
            constraint=models.UniqueConstraint(
                fields=("user", "game_slug"), name="unique_user_game_stats"
            ),
        ),
    ]
