# Generated by Django 5.2.8 on 2025-12-10 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_team_stats_and_ranking_epic83'),
        ('teams', '0020_teammembership_is_role_custom_and_more'),
        ('tournaments', '0029_add_audit_log_epic75_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slug', models.CharField(db_index=True, help_text='Game identifier', max_length=100)),
                ('is_winner', models.BooleanField(default=False)),
                ('is_draw', models.BooleanField(default=False)),
                ('opponent_team_id', models.IntegerField(blank=True, help_text='Opponent team ID', null=True)),
                ('opponent_team_name', models.CharField(blank=True, help_text='Opponent team name (cached)', max_length=255)),
                ('score_summary', models.CharField(blank=True, help_text='Score summary for timeline display', max_length=100)),
                ('elo_before', models.IntegerField(blank=True, help_text='Team ELO before match', null=True)),
                ('elo_after', models.IntegerField(blank=True, help_text='Team ELO after match', null=True)),
                ('elo_change', models.IntegerField(default=0, help_text='ELO rating change from match')),
                ('had_dispute', models.BooleanField(default=False)),
                ('is_forfeit', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_history_entries', to='tournaments.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_match_history', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Team Match History',
                'verbose_name_plural': 'Team Match Histories',
                'db_table': 'leaderboards_teammatchhistory',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['team', '-completed_at'], name='leaderboard_team_id_692d3f_idx'), models.Index(fields=['tournament', '-completed_at'], name='leaderboard_tournam_c5ac57_idx'), models.Index(fields=['game_slug', '-completed_at'], name='leaderboard_game_sl_e86182_idx'), models.Index(fields=['team', 'game_slug', '-completed_at'], name='leaderboard_team_id_97fd93_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slug', models.CharField(db_index=True, help_text='Game identifier (valorant, csgo, etc.)', max_length=100)),
                ('is_winner', models.BooleanField(default=False)),
                ('is_draw', models.BooleanField(default=False)),
                ('opponent_user_id', models.IntegerField(blank=True, help_text='Opponent user ID (for 1v1 matches)', null=True)),
                ('opponent_name', models.CharField(blank=True, help_text='Opponent display name (cached for performance)', max_length=255)),
                ('score_summary', models.CharField(blank=True, help_text="Score summary (e.g., '13-7', '2-1', etc.)", max_length=100)),
                ('kills', models.IntegerField(default=0, help_text='Kills in match')),
                ('deaths', models.IntegerField(default=0, help_text='Deaths in match')),
                ('assists', models.IntegerField(default=0, help_text='Assists in match')),
                ('had_dispute', models.BooleanField(default=False, help_text='Whether match had dispute(s)')),
                ('is_forfeit', models.BooleanField(default=False, help_text='Whether match ended in forfeit')),
                ('completed_at', models.DateTimeField(db_index=True, help_text='When match was completed/finalized')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history_entries', to='tournaments.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_match_history', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Match History',
                'verbose_name_plural': 'User Match Histories',
                'db_table': 'leaderboards_usermatchhistory',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', '-completed_at'], name='leaderboard_user_id_e48e32_idx'), models.Index(fields=['tournament', '-completed_at'], name='leaderboard_tournam_e32a14_idx'), models.Index(fields=['game_slug', '-completed_at'], name='leaderboard_game_sl_bf9a5e_idx'), models.Index(fields=['user', 'game_slug', '-completed_at'], name='leaderboard_user_id_4c7d03_idx')],
            },
        ),
    ]
