# Generated by Django 5.2.8 on 2025-12-10 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0004_match_history_epic84'),
        ('teams', '0020_teammembership_is_role_custom_and_more'),
        ('tournaments', '0029_add_audit_log_epic75_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(db_index=True, help_text="Unique season identifier (e.g., 'S1-2024', 'WINTER-2024')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Season 1 - 2024', 'Winter Championship 2024')", max_length=100)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether season is currently active (only one active season per time)')),
                ('decay_rules_json', models.JSONField(blank=True, default=dict, help_text="Decay rules: {'enabled': bool, 'days_inactive': int, 'decay_percentage': float, 'min_elo': int}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'db_table': 'leaderboards_season',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slug', models.CharField(db_index=True, help_text='Game identifier', max_length=100)),
                ('elo_snapshot', models.IntegerField(default=1200, help_text='Team ELO rating snapshot')),
                ('elo_volatility', models.DecimalField(decimal_places=2, default=0.0, help_text='ELO volatility (standard deviation of recent changes)', max_digits=6)),
                ('avg_member_skill', models.DecimalField(decimal_places=2, default=1200.0, help_text='Average skill rating of active team members', max_digits=8)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall win rate percentage', max_digits=5)),
                ('win_rate_7d', models.DecimalField(decimal_places=2, default=0.0, help_text='Win rate in last 7 days', max_digits=5)),
                ('win_rate_30d', models.DecimalField(decimal_places=2, default=0.0, help_text='Win rate in last 30 days', max_digits=5)),
                ('synergy_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Team synergy score (0-100, based on consistency)', max_digits=5)),
                ('activity_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Activity score (0-100, based on recent match participation)', max_digits=5)),
                ('matches_last_7d', models.IntegerField(default=0)),
                ('matches_last_30d', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond'), ('crown', 'Crown')], db_index=True, default='bronze', help_text='Assigned tier based on team ELO', max_length=20)),
                ('percentile_rank', models.DecimalField(decimal_places=2, default=50.0, help_text='Percentile rank among all teams (0-100)', max_digits=5)),
                ('recalculated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When analytics were last computed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Analytics Snapshot',
                'verbose_name_plural': 'Team Analytics Snapshots',
                'db_table': 'leaderboards_teamanalyticssnapshot',
                'ordering': ['-elo_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='UserAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slug', models.CharField(db_index=True, help_text='Game identifier', max_length=100)),
                ('mmr_snapshot', models.IntegerField(default=1200, help_text='MMR snapshot at calculation time (for MMR-based games)')),
                ('elo_snapshot', models.IntegerField(default=1200, help_text='ELO snapshot at calculation time (fallback/alternative)')),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall win rate percentage (0-100)', max_digits=5)),
                ('kda_ratio', models.DecimalField(decimal_places=2, default=0.0, help_text='(Kills + Assists) / Deaths ratio', max_digits=6)),
                ('matches_last_7d', models.IntegerField(default=0, help_text='Matches played in last 7 days')),
                ('matches_last_30d', models.IntegerField(default=0, help_text='Matches played in last 30 days')),
                ('win_rate_7d', models.DecimalField(decimal_places=2, default=0.0, help_text='Win rate in last 7 days', max_digits=5)),
                ('win_rate_30d', models.DecimalField(decimal_places=2, default=0.0, help_text='Win rate in last 30 days', max_digits=5)),
                ('current_streak', models.IntegerField(default=0, help_text='Current win/loss streak (positive = wins, negative = losses)')),
                ('longest_win_streak', models.IntegerField(default=0, help_text='Longest consecutive win streak')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond'), ('crown', 'Crown')], db_index=True, default='bronze', help_text='Assigned tier based on ELO/MMR', max_length=20)),
                ('percentile_rank', models.DecimalField(decimal_places=2, default=50.0, help_text='Percentile rank (0-100, higher = better)', max_digits=5)),
                ('recalculated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When analytics were last computed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Analytics Snapshot',
                'verbose_name_plural': 'User Analytics Snapshots',
                'db_table': 'leaderboards_useranalyticssnapshot',
                'ordering': ['-elo_snapshot'],
            },
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='computed_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='When leaderboard entry was last computed (Epic 8.5)'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='payload_json',
            field=models.JSONField(blank=True, default=dict, help_text="Flexible payload: {'tier': str, 'percentile': float, 'streak': int, 'kda': float, ...}"),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='reference_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Generic entity ID (user ID or team ID) - preferred over FK for performance', null=True),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leaderboard_type',
            field=models.CharField(choices=[('tournament', 'Tournament'), ('seasonal', 'Seasonal'), ('all_time', 'All-Time'), ('team', 'Team'), ('game_specific', 'Game-Specific'), ('mmr', 'MMR Ranking'), ('elo', 'ELO Ranking'), ('tier', 'Tier Ranking')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['reference_id', 'leaderboard_type'], name='leaderboard_referen_c42db6_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['game', 'leaderboard_type', '-points'], name='leaderboard_game_9389ce_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['is_active', 'start_date'], name='leaderboard_is_acti_bccd35_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['start_date', 'end_date'], name='leaderboard_start_d_f0430a_idx'),
        ),
        migrations.AddField(
            model_name='teamanalyticssnapshot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='teams.team'),
        ),
        migrations.AddField(
            model_name='useranalyticssnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teamanalyticssnapshot',
            index=models.Index(fields=['team', 'game_slug'], name='leaderboard_team_id_a77cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='teamanalyticssnapshot',
            index=models.Index(fields=['game_slug', '-elo_snapshot'], name='leaderboard_game_sl_a12ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='teamanalyticssnapshot',
            index=models.Index(fields=['game_slug', 'tier', '-elo_snapshot'], name='leaderboard_game_sl_3d813b_idx'),
        ),
        migrations.AddIndex(
            model_name='teamanalyticssnapshot',
            index=models.Index(fields=['game_slug', '-percentile_rank'], name='leaderboard_game_sl_b1407f_idx'),
        ),
        migrations.AddIndex(
            model_name='teamanalyticssnapshot',
            index=models.Index(fields=['recalculated_at'], name='leaderboard_recalcu_6833bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamanalyticssnapshot',
            constraint=models.UniqueConstraint(fields=('team', 'game_slug'), name='unique_team_game_analytics'),
        ),
        migrations.AddIndex(
            model_name='useranalyticssnapshot',
            index=models.Index(fields=['user', 'game_slug'], name='leaderboard_user_id_d6ec6f_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalyticssnapshot',
            index=models.Index(fields=['game_slug', '-elo_snapshot'], name='leaderboard_game_sl_c0cb80_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalyticssnapshot',
            index=models.Index(fields=['game_slug', 'tier', '-elo_snapshot'], name='leaderboard_game_sl_4da4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalyticssnapshot',
            index=models.Index(fields=['game_slug', '-percentile_rank'], name='leaderboard_game_sl_228280_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalyticssnapshot',
            index=models.Index(fields=['recalculated_at'], name='leaderboard_recalcu_930219_idx'),
        ),
        migrations.AddConstraint(
            model_name='useranalyticssnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'game_slug'), name='unique_user_game_analytics'),
        ),
    ]
