# Generated by Django 5.2.8 on 2026-01-23 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("user_profile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessagereaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_reactions",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="chatreadreceipt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_read_receipts",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="chattypingindicator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="typing_indicators",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="codmplayermembership",
            name="profile",
            field=models.ForeignKey(
                help_text="Player profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_memberships",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="codmteam",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                help_text="Team captain (must be a team member)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_captain_teams",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="codmplayermembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codm_memberships",
                to="teams.codmteam",
            ),
        ),
        migrations.AddField(
            model_name="cs2playermembership",
            name="profile",
            field=models.ForeignKey(
                help_text="Player profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_memberships",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="cs2team",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                help_text="Team captain (must be a team member)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_captain_teams",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="cs2playermembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cs2_memberships",
                to="teams.cs2team",
            ),
        ),
        migrations.AddField(
            model_name="discussionnotification",
            name="actor",
            field=models.ForeignKey(
                help_text="User who triggered the notification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussion_actions",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="discussionnotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussion_notifications",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="discussionsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussion_subscriptions",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="dota2playermembership",
            name="profile",
            field=models.ForeignKey(
                help_text="Player profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_memberships",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="dota2team",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                help_text="Team captain (must be a team member)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_captain_teams",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="dota2playermembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dota2_memberships",
                to="teams.dota2team",
            ),
        ),
        migrations.AddField(
            model_name="efootballplayermembership",
            name="profile",
            field=models.ForeignKey(
                help_text="Player profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_memberships",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="efootballteam",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                help_text="Team captain (must be a team member)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_captain_teams",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="efootballplayermembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="efootball_memberships",
                to="teams.efootballteam",
            ),
        ),
        migrations.AddField(
            model_name="efootballteampreset",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="efootball_presets",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="fc26playermembership",
            name="profile",
            field=models.ForeignKey(
                help_text="Player profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_memberships",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="fc26team",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                help_text="Team captain (must be a team member)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_captain_teams",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="fc26playermembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fc26_memberships",
                to="teams.fc26team",
            ),
        ),
        migrations.AddField(
            model_name="freefireplayermembership",
            name="profile",
            field=models.ForeignKey(
                help_text="Player profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_memberships",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="freefireteam",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                help_text="Team captain (must be a team member)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_captain_teams",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="freefireplayermembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freefire_memberships",
                to="teams.freefireteam",
            ),
        ),
        migrations.AddField(
            model_name="matchparticipation",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_participation_records",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="matchrecord",
            name="participants",
            field=models.ManyToManyField(
                related_name="match_participations",
                through="teams.MatchParticipation",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="matchparticipation",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_participations",
                to="teams.matchrecord",
            ),
        ),
        migrations.AddField(
            model_name="mlbbplayermembership",
            name="profile",
            field=models.ForeignKey(
                help_text="Player profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_memberships",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="mlbbteam",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                help_text="Team captain (must be a team member)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_captain_teams",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="mlbbplayermembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mlbb_memberships",
                to="teams.mlbbteam",
            ),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_statistics",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="pubgplayermembership",
            name="profile",
            field=models.ForeignKey(
                help_text="Player profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_memberships",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="pubgteam",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                help_text="Team captain (must be a team member)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_captain_teams",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="pubgplayermembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pubg_memberships",
                to="teams.pubgteam",
            ),
        ),
        migrations.AddField(
            model_name="sponsorinquiry",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_inquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TeamRankingBreakdown",
            fields=[
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ranking_breakdown",
                        serialize=False,
                        to="teams.team",
                    ),
                ),
                ("tournament_participation_points", models.PositiveIntegerField(default=0)),
                ("tournament_winner_points", models.PositiveIntegerField(default=0)),
                ("tournament_runner_up_points", models.PositiveIntegerField(default=0)),
                ("tournament_top_4_points", models.PositiveIntegerField(default=0)),
                ("member_count_points", models.PositiveIntegerField(default=0)),
                ("team_age_points", models.PositiveIntegerField(default=0)),
                ("achievement_points", models.PositiveIntegerField(default=0)),
                ("manual_adjustment_points", models.IntegerField(default=0)),
                (
                    "calculated_total",
                    models.PositiveIntegerField(
                        default=0, help_text="Sum of all automatic point calculations"
                    ),
                ),
                (
                    "final_total",
                    models.PositiveIntegerField(
                        default=0, help_text="Final total including manual adjustments"
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team Ranking Breakdown",
                "verbose_name_plural": "Team Ranking Breakdowns",
                "db_table": "teams_ranking_breakdown",
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["-total_points", "name"], name="teams_leaderboard_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["game", "-total_points"], name="teams_game_leader_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["-created_at"], name="teams_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["game", "is_public", "is_active"], name="team_listing_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["game", "region", "is_active"], name="team_region_idx"),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug", ""), _negated=True),
                fields=("game", "slug"),
                name="uniq_team_slug_per_game",
            ),
        ),
        migrations.AddField(
            model_name="sponsorinquiry",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsor_inquiries",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_stats",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="matchrecord",
            name="opponent_team",
            field=models.ForeignKey(
                blank=True,
                help_text="Opponent team (if in our system)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_against",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="matchrecord",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_records",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="chattypingindicator",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="typing_indicators",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="chatreadreceipt",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_read_receipts",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamachievement",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamactivity",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_activities",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamactivity",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentioned_in_activities",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamactivity",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamanalytics",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamchatmessage",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users mentioned in this message (@username)",
                related_name="mentioned_in_messages",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamchatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Original message if this is a reply",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="teams.teamchatmessage",
            ),
        ),
        migrations.AddField(
            model_name="teamchatmessage",
            name="sender",
            field=models.ForeignKey(
                help_text="User who sent the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamchatmessage",
            name="team",
            field=models.ForeignKey(
                help_text="Team this message belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="chatreadreceipt",
            name="last_read_message",
            field=models.ForeignKey(
                help_text="Last message read by this user in this team",
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.teamchatmessage",
            ),
        ),
        migrations.AddField(
            model_name="chatmessagereaction",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="teams.teamchatmessage",
            ),
        ),
        migrations.AddField(
            model_name="teamdiscussioncomment",
            name="author",
            field=models.ForeignKey(
                help_text="User who wrote the comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussion_comments",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamdiscussioncomment",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who liked this comment",
                related_name="liked_comments",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamdiscussioncomment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent comment if this is a reply",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="teams.teamdiscussioncomment",
            ),
        ),
        migrations.AddField(
            model_name="discussionnotification",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="teams.teamdiscussioncomment",
            ),
        ),
        migrations.AddField(
            model_name="teamdiscussionpost",
            name="author",
            field=models.ForeignKey(
                help_text="User who created the post",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussion_posts",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamdiscussionpost",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who liked this post",
                related_name="liked_posts",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamdiscussionpost",
            name="team",
            field=models.ForeignKey(
                help_text="Team this post belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussion_posts",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamdiscussioncomment",
            name="post",
            field=models.ForeignKey(
                help_text="Post this comment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="teams.teamdiscussionpost",
            ),
        ),
        migrations.AddField(
            model_name="discussionsubscription",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="teams.teamdiscussionpost",
            ),
        ),
        migrations.AddField(
            model_name="discussionnotification",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="teams.teamdiscussionpost",
            ),
        ),
        migrations.AddField(
            model_name="teamfollower",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_teams",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamfollower",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamgameranking",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_rankings",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teaminvite",
            name="invited_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_invites",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teaminvite",
            name="inviter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_team_invites",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teaminvite",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="teams.team"
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_join_requests",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_join_requests",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_memberships",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="role_changed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who last changed this member's role",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_changes_made",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teammerchitem",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merchandise",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamotp",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_otps",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamotp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teampost",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_posts",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teampost",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="teams.team"
            ),
        ),
        migrations.AddField(
            model_name="teamactivity",
            name="related_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.teampost",
            ),
        ),
        migrations.AddField(
            model_name="teampostcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_post_comments",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teampostcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="teams.teampostcomment",
            ),
        ),
        migrations.AddField(
            model_name="teampostcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="teams.teampost",
            ),
        ),
        migrations.AddField(
            model_name="teampostlike",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="teams.teampostcomment",
            ),
        ),
        migrations.AddField(
            model_name="teampostlike",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="teams.teampost",
            ),
        ),
        migrations.AddField(
            model_name="teampostlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_post_likes",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teampostmedia",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="teams.teampost",
            ),
        ),
        migrations.AddField(
            model_name="teampromotion",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_promotions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teampromotion",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamrankinghistory",
            name="admin_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who made manual adjustment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teamrankinghistory",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranking_history",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamrankingsettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last admin who updated these settings",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teamsponsor",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_sponsors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teamsponsor",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsors",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="sponsorinquiry",
            name="converted_to_sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_inquiry",
                to="teams.teamsponsor",
            ),
        ),
        migrations.AddField(
            model_name="teamstats",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats_snapshots",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamtournamentregistration",
            name="payment_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_team_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teamtournamentregistration",
            name="registered_by",
            field=models.ForeignKey(
                help_text="Captain who registered the team",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team_tournament_registrations",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamtournamentregistration",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_registrations",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="tournamentparticipation",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_participations",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="tournamentparticipation",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="teams.teamtournamentregistration",
            ),
        ),
        migrations.AddField(
            model_name="tournamentrosterlock",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lock_history",
                to="teams.teamtournamentregistration",
            ),
        ),
        migrations.AddField(
            model_name="tournamentrosterlock",
            name="unlocked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who unlocked roster (if manual)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="valorantplayermembership",
            name="profile",
            field=models.ForeignKey(
                help_text="Player profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_memberships",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="valorantteam",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                help_text="Team captain (must be a team member)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_captain_teams",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="valorantplayermembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valorant_memberships",
                to="teams.valorantteam",
            ),
        ),
        migrations.AddField(
            model_name="valorantteampreset",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valorant_presets",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="valorantplayerpreset",
            name="preset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="teams.valorantteampreset",
            ),
        ),
        migrations.AddConstraint(
            model_name="codmteam",
            constraint=models.UniqueConstraint(
                fields=("game", "slug"), name="unique_codm_team_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="codmplayermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True), ("status", "ACTIVE")),
                fields=("team",),
                name="one_captain_per_codm_team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="codmplayermembership",
            unique_together={("team", "profile")},
        ),
        migrations.AddConstraint(
            model_name="cs2team",
            constraint=models.UniqueConstraint(
                fields=("game", "slug"), name="unique_cs2_team_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="cs2playermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True), ("status", "ACTIVE")),
                fields=("team",),
                name="one_captain_per_cs2_team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cs2playermembership",
            unique_together={("team", "profile")},
        ),
        migrations.AddConstraint(
            model_name="dota2team",
            constraint=models.UniqueConstraint(
                fields=("game", "slug"), name="unique_dota2_team_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="dota2playermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True), ("status", "ACTIVE")),
                fields=("team",),
                name="one_captain_per_dota2_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="dota2playermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_starter", True), ("status", "ACTIVE")),
                fields=("team", "role"),
                name="unique_dota2_position_per_team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dota2playermembership",
            unique_together={("team", "profile")},
        ),
        migrations.AddConstraint(
            model_name="efootballteam",
            constraint=models.UniqueConstraint(
                fields=("game", "slug"), name="unique_efootball_team_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="efootballplayermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True), ("status", "ACTIVE")),
                fields=("team",),
                name="one_captain_per_efootball_team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="efootballplayermembership",
            unique_together={("team", "profile")},
        ),
        migrations.AddConstraint(
            model_name="fc26team",
            constraint=models.UniqueConstraint(
                fields=("game", "slug"), name="unique_fc26_team_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="fc26playermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True), ("status", "ACTIVE")),
                fields=("team",),
                name="one_captain_per_fc26_team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fc26playermembership",
            unique_together={("team", "profile")},
        ),
        migrations.AddConstraint(
            model_name="freefireteam",
            constraint=models.UniqueConstraint(
                fields=("game", "slug"), name="unique_freefire_team_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="freefireplayermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True), ("status", "ACTIVE")),
                fields=("team",),
                name="one_captain_per_freefire_team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="freefireplayermembership",
            unique_together={("team", "profile")},
        ),
        migrations.AddIndex(
            model_name="matchparticipation",
            index=models.Index(fields=["match", "player"], name="teams_analy_match_i_8dd158_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="matchparticipation",
            unique_together={("match", "player")},
        ),
        migrations.AddConstraint(
            model_name="mlbbteam",
            constraint=models.UniqueConstraint(
                fields=("game", "slug"), name="unique_mlbb_team_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="mlbbplayermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True), ("status", "ACTIVE")),
                fields=("team",),
                name="one_captain_per_mlbb_team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mlbbplayermembership",
            unique_together={("team", "profile")},
        ),
        migrations.AddConstraint(
            model_name="pubgteam",
            constraint=models.UniqueConstraint(
                fields=("game", "slug"), name="unique_pubg_team_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="pubgplayermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True), ("status", "ACTIVE")),
                fields=("team",),
                name="one_captain_per_pubg_team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pubgplayermembership",
            unique_together={("team", "profile")},
        ),
        migrations.AddIndex(
            model_name="playerstats",
            index=models.Index(fields=["team", "game"], name="teams_analy_team_id_8ed44f_idx"),
        ),
        migrations.AddIndex(
            model_name="playerstats",
            index=models.Index(fields=["player", "game"], name="teams_analy_player__bfb65c_idx"),
        ),
        migrations.AddIndex(
            model_name="playerstats",
            index=models.Index(
                fields=["-contribution_score"], name="teams_analy_contrib_e5474b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerstats",
            index=models.Index(fields=["-mvp_count"], name="teams_analy_mvp_cou_6bcd28_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="playerstats",
            unique_together={("player", "team", "game")},
        ),
        migrations.AddIndex(
            model_name="matchrecord",
            index=models.Index(
                fields=["team", "-match_date"], name="teams_analy_team_id_a5ad31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchrecord",
            index=models.Index(
                fields=["tournament_id", "-match_date"], name="teams_analy_tournam_7636f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchrecord",
            index=models.Index(fields=["game", "-match_date"], name="teams_analy_game_55e342_idx"),
        ),
        migrations.AddIndex(
            model_name="matchrecord",
            index=models.Index(fields=["result"], name="teams_analy_result_f9a53e_idx"),
        ),
        migrations.AddIndex(
            model_name="chattypingindicator",
            index=models.Index(
                fields=["team", "started_typing_at"], name="teams_chat__team_id_281f41_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chattypingindicator",
            unique_together={("user", "team")},
        ),
        migrations.AddIndex(
            model_name="teamachievement",
            index=models.Index(fields=["team"], name="teams_teama_team_id_daea1e_idx"),
        ),
        migrations.AddIndex(
            model_name="teamachievement",
            index=models.Index(fields=["year"], name="teams_teama_year_42a46a_idx"),
        ),
        migrations.AddIndex(
            model_name="teamanalytics",
            index=models.Index(fields=["team", "game"], name="teams_analy_team_id_853a9b_idx"),
        ),
        migrations.AddIndex(
            model_name="teamanalytics",
            index=models.Index(fields=["win_rate"], name="teams_analy_win_rat_9aac2e_idx"),
        ),
        migrations.AddIndex(
            model_name="teamanalytics",
            index=models.Index(fields=["-total_points"], name="teams_analy_total_p_8f2287_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="teamanalytics",
            unique_together={("team", "game")},
        ),
        migrations.AddIndex(
            model_name="teamchatmessage",
            index=models.Index(
                fields=["team", "created_at"], name="teams_chat__team_id_ff7796_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamchatmessage",
            index=models.Index(
                fields=["sender", "created_at"], name="teams_chat__sender__73e26d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamchatmessage",
            index=models.Index(
                fields=["is_deleted", "created_at"], name="teams_chat__is_dele_3b2d20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatreadreceipt",
            index=models.Index(fields=["user", "team"], name="teams_chat__user_id_a4260e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="chatreadreceipt",
            unique_together={("user", "team")},
        ),
        migrations.AddIndex(
            model_name="chatmessagereaction",
            index=models.Index(fields=["message", "emoji"], name="teams_chat__message_723130_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="chatmessagereaction",
            unique_together={("message", "user", "emoji")},
        ),
        migrations.AddIndex(
            model_name="teamdiscussionpost",
            index=models.Index(
                fields=["team", "-last_activity_at"], name="teams_discu_team_id_3fe107_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamdiscussionpost",
            index=models.Index(
                fields=["team", "post_type", "-last_activity_at"],
                name="teams_discu_team_id_a3cadc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teamdiscussionpost",
            index=models.Index(
                fields=["author", "-created_at"], name="teams_discu_author__8de515_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamdiscussionpost",
            index=models.Index(
                fields=["-is_pinned", "-last_activity_at"], name="teams_discu_is_pinn_13f665_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamdiscussionpost",
            index=models.Index(fields=["is_deleted"], name="teams_discu_is_dele_2aa75f_idx"),
        ),
        migrations.AddIndex(
            model_name="teamdiscussioncomment",
            index=models.Index(
                fields=["post", "created_at"], name="teams_discu_post_id_ce7ee5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamdiscussioncomment",
            index=models.Index(
                fields=["author", "-created_at"], name="teams_discu_author__d85c29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamdiscussioncomment",
            index=models.Index(
                fields=["reply_to", "created_at"], name="teams_discu_reply_t_4a31ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussionsubscription",
            index=models.Index(
                fields=["user", "subscribed_at"], name="teams_discu_user_id_916d9b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="discussionsubscription",
            unique_together={("user", "post")},
        ),
        migrations.AddIndex(
            model_name="discussionnotification",
            index=models.Index(
                fields=["recipient", "-created_at"], name="teams_discu_recipie_e82748_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussionnotification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="teams_discu_recipie_22ea59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teamfollower",
            index=models.Index(
                fields=["team", "-followed_at"], name="teams_teamf_team_id_35cd4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamfollower",
            index=models.Index(
                fields=["follower", "-followed_at"], name="teams_teamf_followe_624478_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamfollower",
            unique_together={("team", "follower")},
        ),
        migrations.AddIndex(
            model_name="teamgameranking",
            index=models.Index(fields=["game", "-elo_rating"], name="ranking_game_elo_idx"),
        ),
        migrations.AddIndex(
            model_name="teamgameranking",
            index=models.Index(fields=["game", "-points"], name="ranking_game_points_idx"),
        ),
        migrations.AddIndex(
            model_name="teamgameranking",
            index=models.Index(fields=["-global_elo"], name="ranking_global_elo_idx"),
        ),
        migrations.AddIndex(
            model_name="teamgameranking",
            index=models.Index(
                fields=["game", "division", "-elo_rating"], name="ranking_division_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamgameranking",
            index=models.Index(fields=["team", "game"], name="ranking_team_game_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="teamgameranking",
            unique_together={("team", "game")},
        ),
        migrations.AddIndex(
            model_name="teaminvite",
            index=models.Index(fields=["team", "status"], name="teams_invite_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="teaminvite",
            index=models.Index(fields=["status", "expires_at"], name="teams_invite_expire_idx"),
        ),
        migrations.AddIndex(
            model_name="teamjoinrequest",
            index=models.Index(
                fields=["team", "status", "-created_at"], name="teams_teamj_team_id_373627_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamjoinrequest",
            index=models.Index(
                fields=["applicant", "status", "-created_at"], name="teams_teamj_applica_abd4cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamjoinrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="teams_teamj_status_5121d8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teamjoinrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("team", "applicant"),
                name="unique_pending_request_per_team",
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["team", "status"], name="teams_member_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["profile", "status"], name="teams_user_teams_idx"),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["team", "role"], name="teams_role_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["locked_for_tournament_id", "locked_until"],
                name="teams_tournament_lock_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["team", "status", "role"], name="membership_active_idx"),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["profile", "status"], name="membership_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "OWNER"), ("status", "ACTIVE")),
                fields=("team",),
                name="uq_one_active_owner_per_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True), ("status", "ACTIVE")),
                fields=("team",),
                name="uq_one_captain_title_per_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "CAPTAIN"), ("status", "ACTIVE")),
                fields=("team",),
                name="uq_one_active_captain_per_team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teammembership",
            unique_together={("team", "profile")},
        ),
        migrations.AddIndex(
            model_name="teammerchitem",
            index=models.Index(fields=["team", "is_active"], name="teams_teamm_team_id_cdb49d_idx"),
        ),
        migrations.AddIndex(
            model_name="teammerchitem",
            index=models.Index(fields=["sku"], name="teams_teamm_sku_f66d44_idx"),
        ),
        migrations.AddIndex(
            model_name="teammerchitem",
            index=models.Index(
                fields=["is_featured", "is_active"], name="teams_teamm_is_feat_1ad750_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamotp",
            index=models.Index(
                fields=["user", "team", "purpose", "is_used"], name="teams_teamo_user_id_8005dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamotp",
            index=models.Index(fields=["code", "expires_at"], name="teams_teamo_code_0367a6_idx"),
        ),
        migrations.AddIndex(
            model_name="teampost",
            index=models.Index(
                fields=["team", "-created_at"], name="teams_teamp_team_id_6f448f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teampost",
            index=models.Index(
                fields=["visibility", "-created_at"], name="teams_teamp_visibil_eb0e6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teampost",
            index=models.Index(
                fields=["is_featured", "-created_at"], name="teams_teamp_is_feat_3e4ac8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamactivity",
            index=models.Index(
                fields=["team", "-created_at"], name="teams_teama_team_id_66ed68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamactivity",
            index=models.Index(
                fields=["activity_type", "-created_at"], name="teams_teama_activit_c585a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamactivity",
            index=models.Index(
                fields=["is_public", "-created_at"], name="teams_teama_is_publ_3d9302_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teampostcomment",
            index=models.Index(
                fields=["post", "created_at"], name="teams_teamp_post_id_d011f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teampostcomment",
            index=models.Index(
                fields=["parent", "created_at"], name="teams_teamp_parent__96ec36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teampostlike",
            index=models.Index(
                fields=["content_type", "created_at"], name="teams_teamp_content_907a79_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teampostlike",
            unique_together={("user", "comment"), ("user", "post")},
        ),
        migrations.AddIndex(
            model_name="teampromotion",
            index=models.Index(fields=["team", "status"], name="teams_teamp_team_id_71eb40_idx"),
        ),
        migrations.AddIndex(
            model_name="teampromotion",
            index=models.Index(
                fields=["status", "is_active"], name="teams_teamp_status_8d0cfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teampromotion",
            index=models.Index(
                fields=["start_at", "end_at"], name="teams_teamp_start_a_1bffa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teampromotion",
            index=models.Index(
                fields=["promotion_type", "is_active"], name="teams_teamp_promoti_ed56d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamrankinghistory",
            index=models.Index(
                fields=["team", "-created_at"], name="teams_ranki_team_id_fecc23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamrankinghistory",
            index=models.Index(
                fields=["source", "-created_at"], name="teams_ranki_source_f101e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamsponsor",
            index=models.Index(fields=["team", "status"], name="teams_teams_team_id_4e5525_idx"),
        ),
        migrations.AddIndex(
            model_name="teamsponsor",
            index=models.Index(
                fields=["status", "is_active"], name="teams_teams_status_86c270_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamsponsor",
            index=models.Index(
                fields=["start_date", "end_date"], name="teams_teams_start_d_eb76c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorinquiry",
            index=models.Index(fields=["team", "status"], name="teams_spons_team_id_6b5cd1_idx"),
        ),
        migrations.AddIndex(
            model_name="sponsorinquiry",
            index=models.Index(
                fields=["status", "created_at"], name="teams_spons_status_7cceaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorinquiry",
            index=models.Index(fields=["contact_email"], name="teams_spons_contact_96b964_idx"),
        ),
        migrations.AddIndex(
            model_name="teamstats",
            index=models.Index(fields=["team"], name="teams_teams_team_id_f0bc27_idx"),
        ),
        migrations.AddIndex(
            model_name="teamstats",
            index=models.Index(fields=["updated_at"], name="teams_teams_updated_01ef2e_idx"),
        ),
        migrations.AddIndex(
            model_name="teamtournamentregistration",
            index=models.Index(
                fields=["tournament_id", "status"], name="teams_tourn_tournam_00b2f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamtournamentregistration",
            index=models.Index(
                fields=["team", "tournament_id"], name="teams_tourn_team_id_4ef1a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamtournamentregistration",
            index=models.Index(
                fields=["status", "-registered_at"], name="teams_tourn_status_f33ab9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teamtournamentregistration",
            constraint=models.UniqueConstraint(
                fields=("team", "tournament_id"), name="unique_team_tournament_registration"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentparticipation",
            index=models.Index(
                fields=["player", "registration"], name="teams_tourn_player__cfb1a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentparticipation",
            index=models.Index(
                fields=["registration", "is_starter"], name="teams_tourn_registr_039227_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentparticipation",
            constraint=models.UniqueConstraint(
                fields=("registration", "player"), name="unique_player_per_registration"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentrosterlock",
            index=models.Index(
                fields=["registration", "-created_at"], name="teams_tourn_registr_0349bb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="valorantteam",
            constraint=models.UniqueConstraint(
                fields=("game", "slug"), name="unique_valorant_team_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="valorantteam",
            constraint=models.UniqueConstraint(
                fields=("game", "name"), name="unique_valorant_team_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="valorantplayermembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True), ("status", "ACTIVE")),
                fields=("team",),
                name="one_captain_per_valorant_team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="valorantplayermembership",
            unique_together={("team", "profile")},
        ),
    ]
