# Generated by Django 4.2.23 on 2025-09-04 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='teaminvite',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='teammembership',
            options={'ordering': ('team', 'role', '-joined_at')},
        ),
        migrations.RemoveIndex(
            model_name='teaminvite',
            name='teams_teami_team_id_5d5657_idx',
        ),
        migrations.RemoveIndex(
            model_name='teaminvite',
            name='teams_teami_invited_23c184_idx',
        ),
        migrations.RemoveIndex(
            model_name='teammembership',
            name='teams_teamm_team_id_4d95f6_idx',
        ),
        migrations.RenameField(
            model_name='teammembership',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='teaminvite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'profile')},
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_team_invites', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='role',
            field=models.CharField(choices=[('CAPTAIN', 'Captain'), ('MANAGER', 'Manager'), ('PLAYER', 'Player'), ('SUB', 'Substitute')], default='PLAYER', max_length=16),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_invites', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('CAPTAIN', 'Captain'), ('MANAGER', 'Manager'), ('PLAYER', 'Player'), ('SUB', 'Substitute')], default='PLAYER', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'CAPTAIN'), ('status', 'ACTIVE')), fields=('team',), name='uq_one_active_captain_per_team'),
        ),
        migrations.RemoveField(
            model_name='teaminvite',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='teaminvite',
            name='message',
        ),
    ]
