# Generated by Django 5.2.8 on 2025-11-17 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message from applicant explaining why they want to join', max_length=1000)),
                ('preferred_role', models.CharField(blank=True, help_text='Player, Substitute, Coach, etc.', max_length=20)),
                ('game_id', models.CharField(blank=True, help_text="Applicant's game ID at time of request", max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by User')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text='Optional note from reviewer', max_length=500)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to='user_profile.userprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to='user_profile.userprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'status', '-created_at'], name='teams_teamj_team_id_373627_idx'), models.Index(fields=['applicant', 'status', '-created_at'], name='teams_teamj_applica_abd4cb_idx'), models.Index(fields=['status', '-created_at'], name='teams_teamj_status_5121d8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('team', 'applicant'), name='unique_pending_request_per_team')],
            },
        ),
    ]
