# Generated by Django 4.2.23 on 2025-09-04 19:47

import apps.teams.models._legacy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_options_alter_teaminvite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.teams.models._legacy.team_logo_path),
        ),
    ]
