# Generated by Django 5.2.8 on 2025-11-20 15:35

import apps.common.game_registry.registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_teamotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="game",
            field=models.CharField(
                blank=True,
                choices=apps.common.game_registry.registry.get_choices,
                default="",
                help_text="Which game this team competes in (blank for legacy teams).",
                max_length=20,
            ),
        ),
    ]
