# Generated by Django 5.2.8 on 2025-11-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembership',
            name='can_edit_team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='can_manage_roster',
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_create_posts',
            field=models.BooleanField(default=False, help_text='Can create posts on team page'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_edit_team_profile',
            field=models.BooleanField(default=False, help_text='Can edit team name, description, logo, etc.'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_edit_team_settings',
            field=models.BooleanField(default=False, help_text='Can modify team privacy and settings'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_invite_members',
            field=models.BooleanField(default=False, help_text='Can send invitations to new members'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_manage_announcements',
            field=models.BooleanField(default=False, help_text='Can create and manage team announcements'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_manage_finances',
            field=models.BooleanField(default=False, help_text='Can manage team finances and entry fees'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_manage_permissions',
            field=models.BooleanField(default=False, help_text='Can grant/revoke permissions to other members'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_manage_posts',
            field=models.BooleanField(default=False, help_text="Can edit/delete team posts (including others' posts)"),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_manage_roles',
            field=models.BooleanField(default=False, help_text='Can change member roles (except Owner)'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_manage_schedule',
            field=models.BooleanField(default=False, help_text='Can manage team schedule and calendar'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_manage_social_links',
            field=models.BooleanField(default=False, help_text='Can update team social media links'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_remove_members',
            field=models.BooleanField(default=False, help_text='Can remove/kick members from team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_schedule_practice',
            field=models.BooleanField(default=False, help_text='Can schedule team practice sessions'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_submit_match_results',
            field=models.BooleanField(default=False, help_text='Can submit match results and scores'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_view_financial_reports',
            field=models.BooleanField(default=False, help_text='Can view team financial reports and transactions'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_withdraw_tournaments',
            field=models.BooleanField(default=False, help_text='Can withdraw team from tournaments'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='can_register_tournaments',
            field=models.BooleanField(default=False, help_text='Can register team for tournaments and competitions'),
        ),
    ]
