# Generated by Django 4.2.23 on 2025-09-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_partB_presets_and_team_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.RemoveField(
            model_name='team',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='team',
            name='game',
        ),
        migrations.RemoveField(
            model_name='team',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='team',
            name='linktree',
        ),
        migrations.RemoveField(
            model_name='team',
            name='region',
        ),
        migrations.RemoveField(
            model_name='team',
            name='roster_image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitch',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='team',
            name='youtube',
        ),
    ]
