# Generated by Django 5.2.8 on 2025-11-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_add_granular_permissions'),
        ('user_profile', '0008_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When the member was locked for tournament', null=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='locked_for_tournament_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Tournament ID this member is locked for (prevents team changes)', null=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='When the lock expires (tournament end date)', null=True),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['locked_for_tournament_id', 'locked_until'], name='teams_tournament_lock_idx'),
        ),
    ]
