# Generated by Django 5.2.8 on 2025-11-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_cleanup_oversized_rosters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='is_captain',
            field=models.BooleanField(default=False, help_text='Team captain for administrative duties (Ban/Pick, check-in). Can be OWNER, MANAGER, PLAYER, or SUBSTITUTE.', verbose_name='Captain Title'),
        ),
    ]
