# Generated by Django 5.2.8 on 2025-11-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_add_roster_slot_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='roster_slot',
            field=models.CharField(blank=True, choices=[('STARTER', 'Starting Player'), ('SUBSTITUTE', 'Substitute Player'), ('COACH', 'Coach'), ('ANALYST', 'Analyst')], help_text='Roster position for tournaments (STARTER, SUBSTITUTE, COACH, ANALYST). Enforces game-specific limits.', max_length=16, null=True, verbose_name='Roster Slot'),
        ),
    ]
