# Generated by Django 5.2.8 on 2025-12-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_add_roster_slot_field'),
        ('user_profile', '0008_follow'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['game', 'is_public', 'is_active'], name='team_listing_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['game', 'region', 'is_active'], name='team_region_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['captain', 'is_active'], name='team_captain_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'status', 'role'], name='membership_active_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['profile', 'status'], name='membership_user_idx'),
        ),
    ]
