# Generated by Django 4.2.23 on 2025-09-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_alter_team_options_alter_team_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.CharField(blank=True, choices=[('efootball', 'eFootball'), ('valorant', 'Valorant')], default='', help_text='Which game this team competes in (blank for legacy teams).', max_length=20),
        ),
    ]
