# Generated by Django 5.2.8 on 2025-12-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_migrate_captain_to_owner_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvite',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Team Owner'), ('GENERAL_MANAGER', 'General Manager'), ('TEAM_MANAGER', 'Team Manager'), ('HEAD_COACH', 'Head Coach'), ('ASSISTANT_COACH', 'Assistant Coach'), ('PERFORMANCE_COACH', 'Performance Coach'), ('ANALYST', 'Analyst'), ('STRATEGIST', 'Strategist'), ('DATA_ANALYST', 'Data Analyst'), ('PLAYER', 'Player'), ('SUBSTITUTE', 'Substitute'), ('CONTENT_CREATOR', 'Content Creator'), ('SOCIAL_MEDIA_MANAGER', 'Social Media Manager'), ('COMMUNITY_MANAGER', 'Community Manager'), ('MANAGER', 'Manager (Legacy)'), ('COACH', 'Coach (Legacy)'), ('CAPTAIN', 'Captain (Legacy)'), ('SUB', 'Substitute (Legacy)')], default='PLAYER', max_length=30),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Team Owner'), ('GENERAL_MANAGER', 'General Manager'), ('TEAM_MANAGER', 'Team Manager'), ('HEAD_COACH', 'Head Coach'), ('ASSISTANT_COACH', 'Assistant Coach'), ('PERFORMANCE_COACH', 'Performance Coach'), ('ANALYST', 'Analyst'), ('STRATEGIST', 'Strategist'), ('DATA_ANALYST', 'Data Analyst'), ('PLAYER', 'Player'), ('SUBSTITUTE', 'Substitute'), ('CONTENT_CREATOR', 'Content Creator'), ('SOCIAL_MEDIA_MANAGER', 'Social Media Manager'), ('COMMUNITY_MANAGER', 'Community Manager'), ('MANAGER', 'Manager (Legacy)'), ('COACH', 'Coach (Legacy)'), ('CAPTAIN', 'Captain (Legacy)'), ('SUB', 'Substitute (Legacy)')], default='PLAYER', max_length=30),
        ),
        migrations.CreateModel(
            name='TeamGameRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(db_index=True, help_text="Game slug/identifier (e.g., 'VALORANT', 'CS2', 'MLBB')", max_length=50)),
                ('points', models.IntegerField(default=0, help_text='Total ranking points earned in this game')),
                ('division', models.CharField(default='BRONZE', help_text='Current division based on ELO', max_length=20)),
                ('elo_rating', models.IntegerField(default=1500, help_text='ELO rating for this game')),
                ('win_streak', models.IntegerField(default=0)),
                ('loss_streak', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('tournaments_played', models.IntegerField(default=0)),
                ('tournaments_won', models.IntegerField(default=0)),
                ('tournament_podium_finishes', models.IntegerField(default=0, help_text='Top 3 finishes')),
                ('global_elo', models.IntegerField(default=1500, help_text='Cross-game ELO (contributes to overall team ranking)')),
                ('last_match_date', models.DateTimeField(blank=True, null=True)),
                ('last_decay_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rankings', to='teams.team')),
            ],
            options={
                'ordering': ['-elo_rating'],
                'indexes': [models.Index(fields=['game', '-elo_rating'], name='ranking_game_elo_idx'), models.Index(fields=['game', '-points'], name='ranking_game_points_idx'), models.Index(fields=['-global_elo'], name='ranking_global_elo_idx'), models.Index(fields=['game', 'division', '-elo_rating'], name='ranking_division_idx'), models.Index(fields=['team', 'game'], name='ranking_team_game_idx')],
                'unique_together': {('team', 'game')},
            },
        ),
    ]
