# Generated by Django 4.2.23 on 2025-09-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_partC_team_achievement_stats'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teamachievement',
            new_name='teams_teama_team_id_daea1e_idx',
            old_name='teams_team_team_id_ach_idx',
        ),
        migrations.RenameIndex(
            model_name='teamachievement',
            new_name='teams_teama_year_42a46a_idx',
            old_name='teams_team_year_idx',
        ),
        migrations.RenameIndex(
            model_name='teamstats',
            new_name='teams_teams_team_id_f0bc27_idx',
            old_name='teams_stat_team_idx',
        ),
        migrations.RenameIndex(
            model_name='teamstats',
            new_name='teams_teams_updated_01ef2e_idx',
            old_name='teams_stat_updated_idx',
        ),
        migrations.AlterField(
            model_name='teamachievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamachievement',
            name='title',
            field=models.CharField(help_text='Tournament or event name', max_length=160),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
