# Generated by Django 5.2.8 on 2025-12-05 13:27

# import apps.games.services.game_service  # REMOVED: migrations don't need hardcoded choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_phase2_professional_roles_and_rankings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.CharField(blank=True, choices=[], default='', help_text='Which game this team competes in (blank for legacy teams).', max_length=20),
        ),
    ]
