# Generated by Django 4.2.23 on 2025-09-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_team_ci_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='uniq_team_game_name_ci',
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='uniq_team_game_tag_ci',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams_team',
        ),
    ]
