# Generated by Django 4.2.23 on 2025-09-21 11:37

import apps.teams.models._legacy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_remove_team_uniq_team_game_name_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, help_text='Brief team description', max_length=500),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, help_text='Team logo image', null=True, upload_to=apps.teams.models._legacy.team_logo_path),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, help_text='Team name must be unique', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tag',
            field=models.CharField(blank=True, help_text='Team tag/abbreviation (2-10 characters)', max_length=10, null=True, unique=True),
        ),
    ]
