# Generated by Django 4.2.23 on 2025-09-21 11:37

from django.db import migrations


def fix_existing_teams(apps, schema_editor):
    """Fix existing teams with null name or tag values."""
    Team = apps.get_model('teams', 'Team')
    
    teams_to_fix = Team.objects.filter(name__isnull=True) | Team.objects.filter(tag__isnull=True)
    
    for i, team in enumerate(teams_to_fix, 1):
        if not team.name:
            team.name = f"Team {i}"
        if not team.tag:
            team.tag = f"T{i}"
        team.save()


def reverse_fix_existing_teams(apps, schema_editor):
    """Reverse operation - not needed for this data migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_team_description_team_logo_team_updated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_existing_teams, reverse_fix_existing_teams),
    ]
