# Generated by Django 5.2.8 on 2025-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0017_remove_team_team_captain_idx_alter_team_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="game",
            field=models.CharField(
                blank=True,
                choices=[],  # Choices are dynamically loaded from GameService in the model
                default="",
                help_text="Which game this team competes in (blank for legacy teams).",
                max_length=20,
            ),
        ),
    ]
