# Generated by Django 5.2.8 on 2025-12-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_alter_team_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.CharField(blank=True, default='', help_text='Which game this team competes in (blank for legacy teams).', max_length=50),
        ),
    ]
