# Generated by Django 4.2.23 on 2025-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_fix_existing_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Team name must be unique', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tag',
            field=models.CharField(help_text='Team tag/abbreviation (2-10 characters)', max_length=10, unique=True),
        ),
    ]
