# Generated by Django 5.2.8 on 2025-12-06 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_remove_game_choices_constraint'),
        ('user_profile', '0008_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='is_role_custom',
            field=models.BooleanField(default=False, help_text='Whether this member has a custom role outside the predefined choices'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='role_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the role was last changed', null=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='role_changed_by',
            field=models.ForeignKey(blank=True, help_text="Who last changed this member's role", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_made', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='role_metadata',
            field=models.JSONField(default=dict, help_text="Additional metadata about the member's role (e.g., jersey number, position details)"),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='role_tier',
            field=models.IntegerField(default=0, help_text='Role hierarchy tier for permission calculations (higher = more authority)'),
        ),
    ]
