# Generated by Django 4.2.24 on 2025-09-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_teampost_teampostcomment_team_allow_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='allow_join_requests',
            field=models.BooleanField(default=True, help_text='Allow users to request to join'),
        ),
        migrations.AddField(
            model_name='team',
            name='banner',
            field=models.ImageField(blank=True, help_text='Team banner image', null=True, upload_to='teams/banners/'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Team is active and visible'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Team profile is public'),
        ),
        migrations.AddField(
            model_name='team',
            name='primary_game',
            field=models.CharField(blank=True, default='', help_text='Primary game for team', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='show_statistics',
            field=models.BooleanField(default=True, help_text='Show team statistics publicly'),
        ),
    ]
