# Generated by Django 4.2.24 on 2025-09-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_add_professional_team_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampost',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Indicates if this post has been edited after creation'),
        ),
    ]
