# Generated by Django 5.2.8 on 2026-01-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0022_backfill_left_at_data"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="teammembership",
            name="teams_member_left_at_idx",
        ),
    ]
