# Generated by Django 4.2.24 on 2025-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0023_teamrankingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='manual_points',
            field=models.IntegerField(default=0, help_text='Manually added points (can be positive or negative)'),
        ),
        migrations.AddField(
            model_name='team',
            name='total_points',
            field=models.PositiveIntegerField(default=0, help_text='Total ranking points earned by this team'),
        ),
    ]
