# Generated by Django 4.2.24 on 2025-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0024_team_manual_points_team_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='manual_points',
        ),
        migrations.AddField(
            model_name='team',
            name='adjust_points',
            field=models.IntegerField(default=0, help_text='Points adjustment field (use Add/Minus buttons to modify total)'),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_points',
            field=models.PositiveIntegerField(default=0, help_text='Total ranking points earned by this team (read-only, calculated automatically)'),
        ),
    ]
