# Generated by Django 4.2.23 on 2025-09-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0026_add_manual_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='manual_points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='total_points',
        ),
    ]
