# Generated by Django 4.2.24 on 2025-09-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0027_remove_team_manual_points_remove_team_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='adjust_points',
            field=models.IntegerField(default=0, help_text='Manual points adjustment (can be positive or negative)'),
        ),
        migrations.AddField(
            model_name='team',
            name='total_points',
            field=models.PositiveIntegerField(default=0, help_text='Total ranking points earned by this team (read-only, calculated automatically)'),
        ),
    ]
