# Generated by Django 4.2.23 on 2025-09-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0030_add_team_ranking_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampointsadjustment',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='teampointsadjustment',
            name='team_ranking',
        ),
        migrations.DeleteModel(
            name='TeamRankingConfig',
        ),
        migrations.RemoveField(
            model_name='teamrankingpoints',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamachievement',
            name='awarded_by',
        ),
        migrations.RemoveField(
            model_name='teamachievement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teamachievement',
            name='points_awarded',
        ),
        migrations.AddField(
            model_name='team',
            name='adjust_points',
            field=models.IntegerField(default=0, help_text='Manual points adjustment (can be positive or negative)'),
        ),
        migrations.AddField(
            model_name='team',
            name='total_points',
            field=models.PositiveIntegerField(default=0, help_text='Total ranking points earned by this team (read-only, calculated automatically)'),
        ),
        migrations.DeleteModel(
            name='TeamPointsAdjustment',
        ),
        migrations.DeleteModel(
            name='TeamRankingPoints',
        ),
    ]
