# Generated by Django 4.2.23 on 2025-09-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0032_teamrankingcategory_teamrankingcontrol_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamRankingCategory',
        ),
        migrations.RemoveField(
            model_name='teamrankingpoints',
            name='awarded_by',
        ),
        migrations.RemoveField(
            model_name='teamrankingpoints',
            name='source_achievement',
        ),
        migrations.RemoveField(
            model_name='teamrankingpoints',
            name='source_tournament_id',
        ),
        migrations.RemoveField(
            model_name='teamrankingpoints',
            name='team',
        ),
        migrations.DeleteModel(
            name='TeamRankingControl',
        ),
        migrations.DeleteModel(
            name='TeamRankingPoints',
        ),
    ]
