# Generated by Django 4.2.24 on 2025-09-26 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0033_delete_teamrankingcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRankingPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_points', models.IntegerField(default=0, help_text='Points from tournament results (auto-calculated)')),
                ('member_points', models.IntegerField(default=0, help_text='Points from active members (auto-calculated)')),
                ('age_points', models.IntegerField(default=0, help_text='Points from team age (auto-calculated)')),
                ('achievement_points', models.IntegerField(default=0, help_text='Points from achievements (auto-calculated)')),
                ('manual_points', models.IntegerField(default=0, help_text='Manually added/subtracted points by admin')),
                ('total_points', models.IntegerField(default=0, help_text='Total ranking points (automatically calculated)')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(help_text='Team these points belong to', on_delete=django.db.models.deletion.CASCADE, related_name='ranking_points', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Ranking Points',
                'verbose_name_plural': 'Team Ranking Points',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='TeamPointsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_before', models.IntegerField(help_text='Total points before adjustment')),
                ('points_after', models.IntegerField(help_text='Total points after adjustment')),
                ('points_changed', models.IntegerField(help_text='Points added (+) or removed (-)')),
                ('reason', models.CharField(help_text='Brief reason for the adjustment', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Detailed notes about the adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(help_text='Admin who made the adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_audit_logs', to='teams.team')),
            ],
            options={
                'verbose_name': 'Points Adjustment Log',
                'verbose_name_plural': 'Points Adjustment Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
