# Generated by Django 4.2.23 on 2025-09-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0034_add_team_ranking_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrankingpoints',
            name='team',
        ),
        migrations.DeleteModel(
            name='TeamPointsAuditLog',
        ),
        migrations.DeleteModel(
            name='TeamRankingPoints',
        ),
    ]
