# Generated by Django 4.2.23 on 2025-09-26 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0036_add_comprehensive_ranking_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrankingadjustment',
            name='adjusted_by',
        ),
        migrations.RemoveField(
            model_name='teamrankingadjustment',
            name='team',
        ),
        migrations.DeleteModel(
            name='TeamRankingLeaderboard',
        ),
        migrations.RemoveField(
            model_name='teamrankingpoints',
            name='team',
        ),
        migrations.AddField(
            model_name='teamrankingsettings',
            name='top8_finish_points',
            field=models.PositiveIntegerField(default=20, help_text='Points awarded for each top 8 tournament finish', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='teamrankingsettings',
            name='general_achievement_points',
            field=models.PositiveIntegerField(default=50, help_text='Points awarded per general achievement/trophy', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='teamrankingsettings',
            name='member_points',
            field=models.PositiveIntegerField(default=5, help_text='Points awarded per active team member', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='teamrankingsettings',
            name='monthly_age_points',
            field=models.PositiveIntegerField(default=2, help_text='Points awarded per month since team creation', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='teamrankingsettings',
            name='participation_points',
            field=models.PositiveIntegerField(default=10, help_text='Points awarded for each tournament participation', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='teamrankingsettings',
            name='runner_up_points',
            field=models.PositiveIntegerField(default=60, help_text='Points awarded for each runner-up finish (2nd place)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='teamrankingsettings',
            name='top4_finish_points',
            field=models.PositiveIntegerField(default=40, help_text='Points awarded for each top 4 tournament finish', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='teamrankingsettings',
            name='tournament_victory_points',
            field=models.PositiveIntegerField(default=100, help_text='Points awarded for each tournament victory (1st place)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='TeamRankingAdjustment',
        ),
        migrations.DeleteModel(
            name='TeamRankingPoints',
        ),
    ]
