# Generated by Django 4.2.24 on 2025-10-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0038_add_ranking_system'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Drop foreign key constraint if teams_ranking table exists
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.tables 
                    WHERE table_name = 'teams_ranking'
                ) THEN
                    -- Drop all foreign keys referencing teams_team from teams_ranking
                    EXECUTE (
                        SELECT string_agg('ALTER TABLE teams_ranking DROP CONSTRAINT IF EXISTS ' || constraint_name || ';', ' ')
                        FROM information_schema.table_constraints
                        WHERE constraint_type = 'FOREIGN KEY'
                        AND table_name = 'teams_ranking'
                        AND constraint_name IN (
                            SELECT constraint_name
                            FROM information_schema.constraint_column_usage
                            WHERE table_name = 'teams_team'
                        )
                    );
                    
                    -- Drop the table if it's orphaned
                    DROP TABLE IF EXISTS teams_ranking CASCADE;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
