# Generated by Django 4.2.23 on 2025-10-09 18:07
# Task 10: Performance Optimization - Strategic Database Indices

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0044_teamsponsor_teampromotion_teammerchitem_and_more'),
    ]

    operations = [
        # Core Team model indices for leaderboards and listings
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['-total_points', 'name'], name='teams_pts_name_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['game', '-total_points'], name='teams_game_pts_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['-created_at'], name='teams_created_idx'),
        ),
        
        # TeamMembership indices for roster queries
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'status'], name='teams_member_team_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['profile', 'status'], name='teams_member_prof_idx'),
        ),
        
        # TeamInvite indices for invitation management
        migrations.AddIndex(
            model_name='teaminvite',
            index=models.Index(fields=['team', 'status'], name='teams_invite_team_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvite',
            index=models.Index(fields=['status', 'expires_at'], name='teams_invite_exp_idx'),
        ),
    ]
