# Generated by Django 4.2.23 on 2025-10-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0045_performance_indices'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='team',
            name='teams_pts_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='teams_game_pts_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='teams_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='teaminvite',
            name='teams_invite_team_idx',
        ),
        migrations.RemoveIndex(
            model_name='teaminvite',
            name='teams_invite_exp_idx',
        ),
        migrations.RemoveIndex(
            model_name='teammembership',
            name='teams_member_team_idx',
        ),
        migrations.RemoveIndex(
            model_name='teammembership',
            name='teams_member_prof_idx',
        ),
    ]
