# Generated by Django 4.2.23 on 2025-10-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0046_remove_team_teams_pts_name_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['-total_points', 'name'], name='teams_leaderboard_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['game', '-total_points'], name='teams_game_leader_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['-created_at'], name='teams_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvite',
            index=models.Index(fields=['team', 'status'], name='teams_invite_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvite',
            index=models.Index(fields=['status', 'expires_at'], name='teams_invite_expire_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'status'], name='teams_member_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['profile', 'status'], name='teams_user_teams_idx'),
        ),
    ]
