# Generated by Django 4.2.24 on 2025-10-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0048_phase3_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teamchatmessage',
            name='teams_chat_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamchatmessage',
            name='teams_chat_team_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamdiscussionpost',
            name='teams_disc_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamdiscussionpost',
            name='teams_disc_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamsponsor',
            name='teams_sponsor_active_idx',
        ),
        migrations.AddField(
            model_name='team',
            name='hero_template',
            field=models.CharField(choices=[('default', 'Classic'), ('centered', 'Centered Focus'), ('split', 'Split Screen'), ('minimal', 'Minimal Modern'), ('championship', 'Championship')], default='default', help_text='Hero section template style', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='is_recruiting',
            field=models.BooleanField(default=False, help_text='Display recruiting badge'),
        ),
        migrations.AddField(
            model_name='team',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Team tagline or motto', max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.CharField(blank=True, choices=[('valorant', 'Valorant'), ('cs2', 'Counter-Strike 2'), ('dota2', 'Dota 2'), ('mlbb', 'Mobile Legends: Bang Bang'), ('pubg', 'PUBG Mobile'), ('freefire', 'Free Fire'), ('efootball', 'eFootball'), ('fc26', 'FC 26'), ('codm', 'Call of Duty Mobile'), ('csgo', 'Counter-Strike: Global Offensive')], default='', help_text='Which game this team competes in (blank for legacy teams).', max_length=20),
        ),
    ]
