# Generated by Django 4.2.24 on 2025-10-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0049_add_hero_template_and_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='auto_accept_join_requests',
            field=models.BooleanField(default=False, help_text='Automatically accept join requests'),
        ),
        migrations.AddField(
            model_name='team',
            name='hide_member_stats',
            field=models.BooleanField(default=False, help_text='Hide individual member statistics'),
        ),
        migrations.AddField(
            model_name='team',
            name='hide_social_links',
            field=models.BooleanField(default=False, help_text='Hide social media links from public'),
        ),
        migrations.AddField(
            model_name='team',
            name='members_can_invite',
            field=models.BooleanField(default=False, help_text='Allow members to send team invites'),
        ),
        migrations.AddField(
            model_name='team',
            name='members_can_post',
            field=models.BooleanField(default=True, help_text='Allow team members to create posts'),
        ),
        migrations.AddField(
            model_name='team',
            name='min_rank_requirement',
            field=models.CharField(blank=True, default='', help_text='Minimum rank/level required to join', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='require_application_message',
            field=models.BooleanField(default=True, help_text='Require message with join requests'),
        ),
        migrations.AddField(
            model_name='team',
            name='require_post_approval',
            field=models.BooleanField(default=False, help_text='Captain must approve member posts'),
        ),
        migrations.AddField(
            model_name='team',
            name='show_achievements_publicly',
            field=models.BooleanField(default=True, help_text='Display achievements publicly'),
        ),
        migrations.AddField(
            model_name='team',
            name='show_captain_only',
            field=models.BooleanField(default=False, help_text='Only show captain, hide other members'),
        ),
        migrations.AddField(
            model_name='team',
            name='show_roster_publicly',
            field=models.BooleanField(default=True, help_text='Allow non-members to view team roster'),
        ),
        migrations.AddField(
            model_name='team',
            name='show_statistics_publicly',
            field=models.BooleanField(default=True, help_text='Display team statistics to public'),
        ),
        migrations.AddField(
            model_name='team',
            name='show_tournaments_publicly',
            field=models.BooleanField(default=True, help_text='Show tournament history publicly'),
        ),
    ]
