# Generated by Django 4.2.24 on 2025-10-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0050_add_enhanced_privacy_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='hero_template',
            field=models.CharField(choices=[('legacy', 'Legacy Banner Profile'), ('split_power', 'Dynamic Split Power'), ('dashboard', 'Professional Dashboard'), ('prestige', 'Elite Prestige'), ('competitive', 'Competitive Edge'), ('minimal_pro', 'Minimal Pro'), ('neon_warrior', 'Neon Warrior'), ('champion_gold', 'Champion Gold')], default='legacy', help_text='Hero section template style', max_length=20),
        ),
    ]
