# Generated by Django 4.2.24 on 2025-10-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0051_alter_team_hero_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='hero_template',
            field=models.CharField(choices=[('legacy_banner', 'Legacy Banner Profile'), ('dynamic_split', 'Dynamic Split Power'), ('pro_dashboard', 'Professional Dashboard'), ('neon_elite', 'Neon Elite'), ('cinematic_wide', 'Cinematic Widescreen'), ('competitive_edge', 'Competitive Edge'), ('prestige_card', 'Prestige Card'), ('tournament_hero', 'Tournament Champion')], default='legacy_banner', help_text='Hero section template style', max_length=20),
        ),
    ]
