# Generated by Django 4.2.23 on 2025-10-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0052_update_hero_template_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='hero_template',
            field=models.CharField(choices=[('default', 'Classic'), ('centered', 'Centered Focus'), ('split', 'Split Screen'), ('minimal', 'Minimal Modern'), ('championship', 'Championship')], default='default', help_text='Hero section template style', max_length=20),
        ),
    ]
