# Generated by Django 4.2.24 on 2025-10-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0053_alter_team_hero_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='player_role',
            field=models.CharField(blank=True, default='', help_text='In-game tactical role (e.g., Duelist, IGL, AWPer). Game-specific.', max_length=50, verbose_name='In-Game Role'),
        ),
    ]
