# Generated by Django 4.2.24 on 2025-11-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0055_role_system_overhaul'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teamtournamentregistration',
            name='unique_team_tournament_registration',
        ),
        migrations.RemoveIndex(
            model_name='matchrecord',
            name='teams_analy_tournam_7636f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamtournamentregistration',
            name='teams_tourn_tournam_00b2f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamtournamentregistration',
            name='teams_tourn_team_id_4ef1a7_idx',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='teamachievement',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='teamtournamentregistration',
            name='tournament',
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='tournament_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Legacy tournament ID - Tournament this match was part of (if any)', null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='tournament_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Legacy tournament ID (reference only)', null=True),
        ),
        migrations.AddField(
            model_name='teamtournamentregistration',
            name='tournament_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Legacy tournament ID (reference only)', null=True),
        ),
        migrations.AddIndex(
            model_name='matchrecord',
            index=models.Index(fields=['tournament_id', '-match_date'], name='teams_analy_tournam_7636f8_idx'),
        ),
        migrations.AddIndex(
            model_name='teamtournamentregistration',
            index=models.Index(fields=['tournament_id', 'status'], name='teams_tourn_tournam_00b2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='teamtournamentregistration',
            index=models.Index(fields=['team', 'tournament_id'], name='teams_tourn_team_id_4ef1a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamtournamentregistration',
            constraint=models.UniqueConstraint(fields=('team', 'tournament_id'), name='unique_team_tournament_registration'),
        ),
    ]
