# Generated by Django 5.2.8 on 2026-01-30 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0100_fix_teamjoinrequest_fk_to_organizations_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamjoinrequest",
            name="team",
            field=models.ForeignKey(
                help_text="Team receiving join request",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="teamsponsor",
            name="team",
            field=models.ForeignKey(
                help_text="Team receiving sponsorship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsors",
                to="teams.team",
            ),
        ),
    ]
