# Generated by Django 4.2.23 on 2025-09-04 16:07

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValorantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_of', models.CharField(choices=[('BO1', 'Best of 1'), ('BO2', 'Best of 2'), ('BO3', 'Best of 3'), ('BO5', 'Best of 5')], default='BO3', max_length=3)),
                ('rounds_per_match', models.PositiveIntegerField(default=13, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(16)])),
                ('map_pool', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('match_duration_limit', models.DurationField(blank=True, null=True)),
                ('overtime_rules', models.CharField(blank=True, help_text='e.g. ‘MR3 OT, win by 2’', max_length=120)),
                ('additional_rules_richtext', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Additional rules')),
                ('regional_lock', models.BooleanField(default=False)),
                ('live_scoreboard', models.BooleanField(default=False)),
                ('sponsor_integration', models.BooleanField(default=False)),
                ('community_voting', models.BooleanField(default=False)),
                ('livestream_customization', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Valorant Config',
                'verbose_name_plural': 'Valorant Configs',
            },
        ),
    ]
