# Generated by Django 4.2.24 on 2025-09-17 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_valorant', '0006_remove_valorantteaminfo_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorantconfig',
            name='best_of',
            field=models.CharField(blank=True, choices=[('BO1', 'Best of 1'), ('BO2', 'Best of 2'), ('BO3', 'Best of 3'), ('BO5', 'Best of 5')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='valorantconfig',
            name='community_voting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valorantconfig',
            name='live_scoreboard',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valorantconfig',
            name='livestream_customization',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valorantconfig',
            name='overtime_rules',
            field=models.CharField(blank=True, help_text='e.g. MR3 OT, win by 2', max_length=120),
        ),
        migrations.AlterField(
            model_name='valorantconfig',
            name='regional_lock',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valorantconfig',
            name='rounds_per_match',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='valorantconfig',
            name='sponsor_integration',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
