# Generated by Django 4.2.7 on 2025-11-05 - FIXED VERSION
# This migration replaces 0001_initial.py with IntegerField references instead of ForeignKeys

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0007_fix_user_fk_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaCrownWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_wallet', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'DeltaCrown Wallet',
                'indexes': [models.Index(fields=['profile'], name='economy_del_profile_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoinPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(blank=True, db_index=True, help_text='Legacy tournament ID (reference only)', null=True, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('participation', models.PositiveIntegerField(default=5)),
                ('top4', models.PositiveIntegerField(default=25)),
                ('runner_up', models.PositiveIntegerField(default=50)),
                ('winner', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeltaCrownTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for credit, negative for debit')),
                ('reason', models.CharField(choices=[('participation', 'Participation'), ('top4', 'Top 4'), ('runner_up', 'Runner-up'), ('winner', 'Winner'), ('entry_fee_debit', 'Entry fee (debit)'), ('refund', 'Refund'), ('manual_adjust', 'Manual adjust'), ('correction', 'Correction')], max_length=32)),
                ('tournament_id', models.IntegerField(blank=True, db_index=True, help_text='Legacy tournament ID (reference only)', null=True)),
                ('registration_id', models.IntegerField(blank=True, db_index=True, help_text='Legacy registration ID (reference only)', null=True)),
                ('match_id', models.IntegerField(blank=True, help_text='Legacy match ID (reference only)', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='economy.deltacrownwallet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DeltaCrown Transaction',
                'ordering': ('-created_at', 'id'),
                'indexes': [
                    models.Index(fields=['reason', 'created_at'], name='economy_del_reason_idx'),
                    models.Index(fields=['wallet'], name='economy_del_wallet_idx'),
                ],
            },
        ),
    ]
