# Generated by Django 4.2.23 on 2025-09-04 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('tournaments', '0002_sync_ts_audit_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaCrownWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_wallet', to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CoinPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('participation', models.PositiveIntegerField(default=5)),
                ('top4', models.PositiveIntegerField(default=25)),
                ('runner_up', models.PositiveIntegerField(default=50)),
                ('winner', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_policy', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='DeltaCrownTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('participation', 'Participation'), ('top4', 'Top 4'), ('runner_up', 'Runner-up'), ('winner', 'Winner'), ('bonus', 'Bonus'), ('adjustment', 'Adjustment')], max_length=32)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='tournaments.match')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='tournaments.registration')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='tournaments.tournament')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='economy.deltacrownwallet')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'indexes': [models.Index(fields=['reason', 'created_at'], name='economy_del_reason_8db686_idx'), models.Index(fields=['tournament', 'created_at'], name='economy_del_tournam_420090_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='deltacrowntransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', 'participation')), fields=('registration', 'reason'), name='uq_participation_once_per_registration'),
        ),
    ]
