# Generated by Django 5.2.8 on 2025-11-16 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(blank=True, db_index=True, help_text='Legacy tournament ID (reference only)', null=True, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('participation', models.PositiveIntegerField(default=5)),
                ('top4', models.PositiveIntegerField(default=25)),
                ('runner_up', models.PositiveIntegerField(default=50)),
                ('winner', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeltaCrownWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_balance', models.IntegerField(default=0)),
                ('allow_overdraft', models.BooleanField(default=False, help_text='If True, allows negative balance (overdraft). Default: False (reject insufficient funds).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_wallet', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'DeltaCrown Wallet',
            },
        ),
        migrations.CreateModel(
            name='DeltaCrownTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for credit, negative for debit')),
                ('reason', models.CharField(choices=[('participation', 'Participation'), ('top4', 'Top 4'), ('runner_up', 'Runner-up'), ('winner', 'Winner'), ('entry_fee_debit', 'Entry fee (debit)'), ('refund', 'Refund'), ('manual_adjust', 'Manual adjust'), ('correction', 'Correction'), ('p2p_transfer', 'P2P Transfer')], max_length=32)),
                ('tournament_id', models.IntegerField(blank=True, db_index=True, help_text='Legacy tournament ID (reference only)', null=True)),
                ('registration_id', models.IntegerField(blank=True, db_index=True, help_text='Legacy registration ID (reference only)', null=True)),
                ('match_id', models.IntegerField(blank=True, help_text='Legacy match ID (reference only)', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='economy.deltacrownwallet')),
            ],
            options={
                'verbose_name': 'DeltaCrown Transaction',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='deltacrownwallet',
            index=models.Index(fields=['profile'], name='economy_del_profile_1fb9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='deltacrowntransaction',
            index=models.Index(fields=['reason', 'created_at'], name='economy_del_reason_8db686_idx'),
        ),
        migrations.AddIndex(
            model_name='deltacrowntransaction',
            index=models.Index(fields=['wallet'], name='economy_del_wallet__8fabbc_idx'),
        ),
        migrations.AddIndex(
            model_name='deltacrowntransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='economy_del_wallet__a8652c_idx'),
        ),
        migrations.AddIndex(
            model_name='deltacrowntransaction',
            index=models.Index(fields=['wallet', 'id'], name='economy_del_wallet__987fc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='deltacrowntransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='economy_transaction_amount_nonzero'),
        ),
    ]
