# Generated by Django 5.2.8 on 2025-11-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deltacrownwallet',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', help_text='Full name as per bank account', max_length=100),
        ),
        migrations.AddField(
            model_name='deltacrownwallet',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', help_text='Bank account number', max_length=30),
        ),
        migrations.AddField(
            model_name='deltacrownwallet',
            name='bank_branch',
            field=models.CharField(blank=True, default='', help_text='Branch name or code', max_length=100),
        ),
        migrations.AddField(
            model_name='deltacrownwallet',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='Name of the bank (e.g., Dutch-Bangla Bank, Brac Bank)', max_length=100),
        ),
        migrations.AddField(
            model_name='deltacrownwallet',
            name='bkash_number',
            field=models.CharField(blank=True, default='', help_text='bKash mobile wallet number (e.g., 01712345678)', max_length=15),
        ),
        migrations.AddField(
            model_name='deltacrownwallet',
            name='last_withdrawal_at',
            field=models.DateTimeField(blank=True, help_text='Last successful withdrawal timestamp', null=True),
        ),
        migrations.AddField(
            model_name='deltacrownwallet',
            name='lifetime_earnings',
            field=models.IntegerField(default=0, help_text='Total DeltaCoins earned from prizes (all-time)'),
        ),
        migrations.AddField(
            model_name='deltacrownwallet',
            name='nagad_number',
            field=models.CharField(blank=True, default='', help_text='Nagad mobile wallet number (e.g., 01812345678)', max_length=15),
        ),
        migrations.AddField(
            model_name='deltacrownwallet',
            name='pending_balance',
            field=models.IntegerField(default=0, help_text='Balance locked in pending withdrawals'),
        ),
        migrations.AddField(
            model_name='deltacrownwallet',
            name='pin_hash',
            field=models.CharField(blank=True, default='', help_text='Hashed 4-digit PIN for withdrawal verification', max_length=255),
        ),
        migrations.AddField(
            model_name='deltacrownwallet',
            name='rocket_number',
            field=models.CharField(blank=True, default='', help_text='Rocket mobile wallet number (e.g., 01912345678)', max_length=15),
        ),
    ]
