# Generated by Django 5.2.8 on 2026-01-23 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False  # Changed from True - FK additions must run after initial batch

    dependencies = [
        ("economy", "0001_initial"),
        ("user_profile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deltacrownwallet",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dc_wallet",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="deltacrowntransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="economy.deltacrownwallet",
            ),
        ),
        migrations.AddField(
            model_name="giftrequest",
            name="receiver_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts_received",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="giftrequest",
            name="sender_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts_sent",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["item_type", "rarity"], name="economy_inv_item_ty_03fbc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["slug"], name="economy_inv_slug_2a5d45_idx"),
        ),
        migrations.AddField(
            model_name="giftrequest",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gift_requests",
                to="economy.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="topuprequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_topups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="topuprequest",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Transaction that credited the coins (created on approval)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topup_request",
                to="economy.deltacrowntransaction",
            ),
        ),
        migrations.AddField(
            model_name="topuprequest",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="topup_requests",
                to="economy.deltacrownwallet",
            ),
        ),
        migrations.AddField(
            model_name="traderequest",
            name="initiator_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades_initiated",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="traderequest",
            name="offered_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trade_offers",
                to="economy.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="traderequest",
            name="requested_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: What initiator wants in return",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trade_requests",
                to="economy.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="traderequest",
            name="target_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades_received",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="userinventoryitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_by",
                to="economy.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="userinventoryitem",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_inventory_items",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="walletpinotp",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pin_otps",
                to="economy.deltacrownwallet",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_withdrawals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Transaction that debited the coins (created on approval)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawal_request",
                to="economy.deltacrowntransaction",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withdrawal_requests",
                to="economy.deltacrownwallet",
            ),
        ),
        migrations.AddIndex(
            model_name="deltacrownwallet",
            index=models.Index(fields=["profile"], name="economy_del_profile_1fb9ea_idx"),
        ),
        migrations.AddIndex(
            model_name="deltacrowntransaction",
            index=models.Index(
                fields=["reason", "created_at"], name="economy_del_reason_8db686_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deltacrowntransaction",
            index=models.Index(fields=["wallet"], name="economy_del_wallet__8fabbc_idx"),
        ),
        migrations.AddIndex(
            model_name="deltacrowntransaction",
            index=models.Index(
                fields=["wallet", "created_at"], name="economy_del_wallet__a8652c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deltacrowntransaction",
            index=models.Index(fields=["wallet", "id"], name="economy_del_wallet__987fc8_idx"),
        ),
        migrations.AddConstraint(
            model_name="deltacrowntransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="economy_transaction_amount_nonzero",
            ),
        ),
        migrations.AddIndex(
            model_name="giftrequest",
            index=models.Index(
                fields=["sender_profile", "-created_at"], name="economy_gif_sender__dfd44d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="giftrequest",
            index=models.Index(
                fields=["receiver_profile", "status", "-created_at"],
                name="economy_gif_receive_b210a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="giftrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="economy_gif_status_943ab9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topuprequest",
            index=models.Index(
                fields=["wallet", "-requested_at"], name="economy_top_wallet__f2ea35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topuprequest",
            index=models.Index(
                fields=["status", "-requested_at"], name="economy_top_status_ed23e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="traderequest",
            index=models.Index(
                fields=["initiator_profile", "-created_at"], name="economy_tra_initiat_3a3e86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="traderequest",
            index=models.Index(
                fields=["target_profile", "status", "-created_at"],
                name="economy_tra_target__e9cb57_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="traderequest",
            index=models.Index(
                fields=["status", "-created_at"], name="economy_tra_status_3e0242_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinventoryitem",
            index=models.Index(
                fields=["profile", "-acquired_at"], name="economy_use_profile_e930ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinventoryitem",
            index=models.Index(fields=["acquired_from"], name="economy_use_acquire_971e90_idx"),
        ),
        migrations.AddConstraint(
            model_name="userinventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="economy_user_inventory_quantity_nonnegative",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userinventoryitem",
            unique_together={("profile", "item")},
        ),
        migrations.AddIndex(
            model_name="walletpinotp",
            index=models.Index(
                fields=["wallet", "-created_at"], name="economy_wal_wallet__c04e85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletpinotp",
            index=models.Index(
                fields=["expires_at", "is_used"], name="economy_wal_expires_b0cb1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["wallet", "-requested_at"], name="economy_wit_wallet__23bf1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["status", "-requested_at"], name="economy_wit_status_f5cc52_idx"
            ),
        ),
    ]
