# Generated by Django 5.2.8 on 2025-11-11 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deltacrownwallet',
            name='allow_overdraft',
            field=models.BooleanField(default=False, help_text='If True, allows negative balance (overdraft). Default: False (reject insufficient funds).'),
        ),
        migrations.AlterField(
            model_name='deltacrowntransaction',
            name='reason',
            field=models.CharField(choices=[('participation', 'Participation'), ('top4', 'Top 4'), ('runner_up', 'Runner-up'), ('winner', 'Winner'), ('entry_fee_debit', 'Entry fee (debit)'), ('refund', 'Refund'), ('manual_adjust', 'Manual adjust'), ('correction', 'Correction'), ('p2p_transfer', 'P2P Transfer')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='deltacrowntransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='economy_del_wallet__a8652c_idx'),
        ),
        migrations.AddIndex(
            model_name='deltacrowntransaction',
            index=models.Index(fields=['wallet', 'id'], name='economy_del_wallet__987fc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='deltacrowntransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='economy_transaction_amount_nonzero'),
        ),
    ]
