# Generated by Django 4.2.23 on 2025-09-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_participation_unique_per_wallet'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deltacrowntransaction',
            name='uq_participation_once_per_registration',
        ),
    ]
