# Generated by Django 4.2.23 on 2025-09-04 20:26
# Updated 2025-11-05: Made no-op since constraint was never created in fixed 0001_initial

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_participation_unique_per_wallet'),
    ]

    operations = [
        # No-op: The constraint 'uq_participation_once_per_registration' was in the
        # old version of 0001_initial.py but not in the fixed version.
        # This migration is kept for historical consistency but does nothing.
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;",
        ),
    ]
