# Generated by Django 5.2.8 on 2026-04-11 08:28

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coinpolicy",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="coinpolicy",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coinpolicy",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="deltacrownwallet",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="deltacrownwallet",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deltacrownwallet",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="giftrequest",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="giftrequest",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="giftrequest",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="topuprequest",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="topuprequest",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="topuprequest",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="traderequest",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="traderequest",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="traderequest",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="userinventoryitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="userinventoryitem",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userinventoryitem",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="walletpinotp",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="walletpinotp",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="walletpinotp",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Item icon/image",
                null=True,
                upload_to="inventory/items/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
    ]
