# Generated by Django 5.2.8 on 2026-01-02 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0003_add_withdrawal_request_model"),
        ("user_profile", "0047_phase2b_notifications_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique immutable identifier (e.g., awp-dragon-lore)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., AWP | Dragon Lore)", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Item description for users"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("COSMETIC", "Cosmetic Skin"),
                            ("CASE", "Loot Case"),
                            ("TOKEN", "Special Token"),
                            ("COLLECTIBLE", "Collectible Item"),
                            ("BADGE", "Achievement Badge"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("COMMON", "Common"),
                            ("RARE", "Rare"),
                            ("EPIC", "Epic"),
                            ("LEGENDARY", "Legendary"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "tradable",
                    models.BooleanField(
                        default=False, help_text="Can this item be traded between users?"
                    ),
                ),
                (
                    "giftable",
                    models.BooleanField(
                        default=False, help_text="Can this item be gifted to other users?"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Item icon/image",
                        null=True,
                        upload_to="inventory/items/",
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="External icon URL (if not using ImageField)",
                        max_length=500,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional item data (game-specific, stats, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "db_table": "economy_inventory_item",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["item_type", "rarity"], name="economy_inv_item_ty_03fbc8_idx"
                    ),
                    models.Index(fields=["slug"], name="economy_inv_slug_2a5d45_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GiftRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("CANCELED", "Canceled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional message from sender",
                        max_length=500,
                    ),
                ),
                (
                    "receiver_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts_received",
                        to="user_profile.userprofile",
                    ),
                ),
                (
                    "sender_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts_sent",
                        to="user_profile.userprofile",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gift_requests",
                        to="economy.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Request",
                "verbose_name_plural": "Gift Requests",
                "db_table": "economy_gift_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender_profile", "-created_at"],
                        name="economy_gif_sender__dfd44d_idx",
                    ),
                    models.Index(
                        fields=["receiver_profile", "status", "-created_at"],
                        name="economy_gif_receive_b210a2_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="economy_gif_status_943ab9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TradeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("offered_quantity", models.PositiveIntegerField(default=1)),
                (
                    "requested_quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Quantity of requested item", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("CANCELED", "Canceled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional message from initiator",
                        max_length=500,
                    ),
                ),
                (
                    "initiator_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades_initiated",
                        to="user_profile.userprofile",
                    ),
                ),
                (
                    "offered_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_offers",
                        to="economy.inventoryitem",
                    ),
                ),
                (
                    "requested_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: What initiator wants in return",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_requests",
                        to="economy.inventoryitem",
                    ),
                ),
                (
                    "target_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades_received",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Request",
                "verbose_name_plural": "Trade Requests",
                "db_table": "economy_trade_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["initiator_profile", "-created_at"],
                        name="economy_tra_initiat_3a3e86_idx",
                    ),
                    models.Index(
                        fields=["target_profile", "status", "-created_at"],
                        name="economy_tra_target__e9cb57_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="economy_tra_status_3e0242_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserInventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="How many of this item the user owns"
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False, help_text="Locked items cannot be traded/gifted"
                    ),
                ),
                (
                    "acquired_from",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("REWARD", "Reward"),
                            ("GIFT", "Gift"),
                            ("TRADE", "Trade"),
                            ("ADMIN", "Admin Grant"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_by",
                        to="economy.inventoryitem",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_inventory_items",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Inventory Item",
                "verbose_name_plural": "User Inventory Items",
                "db_table": "economy_user_inventory_item",
                "ordering": ["-acquired_at"],
                "indexes": [
                    models.Index(
                        fields=["profile", "-acquired_at"], name="economy_use_profile_e930ba_idx"
                    ),
                    models.Index(fields=["acquired_from"], name="economy_use_acquire_971e90_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 0)),
                        name="economy_user_inventory_quantity_nonnegative",
                    )
                ],
                "unique_together": {("profile", "item")},
            },
        ),
    ]
