# Generated by Django 5.2.8 on 2026-04-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0003_coinpolicy_deleted_at_coinpolicy_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deltacrowntransaction",
            name="cached_balance_after",
            field=models.IntegerField(
                blank=True,
                help_text="Wallet balance immediately after this transaction was applied. Populated at creation time; never mutate.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deltacrowntransaction",
            name="reason",
            field=models.CharField(
                choices=[
                    ("participation", "Participation"),
                    ("top4", "Top 4"),
                    ("runner_up", "Runner-up"),
                    ("winner", "Winner"),
                    ("entry_fee_debit", "Entry fee (debit)"),
                    ("refund", "Refund"),
                    ("manual_adjust", "Manual adjust"),
                    ("correction", "Correction"),
                    ("p2p_transfer", "P2P Transfer"),
                    ("top_up", "Top-Up"),
                    ("withdrawal", "Withdrawal"),
                ],
                max_length=32,
            ),
        ),
    ]
