# Generated by Django 4.2.23 on 2025-09-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_remove_paymentverification_pv_payer_account_idx_and_more'),
        ('economy', '0004_coins_polish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deltacrowntransaction',
            options={'ordering': ('-created_at', 'id'), 'verbose_name': 'DeltaCrown Transaction'},
        ),
        migrations.AlterModelOptions(
            name='deltacrownwallet',
            options={'verbose_name': 'DeltaCrown Wallet'},
        ),
        migrations.RemoveConstraint(
            model_name='deltacrowntransaction',
            name='uq_participation_once_per_registration_wallet',
        ),
        migrations.RemoveIndex(
            model_name='deltacrowntransaction',
            name='eco_tx_reason_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='deltacrowntransaction',
            name='eco_tx_tournament_created_idx',
        ),
        migrations.RenameIndex(
            model_name='deltacrowntransaction',
            new_name='economy_del_registr_95670c_idx',
            old_name='eco_tx_registration_idx',
        ),
        migrations.RenameIndex(
            model_name='deltacrowntransaction',
            new_name='economy_del_wallet__8fabbc_idx',
            old_name='eco_tx_wallet_idx',
        ),
        migrations.RemoveField(
            model_name='deltacrowntransaction',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='deltacrowntransaction',
            name='amount',
            field=models.IntegerField(help_text='Positive for credit, negative for debit'),
        ),
        migrations.AlterField(
            model_name='deltacrowntransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deltacrowntransaction',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coin_transactions', to='tournaments.match'),
        ),
        migrations.AlterField(
            model_name='deltacrowntransaction',
            name='reason',
            field=models.CharField(choices=[('participation', 'Participation'), ('top4', 'Top 4'), ('runner_up', 'Runner-up'), ('winner', 'Winner'), ('entry_fee_debit', 'Entry fee (debit)'), ('refund', 'Refund'), ('manual_adjust', 'Manual adjust'), ('correction', 'Correction')], max_length=32),
        ),
        migrations.AlterField(
            model_name='deltacrowntransaction',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coin_transactions', to='tournaments.registration'),
        ),
        migrations.AlterField(
            model_name='deltacrowntransaction',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coin_transactions', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='deltacrowntransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='economy.deltacrownwallet'),
        ),
        migrations.AddIndex(
            model_name='deltacrownwallet',
            index=models.Index(fields=['profile'], name='economy_del_profile_1fb9ea_idx'),
        ),
    ]
