# Generated by Django 5.2.8 on 2026-01-19 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0004_phase3a_inventory_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopUpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.PositiveIntegerField(help_text="Amount in DeltaCoins to add")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("rocket", "Rocket"),
                            ("bank", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        help_text="bKash/Nagad/Rocket transaction ID or bank reference",
                        max_length=50,
                    ),
                ),
                (
                    "payment_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment info (sender name, transaction ID, etc.)",
                    ),
                ),
                (
                    "dc_to_bdt_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="DeltaCoin to BDT exchange rate (e.g., 1 DC = 1.00 BDT)",
                        max_digits=10,
                    ),
                ),
                (
                    "bdt_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount paid in BDT", max_digits=10
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When credits were actually added", null=True
                    ),
                ),
                (
                    "user_note",
                    models.TextField(
                        blank=True, default="", help_text="User note/payment proof details"
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Admin note (approval details, verification notes, etc.)",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for rejection (shown to user)"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_topups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transaction that credited the coins (created on approval)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topup_request",
                        to="economy.deltacrowntransaction",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topup_requests",
                        to="economy.deltacrownwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Top-Up Request",
                "verbose_name_plural": "Top-Up Requests",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-requested_at"], name="economy_top_wallet__f2ea35_idx"
                    ),
                    models.Index(
                        fields=["status", "-requested_at"], name="economy_top_status_ed23e7_idx"
                    ),
                ],
            },
        ),
    ]
