# Generated by Django 4.2.23 on 2025-09-05 17:54
# Modified: Simplified migration to only apply safe operations.
# Removed problematic operations that tried to:
# 1. Remove 'metadata' field that was never created in fixed 0001
# 2. Convert IntegerFields back to ForeignKeys (contradicts model refactoring)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('tournaments', '0004_remove_paymentverification_pv_payer_account_idx_and_more'),  # Commented - tournament app moved to legacy
        ('economy', '0004_coins_polish'),
    ]

    operations = [
        # Keep only the safe operations that don't conflict with our refactored models
        migrations.AlterModelOptions(
            name='deltacrowntransaction',
            options={'ordering': ('-created_at', 'id'), 'verbose_name': 'DeltaCrown Transaction'},
        ),
        migrations.AlterModelOptions(
            name='deltacrownwallet',
            options={'verbose_name': 'DeltaCrown Wallet'},
        ),
        migrations.RemoveConstraint(
            model_name='deltacrowntransaction',
            name='uq_participation_once_per_registration_wallet',
        ),
        migrations.AddIndex(
            model_name='deltacrownwallet',
            index=models.Index(fields=['profile'], name='economy_del_profile_1fb9ea_idx'),
        ),
        # Note: Removed operations that tried to:
        # - RemoveField 'metadata' (field doesn't exist in our fixed 0001)
        # - RemoveIndex/RenameIndex operations (indexes may have different names or not exist)
        # - AlterField operations converting IntegerFields to ForeignKeys (contradicts model state)
    ]
