# Generated by Django 5.2.8 on 2026-04-30 20:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0004_add_cached_balance_after_and_reason_choices"),
        ("user_profile", "0043_bounty_deleted_at_bounty_deleted_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EconomyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "bdt_per_dc",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.1000"),
                        help_text="BDT value of 1 DeltaCoin. Default 0.10 → 1 BDT = 10 DC.",
                        max_digits=10,
                    ),
                ),
                (
                    "top_up_min_dc",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Minimum DeltaCoins a user can top up in a single request.",
                    ),
                ),
                (
                    "withdrawal_min_dc",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Minimum DeltaCoins a user can withdraw in a single request.",
                    ),
                ),
                (
                    "withdrawal_fee_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Processing fee charged on withdrawals, as a percentage (e.g. 2.00 = 2%).",
                        max_digits=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Economy Configuration",
                "verbose_name_plural": "Economy Configuration",
            },
        ),
        migrations.AddField(
            model_name="deltacrownwallet",
            name="is_treasury",
            field=models.BooleanField(
                default=False,
                help_text="True for the single Master Treasury system wallet. Use economy.services.get_master_treasury() to obtain it.",
            ),
        ),
        migrations.AlterField(
            model_name="deltacrownwallet",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                help_text="Owning user profile. Null only for the Master Treasury system wallet.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dc_wallet",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="deltacrownwallet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_treasury", True)),
                fields=("is_treasury",),
                name="economy_single_master_treasury",
            ),
        ),
    ]
