# Generated by Django 5.2.8 on 2026-01-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0005_topuprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="deltacrownwallet",
            name="pin_enabled",
            field=models.BooleanField(default=False, help_text="Whether PIN protection is enabled"),
        ),
        migrations.AddField(
            model_name="deltacrownwallet",
            name="pin_failed_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of consecutive failed PIN attempts"
            ),
        ),
        migrations.AddField(
            model_name="deltacrownwallet",
            name="pin_locked_until",
            field=models.DateTimeField(
                blank=True,
                help_text="PIN lockout expiry timestamp (15 min after 5 failed attempts)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deltacrownwallet",
            name="pin_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hashed 6-digit PIN for withdrawal verification",
                max_length=255,
            ),
        ),
    ]
