# Generated by Django 4.2.24 on 2025-11-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_alter_deltacrowntransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deltacrowntransaction',
            name='economy_del_tournam_420090_idx',
        ),
        migrations.RemoveIndex(
            model_name='deltacrowntransaction',
            name='economy_del_registr_95670c_idx',
        ),
        migrations.RemoveField(
            model_name='coinpolicy',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='deltacrowntransaction',
            name='match',
        ),
        migrations.RemoveField(
            model_name='deltacrowntransaction',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='deltacrowntransaction',
            name='tournament',
        ),
        migrations.AddField(
            model_name='coinpolicy',
            name='tournament_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Legacy tournament ID (reference only)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deltacrowntransaction',
            name='match_id',
            field=models.IntegerField(blank=True, help_text='Legacy match ID (reference only)', null=True),
        ),
        migrations.AddField(
            model_name='deltacrowntransaction',
            name='registration_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Legacy registration ID (reference only)', null=True),
        ),
        migrations.AddField(
            model_name='deltacrowntransaction',
            name='tournament_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Legacy tournament ID (reference only)', null=True),
        ),
    ]
