# Generated by Django 5.2.8 on 2026-04-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0006_phase4_escrow_reasons_and_model_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EconomyDashboard",
            fields=[],
            options={
                "verbose_name": "Economy Dashboard",
                "verbose_name_plural": "Economy Dashboard",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("economy.economyconfig",),
        ),
        migrations.AlterModelOptions(
            name="deltacrowntransaction",
            options={
                "ordering": ("-created_at", "id"),
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="deltacrownwallet",
            options={"verbose_name": "Wallet", "verbose_name_plural": "Wallets"},
        ),
    ]
