# Generated by Django 5.2.8 on 2026-01-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0006_add_wallet_pin_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletPINOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(help_text="Hashed OTP code (6 digits)", max_length=255),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("pin_setup", "PIN Setup (First Time)"),
                            ("pin_change", "PIN Change"),
                        ],
                        default="pin_setup",
                        max_length=20,
                    ),
                ),
                (
                    "attempt_count",
                    models.IntegerField(default=0, help_text="Number of verification attempts"),
                ),
                (
                    "max_attempts",
                    models.IntegerField(default=5, help_text="Maximum allowed attempts"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether OTP has been successfully verified and used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="OTP expiry time (10 minutes from creation)"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="When OTP was successfully used", null=True
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_otps",
                        to="economy.deltacrownwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet PIN OTP",
                "verbose_name_plural": "Wallet PIN OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-created_at"], name="economy_wal_wallet__c04e85_idx"
                    ),
                    models.Index(
                        fields=["expires_at", "is_used"], name="economy_wal_expires_b0cb1b_idx"
                    ),
                ],
            },
        ),
    ]
