# Generated by Django 5.2.8 on 2026-04-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0007_phase35_economy_dashboard_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deltacrowntransaction",
            name="reason",
            field=models.CharField(
                choices=[
                    ("participation", "Participation"),
                    ("top4", "Top 4"),
                    ("runner_up", "Runner-up"),
                    ("winner", "Winner"),
                    ("entry_fee_debit", "Entry fee (debit)"),
                    ("refund", "Refund"),
                    ("manual_adjust", "Manual adjust"),
                    ("correction", "Correction"),
                    ("p2p_transfer", "P2P Transfer"),
                    ("top_up", "Top-Up"),
                    ("withdrawal", "Withdrawal"),
                    ("escrow_lock", "Escrow Locked"),
                    ("escrow_refund", "Escrow Refunded"),
                    ("wager_win", "Wager Winnings"),
                    ("platform_fee", "Platform Fee"),
                    ("withdrawal_revenue", "Withdrawal Revenue (Fee)"),
                ],
                max_length=32,
            ),
        ),
    ]
