# Generated by Django 5.2.8 on 2026-05-01 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0008_phase5_p2p_and_withdrawal_revenue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EconomyPlaybook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short, descriptive title for this playbook entry",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated from title.  Used as a stable identifier.",
                        max_length=280,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full content in Markdown or plain text.  Use ## headings, - bullet lists, and ``` code blocks for structure."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Automatically updated whenever the article is saved",
                    ),
                ),
            ],
            options={
                "verbose_name": "Economy Playbook",
                "verbose_name_plural": "Economy Playbook",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PrizeClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag indicating if this record has been soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when this record was deleted", null=True
                    ),
                ),
                (
                    "tournament_name",
                    models.CharField(
                        help_text="Name of the tournament (denormalised for audit stability after deletion/rename)",
                        max_length=255,
                    ),
                ),
                (
                    "amount_bdt",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prize amount in BDT (Bangladeshi Taka) to be disbursed externally",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("bkash", "bKash"), ("nagad", "Nagad"), ("bank", "Bank Transfer")],
                        help_text="Channel through which the admin will transfer the funds",
                        max_length=10,
                    ),
                ),
                (
                    "account_details",
                    models.TextField(
                        help_text='Full account details for the selected payment method. bKash/Nagad: "01XXXXXXXXX (Account Name)". Bank: "Account No / Branch / Bank Name / Routing No".'
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("verifying_kyc", "Verifying KYC"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Admin-only note. On PAID: record the external transfer reference (e.g. bKash TrxID). On REJECTED: explain the reason clearly.",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the winner submitted this claim"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When an admin marked this claim PAID or REJECTED",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who processed this claim",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_prize_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Wallet of the winner (used for identity reference only — no DC movement occurs)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prize_claims",
                        to="economy.deltacrownwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prize Claim",
                "verbose_name_plural": "Prize Claims",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-submitted_at"], name="economy_pri_wallet__967602_idx"
                    ),
                    models.Index(
                        fields=["status", "-submitted_at"], name="economy_pri_status_42ae99_idx"
                    ),
                ],
            },
        ),
    ]
