# Generated by Django 5.2.8 on 2026-05-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0009_prize_claim_playbook_compliance_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialFortress",
            fields=[],
            options={
                "verbose_name": "🛡️ Financial Fortress",
                "verbose_name_plural": "🛡️ Financial Fortress",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("economy.economyconfig",),
        ),
    ]
