# Generated by Django 5.2.8 on 2026-05-03 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0010_financialfortress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FortressAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("MINT_TO_TREASURY", "Minted to Treasury"),
                            ("AIRDROP", "Direct Airdrop"),
                            ("BULK_AIRDROP", "Bulk Airdrop"),
                            ("APPROVE_TOPUP", "Top-Up Approved"),
                            ("REJECT_TOPUP", "Top-Up Rejected"),
                            ("AUTO_REWARD_KYC", "Auto: KYC Bonus"),
                            ("AUTO_REWARD_MATCH", "Auto: First Match Bonus"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        default="SYSTEM",
                        help_text="Denormalized display name (survives user deletion).",
                        max_length=100,
                    ),
                ),
                (
                    "target_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Denormalized target description (username, 'Treasury', 'BULK: 42 wallets').",
                        max_length=150,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        default=0,
                        help_text="Signed DC amount (positive = credit, negative = debit).",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable note / reference attached to this action.",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the actor at time of action.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="SuperAdmin who triggered the action (NULL for system/auto actions).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fortress_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fortress_audit_entries",
                        to="economy.deltacrownwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fortress Audit Log",
                "verbose_name_plural": "Fortress Audit Logs",
                "ordering": ["-created_at"],
                "default_manager_name": "objects",
            },
        ),
    ]
