# Generated by Django 5.2.8 on 2026-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0011_fortress_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="economyconfig",
            name="fortress_pin_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hashed Fortress master PIN (use 'Set PIN' action in admin to change). If blank, the Fortress is locked and no PIN will be accepted.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="economyconfig",
            name="fortress_pin_max_attempts",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Maximum consecutive wrong-PIN attempts before a 60-second cooldown.",
            ),
        ),
    ]
