# Generated by Django 5.2.8 on 2026-05-30 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0014_dailyreward_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dailyrewardclaim",
            name="unique_daily_claim_per_user_per_day",
        ),
        migrations.AlterField(
            model_name="dailyloginstreak",
            name="total_claimed",
            field=models.PositiveIntegerField(
                default=0, help_text="Lifetime DC earned via daily reward."
            ),
        ),
        migrations.AlterField(
            model_name="dailyrewardclaim",
            name="day_index",
            field=models.SmallIntegerField(help_text="Platform day index 0=Thu…6=Wed."),
        ),
        migrations.AlterField(
            model_name="dailyrewardclaim",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrewardclaim",
            name="platform_date",
            field=models.DateField(
                db_index=True, help_text="Calendar date (server TZ) of this claim."
            ),
        ),
        migrations.AlterField(
            model_name="dailyrewardclaim",
            name="streak_day",
            field=models.PositiveIntegerField(help_text="User's streak count at time of claim."),
        ),
        migrations.AlterField(
            model_name="dailyrewardconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrewardconfig",
            name="week_schedule",
            field=models.JSONField(
                default=list, help_text="7-element list [{day, xp, dc}] — Thu=0 through Wed=6."
            ),
        ),
        migrations.AlterField(
            model_name="dailyrewardmilestone",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="deltacrowntransaction",
            name="reason",
            field=models.CharField(
                choices=[
                    ("participation", "Participation"),
                    ("top4", "Top 4"),
                    ("runner_up", "Runner-up"),
                    ("winner", "Winner"),
                    ("entry_fee_debit", "Entry fee (debit)"),
                    ("refund", "Refund"),
                    ("manual_adjust", "Manual adjust"),
                    ("correction", "Correction"),
                    ("p2p_transfer", "P2P Transfer"),
                    ("top_up", "Top-Up"),
                    ("withdrawal", "Withdrawal"),
                    ("escrow_lock", "Escrow Locked"),
                    ("escrow_refund", "Escrow Refunded"),
                    ("wager_win", "Wager Winnings"),
                    ("platform_fee", "Platform Fee"),
                    ("withdrawal_revenue", "Withdrawal Revenue (Fee)"),
                    ("daily_reward", "Daily Login Reward"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyrewardclaim",
            unique_together={("user", "platform_date")},
        ),
    ]
