# Generated by Django 5.2.8 on 2026-04-11 08:28

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when this record was deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this record has been soft-deleted",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="brands/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="hover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/", validators=[apps.common.validators.validate_image_upload]
            ),
        ),
    ]
