# Generated by Django 5.2.8 on 2026-01-24 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organization legal/brand name (e.g., 'SYNTAX', 'Cloud9 Bangladesh')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (auto-generated from name)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Verified Org Badge status (granted by platform admins)",
                    ),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, help_text="Date verification was granted", null=True
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Organization logo (inherited by teams if enforce_brand=True)",
                        null=True,
                        upload_to="organizations/logos/",
                    ),
                ),
                (
                    "badge",
                    models.ImageField(
                        blank=True,
                        help_text="Verified badge overlay",
                        null=True,
                        upload_to="organizations/badges/",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Profile page header banner",
                        null=True,
                        upload_to="organizations/banners/",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Organization bio/mission statement"),
                ),
                ("website", models.URLField(blank=True, help_text="Official organization website")),
                (
                    "twitter",
                    models.CharField(
                        blank=True, help_text="Twitter handle (without @)", max_length=50
                    ),
                ),
                (
                    "master_wallet_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Prize money destination (FK to economy.Wallet - Phase 3)",
                        null=True,
                    ),
                ),
                (
                    "revenue_split_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Smart contract revenue splits (e.g., {'team': 70, 'org': 30})",
                    ),
                ),
                (
                    "enforce_brand",
                    models.BooleanField(
                        default=False,
                        help_text="Force teams to use organization logo (disable custom team logos)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Organization creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last modification timestamp"),
                ),
                (
                    "ceo",
                    models.ForeignKey(
                        help_text="Organization owner (full control)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations_organization",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Team display name (e.g., 'Protocol V', 'Syntax FC')",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (auto-generated from name)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "game_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Game title ID (FK to games.Game - avoiding direct FK for now)",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Home region (e.g., 'Bangladesh', 'India') - identity, not server",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DELETED", "Deleted"),
                            ("SUSPENDED", "Suspended"),
                            ("DISBANDED", "Disbanded"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        help_text="Team lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Team logo (or inherits from organization if enforce_brand=True)",
                        null=True,
                        upload_to="teams/logos/",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Profile page header banner",
                        null=True,
                        upload_to="teams/banners/",
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Team bio/description")),
                (
                    "preferred_server",
                    models.CharField(
                        blank=True,
                        help_text="TOC: Preferred game server (e.g., 'Singapore', 'Mumbai')",
                        max_length=50,
                    ),
                ),
                (
                    "emergency_contact_discord",
                    models.CharField(
                        blank=True,
                        help_text="TOC: Discord handle for tournament emergencies",
                        max_length=50,
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="TOC: Phone number for tournament emergencies",
                        max_length=20,
                    ),
                ),
                (
                    "is_temporary",
                    models.BooleanField(
                        default=False,
                        help_text="Created during tournament registration (clean up after tournament)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Team creation timestamp"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last modification timestamp"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (NULL if independent team)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner user (NULL if organization-owned team)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": "organizations_team",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CEO", "CEO (Owner)"),
                            ("MANAGER", "Manager"),
                            ("SCOUT", "Scout"),
                            ("ANALYST", "Analyst"),
                        ],
                        help_text="Organization-level role",
                        max_length=20,
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom permission overrides (e.g., {'can_create_teams': True})",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date user joined organization staff"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this staff member belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User with organization-level access",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Membership",
                "verbose_name_plural": "Organization Memberships",
                "db_table": "organizations_org_membership",
            },
        ),
        migrations.CreateModel(
            name="TeamRanking",
            fields=[
                (
                    "team",
                    models.OneToOneField(
                        help_text="Team this ranking belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ranking",
                        serialize=False,
                        to="organizations.team",
                    ),
                ),
                (
                    "current_cp",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Current Crown Points (can decrease via decay)",
                    ),
                ),
                (
                    "season_cp",
                    models.IntegerField(
                        default=0, help_text="CP earned this season (resets every 4 months)"
                    ),
                ),
                (
                    "all_time_cp",
                    models.IntegerField(
                        default=0, help_text="Lifetime maximum CP achieved (never decreases)"
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("UNRANKED", "Unranked"),
                            ("BRONZE", "Bronze"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("PLATINUM", "Platinum"),
                            ("DIAMOND", "Diamond"),
                            ("ASCENDANT", "Ascendant"),
                            ("CROWN", "Crown"),
                        ],
                        db_index=True,
                        default="UNRANKED",
                        help_text="Tier based on current CP thresholds",
                        max_length=20,
                    ),
                ),
                (
                    "global_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Global position (all games, updated every 5 minutes)",
                        null=True,
                    ),
                ),
                (
                    "regional_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Regional position (same region, updated every 5 minutes)",
                        null=True,
                    ),
                ),
                (
                    "rank_change_24h",
                    models.IntegerField(
                        default=0, help_text="Rank change in last 24 hours (positive = climbing)"
                    ),
                ),
                (
                    "rank_change_7d",
                    models.IntegerField(
                        default=0, help_text="Rank change in last 7 days (positive = climbing)"
                    ),
                ),
                (
                    "is_hot_streak",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Currently on hot streak (3+ consecutive wins)",
                    ),
                ),
                (
                    "streak_count",
                    models.IntegerField(
                        default=0, help_text="Current win streak count (resets on loss)"
                    ),
                ),
                (
                    "last_activity_date",
                    models.DateTimeField(auto_now=True, help_text="Last match played timestamp"),
                ),
                (
                    "last_decay_applied",
                    models.DateTimeField(
                        blank=True, help_text="Last time inactivity decay was applied", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Ranking",
                "verbose_name_plural": "Team Rankings",
                "db_table": "organizations_ranking",
                "ordering": ["-current_cp"],
            },
        ),
        migrations.CreateModel(
            name="TeamActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Team Created"),
                            ("UPDATE", "Team Updated"),
                            ("DELETE", "Team Deleted"),
                            ("ROSTER_ADD", "Member Added"),
                            ("ROSTER_REMOVE", "Member Removed"),
                            ("ROSTER_UPDATE", "Member Role Changed"),
                            ("MIGRATE", "Migrated to vNext"),
                            ("ACQUIRE", "Acquired by Organization"),
                            ("TOURNAMENT_REGISTER", "Registered for Tournament"),
                            ("RANKING_UPDATE", "Ranking Changed"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                ("actor_id", models.IntegerField(help_text="User ID who performed action")),
                (
                    "actor_username",
                    models.CharField(
                        help_text="Cached username (preserved if user deleted)", max_length=150
                    ),
                ),
                ("description", models.TextField(help_text="Human-readable description of action")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (e.g., {'old_role': 'PLAYER', 'new_role': 'MANAGER'})",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="When action occurred"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team this activity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Activity Log",
                "verbose_name_plural": "Team Activity Logs",
                "db_table": "organizations_activity_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("INVITED", "Invited (Pending)"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="INVITED",
                        help_text="Membership status (ACTIVE, INACTIVE, INVITED, SUSPENDED)",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("COACH", "Coach"),
                            ("PLAYER", "Player"),
                            ("SUBSTITUTE", "Substitute"),
                            ("ANALYST", "Analyst"),
                            ("SCOUT", "Scout"),
                        ],
                        help_text="Organizational role (determines permissions)",
                        max_length=20,
                    ),
                ),
                (
                    "roster_slot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STARTER", "Starter"),
                            ("SUBSTITUTE", "Substitute"),
                            ("COACH", "Coach (Non-playing)"),
                            ("ANALYST", "Analyst (Non-playing)"),
                        ],
                        help_text="Physical roster slot (STARTER, SUBSTITUTE, COACH, ANALYST)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "player_role",
                    models.CharField(
                        blank=True,
                        help_text="Game-specific tactical role (e.g., 'Duelist', 'IGL', 'AWPer')",
                        max_length=50,
                    ),
                ),
                (
                    "is_tournament_captain",
                    models.BooleanField(
                        default=False,
                        help_text="Designated captain for tournament admin duties (max 1 per team)",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date user joined team roster"
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True, help_text="Date user left team (if status=INACTIVE)", null=True
                    ),
                ),
                (
                    "left_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for leaving (Resignation, Kicked, Transfer, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team this membership belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User on the roster",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Membership",
                "verbose_name_plural": "Team Memberships",
                "db_table": "organizations_membership",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamMigrationMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "legacy_team_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Original teams_team.id from legacy system",
                        unique=True,
                    ),
                ),
                (
                    "vnext_team_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="New organizations_team.id from vNext system",
                        unique=True,
                    ),
                ),
                (
                    "legacy_slug",
                    models.SlugField(
                        help_text="Legacy team slug (for URL redirect middleware)", max_length=100
                    ),
                ),
                (
                    "migration_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when migration occurred"
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Data verification passed (roster, rankings, tournament history)",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, help_text="Any discrepancies found during verification"
                    ),
                ),
                (
                    "migrated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who executed migration script",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Migration Map",
                "verbose_name_plural": "Team Migration Maps",
                "db_table": "organizations_migration_map",
                "ordering": ["-migration_date"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationRanking",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        help_text="Organization this ranking belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ranking",
                        serialize=False,
                        to="organizations.organization",
                    ),
                ),
                (
                    "empire_score",
                    models.IntegerField(
                        db_index=True, default=0, help_text="Aggregated score from top 3 teams' CP"
                    ),
                ),
                (
                    "global_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Global organization rank (updated nightly)",
                        null=True,
                    ),
                ),
                (
                    "regional_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Regional organization rank (updated nightly)",
                        null=True,
                    ),
                ),
                (
                    "total_trophies",
                    models.IntegerField(
                        default=0, help_text="Total tournament wins across all teams"
                    ),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(
                        auto_now=True, help_text="Last empire score calculation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Ranking",
                "verbose_name_plural": "Organization Rankings",
                "db_table": "organizations_org_ranking",
                "ordering": ["-empire_score"],
                "indexes": [
                    models.Index(fields=["-empire_score"], name="org_ranking_score_desc_idx"),
                    models.Index(fields=["global_rank"], name="org_ranking_rank_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="org_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["ceo"], name="org_ceo_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["is_verified"], name="org_verified_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(fields=["organization", "role"], name="orgmem_org_role_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(fields=["user"], name="orgmem_user_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="organizationmembership",
            unique_together={("organization", "user")},
        ),
        migrations.AddIndex(
            model_name="teamranking",
            index=models.Index(fields=["-current_cp"], name="ranking_cp_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="teamranking",
            index=models.Index(fields=["tier"], name="ranking_tier_idx"),
        ),
        migrations.AddIndex(
            model_name="teamranking",
            index=models.Index(fields=["is_hot_streak"], name="ranking_streak_idx"),
        ),
        migrations.AddIndex(
            model_name="teamranking",
            index=models.Index(fields=["-current_cp", "tier"], name="ranking_cp_tier_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["slug"], name="team_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["game_id", "region"], name="team_game_region_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["organization"], name="team_org_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["status"], name="team_status_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["owner", "game_id"], name="team_owner_game_idx"),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", False), ("status", "ACTIVE")),
                fields=("owner", "game_id"),
                name="one_independent_team_per_game",
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("organization__isnull", False), ("owner__isnull", True)),
                    models.Q(("organization__isnull", True), ("owner__isnull", False)),
                    _connector="OR",
                ),
                name="team_has_organization_xor_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="teamactivitylog",
            index=models.Index(fields=["team", "-timestamp"], name="activity_team_time_idx"),
        ),
        migrations.AddIndex(
            model_name="teamactivitylog",
            index=models.Index(fields=["action_type"], name="activity_type_idx"),
        ),
        migrations.AddIndex(
            model_name="teamactivitylog",
            index=models.Index(fields=["-timestamp"], name="activity_time_idx"),
        ),
        migrations.AddIndex(
            model_name="teamactivitylog",
            index=models.Index(fields=["actor_id", "-timestamp"], name="activity_actor_time_idx"),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["team", "status"], name="membership_team_status_idx"),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["user", "status"], name="membership_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["role"], name="membership_role_idx"),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["is_tournament_captain"], name="membership_captain_idx"),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("team", "user"),
                name="one_active_membership_per_user_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_tournament_captain", True), ("status", "ACTIVE")),
                fields=("team",),
                name="one_tournament_captain_per_team",
            ),
        ),
        migrations.AddIndex(
            model_name="teammigrationmap",
            index=models.Index(fields=["legacy_team_id"], name="migration_legacy_idx"),
        ),
        migrations.AddIndex(
            model_name="teammigrationmap",
            index=models.Index(fields=["vnext_team_id"], name="migration_vnext_idx"),
        ),
        migrations.AddIndex(
            model_name="teammigrationmap",
            index=models.Index(fields=["legacy_slug"], name="migration_slug_idx"),
        ),
    ]
