# Generated by Django 5.2.8 on 2026-01-26 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="tag",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Team tag/abbreviation (e.g., 'PRTCL', 'SYN') - max 5 chars, unique per game",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="Short team motto/slogan (e.g., 'Victory Through Strategy')",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["game_id", "tag"], name="team_game_tag_idx"),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tag__isnull", False)),
                fields=("game_id", "tag"),
                name="unique_tag_per_game",
            ),
        ),
    ]
