# Generated by Django 5.2.8 on 2026-01-26 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_add_team_tag_and_tagline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "invited_email",
                    models.EmailField(
                        blank=True, help_text="Email for non-registered users", max_length=254
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("COACH", "Coach"),
                            ("PLAYER", "Player"),
                            ("SUBSTITUTE", "Substitute"),
                            ("ANALYST", "Analyst"),
                            ("SCOUT", "Scout"),
                        ],
                        default="PLAYER",
                        help_text="Role to assign upon acceptance",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Invitation status",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for accepting invitation",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When invitation was sent"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When invitation expires (7 days from creation)"
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When invitee responded (accepted/declined)",
                        null=True,
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User being invited (NULL if invite by email)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who sent the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_team_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team extending the invitation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Invitation",
                "verbose_name_plural": "Team Invitations",
                "db_table": "organizations_team_invite",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["team", "status"], name="team_invite_team_status_idx"),
                    models.Index(fields=["invited_user"], name="team_invite_user_idx"),
                    models.Index(fields=["invited_email"], name="team_invite_email_idx"),
                    models.Index(fields=["token"], name="team_invite_token_idx"),
                ],
            },
        ),
    ]
