# Generated by Django 5.2.8 on 2026-01-26 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_add_team_invite_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationProfile",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        help_text="Organization this profile belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to="organizations.organization",
                    ),
                ),
                (
                    "founded_year",
                    models.IntegerField(
                        blank=True, help_text="Year organization was founded", null=True
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("club", "Esports Club (Casual)"),
                            ("pro", "Pro Organization"),
                            ("guild", "Community Guild"),
                        ],
                        default="club",
                        help_text="Organization classification",
                        max_length=20,
                    ),
                ),
                (
                    "hq_city",
                    models.CharField(
                        blank=True, help_text="City where organization is based", max_length=100
                    ),
                ),
                (
                    "hq_address",
                    models.TextField(
                        blank=True, help_text="Full headquarters address (for Pro orgs)"
                    ),
                ),
                (
                    "business_email",
                    models.EmailField(
                        blank=True,
                        help_text="Official business email (for Pro orgs)",
                        max_length=254,
                    ),
                ),
                (
                    "trade_license",
                    models.CharField(
                        blank=True, help_text="Trade license / BIN / TIN number", max_length=100
                    ),
                ),
                (
                    "discord_link",
                    models.URLField(blank=True, help_text="Discord community invite link"),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, help_text="Instagram handle or URL", max_length=100
                    ),
                ),
                ("facebook", models.URLField(blank=True, help_text="Facebook page URL")),
                ("youtube", models.URLField(blank=True, help_text="YouTube channel URL")),
                (
                    "region_code",
                    models.CharField(
                        default="BD", help_text="ISO country code (e.g., BD, US, SG)", max_length=3
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="BDT",
                        help_text="Primary ledger currency (BDT, USD, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[("mobile", "Mobile Banking"), ("bank", "Bank Transfer")],
                        default="mobile",
                        help_text="Primary payout method for prize money",
                        max_length=20,
                    ),
                ),
                (
                    "brand_color",
                    models.CharField(
                        blank=True,
                        help_text="Primary brand color (hex code, e.g., #FFD700)",
                        max_length=7,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Profile creation timestamp"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last modification timestamp"),
                ),
            ],
            options={
                "verbose_name": "Organization Profile",
                "verbose_name_plural": "Organization Profiles",
                "db_table": "organizations_organizationprofile",
            },
        ),
    ]
