# Generated by Django 5.2.8 on 2026-01-26 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_create_organization_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="public_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Human-readable public identifier (e.g., ORG_A7K2N9Q5B3)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Universal unique identifier for cross-system integration",
                null=True,
                unique=True,
            ),
        ),
    ]
