# Generated by Django 5.2.8 on 2026-01-26 14:47

import secrets
import string
import uuid

from django.db import migrations


def generate_public_id(prefix="ORG", length=10):
    """Generate secure public ID (matches apps.organizations.utils.ids)."""
    alphabet = string.ascii_uppercase + '23456789'
    random_chars = ''.join(secrets.choice(alphabet) for _ in range(length))
    return f"{prefix}_{random_chars}"


def backfill_organization_identifiers(apps, schema_editor):
    """
    Backfill uuid and public_id for all existing organizations.
    
    Handles collision retries for public_id to ensure uniqueness.
    """
    Organization = apps.get_model('organizations', 'Organization')
    
    orgs_without_uuid = Organization.objects.filter(uuid__isnull=True)
    orgs_without_public_id = Organization.objects.filter(public_id__isnull=True)
    
    # Backfill UUIDs (no collision risk)
    for org in orgs_without_uuid:
        org.uuid = uuid.uuid4()
        org.save(update_fields=['uuid'])
    
    # Backfill public_ids (with collision retry)
    for org in orgs_without_public_id:
        # Try up to 10 times to generate unique public_id
        for attempt in range(10):
            candidate_id = generate_public_id(prefix="ORG", length=10)
            if not Organization.objects.filter(public_id=candidate_id).exists():
                org.public_id = candidate_id
                org.save(update_fields=['public_id'])
                break
        else:
            # Extremely unlikely: all 10 attempts collided
            raise ValueError(f"Failed to generate unique public_id for org {org.id} after 10 attempts")


def reverse_backfill(apps, schema_editor):
    """Reverse migration: clear uuid and public_id."""
    Organization = apps.get_model('organizations', 'Organization')
    Organization.objects.update(uuid=None, public_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_add_org_uuid_and_public_id"),
    ]

    operations = [
        migrations.RunPython(backfill_organization_identifiers, reverse_backfill),
    ]
