# Generated by Django Admin on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_backfill_org_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='visibility',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('PUBLIC', 'Public'),
                    ('PRIVATE', 'Private'),
                    ('UNLISTED', 'Unlisted'),
                ],
                default='PUBLIC',
                db_index=True,
                help_text='Team visibility setting'
            ),
        ),
    ]
