# Generated by Django 5.2.8 on 2026-01-30 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_fix_teaminvite_fk_reference"),
        ("teams", "0101_alter_teamjoinrequest_team_alter_teamsponsor_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamranking",
            name="team",
            field=models.OneToOneField(
                help_text="Team this ranking belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="ranking",
                serialize=False,
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="team",
            field=models.ForeignKey(
                help_text="Team extending invitation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vnext_invites",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(
                help_text="Team this membership belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vnext_memberships",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="teamactivitylog",
            name="team",
            field=models.ForeignKey(
                help_text="Team this activity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="teams.team",
            ),
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
