# Generated by Django 5.2.8 on 2026-01-31 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_alter_teamranking_team_alter_teaminvite_team_and_more"),
        ("teams", "0101_alter_teamjoinrequest_team_alter_teamsponsor_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamAdminProxy",
            fields=[],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("teams.team",),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Team display name (e.g., 'Protocol V', 'Syntax FC')",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (auto-generated from name)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Team tag/abbreviation (e.g., 'PRTCL', 'SYN') - max 5 chars, unique per game",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short team motto/slogan (e.g., 'Victory Through Strategy')",
                        max_length=100,
                    ),
                ),
                (
                    "game_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Game title ID (FK to games.Game - avoiding direct FK for now)",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Home region (e.g., 'Bangladesh', 'India') - identity, not server",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DELETED", "Deleted"),
                            ("SUSPENDED", "Suspended"),
                            ("DISBANDED", "Disbanded"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        help_text="Team lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("PRIVATE", "Private"),
                            ("UNLISTED", "Unlisted"),
                        ],
                        db_index=True,
                        default="PUBLIC",
                        help_text="Team visibility setting",
                        max_length=20,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Team logo (or inherits from organization if enforce_brand=True)",
                        null=True,
                        upload_to="teams/logos/",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Profile page header banner",
                        null=True,
                        upload_to="teams/banners/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        default="#3B82F6",
                        help_text="Primary team color (hex format, e.g., #3B82F6)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True,
                        default="#10B981",
                        help_text="Accent team color (hex format, e.g., #10B981)",
                        max_length=7,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Team bio/description")),
                (
                    "preferred_server",
                    models.CharField(
                        blank=True,
                        help_text="TOC: Preferred game server (e.g., 'Singapore', 'Mumbai')",
                        max_length=50,
                    ),
                ),
                (
                    "emergency_contact_discord",
                    models.CharField(
                        blank=True,
                        help_text="TOC: Discord handle for tournament emergencies",
                        max_length=50,
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="TOC: Phone number for tournament emergencies",
                        max_length=20,
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Team Twitter/X profile URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, help_text="Team Instagram profile URL"),
                ),
                ("youtube_url", models.URLField(blank=True, help_text="Team YouTube channel URL")),
                ("twitch_url", models.URLField(blank=True, help_text="Team Twitch channel URL")),
                (
                    "is_temporary",
                    models.BooleanField(
                        default=False,
                        help_text="Created during tournament registration (clean up after tournament)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Team creation timestamp"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last modification timestamp"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (NULL if independent team)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner user (NULL if organization-owned team)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": "organizations_team",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="team_slug_idx"),
                    models.Index(fields=["game_id", "region"], name="team_game_region_idx"),
                    models.Index(fields=["organization"], name="team_org_idx"),
                    models.Index(fields=["status"], name="team_status_idx"),
                    models.Index(fields=["owner", "game_id"], name="team_owner_game_idx"),
                    models.Index(fields=["game_id", "tag"], name="team_game_tag_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("owner__isnull", False), ("status", "ACTIVE")),
                        fields=("owner", "game_id"),
                        name="one_independent_team_per_game",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("organization__isnull", False), ("owner__isnull", True)),
                            models.Q(("organization__isnull", True), ("owner__isnull", False)),
                            _connector="OR",
                        ),
                        name="team_has_organization_xor_owner",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("tag__isnull", False)),
                        fields=("game_id", "tag"),
                        name="unique_tag_per_game",
                    ),
                ],
            },
        ),
    ]
