# Generated by Django 5.2.8 on 2026-01-31 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0011_add_team_colors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teaminvite",
            name="team",
            field=models.ForeignKey(
                help_text="Team extending invitation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vnext_invites",
                to="organizations.team",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(
                help_text="Team this membership belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vnext_memberships",
                to="organizations.team",
            ),
        ),
    ]
