# Generated by Django 5.2.8 on 2026-02-02 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_alter_membership_invite_team_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="team",
            name="one_independent_team_per_game",
        ),
        migrations.RemoveConstraint(
            model_name="team",
            name="team_has_organization_xor_owner",
        ),
        migrations.RemoveIndex(
            model_name="team",
            name="team_owner_game_idx",
        ),
        migrations.RemoveField(
            model_name="team",
            name="owner",
        ),
        migrations.AddField(
            model_name="team",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created/owns this team",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="game_id",
            field=models.IntegerField(
                db_index=True,
                default=1,
                help_text="Game ID (denormalized from team for constraint: one team per game per user)",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (NULL for independent teams)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["created_by"], name="team_created_by_idx"),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(fields=["user", "game_id"], name="membership_user_game_idx"),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("user", "game_id"),
                name="one_active_team_per_game_per_user",
            ),
        ),
    ]
