# Generated by Django 5.2.8 on 2026-02-02 15:36

from django.db import migrations


def populate_game_id(apps, schema_editor):
    """
    Populate game_id for existing memberships from their team's game_id.
    
    This is necessary before the constraint can be enforced.
    """
    TeamMembership = apps.get_model('organizations', 'TeamMembership')
    Team = apps.get_model('organizations', 'Team')
    
    # Update all memberships to have the correct game_id
    for membership in TeamMembership.objects.select_related('team').all():
        membership.game_id = membership.team.game_id
        membership.save(update_fields=['game_id'])


def reverse_populate_game_id(apps, schema_editor):
    """
    No-op reverse operation (game_id can stay populated).
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_phase8_correction_independent_teams"),
    ]

    operations = [
        migrations.RunPython(populate_game_id, reverse_populate_game_id),
    ]
