# Generated by Django 5.2.8 on 2026-02-04 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_populate_membership_game_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMembershipEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("JOINED", "Joined Team"),
                            ("ROLE_CHANGED", "Role Changed"),
                            ("LEFT", "Left Team"),
                            ("REMOVED", "Removed from Team"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("NOTE", "Administrative Note"),
                        ],
                        db_index=True,
                        help_text="Type of event (JOINED, ROLE_CHANGED, LEFT, REMOVED, STATUS_CHANGED, NOTE)",
                        max_length=20,
                    ),
                ),
                (
                    "old_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("COACH", "Coach"),
                            ("PLAYER", "Player"),
                            ("SUBSTITUTE", "Substitute"),
                            ("ANALYST", "Analyst"),
                            ("SCOUT", "Scout"),
                        ],
                        help_text="Role before change (for ROLE_CHANGED events)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("COACH", "Coach"),
                            ("PLAYER", "Player"),
                            ("SUBSTITUTE", "Substitute"),
                            ("ANALYST", "Analyst"),
                            ("SCOUT", "Scout"),
                        ],
                        help_text="Role after change (for JOINED, ROLE_CHANGED events)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("INVITED", "Invited (Pending)"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        help_text="Status before change (for STATUS_CHANGED events)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("INVITED", "Invited (Pending)"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        help_text="Status after change (for STATUS_CHANGED events)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context: reason codes, admin notes, match refs, duration_days",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Event timestamp (immutable)"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who performed this action (creator/manager/admin/system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        help_text="Membership this event relates to (null if membership deleted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="organizations.teammembership",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team (denormalized for queries)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_events",
                        to="organizations.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User (denormalized for player history queries)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_membership_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizations_membership_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="membership_event_user_time"),
                    models.Index(fields=["team", "-created_at"], name="membership_event_team_time"),
                    models.Index(
                        fields=["membership", "-created_at"], name="membership_event_mbr_time"
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"], name="membership_event_type_time"
                    ),
                ],
            },
        ),
    ]
