# Generated by Django 5.2.8 on 2026-02-05 04:45

from django.db import migrations, models
from django.db.models import Q


def populate_organization_id(apps, schema_editor):
    """
    Populate organization_id from team.organization_id.
    This allows the constraint to distinguish independent vs org teams.
    """
    TeamMembership = apps.get_model('organizations', 'TeamMembership')
    Team = apps.get_model('organizations', 'Team')
    
    # Update all memberships with their team's organization_id
    for membership in TeamMembership.objects.select_related('team').iterator(chunk_size=500):
        membership.organization_id = membership.team.organization_id
        membership.save(update_fields=['organization_id'])


class Migration(migrations.Migration):
    """
    Fix the team constraint to only apply to independent teams.
    
    Business Rules:
    - Independent teams: ONE per user per game (organization_id IS NULL)
    - Organization teams: MULTIPLE teams per user per game (allowed)
    
    The old constraint blocked ALL active memberships per user per game,
    preventing users from being in org teams AND owning independent teams.
    
    Solution:
    1. Add organization_id field (denormalized from team)
    2. Populate organization_id from existing teams
    3. Remove old constraint
    4. Add new constraint that only applies when organization_id IS NULL
    """

    dependencies = [
        ("organizations", "0016_normalize_owner_to_manager"),
    ]

    operations = [
        # Step 1: Add organization_id field
        migrations.AddField(
            model_name='teammembership',
            name='organization_id',
            field=models.IntegerField(
                db_index=True,
                null=True,
                blank=True,
                help_text="Organization ID (denormalized from team for constraint: distinguish org vs independent teams)"
            ),
        ),
        
        # Step 2: Populate organization_id from team.organization_id
        migrations.RunPython(populate_organization_id, migrations.RunPython.noop),
        
        # Step 3: Remove old constraint
        migrations.RemoveConstraint(
            model_name='teammembership',
            name='one_active_team_per_game_per_user',
        ),
        
        # Step 4: Add corrected constraint (only for independent teams)
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(
                fields=['user', 'game_id'],
                condition=Q(status='ACTIVE', organization_id__isnull=True),
                name='one_active_independent_team_per_game_per_user'
            ),
        ),
    ]
