# Generated by Django 5.2.8 on 2026-02-08 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_fix_team_constraint_for_orgs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamactivitylog",
            name="team",
            field=models.ForeignKey(
                help_text="Team this activity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="organizations.team",
            ),
        ),
    ]
