# Generated by Django 5.2.8 on 2026-02-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_alter_teamactivitylog_team_to_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembership",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Custom display name for this team (overrides global display_name)",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="roster_image",
            field=models.ImageField(
                blank=True,
                help_text="Dedicated roster photo for this team membership",
                null=True,
                upload_to="roster_photos/",
            ),
        ),
    ]
