# Generated by Django 5.2.8 on 2026-02-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0020_add_hide_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="discord_webhook_url",
            field=models.URLField(
                blank=True, help_text="Discord webhook URL for team notifications", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="facebook_url",
            field=models.URLField(blank=True, help_text="Team Facebook page URL"),
        ),
        migrations.AddField(
            model_name="team",
            name="invite_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Shareable invite code for joining the team",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="roster_locked",
            field=models.BooleanField(
                default=False,
                help_text="Manual roster lock — prevents all roster changes when True",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="tiktok_url",
            field=models.URLField(blank=True, help_text="Team TikTok profile URL"),
        ),
        migrations.AddField(
            model_name="team",
            name="website_url",
            field=models.URLField(blank=True, help_text="Custom team website URL"),
        ),
    ]
