# Generated by Django 5.2.8 on 2026-02-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0021_add_team_roster_locked_socials_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="whatsapp_url",
            field=models.URLField(blank=True, help_text="Team WhatsApp group invite URL"),
        ),
        migrations.AddField(
            model_name="team",
            name="messenger_url",
            field=models.URLField(blank=True, help_text="Team Messenger group URL"),
        ),
    ]
