# Generated by Django 5.2.8 on 2026-02-09 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0023_add_team_change_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("INVITED", "Invited (Pending)"),
                    ("SUSPENDED", "Suspended"),
                    ("REMOVED", "Removed"),
                ],
                db_index=True,
                default="INVITED",
                help_text="Membership status (ACTIVE, INACTIVE, INVITED, SUSPENDED)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="teammembershipevent",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("INVITED", "Invited (Pending)"),
                    ("SUSPENDED", "Suspended"),
                    ("REMOVED", "Removed"),
                ],
                help_text="Status after change (for STATUS_CHANGED events)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teammembershipevent",
            name="old_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("INVITED", "Invited (Pending)"),
                    ("SUSPENDED", "Suspended"),
                    ("REMOVED", "Removed"),
                ],
                help_text="Status before change (for STATUS_CHANGED events)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TeamAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(max_length=2000)),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("general", "General Update"),
                            ("announcement", "Announcement"),
                            ("update", "Update"),
                            ("alert", "Alert"),
                            ("match_result", "Match Result"),
                            ("roster_change", "Roster Change"),
                        ],
                        default="update",
                        max_length=20,
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_team_announcement",
                "ordering": ["-pinned", "-created_at"],
                "indexes": [
                    models.Index(fields=["team", "-created_at"], name="ann_team_created_idx")
                ],
            },
        ),
    ]
