# Generated by Django 5.2.8 on 2026-02-09 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0024_alter_teammembership_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="discord_url",
            field=models.URLField(
                blank=True, help_text="Discord server invite link (discord.gg/...)", max_length=300
            ),
        ),
        migrations.CreateModel(
            name="TeamHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
                ("description", models.TextField(blank=True, default="", max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_highlights_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_team_highlight",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["team", "-created_at"], name="highlight_team_created_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(default="Untitled", max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("match", "Match Screenshot"),
                            ("event", "Event"),
                            ("roster", "Roster Photo"),
                            ("meme", "Meme / Fun"),
                            ("artwork", "Artwork"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="teams/gallery/")),
                ("file_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "file_type",
                    models.CharField(
                        blank=True, default="image", help_text="image or video", max_length=20
                    ),
                ),
                ("file_size", models.PositiveIntegerField(default=0, help_text="Size in bytes")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_gallery",
                        to="organizations.team",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_media_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizations_team_media",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["team", "-created_at"], name="media_team_created_idx")
                ],
            },
        ),
    ]
