# Generated by Django 5.2.8 on 2026-02-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0025_team_discord_url_teamhighlight_teammedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembership",
            name="permissions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom permission overrides per-member. Keys are permission strings, values are booleans. True grants, False revokes. Merges with role defaults.",
            ),
        ),
    ]
