# Generated by Django 5.2.8 on 2026-02-09 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0026_add_membership_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="discord_announcement_channel_id",
            field=models.CharField(
                blank=True, help_text="Channel ID for bi-directional announcements", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="discord_bot_active",
            field=models.BooleanField(
                default=False,
                help_text="True when the platform bot is verified present in this guild",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="discord_chat_channel_id",
            field=models.CharField(
                blank=True, help_text='Channel ID for real-time chat sync ("Lobby")', max_length=20
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="discord_guild_id",
            field=models.CharField(
                blank=True,
                help_text="Discord server (guild) ID — required for bot integration",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="discord_voice_channel_id",
            field=models.CharField(
                blank=True, help_text="Voice channel ID for one-click voice join", max_length=20
            ),
        ),
        migrations.CreateModel(
            name="DiscordChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "discord_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Discord message snowflake ID",
                        max_length=20,
                    ),
                ),
                (
                    "discord_channel_id",
                    models.CharField(
                        blank=True,
                        help_text="Discord channel this message belongs to",
                        max_length=20,
                    ),
                ),
                (
                    "author_discord_id",
                    models.CharField(
                        blank=True, help_text="Discord user snowflake ID", max_length=20
                    ),
                ),
                (
                    "author_discord_name",
                    models.CharField(
                        blank=True,
                        help_text="Discord display name at time of message",
                        max_length=100,
                    ),
                ),
                ("content", models.TextField(help_text="Message text content", max_length=2000)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Discord → Web"), ("outbound", "Web → Discord")],
                        help_text="inbound = Discord→Web, outbound = Web→Discord",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "author_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked DeltaCrown user (if known)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discord_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_chat_messages",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_discord_chat_message",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["team", "-created_at"], name="dchat_team_created_idx"),
                    models.Index(
                        fields=["team", "direction", "-created_at"], name="dchat_team_dir_idx"
                    ),
                ],
            },
        ),
    ]
