# Generated by Django 5.2.8 on 2026-02-10 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0030_team_platform_identity_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamactivitylog",
            name="is_milestone",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Milestone events show in public timeline (auto-set for major actions)",
            ),
        ),
        migrations.AddField(
            model_name="teamactivitylog",
            name="is_pinned",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pinned events always show in public journey timeline",
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="applied_position",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Position the applicant is trying out for",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="tryout_date",
            field=models.DateTimeField(
                blank=True, help_text="Scheduled tryout date/time", null=True
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="tryout_notes",
            field=models.TextField(
                blank=True, default="", help_text="Internal notes about the tryout", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="teamjoinrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("TRYOUT_SCHEDULED", "Tryout Scheduled"),
                    ("TRYOUT_COMPLETED", "Tryout Completed"),
                    ("OFFER_SENT", "Offer Sent"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RecruitmentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Requirement category (e.g. "Minimum Rank")', max_length=40
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text='Requirement detail (e.g. "Diamond+")', max_length=100
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_requirements",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_recruitment_requirement",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Position title (e.g. "Entry Fragger", "IGL")', max_length=60
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Brief description of the role",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this position is currently open",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_positions",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_recruitment_position",
                "ordering": ["sort_order", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("team", "title"),
                        name="unique_active_position_per_team",
                    )
                ],
            },
        ),
    ]
