# Generated by Django 5.2.8 on 2026-02-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0031_smart_recruitment_and_journey"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentposition",
            name="cross_post_community",
            field=models.BooleanField(
                default=False,
                help_text="If True, this position is published to the global community feed",
            ),
        ),
        migrations.AddField(
            model_name="recruitmentposition",
            name="platform",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Platform for this position (auto-filled from team, editable)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="recruitmentposition",
            name="rank_requirement",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Minimum rank (e.g. "Immortal 3+", "Diamond+")',
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="recruitmentposition",
            name="region",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Region for this position (auto-filled from team, editable)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="recruitmentposition",
            name="role_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FLEX", "Flex"),
                    ("IGL", "IGL / Shot-Caller"),
                    ("ENTRY", "Entry Fragger"),
                    ("SNIPER", "Sniper / AWPer"),
                    ("SUPPORT", "Support"),
                    ("LURKER", "Lurker"),
                    ("CONTROLLER", "Controller"),
                    ("SENTINEL", "Sentinel"),
                    ("DUELIST", "Duelist"),
                    ("INITIATOR", "Initiator"),
                    ("TANK", "Tank"),
                    ("DPS", "DPS"),
                    ("HEALER", "Healer"),
                    ("COACH", "Coach"),
                    ("ANALYST", "Analyst"),
                    ("MANAGER", "Manager"),
                    ("CONTENT", "Content Creator"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="Standardized role category (Flex, IGL, Sniper…)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recruitmentposition",
            name="short_pitch",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short description / pitch for the listing (max 140 chars)",
                max_length=140,
            ),
        ),
    ]
