# Generated by Django 5.2.8 on 2026-02-10 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0032_recruitment_position_enrich"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamJourneyMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Milestone headline (e.g., "Qualified for Ascension Pacific")',
                        max_length=120,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional details about this milestone (max 500 chars)",
                        max_length=500,
                    ),
                ),
                ("milestone_date", models.DateField(help_text="When this milestone occurred")),
                (
                    "is_visible",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this milestone appears on the public detail page",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower values appear first (0 = auto-sort by date)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_milestones",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Milestone",
                "verbose_name_plural": "Journey Milestones",
                "db_table": "organizations_journey_milestone",
                "ordering": ["-milestone_date", "-created_at"],
            },
        ),
    ]
