# Generated by Django 5.2.8 on 2026-02-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0034_milestone_type_and_system_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembershipevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("JOINED", "Joined Team"),
                    ("INVITED", "Invited to Team"),
                    ("ROLE_CHANGED", "Role Changed"),
                    ("LEFT", "Left Team"),
                    ("REMOVED", "Removed from Team"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("NOTE", "Administrative Note"),
                ],
                db_index=True,
                help_text="Type of event (JOINED, ROLE_CHANGED, LEFT, REMOVED, STATUS_CHANGED, NOTE)",
                max_length=20,
            ),
        ),
    ]
