# Generated by Django 5.2.8 on 2026-02-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0035_add_team_to_communitypost"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="featured_label",
            field=models.CharField(
                blank=True,
                help_text="Spotlight badge text (e.g. 'Season 1 Champion', 'Community Pick')",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="is_featured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Show this team in the Hero spotlight carousel (admin toggle)",
            ),
        ),
    ]
