# Generated by Django 5.2.8 on 2026-03-17 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0040_drop_orphaned_legacy_tables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamRankingAdjustmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("BONUS", "Bonus CP"),
                            ("PENALTY", "Penalty"),
                            ("MANUAL_CP", "Manual CP Override"),
                            ("TIER_OVERRIDE", "Tier Override"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cp_before", models.IntegerField(help_text="CP before adjustment")),
                ("cp_after", models.IntegerField(help_text="CP after adjustment")),
                ("cp_delta", models.IntegerField(help_text="Net CP change (can be negative)")),
                ("tier_before", models.CharField(blank=True, default="", max_length=20)),
                ("tier_after", models.CharField(blank=True, default="", max_length=20)),
                ("reason", models.TextField(help_text="Admin-supplied justification")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_adjustments",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking Adjustment Log",
                "verbose_name_plural": "Ranking Adjustment Logs",
                "db_table": "organizations_ranking_adjustment_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
