# Generated by Django 5.2.8 on 2026-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0041_add_team_ranking_adjustment_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamranking",
            name="activity_score",
            field=models.IntegerField(
                default=0, help_text="Engagement score 0-100 (badges/visibility, not ranking)"
            ),
        ),
        migrations.AddField(
            model_name="teamranking",
            name="matches_today",
            field=models.IntegerField(
                default=0, help_text="Ranked matches played today (reset at midnight UTC)"
            ),
        ),
        migrations.AddField(
            model_name="teamranking",
            name="matches_today_reset",
            field=models.DateField(
                blank=True, help_text="Date of last daily counter reset", null=True
            ),
        ),
        migrations.AddField(
            model_name="teamranking",
            name="recent_opponents",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Same-opponent tracking: {team_id: [iso_timestamps]}",
            ),
        ),
    ]
