# Generated by Django 5.2.8 on 2026-04-11 08:28

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0043_phase19_elo_rating_and_tier_rebrand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="badge",
            field=models.ImageField(
                blank=True,
                help_text="Verified badge overlay",
                null=True,
                upload_to="organizations/badges/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Profile page header banner",
                null=True,
                upload_to="organizations/banners/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Organization logo (inherited by teams if enforce_brand=True)",
                null=True,
                upload_to="organizations/logos/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Profile page header banner",
                null=True,
                upload_to="teams/banners/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Team logo (or inherits from organization if enforce_brand=True)",
                null=True,
                upload_to="teams/logos/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="teammedia",
            name="file",
            field=models.FileField(
                upload_to="teams/gallery/",
                validators=[apps.common.validators.validate_document_upload],
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="roster_image",
            field=models.ImageField(
                blank=True,
                help_text="Dedicated roster photo for this team membership",
                null=True,
                upload_to="roster_photos/",
                validators=[apps.common.validators.validate_image_upload],
            ),
        ),
    ]
