# Generated by Django 5.2.8 on 2026-05-15 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_seed_lobby_options"),
        ("organizations", "0044_alter_organization_badge_alter_organization_banner_and_more"),
        ("tournaments", "0060_match_submission_ocr_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrimRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("BO1", "Best of 1"),
                            ("BO3", "Best of 3"),
                            ("BO5", "Best of 5"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="BO3",
                        max_length=12,
                    ),
                ),
                ("skill_level", models.CharField(blank=True, max_length=80)),
                ("server_region", models.CharField(blank=True, max_length=80)),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("TEAM_ONLY", "Team only"),
                            ("PUBLIC", "Public"),
                            ("UNLISTED", "Unlisted"),
                        ],
                        db_index=True,
                        default="PUBLIC",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=1200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACCEPTED", "Accepted"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_scrim_requests",
                        to="organizations.team",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scrim_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scrim_requests",
                        to="games.game",
                    ),
                ),
                (
                    "requesting_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrim_requests",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_scrim_request",
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrimBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                ("room_details", models.TextField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="ACCEPTED",
                        max_length=16,
                    ),
                ),
                ("result_notes", models.TextField(blank=True, max_length=1200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_scrim_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "accepted_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_scrim_bookings",
                        to="organizations.team",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_scrim_bookings",
                        to="tournaments.match",
                    ),
                ),
                (
                    "requesting_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_scrim_bookings",
                        to="organizations.team",
                    ),
                ),
                (
                    "scrim_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="organizations.scrimrequest",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_scrim_booking",
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TryoutApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ign", models.CharField(blank=True, max_length=100)),
                ("preferred_role", models.CharField(blank=True, max_length=80)),
                ("rank_tier", models.CharField(blank=True, max_length=80)),
                ("availability", models.CharField(blank=True, max_length=240)),
                ("profile_links", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, max_length=1200)),
                ("review_notes", models.TextField(blank=True, max_length=1600)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REVIEWING", "Reviewing"),
                            ("INVITED", "Invited"),
                            ("SCHEDULED", "Scheduled"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("OBSERVATION", "Observation"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tryout_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tryout_applications",
                        to="games.game",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_tryout_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_tryout_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tryout_applications",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_tryout_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TryoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                ("format", models.CharField(blank=True, max_length=80)),
                ("room_details", models.TextField(blank=True, max_length=1000)),
                ("review_notes", models.TextField(blank=True, max_length=1600)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tryout_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="organizations.tryoutapplication",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_tryout_sessions",
                        to="tournaments.match",
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_tryout_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tryout_sessions",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_tryout_session",
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VodReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("external_url", models.URLField(max_length=500)),
                ("category", models.CharField(default="analysis", max_length=40)),
                ("notes", models.TextField(blank=True, max_length=2400)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("TEAM_ONLY", "Team only"),
                            ("PUBLIC", "Public"),
                            ("UNLISTED", "Unlisted"),
                        ],
                        db_index=True,
                        default="TEAM_ONLY",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("REVIEWED", "Reviewed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_players",
                    models.ManyToManyField(
                        blank=True, related_name="assigned_vod_reviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "linked_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_vod_reviews",
                        to="tournaments.match",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vod_reviews_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vod_reviews",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_vod_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("session_type", models.CharField(default="PRACTICE", max_length=40)),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=60)),
                ("focus", models.CharField(blank=True, max_length=160)),
                ("goals", models.TextField(blank=True, max_length=1200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=1600)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practice_sessions",
                        to="games.game",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_practice_sessions",
                        to="tournaments.match",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="practice_session_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_practice_session",
                "ordering": ["-scheduled_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "status", "scheduled_at"], name="practice_team_status_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="scrimrequest",
            index=models.Index(
                fields=["requesting_team", "status"], name="scrim_req_team_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrimrequest",
            index=models.Index(
                fields=["game", "status", "scheduled_at"], name="scrim_req_game_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrimbooking",
            index=models.Index(fields=["requesting_team", "status"], name="scrim_booking_home_idx"),
        ),
        migrations.AddIndex(
            model_name="scrimbooking",
            index=models.Index(fields=["accepted_team", "status"], name="scrim_booking_away_idx"),
        ),
        migrations.AddConstraint(
            model_name="tryoutapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "REVIEWING", "INVITED", "SCHEDULED", "OBSERVATION"])
                ),
                fields=("team", "applicant"),
                name="unique_active_tryout_application",
            ),
        ),
        migrations.AddIndex(
            model_name="vodreview",
            index=models.Index(fields=["team", "status"], name="vod_review_team_status_idx"),
        ),
    ]
