# Generated by Django 5.2.8 on 2026-05-16 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0045_team_training_ops"),
    ]

    operations = [
        migrations.AddField(
            model_name="tryoutapplication",
            name="join_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Roster pipeline item created or linked when a tryout becomes a join offer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tryout_applications",
                to="organizations.teamjoinrequest",
            ),
        ),
    ]
