# Generated by Django 5.2.8 on 2026-05-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_seed_lobby_options"),
        ("organizations", "0046_tryoutapplication_join_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamCompetitiveSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "showdown_create_policy",
                    models.CharField(
                        choices=[
                            ("owner_manager", "Owner / Manager"),
                            ("owner_manager_captain", "Owner / Manager / Captain"),
                        ],
                        default="owner_manager_captain",
                        max_length=32,
                    ),
                ),
                (
                    "bounty_create_policy",
                    models.CharField(
                        choices=[
                            ("owner_manager", "Owner / Manager"),
                            ("owner_manager_captain", "Owner / Manager / Captain"),
                        ],
                        default="owner_manager_captain",
                        max_length=32,
                    ),
                ),
                ("max_showdown_entry_fee_dc", models.PositiveIntegerField(default=1000)),
                ("max_bounty_reward_dc", models.PositiveIntegerField(default=10000)),
                (
                    "bounty_approval_required_above_dc",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 disables threshold blocking. Captains above this amount require manager action.",
                    ),
                ),
                ("allow_public_scrim_availability", models.BooleanField(default=True)),
                ("allow_public_tryout_applications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_games",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Empty means all active competitive games are allowed.",
                        related_name="team_competitive_settings",
                        to="games.game",
                    ),
                ),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitive_settings",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Competitive Settings",
                "verbose_name_plural": "Team Competitive Settings",
                "db_table": "organizations_team_competitive_settings",
            },
        ),
    ]
