# Generated by Django 5.2.8 on 2026-05-24 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0047_team_competitive_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="accent_color",
            field=models.CharField(
                blank=True,
                default="#10B981",
                help_text="Accent team color (hex format, e.g., #10B981)",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, such as #3B82F6 or #3BF.",
                        regex="^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="primary_color",
            field=models.CharField(
                blank=True,
                default="#3B82F6",
                help_text="Primary team color (hex format, e.g., #3B82F6)",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, such as #3B82F6 or #3BF.",
                        regex="^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                    )
                ],
            ),
        ),
    ]
