# Generated by Django 5.2.8 on 2026-01-23 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event", models.CharField(db_index=True, default="generic", max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("reg_confirmed", "Registration confirmed"),
                            ("bracket_ready", "Bracket generated"),
                            ("match_scheduled", "Match scheduled"),
                            ("result_verified", "Result verified"),
                            ("payment_verified", "Payment verified"),
                            ("checkin_open", "Check-in window open"),
                            ("generic", "Generic"),
                            ("invite_sent", "Team invite sent"),
                            ("invite_accepted", "Team invite accepted"),
                            ("roster_changed", "Team roster changed"),
                            ("tournament_registered", "Tournament registered"),
                            ("match_result", "Match result posted"),
                            ("ranking_changed", "Team ranking changed"),
                            ("sponsor_approved", "Sponsor approved"),
                            ("promotion_started", "Promotion started"),
                            ("payout_received", "Payout received"),
                            ("achievement_earned", "Achievement earned"),
                            ("follow_request", "Follow request received"),
                            ("user_followed", "User followed you"),
                            ("post_liked", "Post liked"),
                            ("comment_added", "Comment added"),
                            ("post_shared", "Post shared"),
                            ("mention", "Mentioned in post"),
                            ("follow_request_approved", "Follow request approved"),
                            ("follow_request_rejected", "Follow request rejected"),
                        ],
                        db_index=True,
                        default="generic",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("body", models.TextField(blank=True)),
                ("url", models.CharField(blank=True, max_length=300)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "is_delivered",
                    models.BooleanField(
                        default=False,
                        help_text="Whether notification was successfully delivered via SSE/WebSocket",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action_label",
                    models.CharField(
                        blank=True,
                        help_text="CTA button text (e.g., 'View Request', 'Approve')",
                        max_length=255,
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, help_text="URL for primary action button", max_length=500
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Notification category (e.g., 'social', 'system')",
                        max_length=100,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, help_text="Alternative message text for display"),
                ),
                (
                    "action_object_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of related object (e.g., FollowRequest.id for follow_request type)",
                        null=True,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Type of action object (e.g., 'follow_request')",
                        max_length=50,
                    ),
                ),
                (
                    "tournament_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Legacy tournament ID (reference only)",
                        null=True,
                    ),
                ),
                (
                    "match_id",
                    models.IntegerField(
                        blank=True, help_text="Legacy match ID (reference only)", null=True
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("digest_date", models.DateField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notifications",
                    models.ManyToManyField(related_name="digests", to="notifications.notification"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_digests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-digest_date"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("invite_sent_channels", models.JSONField(blank=True, default=list)),
                ("invite_accepted_channels", models.JSONField(blank=True, default=list)),
                ("roster_changed_channels", models.JSONField(blank=True, default=list)),
                ("tournament_registered_channels", models.JSONField(blank=True, default=list)),
                ("match_result_channels", models.JSONField(blank=True, default=list)),
                ("ranking_changed_channels", models.JSONField(blank=True, default=list)),
                ("sponsor_approved_channels", models.JSONField(blank=True, default=list)),
                ("promotion_started_channels", models.JSONField(blank=True, default=list)),
                ("payout_received_channels", models.JSONField(blank=True, default=list)),
                ("achievement_earned_channels", models.JSONField(blank=True, default=list)),
                ("enable_daily_digest", models.BooleanField(default=True)),
                ("digest_time", models.TimeField(default="08:00:00")),
                ("opt_out_email", models.BooleanField(default=False)),
                ("opt_out_in_app", models.BooleanField(default=False)),
                ("opt_out_discord", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "created_at"], name="notificatio_recipie_86ea8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "type"], name="notificatio_recipie_036988_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdigest",
            index=models.Index(
                fields=["user", "digest_date", "is_sent"], name="notificatio_user_id_7aa35f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationdigest",
            unique_together={("user", "digest_date")},
        ),
    ]
