# Generated by Django 4.2.23 on 2025-08-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0006_match_start_at'),
        ('user_profile', '0003_userprofile_bio_userprofile_preferred_games_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reg_confirm', 'Registration confirmed'), ('team_invite', 'Team invite'), ('match_scheduled', 'Match scheduled'), ('checkin_open', 'Check-in window opened')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.match')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_profile.userprofile')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx')],
                'unique_together': {('recipient', 'type', 'match')},
            },
        ),
    ]
