# Generated by Django 5.2.8 on 2026-01-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_label",
            field=models.CharField(
                blank=True,
                help_text="CTA button text (e.g., 'View Request', 'Approve')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.CharField(
                blank=True, help_text="URL for primary action button", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Notification category (e.g., 'social', 'system')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.TextField(blank=True, help_text="Alternative message text for display"),
        ),
    ]
