# Generated by Django 5.2.8 on 2026-03-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_phase2_reconciliation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_5a7f6a_idx",
            old_name="notifications_recipient_category_created_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_299942_idx",
            old_name="notifications_recipient_priority_read_idx",
        ),
    ]
