# Generated by Django 5.2.8 on 2026-01-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_add_notification_action_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_object_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID of related object (e.g., FollowRequest.id for follow_request type)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Type of action object (e.g., 'follow_request')",
                max_length=50,
            ),
        ),
    ]
