# Generated by Django 5.2.8 on 2026-01-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_add_action_object_linkage"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_delivered",
            field=models.BooleanField(
                default=False,
                help_text="Whether notification was successfully delivered via SSE/WebSocket",
            ),
        ),
    ]
