# Generated by Django 4.2.23 on 2025-09-05 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


POSTGRES_SAFE_RENAMES = r"""
DO $$
BEGIN
    -- Only rename if the old index exists
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'noti_rec_read_created_idx') THEN
        ALTER INDEX "noti_rec_read_created_idx" RENAME TO "notificatio_recipie_86ea8b_idx";
    END IF;

    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'noti_rec_type_tour_match_idx') THEN
        ALTER INDEX "noti_rec_type_tour_match_idx" RENAME TO "notificatio_recipie_28df99_idx";
    END IF;
END$$;
"""


def do_safe_index_renames(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cur:
            cur.execute(POSTGRES_SAFE_RENAMES)
    # On SQLite/others: nothing to do.


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_rename_noti_rec_read_created_idx_notificatio_recipie_86ea8b_idx_and_more'),
    ]

    operations = [
        # Perform safe/no-op-if-missing index renames first
        migrations.RunPython(do_safe_index_renames, migrations.RunPython.noop),

        # Keep the field alterations Django generated
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notifications',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(
                choices=[
                    ('reg_confirmed', 'Registration confirmed'),
                    ('bracket_ready', 'Bracket generated'),
                    ('match_scheduled', 'Match scheduled'),
                    ('result_verified', 'Result verified'),
                    ('payment_verified', 'Payment verified'),
                    ('checkin_open', 'Check-in window open'),
                    ('generic', 'Generic')
                ],
                db_index=True,
                default='generic',
                max_length=40
            ),
        ),
    ]
