# Generated by Django 5.2.8 on 2026-01-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_notification_is_delivered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("reg_confirmed", "Registration confirmed"),
                    ("bracket_ready", "Bracket generated"),
                    ("match_scheduled", "Match scheduled"),
                    ("result_verified", "Result verified"),
                    ("payment_verified", "Payment verified"),
                    ("checkin_open", "Check-in window open"),
                    ("generic", "Generic"),
                    ("invite_sent", "Team invite sent"),
                    ("invite_accepted", "Team invite accepted"),
                    ("roster_changed", "Team roster changed"),
                    ("tournament_registered", "Tournament registered"),
                    ("match_result", "Match result posted"),
                    ("ranking_changed", "Team ranking changed"),
                    ("sponsor_approved", "Sponsor approved"),
                    ("promotion_started", "Promotion started"),
                    ("payout_received", "Payout received"),
                    ("achievement_earned", "Achievement earned"),
                    ("follow_request", "Follow request received"),
                    ("user_followed", "User followed you"),
                    ("post_liked", "Post liked"),
                    ("comment_added", "Comment added"),
                    ("post_shared", "Post shared"),
                    ("mention", "Mentioned in post"),
                    ("follow_request_approved", "Follow request approved"),
                    ("follow_request_rejected", "Follow request rejected"),
                ],
                db_index=True,
                default="generic",
                max_length=40,
            ),
        ),
    ]
