# Generated by Django 4.2.24 on 2025-09-26 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '__first__'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reg_confirmed', 'Registration confirmed'), ('bracket_ready', 'Bracket generated'), ('match_scheduled', 'Match scheduled'), ('result_verified', 'Result verified'), ('payment_verified', 'Payment verified'), ('checkin_open', 'Check-in window open'), ('team_ranking_up', 'Team ranking improved'), ('team_ranking_down', 'Team ranking decreased'), ('team_points_awarded', 'Points awarded to team'), ('generic', 'Generic')], db_index=True, default='generic', max_length=40),
        ),
    ]
