# Generated by Django 4.2.23 on 2025-09-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_team_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='team',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reg_confirmed', 'Registration confirmed'), ('bracket_ready', 'Bracket generated'), ('match_scheduled', 'Match scheduled'), ('result_verified', 'Result verified'), ('payment_verified', 'Payment verified'), ('checkin_open', 'Check-in window open'), ('generic', 'Generic')], db_index=True, default='generic', max_length=40),
        ),
    ]
