# Generated by Django 4.2.24 on 2025-11-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_type_notificationpreference_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_28df99_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='match',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tournament',
        ),
        migrations.AddField(
            model_name='notification',
            name='match_id',
            field=models.IntegerField(blank=True, help_text='Legacy match ID (reference only)', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='tournament_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Legacy tournament ID (reference only)', null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'type'], name='notificatio_recipie_036988_idx'),
        ),
    ]
